### ISSUE TITLE
Faux Scrolling doesn't work

### ISSUE THREAD

**Issue by avshyz** [alacritty/alacritty#2576]
Which operating system does the issue occur on?
osx 10.14

This is the configured scrolling section:
```
scrolling:
  history: 10000
  multiplier: 3
  faux_multiplier: 3
  auto_scroll: true
```
