### ISSUE TITLE
Windows: startup_mode: Maximized no longer works

### ISSUE THREAD

**Issue by Jiehong** [alacritty/alacritty#2601]
System: Windows 10, Alacritty 0.3.3.

Using `startup_mode: Maximized` has the same effect as `startup_mode: Windowed`.
However, `Fullscreen` works fine.

This seems to be a regression compared to before.

**Comment by chrisduerr** [comment]
When you say regression, where did it regress from? I'd assume you mean 0.3.2?

Generally it would be nice to have a specific commit hash which broke it, but I'd assume that was a winit/glutin update. So before testing that, the #2438 PR should probably be tested, which updates Alacritty to the latest version of winit.

**Comment by JDTX** [comment]
I am able to replicate this, but different behavior I think.

If I use `startup_mode: Maximized` the window starts at the top left of my screen and "thinks" it is maximized. (i.e it displays the "Restore" icon vs Maximize icon), example: https://i.imgur.com/Jc4CWw0.png

If I restore it and maximize again, it then maximizes correctly.

Also, I tested several older versions of Alacrity, `Maximized` does nothing for me before v0.3.3-rc1.  All builds before that just start the window normally.  All builds after cause the behavior mentioned.

I've also tested the #2438 PR, it behaves identically to the most current release (0.3.3)

**Comment by Jiehong** [comment]
I confirm @JDTX comment: it does not exactly behaves like `Windowed` like I said, but like JDTX described.

I can only test further after the weekend for the previous working version (the option used to be called `start_maximized` then).

**Comment by chrisduerr** [comment]
Okay, but then it's not a regression. The following patch might fix this, could someone try it?

```diff
diff --git a/alacritty_terminal/src/display.rs b/alacritty_terminal/src/display.rs
index 4a2e57c..0d73238 100644
--- a/alacritty_terminal/src/display.rs
+++ b/alacritty_terminal/src/display.rs
@@ -245,7 +245,7 @@ impl Display {
             StartupMode::Fullscreen => window.set_fullscreen(true),
             #[cfg(target_os = "macos")]
             StartupMode::SimpleFullscreen => window.set_simple_fullscreen(true),
-            #[cfg(not(any(target_os = "macos", windows)))]
+            #[cfg(not(target_os = "macos")))]
             StartupMode::Maximized if window.is_x11() => window.set_maximized(true),
             _ => (),
         }
```

**Comment by JDTX** [comment]
@chrisduerr Your patch had some issues,
```
[alacritty]$ git apply fullscreen.patch
[alacritty]$ cargo build --release
   Compiling alacritty_terminal v0.3.3 (C:\cygwin64\usr\local\src\alacritty\alacritty_terminal)
error: unexpected close delimiter: `}`
   --> alacritty_terminal\src\display.rs:596:1
```

There was an extra ")" character from "any" that wasn't removed, I removed the extra ")" and got another compilation error:
```
error[E0599]: no method named `is_x11` found for type `window::Window` in the current scope
   --> alacritty_terminal\src\display.rs:249:46
    |
249 |             StartupMode::Maximized if window.is_x11() => window.set_maximized(true),
    |                                              ^^^^^^
    |
   ::: alacritty_terminal\src\window.rs:59:1
    |
59  | pub struct Window {
    | ----------------- method `is_x11` not found for this
```

I removed `if window.is_x11()`, it compiled, but `startup_mode: Maximized` still behaves the same.

**Comment by chrisduerr** [comment]
It would be nice if someone could test the examples of https://github.com/rust-windowing/glutin. The normal window example can be run with `cargo run --example window`, though the following diff needs to be applied first:

```diff
diff --git a/glutin_examples/examples/window.rs b/glutin_examples/examples/window.rs
index f7da6c4..40b0c05 100644
--- a/glutin_examples/examples/window.rs
+++ b/glutin_examples/examples/window.rs
@@ -7,7 +7,7 @@ use glutin::ContextBuilder;
 
 fn main() {
     let el = EventLoop::new();
-    let wb = WindowBuilder::new().with_title("A fantastic window!");
+    let wb = WindowBuilder::new().with_title("A fantastic window!").with_maximized(true);
 
     let windowed_context =
         ContextBuilder::new().build_windowed(wb, &el).unwrap();
```

If that doesn't work, this needs to be reported to winit.

**Comment by JDTX** [comment]
@chrisduerr The example had the same results, I've reported the issue upstream w/ winit.
https://github.com/rust-windowing/winit/issues/1009

**Comment by BYK** [comment]
Seems like upstream is fixed now with https://github.com/rust-windowing/winit/pull/1013

**Comment by benrosenblum** [comment]
I get the same behavior as @Jiehong with 0.4.2 on Windows 10 Version 1909.

Relevant section of config:
```yaml
window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 0
    y: 0

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  decorations: full

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Maximized
```
