### ISSUE TITLE
Certain UTF-8 characters not showing

### ISSUE THREAD

**Issue by miguelmota** [alacritty/alacritty#2800]
Alacritty doesn't show certain UTF-8 characters, for example, like the Russian ruble sign `₽`

iTerm on the left, Alacritty on the right

<img width="1178" alt="Screen Shot 2019-09-14 at 7 23 44 PM" src="https://user-images.githubusercontent.com/168240/64915838-6634aa00-d725-11e9-9234-2339ac974b9f.png">

Using default config settings

macOS version 10.14.6

**Comment by kchibisov** [comment]
What’s your output of `locale` in alacritty?

**Comment by miguelmota** [comment]
Output of `locale` in Alacritty:

```bash
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

@kchibisov

**Comment by chrisduerr** [comment]
You seem to be using different fonts here. Does switching the Alacritty font to what you're using in iTerm fix this?

**Comment by miguelmota** [comment]
Current font in iTerm

<img width="575" alt="Screen Shot 2019-09-15 at 5 51 15 PM" src="https://user-images.githubusercontent.com/168240/64930026-9477bf80-d7e1-11e9-9816-ff66d38c61b8.png">


Updated alacritty config in `/Users/mota/.config/alacritty/alacritty.yml`

```yaml
# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    family: DejaVu Sans Mono for Powerline

    # The `style` can be specified to pick a specific face.
    #style: Regular
    style: Book

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: DejaVu Sans Mono Bold for Powerline

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: DejaVu Sans Mono Oblique for Powerline

    # The `style` can be specified to pick a specific face.
    #style: Italic
    style: Oblique

  # Point size
  size: 11.0
```

Restarted Alacritty but some symbols still show up as blank

<img width="1505" alt="Screen Shot 2019-09-15 at 5 55 29 PM" src="https://user-images.githubusercontent.com/168240/64930073-0f40da80-d7e2-11e9-99b8-7978860046fa.png">

**Comment by kchibisov** [comment]
Would you mind launching `Alacritty` from iterm and retesting?

**Comment by miguelmota** [comment]
Same problem when launching Alacritty from iTerm; see gif

![dXnQOwjp6I](https://user-images.githubusercontent.com/168240/64933111-4e7a2600-d7f8-11e9-8519-a537e6e339e4.gif)

**Comment by chrisduerr** [comment]
Could you try the default macOS terminal? Does that behave like iTerm or Alacritty?

**Comment by miguelmota** [comment]
The default macOS Terminal.app behaves like iTerm where the symbols are displayed as expected

**Comment by kchibisov** [comment]
I'm not sure about the close of this issue, but could you retest @miguelmota the latest master?

**Comment by chrisduerr** [comment]
Since you're locale is already en_US.UTF-8, this is not a locale issue. So 7901b45 should not have closed this, thanks @kchibisov.

**Comment by miguelmota** [comment]
I built from master but still having the same problem where some characters don't show up.

![1588321363565_image_png](https://user-images.githubusercontent.com/168240/80792939-957c1800-8b4a-11ea-9bd6-26fd253e4c77.png)

**Comment by kchibisov** [comment]
Thanks for one more testing. I guess it's related to a bit strange font fallbacks behavior on macOS, so you should manually add some fonts to a list, which OS is giving you for a font you've requested, so it seems like it's not fully covering them or something like that. However I'm not sure why missing glyph isn't showing, however when I was testing it, I didn't get missing glyph either.

**Comment by chrisduerr** [comment]
Hmm maybe the glyph isn't missing?

This might sound strange, but usually when a glyph is missing a character is rendered that shows that it is. However in this case nothing is rendering.

Usually the only scenario where nothing is rendered should be when a font actually renders the glyph as nothing. So maybe the problem isn't that there is no fallback font found that has this glyph, but the issue is that there is a font and it just doesn't render anything?

**Comment by kchibisov** [comment]
>This might sound strange, but usually when a glyph is missing a character is rendered that shows that it is. However in this case nothing is rendering.

I know, but it's something I can repro quite easy with emojis and leaving only 1 font. Like emojis are not rendered at all, but missing glyph isn't presented. That could happen if our font backend is error out somewhere, so we're ending up with nothing in place.

**Comment by nixpulvis** [comment]
FWIW I just tested copying and pasting this character from Safari into the latest Alacritty master and it seemed to work just fine. I'm running macOS 10.15.6. @miguelmota can you still reproduce this?

**Comment by miguelmota** [comment]
Not sure what's going on but still not working on a stock macbook with macOS 11 Big Sur. Screenshot shows Terminal.app on left and Alacritty on right.

<img width="1136" alt="Screen Shot 2020-09-25 at 3 07 05 PM" src="https://user-images.githubusercontent.com/168240/94320072-e39e1780-ff40-11ea-8a57-f4c872c4e83c.png">

Instructions I followed:

```bash
git clone https://github.com/alacritty/alacritty.git
brew install rust
cd alacritty/
make app
git clone https://github.com/alacritty/alacritty.git
cp -r target/release/osx/Alacritty.app /Applications/
echo "₽" > /tmp/symbol.txt
open /Applications/Alacritty.app
```

**Comment by nixpulvis** [comment]
I'm going to have to assume Big Sur broke something then. If I still have access to this MacBook I've been using to test when it comes out perhaps I'll upgrade, and test again.

**Comment by theodore-s-beers** [comment]
It looks like a number of similar issues have been opened over the months/years. Mine was #4657. Another is #3737.

**Comment by theodore-s-beers** [comment]
@nixpulvis, for what it's worth, I still have one Mac running Catalina, and I just checked and saw the same problem there. The missing characters in Alacritty in my case are double parentheses ⸨ and ⸩. These are used in some NPM progress bars. Glyphs are present in the macOS preinstalled font Geneva, and Terminal.app and iTerm2 are able to locate them.

As for the ruble symbol, I see it rendered in Alacritty, but only because the font that I normally use (Iosevka Term) has the glyph. If I switch to a font that lacks it, no dice.

**Comment by danielfalbo** [comment]
I have more or less the same issue

#4709

**Comment by theodore-s-beers** [comment]
A number of us have ended up in a similar position. The code that determines (among other things) font fallback behavior is in alacritty's [crossfont](https://github.com/alacritty/crossfont) library. Here's [a link](https://github.com/alacritty/crossfont/blob/9d903fd288ca49af3c4a6c029d5683192eff0152/src/darwin/mod.rs#L91) to the exact spot.

It could be a while before someone who actually knows how to address this gets around to it. What I did for a temporary fix—like others, I guess—was to fork crossfont, manually add another high-coverage font (I chose Noto Sans) to the fallback list, and build Alacritty using the modified version of crossfont. It takes only a few minutes.

**Comment by nyngwang** [comment]
@theodore-s-beers
In my case I can type  by pressing `<ctr><shift>k` while in alacritty it doesn't respond. Is this related to the second link? Thanks in advance...

**Comment by theodore-s-beers** [comment]
@nyngwang, that sounds to me like it might be a different issue. What happens if you copy the character  to your clipboard and try to paste it in Alacritty?

**Comment by rpearce** [comment]
I'm having the same issue on latest Catalina 10.15.7 with all font icons coming from any nerd font I try. My test case is the icons coming from [exa](https://github.com/ogham/exa).

✅ iTerm2
✅ alacritty launched via iTerm2
❌ alacritty

Left is alacritty and right is alacritty launched via iTerm2:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/592876/119271034-383c8400-bbef-11eb-8690-5df30fa9df9e.png">

The picture above is using this `alacritty.yml` font config:

```yml
font:
  normal:
    family: FiraMono Nerd Font
    style: Regular

  bold:
    family: FiraMono Nerd Font
    style: Bold
```
