### ISSUE TITLE
Bold font is used for normal font

### ISSUE THREAD

**Issue by juw** [alacritty/alacritty#3257]
Hi,

alacritty picks up the wrong font for the normal font: what I have configured as bold font is used as regular font and the `normal` part of the font configuration is ignored.

Cheers.

### System

OS: Linux (Debian Sid(
Version: alacritty 0.4.2-dev (6b327b6)
Linux/BSD: X11, i3

### Logs

Font/Terminal size: `alacritty -vv`

### Font part of config

```
# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: Source Code Variable

    # The `style` can be specified to pick a specific face.
    style: Semibold

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Source Code Variable

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Source Code Variable

    # The `style` can be specified to pick a specific face.
    style: Semibold Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Source Code Variable

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 6.5
```
