### ISSUE TITLE
Can't render Chinese characters in bold face

### ISSUE THREAD

**Issue by hkunzhe** [alacritty/alacritty#3271]
### System

OS: macOS Mojave
Version: 0.4.1

### Logs

It's a bit weird when I type `alacritty` in terminal, outputing with `zsh: command not found: alacritty`

### Font configuration
```
font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: Hack Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: Hack Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic
```

In alacritty:
![image](https://user-images.githubusercontent.com/30763967/73516016-3404ba00-4432-11ea-9bce-bc0ad789d627.png)
In iTerm2:
![image](https://user-images.githubusercontent.com/30763967/73516043-441c9980-4432-11ea-8c44-b3fe34338a35.png)
As the pictures show above, the characters `中文` is not correctly rendered as bold face in alacritty compared to iTerm2.
