### ISSUE TITLE
Configurable URL Formats

### ISSUE THREAD

**Issue by samcal** [alacritty/alacritty#3408]
# Feature Request

After reading [this article](https://banga.github.io/blog/2020/03/02/little-known-features-of-iterm2.html), I was envious of the ability to configure different link formats, which is a feature of iTerm. I wonder if Alacritty could extend its ability to configure a url launcher to include other reference types, such as clicking on a git commit hash to open the commit in GitHub.

## Rough Configuration Proposal

Disclaimer: not particularly familiar with YAML, but this illustrates what I would like to see:

```yaml
launchers:
  url:
    regex: <some good url regex>
    modifiers: None
    launcher:
      program: xdg-open
      args: []
  hub:
    regex: [0-9a-f]{8,40}
    modifiers: None
    launcher:
      program: /usr/local/bin/hub
      args: ["browse", "-- commit/"]
      
```
