### ISSUE TITLE
Errors displaying powerline fonts (Ubuntu 19.10)

### ISSUE THREAD

**Issue by aslatter** [alacritty/alacritty#3464]
Prior to commit 84f57ac8 (identified via *git bisect*) I had successfully been using a "powerline" shell-prompt using the "Fira Mono" font. Specifically, I'm using the "agnoster" oh-my-zsh theme, if that's helpful.

Example before (on commit 14dc170):

![Screenshot from 2020-03-14 21-36-27](https://user-images.githubusercontent.com/44175/76694069-1b481080-663c-11ea-9cdb-d0be28632347.png)

Example after (on commit 84f57ac8):

![image](https://user-images.githubusercontent.com/44175/76694079-50546300-663c-11ea-984a-37070cc32c80.png)

### System

OS: Linux
Version: alacritty 0.5.0-dev (e272572)
Linux/BSD: X11/Wayland, DE or Compositor and WM: Whatever stock Ubuntu 19.10 is.

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`

```
[2020-03-14 21:33:30.381619295] [INFO] Welcome to Alacritty
[2020-03-14 21:33:30.382721496] [INFO] Configuration loaded from "/home/redacted/.config/alacritty/alacritty.yml"
[2020-03-14 21:33:30.393281093] [DEBUG] Estimated DPR: 1
[2020-03-14 21:33:30.393314647] [DEBUG] Estimated Cell Size: 14 x 27
[2020-03-14 21:33:30.393321130] [DEBUG] Estimated Dimensions: None
[2020-03-14 21:33:30.416520032] [INFO] Device pixel ratio: 1
[2020-03-14 21:33:30.420634041] [INFO] Initializing glyph cache...
[2020-03-14 21:33:30.435350588] [INFO] ... finished initializing glyph cache in 0.01467219s
[2020-03-14 21:33:30.435391252] [INFO] Cell Size: 14 x 27
[2020-03-14 21:33:30.435400038] [INFO] Padding: 2 x 2
[2020-03-14 21:33:30.435431891] [INFO] Width: 800, Height: 600
[2020-03-14 21:33:30.437412960] [INFO] PTY Dimensions: Line(22) x Column(56)
[2020-03-14 21:33:30.443444437] [INFO] Initialisation complete
[2020-03-14 21:33:30.446742826] [DEBUG] Term::resize dimensions unchanged
[2020-03-14 21:33:30.446970023] [INFO] Width: 800, Height: 600
[2020-03-14 21:33:30.480698993] [DEBUG] New num_cols is 131 and num_lines is 37
[2020-03-14 21:33:30.481831771] [INFO] Width: 1850, Height: 1016
[2020-03-14 21:33:33.108794312] [INFO] Goodbye
```

Keyboard and bindings: `alacritty --print-events`
(let me know if you want this)

**Comment by aslatter** [comment]
I think I'm using this version of Fira Mono: https://github.com/mozilla/Fira

The built-in terminal has the same rendering bug as Alacritty as of 84f57ac8367e3e24e0347515e6681c0478fc3d29.

The bug seems specific to \ue0b0 and \ue0a0 - the other glyphs in the recommended powerline test seem to show up fine.

If I switch to the "Hack" font in both "alacritty 0.5.0-dev (e272572)" and the default Ubuntu 19.10 terminal the glyphs show up as expected in both (however there is a weird alignment issue in Alacritty not seen in the built-in terminal). So maybe this is something specific to Fira Mono?

**Comment by aslatter** [comment]
And if I install "Fira Mono for Powerline" from here https://github.com/powerline/fonts/tree/master/FiraMono I get working powerline-glyphs.

So I'm a bit stumped as to how the old version of Alacritty was even able to display the glyphs using a non-powerline-patched version of the font.

Maybe there was some old fallback behavior somehow?

**Comment by aslatter** [comment]
(my recent tests were on e272572, which for these purposes has been pretty much the same as 84f57ac as far as I can tell)

**Comment by kchibisov** [comment]
The font fallback was changed, indeed, but it wasn't on the commit you've bisected, so it's pretty strange to see such change on this commit. Anyway, we should at least understand what happened on it.

>So I'm a bit stumped as to how the old version of Alacritty was even able to display the glyphs using a non-powerline-patched version of the font.

You've likely had them somewhere, idk.

>Maybe there was some old fallback behavior somehow?

Well, old fallback is on v0.4.1. which could do such thing, but both commits you've linked are using new fallback behavior.

**Comment by kchibisov** [comment]
Could you provide me the output files from the this 2 patches. Just use log with `alacritty > master.txt`/`alacritty > old.txt` and upload 2 txt files.

For master:
```diff
diff --git a/font/src/ft/mod.rs b/font/src/ft/mod.rs
index d2a99ca..8b8d449 100644
--- a/font/src/ft/mod.rs
+++ b/font/src/ft/mod.rs
@@ -240,12 +240,19 @@ impl FreeTypeRasterizer {
 
         let primary_font =
             matched_fonts.next().ok_or_else(|| Error::MissingFont(desc.to_owned()))?;
+        print!(
+            "Primary font family {:?}, path: {:?}, style: {:?}",
+            primary_font.family(),
+            primary_font.file(0),
+            primary_font.style()
+        );
 
         // We should render patterns to get values like `pixelsizefixupfactor`
         let primary_font = pattern.render_prepare(config, primary_font);
 
         // Hash pattern together with request pattern to include requested font size in the hash
         let primary_font_key = FontKey::from_pattern_hashes(hash, primary_font.hash());
+        println!(" key {:?}", primary_font_key);
 
         // Return if we already have the same primary font
         if self.fallback_lists.contains_key(&primary_font_key) {
@@ -278,6 +285,19 @@ impl FreeTypeRasterizer {
 
         self.fallback_lists.insert(primary_font_key, FallbackList { list, coverage });
 
+        println!("Dumping fallback list");
+
+        for font in &self.fallback_lists.get(&primary_font_key).unwrap().list {
+            println!(
+                "Family {:?}, path: {:?}, style: {:?}, key: {:?}",
+                font.pattern.family(),
+                font.pattern.file(0),
+                font.pattern.style(),
+                font.key
+            );
+        }
+        println!("----------------------------------------");
+
         Ok(primary_font_key)
     }
 
@@ -358,11 +378,14 @@ impl FreeTypeRasterizer {
             let index = face.ft_face.get_char_index(glyph_key.c as usize);
 
             if index != 0 {
+                println!("For char {} - using key {:?}", glyph_key.c, glyph_key.font_key);
                 return Ok(glyph_key.font_key);
             }
         }
 
-        Ok(self.load_face_with_glyph(glyph_key).unwrap_or(glyph_key.font_key))
+        let key = self.load_face_with_glyph(glyph_key).unwrap_or(glyph_key.font_key);
+        println!("For char {} - using key {:?}", glyph_key.c, key);
+        Ok(key)
     }
 
     fn load_face_with_glyph(&mut self, glyph: GlyphKey) -> Result<FontKey, Error> {

```

and for  14dc170 :
```diff
diff --git a/font/src/ft/mod.rs b/font/src/ft/mod.rs
index 385c66d..3269fdf 100644
--- a/font/src/ft/mod.rs
+++ b/font/src/ft/mod.rs
@@ -248,12 +248,19 @@ impl FreeTypeRasterizer {
 
         let primary_font =
             matched_fonts.next().ok_or_else(|| Error::MissingFont(desc.to_owned()))?;
+        print!(
+            "Primary font family {:?}, path: {:?}, style: {:?}",
+            primary_font.family(),
+            primary_font.file(0),
+            primary_font.style()
+        );
 
         // We should render patterns to get values like `pixelsizefixupfactor`
         let primary_font = pattern.render_prepare(config, primary_font);
 
         // Hash pattern together with request pattern to include requested font size in the hash
         let primary_font_id = FontID::new(hash, primary_font.hash());
+        println!(" ID {:?}", primary_font_id);
 
         // Reload already loaded faces and drop their fallback faces
         let font_key = if let Some(font_key) = self.keys.remove(&primary_font_id) {
@@ -300,6 +307,19 @@ impl FreeTypeRasterizer {
 
         self.fallback_lists.insert(font_key, FallbackList { list, coverage });
 
+        println!("Dumping fallback list for font_key {:?}", font_key);
+
+        for font in &self.fallback_lists.get(&font_key).unwrap().list {
+            println!(
+                "Family {:?}, path: {:?}, style: {:?}, ID: {:?}",
+                font.pattern.family(),
+                font.pattern.file(0),
+                font.pattern.style(),
+                font.id
+            );
+        }
+        println!("----------------------------------------");
+
         Ok(font_key)
     }
 
@@ -380,6 +400,7 @@ impl FreeTypeRasterizer {
             let index = face.ft_face.get_char_index(glyph_key.c as usize);
 
             if index != 0 {
+                println!("For char {} - using key {:?}", glyph_key.c, glyph_key.font_key.token);
                 return Ok(glyph_key.font_key);
             }
         }
@@ -409,6 +430,7 @@ impl FreeTypeRasterizer {
 
                     // We found something in a current face, so let's use it
                     if index != 0 {
+                        println!("For char {} - using ID {:?}", glyph.c, font_id);
                         return Ok(key);
                     }
                 },
@@ -419,6 +441,7 @@ impl FreeTypeRasterizer {
 
                     let pattern = font_pattern.clone();
                     let key = self.face_from_pattern(&pattern, font_id, None)?.unwrap();
+                    println!("For char {} - using ID {:?}", glyph.c, font_id);
                     return Ok(key);
                 },
             }

```

**Comment by aslatter** [comment]
Here you go:

[old.txt](https://github.com/alacritty/alacritty/files/4335605/old.txt)
[master.txt](https://github.com/alacritty/alacritty/files/4335606/master.txt)

**Comment by kchibisov** [comment]
Could you share your config `font` section and provide me the output from.

`fc-match -s 'Fira Mono:style=Italic:pixelsize=12'`

**Comment by kchibisov** [comment]
In addition could you provide output from this patch on 14dc170

```diff
diff --git a/font/src/ft/mod.rs b/font/src/ft/mod.rs
index 385c66d..e394c34 100644
--- a/font/src/ft/mod.rs
+++ b/font/src/ft/mod.rs
@@ -248,12 +248,19 @@ impl FreeTypeRasterizer {

         let primary_font =
             matched_fonts.next().ok_or_else(|| Error::MissingFont(desc.to_owned()))?;
+        print!(
+            "Primary font family {:?}, path: {:?}, style: {:?}",
+            primary_font.family(),
+            primary_font.file(0),
+            primary_font.style()
+        );

         // We should render patterns to get values like `pixelsizefixupfactor`
         let primary_font = pattern.render_prepare(config, primary_font);

         // Hash pattern together with request pattern to include requested font size in the hash
         let primary_font_id = FontID::new(hash, primary_font.hash());
+        println!(" ID {:?}", primary_font_id);

         // Reload already loaded faces and drop their fallback faces
         let font_key = if let Some(font_key) = self.keys.remove(&primary_font_id) {
@@ -300,6 +307,19 @@ impl FreeTypeRasterizer {

         self.fallback_lists.insert(font_key, FallbackList { list, coverage });

+        println!("Dumping fallback list for font_key {:?}", font_key);
+
+        for font in &self.fallback_lists.get(&font_key).unwrap().list {
+            println!(
+                "Family {:?}, path: {:?}, style: {:?}, ID: {:?}",
+                font.pattern.family(),
+                font.pattern.file(0),
+                font.pattern.style(),
+                font.id
+            );
+        }
+        println!("----------------------------------------");
+
         Ok(font_key)
     }

@@ -380,6 +400,7 @@ impl FreeTypeRasterizer {
             let index = face.ft_face.get_char_index(glyph_key.c as usize);

             if index != 0 {
+                println!("For char {} - using key {:?}", glyph_key.c, glyph_key.font_key.token);
                 return Ok(glyph_key.font_key);
             }
         }
@@ -388,6 +409,7 @@ impl FreeTypeRasterizer {
     }

     fn load_face_with_glyph(&mut self, glyph: GlyphKey) -> Result<FontKey, Error> {
+        println!("Searching fallback for {:?}", glyph.font_key);
         let fallback_list = self.fallback_lists.get(&glyph.font_key).unwrap();

         // Check whether glyph is presented in any fallback font
@@ -398,6 +420,7 @@ impl FreeTypeRasterizer {
         for fallback_font in &fallback_list.list {
             let font_id = fallback_font.id;
             let font_pattern = &fallback_font.pattern;
+            println!("Trying pattern {:?}", font_pattern.family());
             match self.keys.get(&font_id) {
                 Some(&key) => {
                     let face = match self.faces.get(&key) {
@@ -409,6 +432,7 @@ impl FreeTypeRasterizer {

                     // We found something in a current face, so let's use it
                     if index != 0 {
+                        println!("For char {} - using ID {:?}", glyph.c, font_id);
                         return Ok(key);
                     }
                 },
@@ -419,6 +443,7 @@ impl FreeTypeRasterizer {

                     let pattern = font_pattern.clone();
                     let key = self.face_from_pattern(&pattern, font_id, None)?.unwrap();
+                    println!("For char {} - using ID {:?}", glyph.c, font_id);
                     return Ok(key);
                 },
             }
```

**Comment by aslatter** [comment]
Output of `fc-match -s 'Fira Mono:style=Italic:pixelsize=12'`:

[fc_match.txt](https://github.com/alacritty/alacritty/files/4335729/fc_match.txt)

Output of second patch on 14dc170caafc47a46d4c040a17829b52d431bbcd:

[old_2.txt](https://github.com/alacritty/alacritty/files/4335730/old_2.txt)

**Comment by aslatter** [comment]
Ooops, I forgot the font config - it isn't very customized (but perhaps old):

```yaml
font:
  # The normal (roman) font face to use.
  normal:
    family: "Fira Mono" # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: "Fira Mono" # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: "Fira Mono" # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 17

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # Scale the font size based on the monitor's DPI. This will lead to bigger text on HiDPI
  # screens and make reading text a little easier.
  # On X11 it is possible to change the DPI for each instance of alacritty by using
  # `WINIT_HIDPI_FACTOR=1.0 alacritty` to scale the font.
  # scale_with_dpi: true

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true
```
