### ISSUE TITLE
URL Launcher Config is in Wrong Place

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#3497]
Currently the configuration for the URL launcher is `mouse.url.launcher`, which made sense before the addition of `VI` mode. However, now we should decide on a better place for this config, since the `Open` action can be used to open a URL without the use of the mouse at all.

This is a little awkward, since `mouse.url.modifiers` still makes sense, and we'd end up with duplicated `url` keys. Perhaps duplicate `mouse` keys is better, making my current suggestion:

```yaml
url:
  launcher: ...
  mouse:
    modifiers: ...

mouse: ...
```
