### ISSUE TITLE
[BUG] Primary background color will overwrite the symbols color

### ISSUE THREAD

**Issue by ztlevi** [alacritty/alacritty#3524]
By setting the foreground and background like this
```
colors:
  # Default colors
  primary:
    background: "0xeeeeee"
    foreground: "0x2d2d2c"
```

The language symbols (python sneak or rust crab) become completely white. 

I'm not able to upload screenshots from the company's laptop but it should be pretty easy to reproduce.

### System

OS: Linux/macos
Version: 0.41
