### ISSUE TITLE
New feature: Make various cursor dimensions configurable

### ISSUE THREAD

**Issue by f1reflyyyylmao** [alacritty/alacritty#3526]
I think it'd be great if the beam width could be adjusted from the configuration file. I'm not sure how the cursor is rendered and what scale could be applied, but some way of adjusting it should probably exist. In a discussion on irc @kchibisov said it'd be nice to have some sort of option to tune the style of the underline as well. 

A good solution would likely be a uniform way of tuning the different cursor styles, my proposed format for the configuration file is:
```
cursor:
  style: [Block/Underline/Beam]
  height: [\dpx]
  width: [\dpx]

  Underline:
    height: [\dpx]
    width: [\dpx] (inhibit from default)
  Beam:
    height: [\dpx] (inhibit from default)
    width: [\dpx]
  Box:
    height: [\dpx] (inhibit from default)
    width: [\dpx] (inhibit from default)
    border_thickness: [\dpx]
```

**Comment by chrisduerr** [comment]
I personally think this would make cursor configuration far too complex and it's actually less reliable than what we have today. Currently the width is calculated based on your font, so you can actually change the width by switching out your font with one that has metrics you prefer.

Setting the width in the config does not work, since it will prevent automatic scaling from working when you change your font size. The dimensions of cursors like the box also should never be anything different than the cell rects.

**Comment by kchibisov** [comment]
> Currently the width is calculated based on your font, so you can actually change the width by switching out your font with one that has metrics you prefer.

This is not entirely true, cursors is being calculated based on cell metrics, which you get from the font, so it has little to do with font tbh. We're not using underline metrics, etc, also if we use underline metrics, it could be hard to distinguish Underline cursor and Underline in some cases with small font.

>Setting the width in the config does not work, since it will prevent automatic scaling from working when you change your font size.

I agree with you here, it won't work, however if you use some base metrics like we have today and width will be percent of this setting, it'll work, so you'll be getting 20% thicker cursor, which will work, and limit it to let's say 100% of the base.

>The dimensions of cursors like the box also should never be anything different than the cell rects.

I absolutely agree with you here and I think we shouldn't touch block cursor at all.

So if I would propose such change, I'll likely do the following.
```yaml
cursor:
  style: [Block/Underline/Beam]

  Underline:
    # I doubt you want less width for this thing.
    height: 0.5 - 2
  Beam:
    height: 0.85 - 1.15 
    width: 0.5 - 2.
```

Those values for `height` and `width` are multiplier of our current base width/height, which should work well with scaling, etc.
