### ISSUE TITLE
URL Launcher doesn't work on macOS with alternate launchers

### ISSUE THREAD

**Issue by nchase** [alacritty/alacritty#3531]
### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty 0.4.2-rc4 (3d5fe5f)`

### Logs

I supplied an alternate program to execute for clicked URLs, e.g.:

```yaml
mouse:
 
  url:
    launcher:
      program: open -a Safari

```

And in my Alacritty logs, after clicking:

```
[2020-03-29 21:12:43.063060000] [WARN] Unable to launch open -a Safari with args ["https://www.google.com"]
```

Same behavior for other browsers

**Comment by cole-h** [comment]
That's because Alacritty is trying to use an executable named `open -a Safari`, not `open` with the arguments `-a Safari`. Try the following:

```yaml
mouse:
  url:
    launcher:
      program: open
      args: [ "-a Safari" ] # if that doesn't work, try separating them out: `[ "-a" "Safari" ]`
```
