### ISSUE TITLE
hintfull setting is not respected

### ISSUE THREAD

**Issue by mahkoh** [alacritty/alacritty#3534]
I've configured hintfull in fontconfig:

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <match target="font">
  <edit mode="assign" name="hintstyle">
   <const>hintfull</const>
  </edit>
 </match>
</fontconfig>
 ```

This is recognized by alacritty. I've not disabled antialiasing for any font. Therefore alacritty uses the following code path:

https://github.com/alacritty/alacritty/blob/fde2424b398dadd2310686b365041189decd1d63/font/src/ft/mod.rs#L491

hintfull is not applied in this case.

Disabling antialiasing via fontconfig makes the font ragged in alacritty and other programs and is therefore not an option.

This problem is specific to alacritty. Hinting works as expected in all other programs I'm using.

The following patch fixes the problem:

```
diff --git a/font/src/ft/mod.rs b/font/src/ft/mod.rs
index d393b63..76b0dc7 100644
--- a/font/src/ft/mod.rs
+++ b/font/src/ft/mod.rs
@@ -453,7 +453,7 @@ impl FreeTypeRasterizer {
     }
 
     fn ft_load_flags(pattern: &PatternRef) -> freetype::face::LoadFlag {
-        let antialias = pattern.antialias().next().unwrap_or(true);
+        let antialias = pattern.antialias().next().unwrap_or(false);
         let hinting = pattern.hintstyle().next().unwrap_or(fc::HintStyle::Slight);
         let rgba = pattern.rgba().next().unwrap_or(fc::Rgba::Unknown);
         let embedded_bitmaps = pattern.embeddedbitmap().next().unwrap_or(true);
```

Current master with antialiasing enabled:
![2020-03-30-094447_412x159_scrot](https://user-images.githubusercontent.com/1882250/77887817-87955780-726b-11ea-82f6-ce6df9e3588d.png)
Current master with the patch applied and antialiasing enabled:
![2020-03-30-094529_371x156_scrot](https://user-images.githubusercontent.com/1882250/77887820-882dee00-726b-11ea-8380-a058be7c5f36.png)
Current master with antialiasing disabled:
![2020-03-30-094617_345x151_scrot](https://user-images.githubusercontent.com/1882250/77887821-882dee00-726b-11ea-9113-ccf5c1733ce2.png)

**Comment by kchibisov** [comment]
All 3 screenshots are different for me tbh. The following patch doesn't make any sense, since AA shouldn't be turned off. I feel like our FreeType loading flags are not optimal in some cases.

**Comment by mahkoh** [comment]
>All 3 screenshots are different for me tbh.

Yes that is the point. The second screenshot (Current master with the patch applied and antialiasing enabled) is the desired result. This is how fonts are rendered in all other programs and how I want them to be rendered.

>The following patch doesn't make any sense, since AA shouldn't be turned off.

Of course I'm not saying that this patch should be applied. It merely shows that alacritty's decision to use the antialiasing configuration in fontconfig to make hinting decisions leads to inconsistent results.

**Comment by mahkoh** [comment]
>The following patch doesn't make any sense, since AA shouldn't be turned off.

And of course AA **isn't** turned off even with the patch applied as you can see from my screenshots.

**Comment by kchibisov** [comment]
FWIW each font on my system, except bitmap/emoji fonts require AA according to Fontconfig, and alacritty is just following it. However I really feel like our loading flags are a bit messed up or we're not using AA correctly.

**Comment by Dettorer** [comment]
Small contribution to debugging this: I took some screenshots comparing Alacritty on hintfull against urxvt on every level of hinting. Antialiasing is on in each screenshot, the font is DejaVu Sans Mono, size 12 on urxvt, 9.5 on Alacritty (I don't know why those settings differ and how this factors in the issue here, but 9.5 seems to give me the same font size as my usual urxvt does).

Renderer | rendered
------------ | ------------
Alacritty, hintfull | ![alacritty_hintfull](https://user-images.githubusercontent.com/2761682/86283685-bbbd4300-bbe1-11ea-8372-11065dd22139.png)
urxvt, hintfull | ![urxvt_hintfull](https://user-images.githubusercontent.com/2761682/86283686-bc55d980-bbe1-11ea-8a9e-1170c307cf27.png)
urxvt, hintmedium | ![urxvt_hintmedium](https://user-images.githubusercontent.com/2761682/86283689-bcee7000-bbe1-11ea-94e5-75cd55a18980.png)
urxvt, hintslight | ![urxvt_hintslight](https://user-images.githubusercontent.com/2761682/86283693-be1f9d00-bbe1-11ea-9065-af10e79bd42f.png)
urxvt, hintnone | ![urxvt_hintnone](https://user-images.githubusercontent.com/2761682/86283692-bd870680-bbe1-11ea-8f04-91c76ab279e8.png)

The difference is small, but noticeable. I also notice that Alacritty's render on hintfull doesn't match with any hint level with urxvt.

I tried to see how the patch proposed in the first message of this issue changes the rendering, the code seems to have changed quite a bit since it was posted and applying it does not change anything (to my knowledge) to the rendering.

I also tried to compare the load flags actually used on my setup in both Alacritty and urxvt on hintfull, they were the same (`0x0` in both case, the default). This is just my particular setup but load flags don't seem to be a problem.

For reference, some config files on my setup (archlinux, last git version of urxvt and Alacritty):

<details>
    <summary>.Xresources</summary>

```
!--------------------
! rxvt-unicode

!---------------------------------------------------------------!
! .Xdefaults: kushou s main configuration file for rxvt-unicode !
!---------------------------------------------------------------!
!--------------------
! Main Configuration

*.background:           [85]black
*.foreground:           #dcdcdc
*.font:                 xft:DejaVu Sans Mono:pixelsize=12,xft:Symbola:pixelsize=12,xft:DejaVuSansMono Nerd Font:pixelsize=12
URxvt.scrollBar:        false
URxvt.urgentOnBell:     true

URxvt.perl-ext-common:  default,matcher,clipboard,url-select,keyboard-select,font-size
URxvt.url-launcher:     /usr/bin/firefox
URxvt.matcher.button:   1

urxvt*depth: 32

urxvt*cursorColor:      cyan

urxvt*termName:         rxvt-256color

URxvt.url-select.underline: true
URxvt.keysym.M-u:           perl:url-select:select_next
URxvt.keysym.M-Escape:      perl:keyboard-select:activate
URxvt.keysym.M-s:           perl:keyboard-select:search

XTerm*metaSendsEscape: true

! rebind some font-size functions
URxvt.keysym.C-equal:  font-size:reset

! bindings that switches between opaque white and transparent black
URxvt.keysym.C-quotedbl: command:\033]11;white\007\033]10;black\007
URxvt.keysym.C-guillemotleft: command:\033]11;[85]black\007\033]10;#dcdcdc\007

!-------------------------------------------------
! Colors
! black, red, green, yellow, blue, magenta, cyan, white
! Tango Color Theme

*color0:    #2E3436
*color1:    #CC0000
*color2:    #4E9A06
*color3:    #C4A000
*color4:    #3465A4
*color5:    #75507B
*color6:    #06989A
*color7:    #D3D7CF
*color8:    #555735
*color9:    #EF2929
*color10:   #8AE234
*color11:   #FCE94F
*color12:   #729FCF
*color13:   #AD7DA8
*color14:   #34E2E2
*color15:   #EEEEEC
```
</details>

<details>
  <summary>.alacritty.yml</summary>

```yaml
# Configuration for Alacritty, the GPU enhanced terminal emulator


# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color

# Window dimensions in character columns and lines
# (changes require restart)
dimensions:
  columns: 80
  lines: 24

# Adds this many blank pixels of padding around the window
# Units are physical pixels; this is not DPI aware.
# (change requires restart)
window:
  padding:
    x: 2
    y: 2

# The FreeType rasterizer needs to know the device DPI for best results
# (changes require restart)
dpi:
  x: 95.0
  y: 96.0

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: DejaVu Sans Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: DejaVu Sans Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: DejaVu Sans Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Oblique

  # Point size of the font
  size: 9.5

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

# Should display the render timer
debug.render_timer: false

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: false

# Colors (Tomorrow Night Bright)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xeaeaea'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x2e3436'
    red:     '0xcc0000'
    green:   '0x4e9a06'
    yellow:  '0xC4A000'
    blue:    '0x3465A4'
    magenta: '0x75507B'
    cyan:    '0x06989A'
    white:   '0xD3D7CF'

  # Bright colors
  bright:
    black:   '0x555735'
    red:     '0xEF2929'
    green:   '0x8AE234'
    yellow:  '0xFCE94F'
    blue:    '0x729FCF'
    magenta: '0xAD7DA8'
    cyan:    '0x34E2E2'
    white:   '0xEEEEEC'

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
visual_bell:
  animation: EaseOutExpo
  duration: 0

# Key bindings
#
# Each binding is defined as an object with some properties. Most of the
# properties are optional. All of the alphabetical keys should have a letter for
# the `key` value such as `V`. Function keys are probably what you would expect
# as well (F1, F2, ..). The number keys above the main keyboard are encoded as
# `Key1`, `Key2`, etc. Keys on the number pad are encoded `Number1`, `Number2`,
# etc.  These all match the glutin::VirtualKeyCode variants.
#
# Possible values for `mods`
# `Command`, `Super` refer to the super/command/windows key
# `Control` for the control key
# `Shift` for the Shift key
# `Alt` and `Option` refer to alt/option
#
# mods may be combined with a `|`. For example, requiring control and shift
# looks like:
#
# mods: Control|Shift
#
# The parser is currently quite sensitive to whitespace and capitalization -
# capitalization must match exactly, and piped items must not have whitespace
# around them.
#
# Either an `action` or `chars` field must be present. `chars` writes the
# specified string every time that binding is activated. These should generally
# be escape sequences, but they can be configured to send arbitrary strings of
# bytes. Possible values of `action` include `Paste` and `PasteSelection`.
#
# Want to add a binding (e.g. "PageUp") but are unsure what the X sequence
# (e.g. "\x1b[5~") is? Open another terminal (like xterm) without tmux,
# then run `showkey -a` to get the sequence associated to a key combination.
key_bindings:
  # - { key: V,        mods: Control|Shift,    action: Paste               }
  # - { key: C,        mods: Control|Shift,    action: Copy                }
  # - { key: Q,        mods: Command, action: Quit                         }
  # - { key: W,        mods: Command, action: Quit                         }
  # - { key: Insert,   mods: Shift,   action: PasteSelection               }
  # - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  # - { key: Home,                    chars: "\x1b[1~",  mode: ~AppCursor  }
  # - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  # - { key: End,                     chars: "\x1b[4~",  mode: ~AppCursor  }
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp                 }
  # - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                   }
  # - { key: PageUp,                  chars: "\x1b[5~"                     }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown               }
  # - { key: PageDown, mods: Control, chars: "\x1b[6;5~"                   }
  # - { key: PageDown,                chars: "\x1b[6~"                     }
  # - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
  # - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  # - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  # - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  # - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  # - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  # - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  # - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  # - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  # - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  # - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  # - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  # - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  # - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  # - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  # - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  # - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  # - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  # - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  # - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
  # - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                      }
  # - { key: F1,                      chars: "\x1bOP"                      }
  # - { key: F2,                      chars: "\x1bOQ"                      }
  # - { key: F3,                      chars: "\x1bOR"                      }
  # - { key: F4,                      chars: "\x1bOS"                      }
  # - { key: F5,                      chars: "\x1b[15~"                    }
  # - { key: F6,                      chars: "\x1b[17~"                    }
  # - { key: F7,                      chars: "\x1b[18~"                    }
  # - { key: F8,                      chars: "\x1b[19~"                    }
  # - { key: F9,                      chars: "\x1b[20~"                    }
  # - { key: F10,                     chars: "\x1b[21~"                    }
  # - { key: F11,                     chars: "\x1b[23~"                    }
  # - { key: F12,                     chars: "\x1b[24~"                    }
  # - { key: Back,                    chars: "\x7f"                        }
  # - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    }
  # - { key: Insert,                  chars: "\x1b[2~"                     }
  # - { key: Delete,                  chars: "\x1b[3~"                     }

# Mouse bindings
#
# Currently doesn't support modifiers. Both the `mouse` and `action` fields must
# be specified.
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# Values for `action`:
# - Paste
# - PasteSelection
# - Copy (TODO)
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

url:
  launcher: xdg-open

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

hide_cursor_when_typing: false

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#shell:
#  program: /bin/bash
#  args:
#    - --login
```
</details>

<details>
    <summary>.fonts.conf</summary>

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
    <dir>/usr/share/texmf-dist/fonts/opentype/</dir>

    <match target="font">
        <edit name="hintstyle" mode="assign">
            <const>hintfull</const>
        </edit>
    </match>

    <match target="font">
        <edit mode="assign" name="antialias">
            <bool>true</bool>
        </edit>
    </match>

    <dir>~/.fonts</dir>
</fontconfig>
```
</details>
