### ISSUE TITLE
How to set the shell command. I can't figure out how to make `args` work.

### ISSUE THREAD

**Issue by trusktr** [alacritty/alacritty#3540]
In Gnome Terminal, I simply set my "Custom command" to `nvim '+execute "normal! :term\<enter>i"'` and it works perfectly.

I can't figure out how to set the same thing with Alacritty. For example, this doesn't work:

```yml
shell:                                                                                      
 program: nvim
 args:
   - '+execute "normal! :term<enter>i"'
```

How do we do it?

**Comment by cole-h** [comment]
```yml
shell:                                                                                      
 program: nvim
 args: 
   - '+execute "normal! :term\<enter>i"'
```

The above works for me. Notice that I escaped the first angled bracket, like what you had in Gnome Terminal. You were so close!
