### ISSUE TITLE
Some emojis missing on macOS

### ISSUE THREAD

**Issue by maxcountryman** [alacritty/alacritty#3579]
I seem to be running into a strange issue where a handful of emoji aren't rendering properly in Alacritty. The same emoji render in Terminal, however. (This seems to happen regardless of font and is consistently broken in Alacritty.)

## Alacritty
<img width="832" alt="Screen Shot 2020-04-11 at 3 10 38 PM" src="https://user-images.githubusercontent.com/74351/79056040-23797880-7c07-11ea-8e95-d3a0b00b0e24.png">

## Terminal
<img width="682" alt="Screen Shot 2020-04-11 at 3 13 07 PM" src="https://user-images.githubusercontent.com/74351/79056044-2ecca400-7c07-11ea-956d-1236b2c462dc.png">

Any pointers on what could be going on here would be appreciated! 🙂 

### System

OS: macOS 10.15.4 (19E287)
Version: alacritty 0.4.2 (f68de37)

**Comment by kchibisov** [comment]
They are not missing, they are from your primary font. We'll add option to override curtain glyphs in #957

**Comment by maxcountryman** [comment]
@kchibisov I'm not sure that's what's going on here. For instance, if I change my Alacritty font to match Terminal's (SF Mono), I still see the same issue.

<img width="832" alt="Screen Shot 2020-04-11 at 3 28 54 PM" src="https://user-images.githubusercontent.com/74351/79056240-2a08ef80-7c09-11ea-86dc-3099539f92d7.png">

```yaml
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: SF Mono
```

Are you referring to something else?

**Comment by kchibisov** [comment]
That means that SF Mono has the characters you're testing, since they are not really emojis according to history, macOS can just use emojis when it finds out that glyph is actually an emoji according to their heuristics, a lot of apps are doing the same thing. However I don't like the solution to use special font for special glyphs, based on some strange heuristics(e.g. hardcoding). Could you try some font that doesn't have any emoji chars + special chars at all? e.g. https://github.com/JetBrains/JetBrainsMono

**Comment by maxcountryman** [comment]
No dice:

<img width="832" alt="Screen Shot 2020-04-11 at 3 39 04 PM" src="https://user-images.githubusercontent.com/74351/79056367-9c2e0400-7c0a-11ea-9c3e-906444fe1306.png">

```yaml
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: JetBrains Mono
```
