### ISSUE TITLE
`draw_bold_text_with_bright_colors` option works in reverse

### ISSUE THREAD

**Issue by atchim** [alacritty/alacritty#3616]
`draw_bold_text_with_bright_colors` works in reverse. For example, if I set it true, bold text won't change the color, but if I set this option to false it would change.

### Infos

OS: Funtoo Linux
Window Manager: dwm
Alacritty: alacritty 0.5.0-dev (03bce99)

**Comment by kchibisov** [comment]
How are you testing this? Try this `echo -e "\e[31;1mRED"` It should draw `RED` with bold in normal red color, and toggling `draw_bold_with_with_bright_colors: true` should draw it with bold in bright red(from the config).

**Comment by atchim** [comment]
> How are you testing this?

First I realized that dir colors were bright blue when doing ls. Normally ls show dirs in dark blue. So I noticed that dirs in ls are in bold and I changed `draw_bold_with_with_bright_colors` to true and then the dir colors and all bold text got working fine.

> Try this `echo -e "\e[31;1mRED"`

Did not worked as it should. When `draw_bold_with_with_bright_colors` is false I got bold text in bright colors and vice versa.

**Comment by chrisduerr** [comment]
Sounds like your bold and non-bold colors might be swapped? Only because it's called `bright` colors does not mean it's necessarily brighter. It depends on your colorscheme.

**Comment by kchibisov** [comment]
Could you try this config.You can try config file with `alacritty --config-file alacritty.yml`

```yaml
colors:
  primary:
    background: '#1c1c1c'
    foreground: '#dddddd'

  selection:
    background: '#444444'

  vi_mode_cursor:
    text: '#000000'
    cursor: '#ffffff'

  normal:
    black:   '#1c1c1c'
    red:     '#00ff00'
    green:   '#799d6a'
    yellow:  '#ffb964'
    blue:    '#6d85b0'
    magenta: '#baa6ed'
    cyan:    '#9fbacb'
    white:   '#dddddd'

  bright:
    black:   '#888888'
    red:     '#ff00ff'
    green:   '#99ad6a'
    yellow:  '#fad07a'
    blue:    '#8197bf'
    magenta: '#c6b6ee'
    cyan:    '#8fbfdc'
    white:   '#ffffff'

draw_bold_text_with_bright_colors: true
```

it should show you pink color on `echo -e "\e[31;1mRED"`
