### ISSUE TITLE
Missing or unsuitable terminal

### ISSUE THREAD

**Issue by fuzunspm** [alacritty/alacritty#3633]
### System

OS: Linux
Version: 0.4.2
Linux/BSD: Wayland, Sway

### Issue

I'm trying to attach tmux on a remote server via ssh but whenever i attach it throws the error below:

```
open terminal failed: missing or unsuitable terminal: alacritty
```

in addition to that all of my terminal is acting weird on ssh like backspace is not working, colored username/paths are not visible

### Config File
```
background_opacity: 0.7
draw_bold_text_with_bright_colors: true
font:
  normal:
    family: monospace
  italic:
    family: monospace
  size: 12

live_config_reload: true
```
