### ISSUE TITLE
Multiline Paste in Vim different by file type

### ISSUE THREAD

**Issue by yawpitch** [alacritty/alacritty#3677]
### System

OS: Linux
Version: 0.4.2
Linux/BSD: X11 + I3WM + BASH

Attempting to paste the same content into Vim 8.2 in an Alacritty session results in different content depending on file type:

## vim test.txt
```
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d1f21'
    cursor: '0xc5c8c6'
```

## vim test.yml
```
  # Colors the cursor will use if `custom_cursor_colors` is true
  #   cursor:
  #       text: '0x1d1f21'
  #           cursor: '0xc5c8c6'
```

## vim test.py
```
  # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
            text: '0x1d1f21'
                cursor: '0xc5c8c6'
```

## vim test.rs
```
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
      text: '0x1d1f21'
          cursor: '0xc5c8c6'
```

When I create the same files but using **termite** as the underlying shell there's no difference, all are the same as test.txt above.

However if I switch to **neovim** then multiline paste is consistent in both **termite** and **alacritty**.

Likewise if I `:set paste` _before_ pasting into standard **vim** I get consistent pasting.

Clearly something is misconfigured, somewhere, when it comes to Bracketed Paste Mode, but I've honestly got no idea _what_ part of my setup is the culprit, and since this attempt to move to Alacritty is the first I've run into it I thought I'd ask here.
