### ISSUE TITLE
Char ₿ not being rendered

### ISSUE THREAD

**Issue by ademar111190** [alacritty/alacritty#3737]
The char ₿ [("\u20BF", "\xE2\x82\xBF")](https://en.wikipedia.org/wiki/Currency_Symbols_(Unicode_block)) is not being rendered on alacritty, but it is being rendered on iterm and terminal.

I'm using the same font, [Meslo LG S for Powerline](https://github.com/powerline/fonts/tree/master/Meslo%20Dotted) for all 3 terminal emulators.

The following table has a print of each app, I'm adding another unusual char and an emoji both correctly displayed to show that the issue does not seem to be related to the font.

|alacritty|iterm|terminal|
|---|---|---|
|![alacritty](https://user-images.githubusercontent.com/1225438/82137370-ad5fc700-97ed-11ea-9d56-c81c2ab995b4.png)|![iterm](https://user-images.githubusercontent.com/1225438/82137302-31fe1580-97ed-11ea-8a90-8328758f079b.png)|![terminal](https://user-images.githubusercontent.com/1225438/82137301-31657f00-97ed-11ea-9011-b4ebeca54bc1.png)|

It is my first time using this app, so I'm not sure if I'm doing some mistake, so I'm sharing my config font section:

```
font:
    normal:
        family: Meslo LG S for Powerline
        style: Regular
    bold:
        family: Meslo LG S for Powerline
        style: Bold
    italic:
        family: Meslo LG S for Powerline
        style: Italic
    bold_italic:
        family: Meslo LG S for Powerline
        style: Bold Italic
    size: 12
    use_thin_strokes: true
```

### System

OS: macOS
Version: alacritty 0.4.2 (f68de37)
