### ISSUE TITLE
Font not using thin strokes/bold

### ISSUE THREAD

**Issue by VictorTennekes** [alacritty/alacritty#3760]
### Bug
So when looking at my font in Alacritty it seems like its bold compared to the same font in iTerm, i already turned on thin strokes but that doesn't seem to change anything.

up: Alacritty
down: iTerm
<img width="196" alt="Screenshot 2020-05-23 at 02 54 34" src="https://user-images.githubusercontent.com/19930858/82718181-3456e880-9ca1-11ea-8416-7f242a64c460.png">

### System

OS: macOS
Version: Alacritty 0.4.2 (f68de37)

**Comment by chrisduerr** [comment]
Can you give the latest master a shot, specifically https://github.com/alacritty/alacritty/commit/ab1f173ccd20001aafe2f5b3268423861b0ecdfe?

**Comment by VictorTennekes** [comment]
Ah that seemed to fix it, thank you very much dude :)

**Comment by laktak** [comment]
@chrisduerr I have the same issue - should this be in 0.4.3?

**Comment by kchibisov** [comment]
No, only on master branch, and you should have style being commented out in `bold`,`italic`, and `bold_italic` font sections.

**Comment by laktak** [comment]
@chrisduerr thanks for the 0.5.0 rc1 ("Regression in font rendering on macOS") though it does not fix the issue for me

@kchibisov I only have the normal font specified but I don't see a difference with `use_thin_strokes` - it is still bold compared to iTerm.

```
# Font configuration
font:
  # Normal font face, others fall back to normal
  normal:
    family: Consolas
    style: Regular

  # Point size
  size: 16

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 1

  # Thin stroke font rendering (macOS only)
  use_thin_strokes: true
```
