### ISSUE TITLE
Visual bell fails to fully animate.

### ISSUE THREAD

**Issue by allisio** [alacritty/alacritty#3806]
### System

OS: Linux 5.7.0
Version: alacritty 0.4.3
X11, spectrwm, no compositor

``` yaml
visual_bell:
  animation: EaseOutExpo
  duration: 100
  color: '#ff0000'
```

This works fine on 0.4.2.2. Since 0.4.3, ringing the visual bell starts out fine, but the animation stops midway through, leaving the terminal background somewhere between the start and finish colors. This seems to be true for all animation styles. Any subsequent action causes the animation to "complete" immediately.
