### ISSUE TITLE
MacOS stack overflow on f99220f

### ISSUE THREAD

**Issue by DivineGod** [alacritty/alacritty#3820]
Running alacritty build from master at ref f99220f causes a runtime error immediately when starting up.

The following PR caused this: https://github.com/alacritty/alacritty/pull/3817

Using the commit before works fine

### System

OS: macOS
Version: alacritty 0.5.0-dev (f99220f)

### Logs
```bash
./target/release/alacritty

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
fish: './target/release/alacritty' terminated by signal SIGABRT (Abort)
```

**Comment by DivineGod** [comment]
seems like something in my config is causing the crash. I'll try to narrow down what that might be

**Comment by DivineGod** [comment]
turns out I had the following enabled:

```yaml
window:
# Window class (Linux only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty
```
