### ISSUE TITLE
Emojis rendered in black and white

### ISSUE THREAD

**Issue by antoinemadec** [alacritty/alacritty#3823]
### System

OS: Linux, Debian testing
Version: alacritty 0.4.3
Linux/BSD: i3 + compton
Windows:
```
Created log file at "/tmp/Alacritty-52720.log"
[2020-06-05 13:30:30.534658483] [INFO] Welcome to Alacritty
[2020-06-05 13:30:30.534783783] [INFO] Configuration loaded from "/home/antoine/.config/alacritty/alacritty.yml"
[2020-06-05 13:30:30.576208520] [INFO] Device pixel ratio: 1.75
[2020-06-05 13:30:30.582148357] [INFO] Initializing glyph cache...
[2020-06-05 13:30:30.629329771] [INFO] ... finished initializing glyph cache in 0.047126362s
[2020-06-05 13:30:30.629368169] [INFO] Cell Size: 10 x 19
[2020-06-05 13:30:30.629377126] [INFO] Padding: 0 x 0
[2020-06-05 13:30:30.629405093] [INFO] Width: 800, Height: 600
[2020-06-05 13:30:30.631328088] [INFO] PTY Dimensions: Line(31) x Column(80)
[2020-06-05 13:30:30.641283764] [INFO] Initialisation complete
[2020-06-05 13:30:30.642031984] [INFO] Width: 1914, Height: 342
```

### Logs

Font/Terminal size:
```yml
background_opacity: 0.96

font:
  normal:
    family: DejaVuSansMono Nerd Font Mono
    style: Book
  bold:
    family: DejaVuSansMono Nerd Font Mono
  italic:
    family: DejaVuSansMono Nerd Font Mono
  size: 7.0

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: "#282828"
    # soft contrast: background = '#32302f'
    foreground: "#ebdbb2"

  # Normal colors
  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"

  # Bright colors
  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"
```

### Problem
A lot of emojis are rendered in black and white, when ```termite``` renders them with color.
Termite:
![termite](https://user-images.githubusercontent.com/10830594/83920643-8d0e9280-a731-11ea-9cb6-31885c113001.png)

Alacritty:
![alacritty](https://user-images.githubusercontent.com/10830594/83920665-926bdd00-a731-11ea-93b2-1643fda93b9c.png)

Note that some emojis are properly rendered by Alacritty, like this one: 🥰 smiling face with 3 hearts; U+1F970

For info, here is the output of **fc-match**:
```
> fc-match -s 'DejaVuSansMono Nerd Font Mono' | head
DejaVu Sans Mono Nerd Font Complete Mono.ttf: "DejaVuSansMono Nerd Font Mono" "Book"
DejaVu Sans Mono Bold Nerd Font Complete Mono.ttf: "DejaVuSansMono Nerd Font Mono" "Bold"
DejaVu Sans Mono Oblique Nerd Font Complete Mono.ttf: "DejaVuSansMono Nerd Font Mono" "Oblique"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
NimbusSans-Regular.otf: "Nimbus Sans" "Regular"
opens___.ttf: "OpenSymbol" "Regular"
Aegean_hint.ttf: "Aegean" "Regular"
```

**Is this expected?**

I spend 2 hours beforehand on the issues to find similar problem, but I was not able to find any clear explanation.
It seemed that the emoji support has change in 0.4.1 and fixed a bunch of problems, but I am using 0.4.3

Thanks a lot for this great project!
Antoine
