### ISSUE TITLE
Unclean drawing of font on small point size

### ISSUE THREAD

**Issue by HeapUnderfl0w** [alacritty/alacritty#3866]
On my secondary screen, all ttf fonts are drawn very uncleanly, almost illegible. Increasing the font size helps to alleviate that, **but** then the fonts look super huge on my primary screen.

To explain further: I am used to working with very small font sizes (6.0pt in alacritty). When i use the bitmap font Terminus, it is properly small on my primary screen. Do i now move that terminal to my secondary screen, the whole appearance of the terminal gets larger, as i would expect on a screen with more area, but the same resolution.
When i now swap out the bitmap font for any TTF font, i observe a unexpected behavior. Instead of getting sized slightly larger (to accommodate screen area), it gets scaled so it has the same size as on the primary screen, but in the process gets rendered very uncleanly.
(this all is better visualized by the pictures included below).

Now, i don't know if this is an issue in the way alacritty behaves, or if its an issue with my setup so i am also open to the resolution of "its not alacrittys fault".

### System

OS: `Linux (Kernel 5.7.2-arch1-1)`
Version: `alacritty 0.5.0-dev (ab1f173)`
Linux/BSD: `X11 with KDE Plasma 5.19.1`
Graphics: `Intel UHD Graphics 620`
Screens:
- 1x 13" Laptop Screen @ 1920x1080
- 1x 24" External Screen @ 1920x1080

### Logs

The font config used for **all** of these, with only the font name changed:

```yml
# Font configuration
font:
  normal:
    family: "Iosevka Term SS09 Extended"
    style: Regular
  bold:
    family: "Iosevka Term SS09 Extended"
    style: Bold
  bold_italic:
    family: "Iosevka Term SS09 Extended"
    style: Bold Italic

  # Point size
  size: 6.0
```

- [Log for ttf font Iosevka SS09 Term Extended](https://i.heap.wtf/2020/06/iosevka_ss09_term_extended.yml.alacritty.log)
- [Log for ttf font Source Code Pro](https://i.heap.wtf/2020/06/source_code_pro.yml.alacritty.log)
- [Log for bitmap font Terminus](https://i.heap.wtf/2020/06/terminus.yml.alacritty.log)

Fonts in these images:
Left = `Source Code Pro`
Middle = `Iosevka SS09 Term Extended`
Right = `Terminus`

- [@ 7.5pt size](https://i.heap.wtf/2020/06/alacritty_7.5pt.png)
- [@ 6.0pt size](https://i.heap.wtf/2020/06/alacritty_6.0pt.png)

- [Iosevka @ 6.9pt size on primary screen](https://i.heap.wtf/2020/06/primary_screen.png)
