### ISSUE TITLE
uncommenting padding gives error

### ISSUE THREAD

**Issue by apoorv569** [alacritty/alacritty#3875]
i want to adding a little padding around the window for that i uncommented these lines
```
# Window padding (changes require restart)
#
# Blank space added around the window in pixels. This padding is scaled
# by DPI and the specified value is always added at both opposing sides.
padding:
  x: 2
  y: 2
```
and it gives me error on bottom of the terminal with red box saying
> [ERROR] See log at /tmp/Alacritty-16189.log ($ALACRITTY_LOG):
>Unable to load config "/home/apoorv/.config/alacritty/alacritty.yml": Problem with config: did not find expected <document start> at line 91 column 5
