### ISSUE TITLE
Background opacity not rendering properly in top left corner of terminal

### ISSUE THREAD

**Issue by ed-velez** [alacritty/alacritty#4003]
When I adjust the `background_opacity` to something like .5, I've noticed there is a clear box that is not getting rendered properly:
<img width="500" alt="Screen Shot 2020-07-19 at 10 12 31 PM" src="https://user-images.githubusercontent.com/3869323/87896177-18f02b80-ca0d-11ea-9f26-fbf41866e4de.png">

If I adjust the cursor style to something like `Beam` - the clear box is still there but it looks more like a sliver. I thought it maybe something with starship prompt but I disabled it and could still see the issue. I even temporarily switched my shell to bash to further ensure there wasn't something loading in my zsh environment maybe causing an issue - and I could still see a problem.

### System

OS: macOS Catalina 10.15.6
Version: alacritty 0.4.3 (c723247)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

```
window:
    decorations: full
    padding:
        x: 4
        y: 4
    startup_mode: Maximized
    title: alacritty

scrolling:
    history: 100000

colors:
    primary:
        background: '0x2E3440'
        foreground: '0xD8DEE9'
    cursor:
        text: '0x2E3440'
        cursor: '0xD8DEE9'
    normal:
        black: '0x3B4252'
        red: '0xBF616A'
        green: '0xA3BE8C'
        yellow: '0xEBCB8B'
        blue: '0x81A1C1'
        magenta: '0xB48EAD'
        cyan: '0x88C0D0'
        white: '0xE5E9F0'
    bright:
        black: '0x4C566A'
        red: '0xBF616A'
        green: '0xA3BE8C'
        yellow: '0xEBCB8B'
        blue: '0x81A1C1'
        magenta: '0xB48EAD'
        cyan: '0x8FBCBB'
        white: '0xECEFF4'

font:
    normal:
        family: Fira Code
        style: Regular

    bold:
        family: Fira Code
        style: Bold

    italic:
        family: Menlo
        style: Italic

    size: 13.0

background_opacity: .5
dynamic_title: true
alt_send_esc: false
key_bindings:
    - { key: A,         mods: Alt,       chars: "\x1ba"                       }
    - { key: B,         mods: Alt,       chars: "\x1bb"                       }
    - { key: C,         mods: Alt,       chars: "\x1bc"                       }
    - { key: D,         mods: Alt,       chars: "\x1bd"                       }
    - { key: E,         mods: Alt,       chars: "\x1be"                       }
    - { key: F,         mods: Alt,       chars: "\x1bf"                       }
    - { key: G,         mods: Alt,       chars: "\x1bg"                       }
    - { key: H,         mods: Alt,       chars: "\x1bh"                       }
    - { key: I,         mods: Alt,       chars: "\x1bi"                       }
    - { key: J,         mods: Alt,       chars: "\x1bj"                       }
    - { key: K,         mods: Alt,       chars: "\x1bk"                       }
    - { key: L,         mods: Alt,       chars: "\x1bl"                       }
    - { key: M,         mods: Alt,       chars: "\x1bm"                       }
    - { key: N,         mods: Alt,       chars: "\x1bn"                       }
    - { key: O,         mods: Alt,       chars: "\x1bo"                       }
    - { key: P,         mods: Alt,       chars: "\x1bp"                       }
    - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
    - { key: R,         mods: Alt,       chars: "\x1br"                       }
    - { key: S,         mods: Alt,       chars: "\x1bs"                       }
    - { key: T,         mods: Alt,       chars: "\x1bt"                       }
    - { key: U,         mods: Alt,       chars: "\x1bu"                       }
    - { key: V,         mods: Alt,       chars: "\x1bv"                       }
    - { key: W,         mods: Alt,       chars: "\x1bw"                       }
    - { key: X,         mods: Alt,       chars: "\x1bx"                       }
    - { key: Y,         mods: Alt,       chars: "\x1by"                       }
    - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
    - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
    - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
    - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
    - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
    - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
    - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
    - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
    - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
    - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
    - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
    - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
    - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
    - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
    - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
    - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
    - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
    - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
    - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
    - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
    - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
    - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
    - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
    - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
    - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
    - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
    - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
    - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
    - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
    - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
    - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
    - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
    - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
    - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
    - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
    - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
    - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
    - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
    - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
    - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
    - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
    - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
    - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
    - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
    - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
    - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
    - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
    - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
    - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
    - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |
```
