### ISSUE TITLE
Can't place window on secondary monitor since 0.5.0

### ISSUE THREAD

**Issue by darsain** [alacritty/alacritty#4061]
### System

OS: Windows
Version: alacritty 0.5.0 (a6681e3)

### Problem

Up until now I was using:

```yaml
window:
  position:
    x: -1920
    y: 100
  dimensions:
    columns: 80
    lines: 60
  padding:
    x: 20
    y: 20
  decorations: none
```

to place the window on a secondary monitor located to the left of the primary one. Since 0.5.0 the window is always placed as if the `x` value was `0`.
