### ISSUE TITLE
font anti-aliasing

### ISSUE THREAD

**Issue by zhengkai** [alacritty/alacritty#4135]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Ubuntu 20.04 TLS
Version: alacritty 0.5.0 (a6681e3)

### Config

```
font:
  normal:
    family: JetBrains Mono NL
    style: Regular
  size: 13.0
  offset:
    x: 0
    y: 0
```

I'm using character `│` as seperator line, there are some "dot" in line

![a](https://user-images.githubusercontent.com/247015/90387872-84cfbd80-e0b9-11ea-9fb8-3f4793a370ac.png)

In `gnome-terminal` , same config （ [JetBrains Mono NL](https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.6) Regular 13 ）, no dot in seperator line, looks smooth

![b](https://user-images.githubusercontent.com/247015/90387876-8600ea80-e0b9-11ea-8e27-e9bd002ee3dd.png)
