### ISSUE TITLE
MacOS Alacritty doesn't capture keybinds when focused on different desktop

### ISSUE THREAD

**Issue by Exr0n** [alacritty/alacritty#4151]
## Problem:
When Alacritty is on a desktop (say Desktop 1) and the screen is focused on a different desktop (say Desktop 2) but Alacritty is the active application, (syspref > Mission Control > uncheck "When switching to an application, ...." then click on Alacritty in the dock from a different desktop), activating an Alacritty keybind does nothing. In my case, that keybind is cmd-N which should open a new instance of Alacritty. This works when an Alacritty instance already exists on the active desktop, but not when it's on a different one. Keyboard shortcuts from different desktops work as expected in other applications, such as Chrome.

### System

OS: macOS 10.15.6
Version: 0.5.0 just downloaded from the releases page

<details>

<summary>my config</summary>

```yml
window:
    decorations: buttonless
    startup_mode: Maximized
scrolling:
    history: 100000
font:
    size: 14
    normal:
        family: Hack
    use_thin_strokes: true
colors:
    cursor:
        text: '#000000'
        cursor: '#eaea00'
    # [challenger deep colors](https://github.com/challenger-deep-theme/alacritty/blob/master/challenger-deep.yml)
    # Default colors
    primary:
        background: '0x1b182c'
        foreground: '0xcbe3e7'

    # Normal colors
    normal:
        black:   '0x100e23'
        red:     '0xff8080'
        green:   '0x95ffa4'
        yellow:  '0xffe9aa'
        blue:    '0x91ddff'
        magenta: '0xc991e1'
        cyan:    '0xaaffe4'
        white:   '0xcbe3e7'

    # Bright colors
    bright:
        black:   '0x565575'
        red:     '0xff5458'
        green:   '0x62d196'
        yellow:  '0xffb378'
        blue:    '0x65b2ff'
        magenta: '0x906cff'
        cyan:    '0x63f2f1'
        white:   '0xa6b3cc'
key_bindings:
    - { key: N, mods: Command, command: { program: "open", args: ["-nb", "io.alacritty"] } }
```

</details>

### Logs
`alacritty command not found`... not sure how to get the CLI.
