### ISSUE TITLE
Mouse fails to hide on key press

### ISSUE THREAD

**Issue by casonadams** [alacritty/alacritty#4178]
### System

OS: Linux
Version: alacritty 0.5.0
Linux/BSD: X11/GNOME Shell

### Description
After update to 0.5.0 mouse fails to hide on key press

### Config
[alacritty.yml](https://github.com/alacritty/alacritty/files/5139278/alacritty.txt)

### Logs
[output.txt](https://github.com/alacritty/alacritty/files/5139294/output.txt)
[events.txt](https://github.com/alacritty/alacritty/files/5139298/events.txt)

**Comment by kchibisov** [comment]
Is it on Wayland or X11?

**Comment by chrisduerr** [comment]
>  Linux/BSD: X11/GNOME Shell

Seems to be X11?

@casonadams you say "After update to 0.5.0", so did it work previously?

**Comment by casonadams** [comment]
@chrisduerr that is correct.  Always worked until updating to 0.5.0.

Just to confirm I’m on Linux Fedora 32, using X11 with Gnome Shell.  I suppose I could roll back and verify the previous version just in case something else updated on my OS (using dnf to manage alacritty updates)

**Comment by chrisduerr** [comment]
> Just to confirm I’m on Linux Fedora 32, using X11 with Gnome Shell. I suppose I could roll back and verify the previous version just in case something else updated on my OS (using dnf to manage alacritty updates)

Please do, even better if you could pinpoint the exact commit that broke this.

**Comment by casonadams** [comment]
Well, noob mistake!  When I updated alacritty to 0.5.0 I had some deprecated artifacts in my alacritty.yml file.  I fat fingered 

Should be this
```yml
mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  #double_click: { threshold: 300 }
  #triple_click: { threshold: 300 }
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true
```

Fat fingered
```yml
  hide_when_typing: true
```

Going to close this one out sorry for the noise.
