### ISSUE TITLE
Tilde character Danish MacOS keyboard

### ISSUE THREAD

**Issue by micknudsen** [alacritty/alacritty#4251]
On the Danish MacOS keyboard, the tilde (`~`) character is typed by pressing `ALT + ¨` followed by space. By default, this does not work in Alacritty. Here the output is `]~`.

This is what happens, when I press `ALT + ¨`:

`[2020-09-25 08:59:09.660367000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140327467903584)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 30, state: Released, virtual_keycode: Some(Grave), modifiers: ALT }, is_synthetic: false } }`

I have tried adding

`- { key: 30,  mods: Alt,      chars: "~"      }`

to my config file, but then output of  `ALT + ¨` followed by space becomes `]~~`.  I have tried setting both `alt_send_esc: true` and `alt_send_esc: false`, but that doesn't change anything.

Any clue how to fix this? I guess it all boils down to umlaut being a special character which must be followed by another character.

**Comment by chrisduerr** [comment]
>  I have tried setting both alt_send_esc: true and alt_send_esc: false, but that doesn't change anything.

Are you sure you've edited this option correctly?

**Comment by micknudsen** [comment]
Pretty sure. I have also tried putting the `alt_send_esc` at the very top of my configuration file. That was suggested in similar issues. Here are the contents of my `.alacritty.yml` file:

```
alt_send_esc: false
window:
  padding:
    x: 5
    y: 3
key_bindings:
  - { key: LBracket,	mods: Alt,	chars: "["	}
  - { key: RBracket,	mods: Alt,	chars: "]"	}
  - { key: LBracket,	mods: Shift|Alt,	chars: "{"	}
  - { key: RBracket,	mods: Shift|Alt,	chars: "}"	}
  - { key: 34,	mods: Alt,	chars: "|"	}
  - { key: 42,	mods: Alt,	chars: "@"	}
```
