### ISSUE TITLE
`draw_bold_text_with_bright_colors: true` not working with `font.bold.style: Regular`

### ISSUE THREAD

**Issue by iamFIREcracker** [alacritty/alacritty#4252]
I am trying to get alacritty to render bold text as regular and use bright colors, but somehow I am failing at it; I think it was possible to do so by using a combination of `draw_bold_text_with_bright_colors` and `font.bold.style`, but I guess I am doing something wrong.

OS: macOS
Version: alacritty 0.5.0 (a6681e3)

## Take 1: `draw_bold_text_with_bright_colors:  false`

With this inside my alacritty.yml:

```
font:
  normal:
    family: monospace

  size: 10.5

draw_bold_text_with_bright_colors: false
```

This is what I get when I run the following command (characters which are rendered as bold, I made uppercased them):

```
$ echo "this is $(tput bold)bold$(tput sgr0) but this isn't"
this is BOLD but this isn't
```
Nothing to flag here.

## Take 2: `draw_bold_text_with_bright_colors: true`

With this inside my alacritty.yml:

```
font:
  normal:
    family: monospace

  size: 10.5

draw_bold_text_with_bright_colors: true
```

This is what I get when I run the following command:

```
$ echo "this is $(tput bold)bold$(tput sgr0) but this isn't"
this is BOLD but this isn't
```

Text is getting rendered exactly as in the previous example, so I am not sure what's going on here.  Anyway, maybe there is another setting I can combine this with, to get what I want...

## Take 3: `draw_bold_text_with_bright_colors: true`, and `font.bold.style: Regular`

With this inside my alacritty.yml:

```
font:
  normal:
    family: monospace

  bold:
    # disable bold fonts
    style: Regular

  size: 10.5
```

This is what I get when I run the following command:

```
$ echo "this is $(tput bold)bold$(tput sgr0) but this isn't"
this is bold but this isn't
```
Here, bold is rendered as regular text, with standard colors -- not the one picked from the bright palette:

```
colors:
  primary:
    foreground: "0xc7c7c7"

  cursor:
    text: "0xbbbbbb"
    cursor: "0xaf00ff"

  # Normal colors
  normal:
    black: "0x000000"
    red: "0xe92f2f"
    green: "0x0ed839"
    yellow: "0xdddd13"
    blue: "0x3b48e3"
    magenta: "0xf996e2"
    cyan: "0x23edda"
    white: "0xababab"

  # Bright colors
  bright:
    black: "0x343434"
    red: "0xf07474"
    green: "0x40f366"
    yellow: "0xf0f04e"
    blue: "0x7d87ec"
    magenta: "0xfddef6"
    cyan: "0x6bf3e6"
    white: "0xf9f9f9"
```

What am I doing it wrong?
