### ISSUE TITLE
How can I use inverted colors on selected text?

### ISSUE THREAD

**Issue by Morantxu** [alacritty/alacritty#4286]
With the text under the cursor, the colors invert well but they don't on selected text, how do I change that?
Here is my color setup : 

```
colors:

  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
 # cursor:
 #   text: '#2e3440'
 #   cursor: '#d8dee9'
 # vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
 # selection:
 #   text: CellForeground
 #   background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
  bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #cursor:
  #text: CellBackground
  #cursor: CellForeground

  # Vi mode cursor colors
  #
  # Colors for the cursor when the vi mode is active.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #vi_mode_cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  # Selection colors
  #
  # Colors which should be used to draw the selection area.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #selection:
  #  text: CellBackground
  #  background: CellForeground

  # Search colors
  #
  # Colors used for the search bar and match highlighting.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #search:
  #  matches:
  #    foreground: '#000000'
  #    background: '#ffffff'
  #
  #  bar:
  #    background: CellForeground
  #    foreground: CellBackground

```

**Comment by kchibisov** [comment]
it's done by default, how are you testing it? You can also look at default config to see how it's done there. Something like that should also work.

```yml
selection:
  text: CellBackground
  background: CellForeground
```
