### ISSUE TITLE
Not possible to set the search color's bar to CellForeground or CellBackground, contrary to documentation

### ISSUE THREAD

**Issue by tchici** [alacritty/alacritty#4305]
### System

OS: Linux
Version: alacritty 0.5.0 (a6681e3a)

### Logs

```
[2020-10-11 04:25:46.196105782] [ERROR] Problem with config: failed to parse rgb color CellForeground; expected hex color like #ff00ff; using default value
[2020-10-11 04:25:46.196144889] [ERROR] Problem with config: failed to parse rgb color CellBackground; expected hex color like #ff00ff; using default value
```

### Configuration

```
[snip]
schemes:
  some_scheme: &ascheme
[snip]
    search:
      matches:
        foreground: '#000000'
        background: '#ffffff'

      bar:
        background: CellForeground
        foreground: CellBackground
[snip]
colors: *ascheme
[snip]
```

### Description

Over [here](<https://github.com/alacritty/alacritty/blob/v0.5.0/alacritty.yml#L214>), it says its possible to use `CellForeground` or `CellBackground` as the color, but it doesn't actually work, as seen in the logs.

Also, for some reason, there are no line numbers in the logs, but I have confirmed that the cause is those two lines by changing them. I think there are no line numbers in the logs when the problem has something to do with wrong types; I think also got an error without a line number when I messed something up in the `env`. Should I open a new issue for this, or is this intended?
