### ISSUE TITLE
Using Powershell 7 on Windows 10?

### ISSUE THREAD

**Issue by kirawi** [alacritty/alacritty#4333]
### System

OS: Windows
Version: 0.50
Windows: ConPTY

How do I use Powershell 7 instead of the default Powershell 5.1 in config? It's currently:
```
shell:
  program: powershell
  args:
    - -NoExit
```
