### ISSUE TITLE
[Config] Is there a way to have conditionals for different OSes? 

### ISSUE THREAD

**Issue by edgybuddha** [alacritty/alacritty#4408]
Currently, my config.yaml is set-up so that Alacritty opens to cmd in Windows:
```
# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
# Entries in `shell.args` are passed unmodified as arguments to the shell.
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux/BSD) user login shell
#   - (Windows) powershell
  shell:
    program: cmd.exe
    args:
            - /s /k pushd C:\Users\Repos
```
I want to make it so that I can also use the same config to open to fish in macOS and Arch.
Thank You
