### ISSUE TITLE
some colors appear as black

### ISSUE THREAD

**Issue by ExpandingMan** [alacritty/alacritty#4464]
Hello all, I have no doubt this is due to something being mis-configured by me, but I can't seem to solve it.  Some colors appear as black when they are not supposed to be.

Here is my color config
```yaml
colors:
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'

  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xf8f8f2'

  bright:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xf8f8f2'

  indexed_colors: []
```
I tried also defining `dim` but it did not help.

Here's how it looks:
![2020-11-23-163704_1978x335_scrot](https://user-images.githubusercontent.com/11379353/100022777-c0ada980-2db1-11eb-9ffc-cb8eb85d9a0b.png)

I know that `TERM` can cause trouble, but by default it's `alacritty` and using `xterm-256color` makes no difference.

Any ideas?

### System

OS: `Kernel: 5.4.78-1-MANJARO x86_64 bits: 64 Desktop: i3 4.19 Distro: Manjaro Linux`
Version: 0.5.0
Linux/BSD: X11, i3
