### ISSUE TITLE
Feature request - colors matching system appearance

### ISSUE THREAD

**Issue by danielfalbo** [alacritty/alacritty#4646]
I was thinking about something like this for the conf file
```yaml
colors:
  primary:
    background: 
      dark: "#ffffff"
      light: "#ffffff"
    foreground: 
      dark: "#ffffff"
    dim_foreground: 
      light: "#ffffff"
```

such that when the user defines both the dark and the light colours, the one used is determined by the current system appearance preference, and when only one colour is defined, that will be used unconditionally.

What do you think about this?
