### ISSUE TITLE
Cursor doesn't behave according to Vim/Neovim's settings

### ISSUE THREAD

**Issue by ndavidpsi** [alacritty/alacritty#4656]
### System

OS: Windows
Version: 0.7.0-dev (f701b22)

### Description

There are some issues with the cursor.
For instance if I put the following in my init.vim/vimrc:
```
highlight Cursor ctermbg=white ctermfg=white guibg=white guifg=white
```
The cursor should become completely white. But that doesn't happen. No matter what I do, the cursor foreground (aka character) doesn't change color, only the cursor background changes.

Another issue is with the shape... Put the following in init.vim/vimrc:
```
set guicursor = a:hor20-Cursor
```
The cursor should become an horizontal bar that's 20% filled. Instead, what happens is that it becomes a thin horizontal bar, no matter what percentage I specify. The same applies to the vertical cursor.
It seems that the only possible cursor shapes are block cursor, thin vertical cursor and thin horizontal cursor, but nothing in between.

**Comment by unalhazal** [comment]
4 Oca 2021 Pzt, saat 03:12 tarihinde ndavidpsi <notifications@github.com>
şunu yazdı:

**Comment by chrisduerr** [comment]
> The cursor should become completely white. But that doesn't happen. No matter what I do, the cursor foreground (aka character) doesn't change color, only the cursor background changes.

Does this work in any other terminal? You might be misunderstanding what that option does, I personally have never used it.

> The cursor should become an horizontal bar that's 20% filled. Instead, what happens is that it becomes a thin horizontal bar, no matter what percentage I specify. The same applies to the vertical cursor.

GUI options are for GUI neovim. Not terminal neovim.

**Comment by ndavidpsi** [comment]
No. It works with the default cmd. The guioptions. And as you can see they do have some effect in alacritty, when I specify the shape of the cursor it changes it just not according to the percentage. When I change the color it changes the cursor background color, just not the foreground color. So it is partially working

**Comment by chrisduerr** [comment]
> And as you can see they do have some effect in alacritty, when I specify the shape of the cursor it changes it just not according to the percentage.

Because they shouldn't. Percentage based cursors are not a thing in terminal emulators. You have your predefined cursor shapes and that's it. That's all you need and all you get.

**Comment by ndavidpsi** [comment]
@chrisduerr Is there a way to change how thick the "horizontal" and "vertical" cursor is before compiling, I'd like to change it in my build? I just find those too thin. I don't need the percentage option.

**Comment by chrisduerr** [comment]
There's an option in the configuration file to set the thickness of those cursors.

**Comment by ndavidpsi** [comment]
@chrisduerr Found it thanks. Also, you didn't mention the color issue. I assume there's no way to change the foreground color in nvim right?

**Comment by chrisduerr** [comment]
I'm not sure what neovim does. In theory it shouldn't be a problem to change both. Alacritty supports these escape sequences without any issue, just a question about neovim at that point.

**Comment by ndavidpsi** [comment]
Interesting. I'll look into it. Thanks for the help

**Comment by alealv** [comment]
Hi, I'm having a similar issue. When opening `neovim` It shows a *beam* cursor instead of a *block* although is correctly configured (AFAIK).

```sh
nvim -c ':set guicursor'
  guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20
```

alacritty.yml
```yaml
cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Beam

    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: On

  # Vi mode cursor style
  #
  # If the vi mode cursor style is `None` or not specified, it will fall back to
  # the style of the active value of the normal cursor.
  #
  # See `cursor.style` for available options.
  vi_mode_style: Block

  # Cursor blinking interval in milliseconds.
  blink_interval: 500

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  #unfocused_hollow: true

  # Thickness of the cursor relative to the cell width as floating point number
  # from `0.0` to `1.0`.
  #thickness: 0.15
```
