### ISSUE TITLE
Cursor shape returns to Block after exiting neovim

### ISSUE THREAD

**Issue by Adoliin** [alacritty/alacritty#4868]
So i am setting the cursor shape to `Underline` like this (in alacritty.yaml):
```
cursor:
  style:
    shape: Underline
    blinking: Always
    blink_interval: 500
``` 
The cursor shape is Underline for the most part but if I start Neovim the cursor shape turns into Block (which is expected behavior) but after exiting Neovim the cursor stay in the Block shape 

### System

OS: Linux (Arch Linux)
Version: alacritty 0.7.2 (5ac8060b)
Linux: X11, i3-gaps
SHELL: zsh
