### ISSUE TITLE
Change windows default url_launcher to cmd.exe /c start ''

### ISSUE THREAD

**Issue by SuperSandro2000** [alacritty/alacritty#4885]
When clicking a link on windows with the default url_launcher explorer opens in My Documents.

It would be better to use ``cmd.exe /c start "" $LINK/$PATH`` because it opens files and protocols with their default programs in windows (eg links with your browser and files with the program associated with that file ending).

The config for that would be:

```yaml
mouse:
  url:
    launcher:
      program: cmd.exe
      args: [ '/c', 'start', '']
```

I am not sure how to translate that into rust code.
