### ISSUE TITLE
How to match Neovim terminal colors to that of Alacritty?

### ISSUE THREAD

**Issue by doronbehar** [alacritty/alacritty#4900]
### System

OS: Linux (NixOS)
Version: 0.7.2
Linux/BSD: Gnome with Wayland and Xorg

### Logs

Irrelevant.

### Issue / Question:

Outside of Neovim:

![ZENIX-selection-2021-03-16T22:03:19+02:00](https://user-images.githubusercontent.com/10998835/111372681-db729980-8692-11eb-8c21-6283af12af9e.png)

And inside Neovim's `:terminal`:

![ZENIX-selection-2021-03-16T22:03:44+02:00](https://user-images.githubusercontent.com/10998835/111372707-e4636b00-8692-11eb-8341-7ac792974df9.png)

Hardly readable. Neovim has this settings: https://neovim.io/doc/user/nvim_terminal_emulator.html (Under "TERMINAL COLORS") - setting:

```
let g:terminal_color_{0..255} = ..
```

changes the colors Alacritty eventually displays inside Neovim's integrated `:terminal`. Is there a way to look at the `alacritty.yml` and know what values to put there? I'm currently using the default colors of alacritty.

**Comment by chrisduerr** [comment]
I don't see what this has to do with Alacritty. If you have problems configuring your neovim theme, that's a neovim question.

**Comment by doronbehar** [comment]
> I don't see what this has to do with Alacritty. If you have problems configuring your neovim theme, that's a neovim question.

You are right so I'll explain myself better:

Alacritty's config says:

```yml
  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xd54e53'
    green:   '0xb9ca4a'
    yellow:  '0xe6c547'
    blue:    '0x7aa6da'
    magenta: '0xc397d8'
    cyan:    '0x70c0ba'
    white:   '0xeaeaea'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xff3334'
    green:   '0x9ec400'
    yellow:  '0xe7c547'
    blue:    '0x7aa6da'
    magenta: '0xb77ee0'
    cyan:    '0x54ced6'
    white:   '0xffffff'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #  black:   '0x000000'
  #  red:     '0x8c3336'
  #  green:   '0x7a8530'
  #  yellow:  '0x97822e'
  #  blue:    '0x506d8f'
  #  magenta: '0x80638e'
  #  cyan:    '0x497e7a'
  #  white:   '0x9a9a9a'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '0xff00ff' }`
  #
  indexed_colors: []
```

But I don't know what are the "sensible defaults" for the indexed colors - or how to compute them myself considering (the default) "bright" and "normal" colors.

The bright and normal named colors (red, green, blue etc.) correspond to Neovim's `g:terminal_color_{0..15}`, with odd numbers for the normal colors and the even numbers for the bright colors. The rest `g:terminal_color_{16..255}` don't have a direct name and alacritty doesn't name them as well, but they are defined (I'm rather sure) in the `indexed_colors` config value. Eventually, I would like to know what are the hex codes for all default 256 colors of Alacritty.
