### ISSUE TITLE
wrong power line symbol display

### ISSUE THREAD

**Issue by iysheng** [alacritty/alacritty#4931]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: `alacritty --version` output
``` bash
▸ alacritty --version
alacritty 0.8.0-dev (974392c)
```
Linux/BSD: X11/dwm

### Logs
wrong power line symbol as:
![](https://ftp.bmp.ovh/imgs/2021/04/e2742936f143ca2e.png)`
but the right should be:
![](https://ftp.bmp.ovh/imgs/2021/04/01cde686e67c20d9.png)
the font i use in alacritty.yml is:
```
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) Cascadia Code PL
    #   - (Windows) Consolas
    family: "FontAwesome"
    family: "Operator Mono Book"
    family: "Operator Mono Medium"
    #style: "Book Italic,Italic"
    family: " Cascadia Mono PL"
```
