### ISSUE TITLE
Cursor disappears on matching whitespace in neovim

### ISSUE THREAD

**Issue by garrettoreilly** [alacritty/alacritty#4954]
I use `/\[\zs \ze\]` to find and jump between checkboxes in Markdown files, but the cursor disappears inside the checkbox because it's just whitespace, making it difficult to determine where the cursor is.

<img width="243" alt="Screen Shot 2021-04-07 at 10 25 02" src="https://user-images.githubusercontent.com/1154912/113882708-873b7080-978b-11eb-8e30-8bec8decd0a0.png">

### System

macOS
alacritty 0.7.2 (5ac8060)

**Comment by nixpulvis** [comment]
@garrettoreilly

- What are your configuration values for `colors.cursor`?
- Can you reproduce this while running `nvim --clean`?

I tried to reproduce this in my own neovim, and wasn't able to, both with the default cursor configuration, and one where I set the colors to something other than inversion.

**Comment by garrettoreilly** [comment]
Using `nvim --clean` the cursor is just barely distinguishable from the background (and I think it's using the same color as the cursorline in my initial screenshot):

<img width="243" alt="Screen Shot 2021-04-08 at 11 28 18" src="https://user-images.githubusercontent.com/1154912/114054076-870ba580-985d-11eb-8158-cf8194676ce9.png">

> What are your configuration values for colors.cursor?

I'm new to Alacritty, but I presume you're asking about this section of the Solarized Dark theme, yeah?

```  
# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '#002b36' # base03
    foreground: '#839496' # base0

  # Cursor colors
  cursor:
    text:   '#002b36' # base03
    cursor: '#839496' # base0
```
