### ISSUE TITLE
Weid glyphs, font appears not to load

### ISSUE THREAD

**Issue by Mdsp9070** [alacritty/alacritty#4964]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: `Linux (NixOS 20.09)`
Version: `0.5.0`
Linux/BSD: `X11`, `picom`, `Xmonad`

### Logs

my home ls:
![image](https://user-images.githubusercontent.com/44469426/114478945-caf00900-9bd5-11eb-87f3-5b296f6a629f.png)
`alacrity -vv`:
![image](https://user-images.githubusercontent.com/44469426/114478867-a09e4b80-9bd5-11eb-93ae-b7e3bddb0b17.png)
`neofetch`:
![image](https://user-images.githubusercontent.com/44469426/114478990-e4915080-9bd5-11eb-9012-3ec6640bfea2.png)
`fontpreview`:
![image](https://user-images.githubusercontent.com/44469426/114479031-fa9f1100-9bd5-11eb-83b0-d0a99759a8f8.png)

Yeah, I know that you may receive this type of issue very often, but I really searched before :/
I'm trying to setup a new machine and went witj `NixOS`. All going fine exept alacritty with fonts!
Screenshots only shows JetBrains, but I also tried FiraCode and others "no-nerdfonts".

Here's my config:
```yaml
import:
  - /home/matthew/.config/alacritty/omni.yml

window:
  dynamic_title: true

  dynamic_padding: false
  decorations: none

selection:
  save_to_clipboard: true

scrolling:
  history: 50000
  multiplier: 3

font:
  normal:
    family: JetBrains-Mono-Regular-Nerd-Font-Complete

  bold:
    family: JetBrains-Mono-Bold-Nerd-Font-Complete

  italic:
    family: JetBrains-Mono-Italic-Nerd-Font-Complete

  size: 13.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

background_opacity: 1

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
```
