### ISSUE TITLE
Block cursor dissapears when moved in zsh with zsh-syntax-highlighting plugin

### ISSUE THREAD

**Issue by adzierzanowski** [alacritty/alacritty#4975]
When cursor shape is set to `Block`, it disappears when I press arrow keys to edit command in zsh. I use zsh-syntax-highlighting plugin which colors commands as I type them and I managed to find out that disabling it makes the cursor behave as expected. Other cursor shapes don't disappear. Also, when `Block` cursor's blinking is set to `On` - it dissapears at first but as it blinks it becomes visible again.

This didn't happen until some update but I sadly don't remember which one was it (mac, zsh or alacritty).

### System

OS: macOS Big Sur 11.2.3
Version: alacritty 0.7.2 (5ac8060)
Zsh version: zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by chrisduerr** [comment]
Can you share a recording please?

**Comment by adzierzanowski** [comment]
![Screen Recording 2021-04-15 at 11 12 53](https://user-images.githubusercontent.com/7986275/114845165-d57bef80-9ddb-11eb-9994-37f95d7ce59e.gif)

**Comment by chrisduerr** [comment]
If you set the cursor to a fixed color, does that resolve the issue?

**Comment by adzierzanowski** [comment]
My cursor is set to a fixed color. When I unset the color it becomes even worse as it disappears on the green text too (on other text colors than green it dissapears in both circumstances).

**Comment by chrisduerr** [comment]
Does `alacritty -vvv | grep "mode.*ShowCursor"` print anything?

**Comment by adzierzanowski** [comment]
No, it only spawns a new terminal window.

**Comment by chrisduerr** [comment]
Yes, reproduce the bug in that window and check if there is any output.

**Comment by adzierzanowski** [comment]
The bug is still present in the new window and there's no output whatsoever.

**Comment by chrisduerr** [comment]
What about `alacritty -vvv | grep "Setting color"`?

**Comment by adzierzanowski** [comment]
Same, no output, bug persists. As I said, it happens when cursor blinking is disabled. When blinking is enabled, the cursor  disappears on movement but comes back visible after the blinking interval and blinks as it should.

I'm attaching a gif with blinking **enabled** for comparsion.

![blinking-enabled](https://user-images.githubusercontent.com/7986275/114850901-8c2e9e80-9de1-11eb-8197-619df2da097d.gif)

**Comment by adzierzanowski** [comment]
This is `alacritty -vvv`'s output without grepping when  left arrow key is pressed inside the "hello" word.

```
[2021-04-15 11:59:17.829581000] [TRACE] [alacritty_terminal] Backspace
[2021-04-15 11:59:17.829758000] [TRACE] [alacritty_terminal] Setting attribute: Reverse
[2021-04-15 11:59:17.829815000] [TRACE] [alacritty_terminal] Setting attribute: CancelReverse
[2021-04-15 11:59:17.829865000] [TRACE] [alacritty_terminal] Setting attribute: CancelReverse
[2021-04-15 11:59:17.829918000] [TRACE] [alacritty_terminal] Backspace
[2021-04-15 11:59:17.829959000] [TRACE] [alacritty_terminal] Backspace
```

**Comment by adzierzanowski** [comment]
Ok, also I didn't know about `colors.cursor.text` setting  (I only had `colors.cursor.cursor` set) but setting it doesn't change anything and the bug is still present.

**Comment by chrisduerr** [comment]
Can you reproduce this with the vi mode cursor, when it it set to the same colors as your primary cursor? That way it might be easier to reproduce and we can assure there's no terminal shenanigans going on.

**Comment by adzierzanowski** [comment]
I've set vi mode cursor colors to my main cursor colors. When I enter vi mode, the cursor behaves properly.

![out](https://user-images.githubusercontent.com/7986275/114938137-05a8aa00-9e3f-11eb-806b-bb66ea119a1e.gif)

**Comment by chrisduerr** [comment]
Could you please try the latest masters? There have been some changes in this regard and I'd like to make sure we're not troubleshooting something that is already fixed.

**Comment by adzierzanowski** [comment]
alacritty 0.8.0-dev (1f46bb7)

The bug is still there.

**Comment by chrisduerr** [comment]
If you're willing to test out this patch, it would be very helpful:

```diff
diff --git a/alacritty/src/display/content.rs b/alacritty/src/display/content.rs
index 1d06c349..8361019c 100644
--- a/alacritty/src/display/content.rs
+++ b/alacritty/src/display/content.rs
@@ -56,6 +56,10 @@ impl<'a> RenderableContent<'a> {
             || display.cursor_hidden
             || search_state.regex().is_some()
         {
+            println!("SHAPE: {:?}", terminal_cursor.shape);
+            println!("CURSOR HIDDEN: {}", display.cursor_hidden);
+            println!("SEARCH STATE: {}", search_state.regex().is_some());
+
             terminal_cursor.shape = CursorShape::Hidden;
         } else if !term.is_focused && config.cursor.unfocused_hollow {
             terminal_cursor.shape = CursorShape::HollowBlock;
@@ -125,6 +129,7 @@ impl<'a> RenderableContent<'a> {
             cursor_color,
             CellRgb::Rgb(color) if color.contrast(cell.bg) < MIN_CURSOR_CONTRAST
         ) {
+            println!("CONTRAST TOO LOW");
             cursor_color = CellRgb::CellForeground;
             text_color = CellRgb::CellBackground;
         }
```

**Comment by adzierzanowski** [comment]
`CONTRAST TOO LOW` message shows up multiple times when cursor moves around "hello". The green "echo" doesn't trigger the message.

**Comment by chrisduerr** [comment]
Ah, changing the constant at the top called `MIN_CURSOR_CONTRAST` to `0.0` probably fixes it?

**Comment by adzierzanowski** [comment]
Yup, now it's fixed.

**Comment by chrisduerr** [comment]
Could you share a screenshot of how it looks?

**Comment by adzierzanowski** [comment]
<img width="838" alt="Screen Shot 2021-04-16 at 00 35 17" src="https://user-images.githubusercontent.com/7986275/114946525-a43b0800-9e4b-11eb-8171-e9d6fdf4cfe9.png">

**Comment by chrisduerr** [comment]
Hm, it should be a dark blue `l` on top of a light blue background. So something's not quite right here.

Can you share your complete config so I can test things with your colors?

**Comment by adzierzanowski** [comment]
```yml
background_opacity: 1.0
colors:
  bright:
    black: '0x434758'
    blue: '0x9cc4ff'
    cyan: '0xa3f7ff'
    green: '0xddffa7'
    magenta: '0xe1acff'
    red: '0xff8b92'
    white: '0xfefefe'
    yellow: '0xffe585'
  cursor:
    cursor: '0xaabb00'
    text: '0x000000'
  vi_mode_cursor:
    cursor: '0xaabb00'
    text: '0x000000'
  normal:
    black: '0x292d3e'
    blue: '0x82aaff'
    cyan: '0x89ddff'
    green: '0xc3e88d'
    magenta: '0xc792ea'
    red: '0xf07178'
    white: '0xd0d0d0'
    yellow: '0xffcb6b'
  primary:
    background: '0x1a2432'
    foreground: '0x959dcb'

cursor:
  style:
    shape: Block
    blinking: Off
    thickness: 0.3
font:
  normal:
    family: Iosevka Term Medium
    #family: JetBrains Mono
  size: 13.0
  use_thin_strokes: true
key_bindings:
- action: SpawnNewInstance
  key: N
  mods: Command
- action: ToggleSimpleFullscreen
  key: F
  mods: Command | Shift
- action: ToggleViMode 
  key: V
  mods: Command | Shift
mouse:
  hide_when_typing: true
window:
  dynamic_title: true
  dimensions:
    columns: 80
    lines: 25
  padding:
    x: 5
    y: 5 
  title: Terminal
  decorations: none
draw_bold_text_with_bright_colors: true
selection:
  save_to_clipboard: true
shell:
  program: /bin/zsh
  args:
    - --login
```
