### ISSUE TITLE
Mouse enabled hint only highlights first match

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#5010]
With this simple hint:

```yaml
hints:
  enabled:
    - regex: foo
      action: Select
      mouse:
        enabled: true
```

And the following text in the grid:

```
foo foo
```

Only  the first `foo` will be highlighted on mouseover.

This does not seem to be an issue for the keyboard hints.
