### ISSUE TITLE
Search mode focused_match using incorrect CellBackground/CellForeground colors

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [alacritty/alacritty#5022]
### System

OS: Linux
Version: 0.7.2
Linux/BSD: X11, i3wm
Tested with the default config.
```
colors:
  search:
      matches:
        foreground: '#000000'
        background: '#ffffff'
      focused_match:
        foreground: CellBackground
        background: CellForeground
```
https://user-images.githubusercontent.com/33134232/116493381-798d7e00-a853-11eb-9a75-ed63188a5623.mp4

While in search mode, the focused match is expected to use the CellBackground/CellForeground colors like when selecting text. However, alacritty seems to be using the whatever colors are set under `search.matches` as the cell background/foreground.
