### ISSUE TITLE
Odd artifact while using tmux 4 pane split

### ISSUE THREAD

**Issue by casonadams** [alacritty/alacritty#5052]
Odd artifact while using tmux 4 pane split.  This artifact is not shown using `kitty` or `termite` terminals

![image](https://user-images.githubusercontent.com/17597548/116907722-32124380-abff-11eb-85cc-e7f94f285acd.png)

### System

OS: Linux
Version: alacritty 0.7.2
Linux/BSD: X11

### Logs

Font/Terminal size: `thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /usr/share/cargo/registry/winit-0.24.0/src/platform_impl/linux/mod.rs:605:9`

### Config

```
env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 1
    y: 0

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true
  decorations: none
  startup_mode: Windowed

scrolling:
  history: 10
  multiplier: 3

# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    # family: "OpenDyslexicMono"
    family: "JetBrains Mono"
    style: Regular

  bold:
    family: "JetBrains Mono"
    style: Bold

  italic:
    family: "JetBrains Mono"
    style: Italic

  bold_italic:
    family: "JetBrains Mono"
    style: Bold Italic

  size: 13.0
  offset:
    x: 0
    y: 1
  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

background_opacity: 1.00

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: false

colors:
  # Default colors
  primary:
    background: "#2B2B2B"
    foreground: "#BBBBBB"

  normal:
    black: "#000000"
    red: "#DB5451"
    green: "#548C26"
    yellow: "#A89022"
    blue: "#3A91CF"
    magenta: "#A575BA"
    cyan: "#009191"
    white: "#7A7A7A"

  bright:
    black: "#4F4F4F"
    red: "#FF5452"
    green: "#61AB11"
    yellow: "#FFFF00"
    blue: "#1EA0FC"
    magenta: "#E55CE5"
    cyan: "#00FFFF"
    white: "#FFFFFF"

  indexed_colors:
    - { index: 17, color: "0x214283" }

mouse:
  hide_when_typing: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    unfocused_hollow: true
    blinking: Off

# Live config reload (changes require restart)
live_config_reload: true
```
