### ISSUE TITLE
'Smart Selection Rules' - mapping buffer regex to clickable URLs

### ISSUE THREAD

**Issue by OJFord** [alacritty/alacritty#5054]
I just heard about [a nice feature of iterm2](https://iterm2.com/documentation-smart-selection.html) that it calls 'smart selection rules'; which I'd definitely be making use of if I used (macOS and) iterm2.

Essentially it's a configuration option to specify regexes like `SC\d+` (shellcheck error codes) or `JIRA-\d+` (issue tracker), or whatever one might think of, to appropriate URLs (shellcheck wiki or Jira base URLs to which the matched rule can be inserted).

I couldn't find any issues mentioning it, so I thought I'd suggest it.

Added configuration options are obviously unavoidable for this (for those that want to use it), so I recognise that may make it unappealing. If nothing else though this issue can at least be 'no alacritty doesn't and won't have this for this reason' for anyone else looking for it in future.

(NB - I thought the Jira example was silly at first, but actually, I tend to have `project-123` branch names, and my branch name in my shell prompt. Having the current branch's ticket a click away would be pretty nice!)

**Comment by chrisduerr** [comment]
> I couldn't find any issues mentioning it, so I thought I'd suggest it.

That's because all of them got closed after it has been implemented.

**Comment by OJFord** [comment]
Well, I didn't find any that were closed either.

But, great! 'Regex hints':
https://github.com/alacritty/alacritty/blob/8f4b752a988c80e27c06582363f6ebbf55ddbfca/alacritty.yml#L448-L490

**Comment by OJFord** [comment]
Although it's not _quite_ the same, since it requires an external wrapper program to formulate the match as an appropriate URL (or whatever).

It'd be convenient if there were a `substitution` or similar option, so to take the shellcheck example, you could do:
```yml
regex: "SC[0-9]{4}"
substitution: "https://github.com/koalaman/shellcheck/wiki/\0"
command: xdg-open
```

In this case I suppose ~the `command` could just be a trivial `xargs` invocation~^, but in general that could be messy. My branch names I mentioned, for example, are lowercase `prj-123`, and Jira does redirect `/browse/prj-123` to `/browse/PRJ-123` fortunately, but you could imagine something else not doing that; in which case it could be more awkward. But with a `substitution` type option:
```yml
regex: "prj-([1-9][0-9]*)"
substitution: "https://prj.atlassian.net/browse/PRJ-\1"
command: xdg-open
```

---

^ actually, having built v0.8.0-rc3 while I wrote this, and now played with it a little, it seems it's not possible with `xargs` because the match is passed as arg, not stdin, fine; but also not possible as `sh -c 'xdg-open ...$1'`, presumably because `command` is expected to be a binary on `PATH`? So a wrapper script _is_ required if the match needs to be modified at all, in the present implementation?

Thanks again though, even with that I think once I have this set up for some things it'll be one of those 'how did I ever not have this' features! Cheers.

**Comment by OJFord** [comment]
> command is expected to be a binary on PATH

Only if given as a simple string:
https://github.com/alacritty/alacritty/blob/706f476dee4f636ad5ce50e310f3a28e51987896/alacritty_terminal/src/config/mod.rs#L179-L186

So this is somewhat ameliorated by using `sh` as the `program`:
```yml
    - regex: "SC[0-9]{4}"
      command:
        program: sh
        args: ["-c", "xdg-open https://github.com/koalaman/shellcheck/wiki/$0"]
```
