### ISSUE TITLE
`mouse: hints: modifiers: Control` No longer works

### ISSUE THREAD

**Issue by dkowis** [alacritty/alacritty#5057]
There was a change in 0.8.0-rc3 that wasn't documented on the release page. Perhaps I'm simply configuring it wrong?

The configuration for  `url` under mouse is deprecated, and you're supposed to use `hints` instead.

```
[2021-05-05 09:38:16.956214597] [WARN ] [alacritty_config_derive] Config warning: url is deprecated; use `hints` section instead
```

However, 
```yaml
mouse:
  # url:
  hints:
    modifiers: Control
```

The modifiier statement, which used to require me to use Control to click on URLs, no longer works. Is there a different way to set this now?

### System

OS: Linux
Version: alacritty 0.8.0-rc3
Linux/BSD: X11, PopOS (gnome shell)

### Logs
Didn't crash, and the only log message is included above.

**Comment by chrisduerr** [comment]
It's `mods: Control`, where did you get `modifiers` from?

**Comment by dkowis** [comment]
That's a good question. But that's what I've had for a long time. I didn't document exactly how I discovered what to put in there, but it wasn't upset until today. 

So I have this now:

```yaml
mouse:
  hints:
    mods: Control
```

However, I am still not having to press Control, like I used to, to click on links, they're clickable without Control.

**Comment by chrisduerr** [comment]
Oh, that's because you're doing it wrong. Check the example configuration file in the repository for the latest master. The hints section is completely separate from the `mouse` section. You'll have to copy the default url hint and add the mouse mod there.

**Comment by dkowis** [comment]
Yeah it is, you're super correct. Thanks, I'll rework it.

 Could there be a feature request to avoid having to copy the default url hint just to tweak the mouse modifier key?

**Comment by chrisduerr** [comment]
> Could there be a feature request to avoid having to copy the default url hint just to tweak the mouse modifier key?

I've considered it but I do not think that is worth it. I prefer a uniform workflow that is the same no matter what, with no magic happening in the background that is difficult to understand. This does mean a configuration file might be a little bigger, but I think in general Alacritty's config should still be manageable.

**Comment by dkowis** [comment]
That's a good point, however, now I've got to keep up with a variable that I don't really care for. Like, it's not part of my configuration, and I don't need it to be.

I've got copypasta in there that I'll have to monitor between version updates. In my mind, this makes it less manageable, because I've got more config in there than I actually need to achieve my goal.

**Comment by chrisduerr** [comment]
If you have a suggestion for something that would sidestep that issue, feel free to make it. But I think since the hints are a list of different configurations, it's not easily possible to change parts of just one of the elements in this list.

Generally there shouldn't be many changes to this structure that require manual user interaction though. I'd consider it more of a helpful pre-configuration that mimics the old behavior than something fixed provided by Alacritty. It's just one hint people might find useful and others could potentially be added to the defaults in the future.

**Comment by dkowis** [comment]
Okay, I see what you're getting at. I thought of URL link detection as a feature provided by Alacritty. 

As a final bit to this:

```yaml
hints:
  enabled:
    - regex: "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\" {-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        mods: Control
```
should be correct right?

Sadly, I don't have ctrl clicking for my URLs any more :(

**Comment by dkowis** [comment]
oof, Needed `enabled: true`

This was a little rough, but I think I got through it.

```yaml
hints:
  enabled:
    - regex: "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\" {-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        enabled: true
        mods: Control
```

**Comment by EFanZh** [comment]
I just want to add `Control` modifier to the URL links, do I have to specify all the fields (`regex`, `command`, `post_processing`) in order to do that?

Previously:

```yaml
mouse:
    url:
        modifiers: Control
```

Now:

```yaml
hints:
    enabled:
      - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
        command: xdg-open
        post_processing: true
        mouse:
            enabled: true
            mods: Control
        binding:
            key: U
            mods: Control|Shift
```
