### ISSUE TITLE
[Help] Can't get hints to work

### ISSUE THREAD

**Issue by vim-zz** [alacritty/alacritty#5110]
I am using the following section in my yml config file:

```
hints:
  enabled:
    - regex: warning
      action: Select
      mouse:
        enabled: true
```

I produce output on the screen which includes the work 'warning', and I expect that when I hover with the mouse cursor over it to see an underline or something. But I can see nothing. I also tried to click over the work, and nothing happen.

Am I doing it wrong?

### System

OS:macOS
Version: alacritty 0.7.2 (5ac8060)
