### ISSUE TITLE
[Help] What's the context of a hint command?

### ISSUE THREAD

**Issue by vim-zz** [alacritty/alacritty#5115]
I would like to click on the terminal where my compiler outputs a filename and line number on errors so I can click to open in my text editor. From some reason it seems it looks for the file in my home dir, rather than the directory in which I currently am on the terminal.

I use the following yml:
```
hints:
  enabled:
    - regex: "([^:\\s]+):([0-9]+):([0-9]+)"
      command: /Users/vim-zz/.local/bin/subl
      mouse:
        enabled: true
```

Is there a way to change the current working dir for this?
Is there a way to access the current path at the terminal?

### System

OS: macOS
Version: alacritty 0.8.0-rc6 (a39fbeb)
