### ISSUE TITLE
Allow specifying a mode for hint bindings

### ISSUE THREAD

**Issue by johannesneyer** [alacritty/alacritty#5154]
I'm trying out the new hints feature and hacked together a regex for file paths. I'd now like to use `F` in vi mode as hint binding. Am I missing something or is this currently not supported?

Relevent part of my config:

```yml
hints:
  enabled:
   - regex: "(/|~/)[[:print:]]+/([[:alnum:]]+[.])+[[:alnum:]]+[[:space:]]"
     command:
       program: emacsclient
       args: [--no-wait, --create-frame, --alternate-editor=""]
     post_processing: true
     mouse:
       enabled: true
       mods: None
     binding:
        key: F
        # mode: Vi|~Search

```

Version: `alacritty 0.8.0 (a1b13e68)`
