### ISSUE TITLE
[feature request] Allow specifying the same key for multiple hints

### ISSUE THREAD

**Issue by shibumi** [alacritty/alacritty#5161]
Imagine the following use case. You want to filter the buffer for different regex, but you want to do the same thing with them. For example copying:

* kubernetes resources
* UUIDs
* IP addresses
* GPG fingerprints

I tried achieving this behavior via adding multiple regex with the same key and mod to the alacritty.yml. Alacritty did not complain about this (no error has been thrown), but it looks like only the last entry gets applied:

```
 hints:
   enabled:
     - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
               [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
       command: chromium
       post_processing: true
       mouse:
         enabled: true
     - regex: "(deployment.app|binding|componentstatuse|configmap|endpoint|event|limitrange|namespace|node|persistentvolumeclaim|persistentvolume|pod|podtemplate|replicationcontroller|resourcequota|secret|serviceaccount|service|mutatingwebhookconfiguration.admissionregistration.k8s.io|validatingwebhookconfiguration.admissionregistration.k8s.io|customresourcedefinition.apiextension.k8s.io|apiservice.apiregistration.k8s.io|controllerrevision.apps|daemonset.apps|deployment.apps|replicaset.apps|statefulset.apps|tokenreview.authentication.k8s.io|localsubjectaccessreview.authorization.k8s.io|selfsubjectaccessreviews.authorizat
ion.k8s.io|selfsubjectrulesreview.authorization.k8s.io|subjectaccessreview.authorization.k8s.io|horizontalpodautoscaler.autoscaling|cronjob.batch|job.batch|certificatesigningrequest.certificates.k8s.io|events.events.k8s.io|daemonset.extensions|deployment.extensions|ingress.extensions|networkpolicies.extensions|podsecuritypolicies.extensions|replicaset.extensions|networkpolicie.networking.k8s.io|poddisruptionbudget.policy|clusterrolebinding.rbac.authorization.k8s.io|clusterrole.rbac.authorization.k8s.io|rolebinding.rbac.authorization.k8s.io|role.rbac.authorization.k8s.io|storageclasse.storage.k8s.io)[[:alnum:]_#$%&+=/@-]+"
       action: Copy
       post_processing: false
       binding:
         key: U
         mods: Control|Shift
     - regex: "([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})"
       action: Copy
       post_processing: false
       binding:
         key: U
         mods: Control|Shift
     - regex: "([0-9a-f]{7,128})"
       action: Copy
       post_processing: false
       binding:
         key: U
         mods: Control|Shift
     - regex: '([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})'
       action: Copy
       post_processing: false
       binding:
         key: U
         mods: Control|Shift
```

I could maybe fix this with either adding one big regex (this will be really difficult to maintain and read and might be error-prone) or via using multiple keys (which I have to remember :( ).

What I would like to achieve is the same behavior like tmux-fingers... I press `ctrl+shift+U` and just all regex should be tried to match and hints should get added.
