### ISSUE TITLE
Opening hints on click without mouse modifiers does not work

### ISSUE THREAD

**Issue by leotaku** [alacritty/alacritty#5173]
My configuration contains the hints section copied from the sample configuration. I have included the relevant snippet. 

As you should be able to see, I have the default `mouse.mods: None` setting. However, I still have to press the `Shift` modifier in order to be able to see the underlined URL and open it by clicking. If I set a different modifier, such as `Control`, I no longer have to press `Shift`.

In my opinion, the meaning of `mouse.mods: None`  in this context should be changed to actually mean that no modifier keys have to be pressed in order to interact with hints using the mouse. If this is not possible, the default setting should be changed to `Shift` and the sample configuration should include a comment explaining that `mouse.mods: None` will not work properly.
```yaml
hints:
  alphabet: "jfkdls;ahgurieowpq"
  enabled:
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     command: xdg-open
     post_processing: true
     mouse:
       enabled: true
       mods: None # <--
     binding:
       key: U
       mods: Control|Shift

```

### System

OS: Linux
Version: `alacritty 0.9.0-dev` (latest master `3c61e075fef7b02ae0d043e4a4e664b8bc7221e9`)
Linux/BSD: X11, awesomewm + picom
