### ISSUE TITLE
Regex hinting ignoring action and new regex give errors

### ISSUE THREAD

**Issue by shubham-cpp** [alacritty/alacritty#5184]
Updated alacritty and found out that it now supports regex hinting, very cool but I have encountered few problems.
1. If I hint `Control+Shift+U`  it will open the url instead of copying it to clipboard
```yaml
hint:
  alphabet: "jfkdls;ahgurieowpq"

  enabled:
   - regex: "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     action: Copy
     mouse:
       enabled: true
       mods: Control
     binding:
       key: U
       mods: Control|Shift
```
2. Newly added regexes dont work
```yaml
# FIXME: Regex to find email
   - regex: "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+"
     action: Copy
     mouse:
       enabled: true
       mods: None
     binding:
       key: E
       mods: Control|Shift

```
Hitting `Control+Shift+E` doesnt do anything even though the regex is tested on [rustexp](https://rustexp.lpil.uk/)
### System

OS: ArchLinux
Version: alacritty 0.8.0 (a1b13e68)
Linux/BSD: X11 , Bspwm, Xcompmgr
