### ISSUE TITLE
Be able to select custom fallback font

### ISSUE THREAD

**Issue by mTvare6** [alacritty/alacritty#5222]
Currently I use a nerd font because my prompt depends on some fancy characters and without those looks like this
![image](https://user-images.githubusercontent.com/57838468/121311278-e3ed1000-c921-11eb-824f-11ed578a02b5.png)
It would be nice if I can specify which font to use, if my current font doesn't support these symbols

Some way to manage this config would be this, with which font should be tried first to use
```yml
font:
  size: 12
  normal:
    - family: Bitmap font
    - family: ANerdFont
```
