### ISSUE TITLE
Alacritty.app crashes when specifying startup shell command

### ISSUE THREAD

**Issue by nathom** [alacritty/alacritty#5232]
After I put the following in `alacritty.yml`,

```yml
shell:
  program: /bin/bash
  args:
    - -c
    - nvim
```

opening Alacritty as a macOS application (through Finder or Spotlight) crashes quietly. However, executing the `/Applications/Alacritty.app/Contents/MacOS/alacritty` executable works fine.

### System

OS: macOS 12
Version: alacritty 0.8.0 (a1b13e6)

### Logs

**Full `alacritty.yml`**
```yml
shell:
  program: /bin/bash
  args:
    - -c
    - nvim

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'


font:
  normal:
    family: FiraCode Nerd Font
```
