### ISSUE TITLE
Changing scrolling multiplier in config doesn't work

### ISSUE THREAD

**Issue by nathom** [alacritty/alacritty#5241]
After putting `scrolling: multiplier: 1` in the config file, it still scrolls by multiples of 3 in neovim. 

### System

OS: macOS
Version: alacritty 0.8.0 using tmux

### alacritty.yml
```yaml
# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'


font:
  normal:
    family: FiraCode Nerd Font
  size: 12.0

window:
  padding:
    x: 5
    y: 2

shell: /usr/local/bin/tmux
scrolling:
  # history: 10000
  multiplier: 1
```

### Logs
`alacritty --print-events`
[alacritty_scrolling.log](https://github.com/alacritty/alacritty/files/6660483/alacritty_scrolling.log)
