### ISSUE TITLE
Don't open links on click

### ISSUE THREAD

**Issue by ElementalWarrior** [alacritty/alacritty#5246]
This isn't really a bug, probably a feature request, or config request.

I don't expect to open links on click in the terminal, I like the ability to for example Ctrl+Click a link, but would rather not have the default be to open links.

I'd be happy enough to have this be configurable via config file.

Part of my desire for this is I like being able to double click links so I can copy it to clipboard. Right now if I double click a link it selects from `//` on (another issue entirely, I would expect this behaviour to select the whole link), but also opens the link in my browser.

### System

OS: Linux
Version: `alacritty --version` output
```
alacritty 0.7.2 (5ac8060b)
```
Linux/BSD: i3 manjaro 5.10.26-1-MANJARO

**Comment by chrisduerr** [comment]
It is configurable and the default is not going to change.

**Comment by ElementalWarrior** [comment]
I wasn't suggesting to change the default. But I couldn't find where it was configurable. More specifically I tried setting `hints` but that didn't work.

It looks like the api surface changed from 0.7.2 to 0.8.

0.8 uses `hints` in the yaml to handle it. 0.7.2 uses `mouse.url`

This worked for 0.7.2 after creating `~/.alacritty.yaml`
```
mouse:
  url:
    launcher:
      program: xdg-open
      args: []
    modifiers: "Control"
```

If you're going to reply and say something is configurable, you could at least reference how its configurable. Not just close the ticket. At least for the person after me who hits this ticket via search engine.

**Comment by dlobue** [comment]
@chrisduerr I'm in the same boat as @ElementalWarrior . I'd like to disable links opening automatically when clicked. The reference configuration file is unhelpfully vague. Can you please provide an example of how to accomplish this? Thanks!

**Comment by snylonue** [comment]
@ElementalWarrior 
This config works for me
```ymal
hints:
  enabled:
  - regex: "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    command: program
    post_processing: true
    mouse:
      enabled: true
      mods: None
```

**Comment by divoxx** [comment]
@snylonue thanks for sharing this snippet. 

I do want to take the opportunity to provide some feedback on this too. It's great that the configuration is very flexible now, but on the other hand it makes it really hard for someone who doesn't fully understand how things work behind the scene to figure out the necessary configuration.

Maybe having something like 'hints presets' would be interesting, for commonly used configurations.

**Comment by cyqsimon** [comment]
I wanted to change the behaviour so that the click only happens when the control modifier is held down. This is my config in 0.13 TOML format:

```toml
[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
```

Everything here except for `mouse.mods` is the default value. Due to how the config file is loaded, you still have to specify everything else unfortunately.

**Comment by mdkcore0** [comment]
if anyone wondering how to disable mouse click, this is the minimal conf I got here:
```toml
[[hints.enabled]]
command = ""
hyperlinks = true
mouse.enabled = false
```

**Comment by skylarmb** [comment]
If anyone else stumbles across this due to the opaque and unhelpful error in this form:

```
[WARN ] [alacritty] Unable to launch open with args ["http://127.0.0.1:32769"]   
```

In my case it was because alacritty did not have the appropriate path to find the program I was attempting to launch. Try `command = "/usr/bin/open"` instead of `command = "open"`

**Comment by namn** [comment]
This should be treated as a security issue. The terminal is not a web page. Unintended opening of web links could further elevate cross-site request forgery. For example, you are signed into a web app on your default browser. Unknown to you, that web app accepts an immediate (without user confirmation) action that could be triggered from a simple GET request. Somewhere in your terminal's wall of text contains such a link. Now your focus moves from the web browser back to the terminal and you click on your terminal window. Unfortunately, the mouse click hits that link, and cross-site request forgery happens.

The defaults should be changed.

**Comment by nixpulvis** [comment]
> Now your focus moves from the web browser back to the terminal and you click on your terminal window. Unfortunately, the mouse click hits that link, and cross-site request forgery happens.

Wouldn't some of the methods of [CSRF protection](https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/CSRF_prevention) help with this?

I do think it's a slight hazard, and personally believe it should be either shift-click, or ctrl-click by default to reduce the impact. I've been known to accidentally open a click I'm trying to select a part of. I don't click on my window to focus it, or else I might run into this more often.

**Comment by namn** [comment]
No doubts the linked mitigations are useful if the web app makes use of them, particularly CSRF-tokens. But whether the web app does or does not have protection against CSRF is likely outside any of its visitors' control :'(

**Comment by toonn** [comment]
Thank you to @cyqsimon for the clear example of how to achieve this, seems the default has changed the binding to `O` instead of `U` so the following is now closer to the default:

```toml
[[hints.enabled]]
command         = "xdg-open" # On Linux/BSD
# command       = "open" # On macOS
# command       = { program = "cmd", args = [ "/c", "start",  "" ] } # On Windows
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
mouse.mods      = "Control" # "Control|Shift" is my preference
binding         = { key = "O", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u{0000}-\u{001F}\u{007F}-\u{009F}<>\"\\s{-}\\^⟨⟩`\\\\]+"
```

As the commented `command`s indicate though, it's a shame that it's impossible to overwrite only the `mouse.mods` because this config is now not cross-platform anymore since `xdg-open` won't work on macOS and Windows.

EDIT: Was checking the regex in case it has been updated in the meantime, dropped a dash from `go-pher` that was added erroneously.
