### ISSUE TITLE
Add command line options to override initial window dimensions

### ISSUE THREAD

**Issue by mjkalyan** [alacritty/alacritty#5290]
There are some cases where it would be convenient to override the dimensions (lines/columns) set here:
```
window:
  dimensions:
    columns: x
    lines: y
```
with command line options. Perhaps `--columns` and `--lines`?
