### ISSUE TITLE
Alacritty rendering issue with Starship prompt and Nushell

### ISSUE THREAD

**Issue by thesobercoder** [alacritty/alacritty#5370]
Alacritty rendering issue with Starship prompt and Nushell. Checked on Windows Terminal with the same font and settings, it renders fine.

![image](https://user-images.githubusercontent.com/1915249/126910438-73fbe134-2c39-4d77-8077-fede415598d0.png)

alacritty.yml

```
colors:
  primary:
    background: "0x282a36"
    foreground: "0xf8f8f2"
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: "0x44475a"
      background: "0x50fa7b"
    focused_match:
      foreground: "0x44475a"
      background: "0xffb86c"
    bar:
      background: "0x282a36"
      foreground: "0xf8f8f2"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: "0x44475a"
  normal:
    black: "0x000000"
    red: "0xff5555"
    green: "0x50fa7b"
    yellow: "0xf1fa8c"
    blue: "0xbd93f9"
    magenta: "0xff79c6"
    cyan: "0x8be9fd"
    white: "0xbfbfbf"
  bright:
    black: "0x4d4d4d"
    red: "0xff6e67"
    green: "0x5af78e"
    yellow: "0xf4f99d"
    blue: "0xcaa9fa"
    magenta: "0xff92d0"
    cyan: "0x9aedfe"
    white: "0xe6e6e6"
  dim:
    black: "0x14151b"
    red: "0xff2222"
    green: "0x1ef956"
    yellow: "0xebf85b"
    blue: "0x4d5b86"
    magenta: "0xff46b0"
    cyan: "0x59dffc"
    white: "0xe6e6d1"

cursor:
  style:
    shape: Beam
    blinking: On

window:
  dynamic_padding: false
  dynamic_title: false
  title: Alacritty
  padding:
    x: 6
    y: 6

font:
  normal:
    family: "Cascadia Code PL"
  size: 13.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true

draw_bold_text_with_bright_colors: false

shell:
  program: "C:\\nu\\nu.exe"

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: N, mods: Control, action: SpawnNewInstance }

```

### System

OS: Windows
Version: alacritty 0.8.0 (a1b13e6)
