### ISSUE TITLE
Alacritty failed to launch.

### ISSUE THREAD

**Issue by atree-GitHub** [alacritty/alacritty#5380]
I used to use alacritty, but when I tried to open it today, it failed opening. I have no idea why. I tried to find an issue, but couldn't find anything like it, so I wrote one. I'm sorry if this is a rudimentary misunderstanding, but I would appreciate your help. Also, I apologize if my English is unnatural, sorry.
### System

OS: macOS Big Sur Version 11.5
Version: 
```
❯ alacritty --version
alacritty 0.8.0 (a1b13e6)
```
- fish shell

### Logs

```
❯ alacritty
Created log file at "/var/folders/cl/ksyr2fws5m7gwzrt4d3q1nyr0000gn/T/Alacritty-4045.log"
[2021-08-01 21:42:06.094487000] [ERROR] [alacritty_terminal] Failed to spawn command '/usr/local/bin/fish': No such file or directory (os error 2)
```
But```/usr/local/bin/fish```looks fine.
```
❯ /usr/local/bin/fish --version
fish, version 3.3.1
```

### Others
- My Alacritty.app is installed by ```brew install alacritty --cask```(I have reinstalled)
<details><summary>alacritty/alacritty.yml</summary>

```yml
live_config_reload: true
shell:
    program: /usr/local/bin/fish
    args:
        - --login
font:
    size: 12
    normal:
        family: 'JetbrainsMono NF'
        style: Regular
    bold:
        family: 'JetbrainsMono NF'
        style: Bold
    italic:
        family: 'JetbrainsMono NF'
        style: Italic
    bold_italic:
        family: 'JetbrainsMono NF'
        style: Bold Italic
background_opacity: 0.90
window:
    padding:
        x: 3
        y: 3
cursor:
    style:
        shape: Beam
working_directory: $HOME/Documents
key_bindings:
  - { key: Return, mods: Command, action: ToggleFullscreen }
schemes:
    monokai_pro: &monokai_pro
        primary:
            background: "0x2D2A2E"
            foreground: "0xFCFCFA"
        normal:
            black: "0x403E41"
            red: "0xFF6188"
            green: "0xA9DC76"
            yellow: "0xFFD866"
            blue: "0xFC9867"
            magenta: "0xAB9DF2"
            cyan: "0x78DCE8"
            white: "0xFCFCFA"
        bright:
            black: "0x727072"
            red: "0xFF6188"
            green: "0xA9DC76"
            yellow: "0xFFD866"
            blue: "0xFC9867"
            magenta: "0xAB9DF2"
            cyan: "0x78DCE8"
            white: "0xFCFCFA"
    one_dark: &one_dark
        primary:
            background: '#282c34'
            foreground: '#abb2bf'
        normal:
            black:   '#282c34'
            red:     '#e06c75'
            green:   '#98c379'
            yellow:  '#d19a66'
            blue:    '#61afef'
            magenta: '#c678dd'
            cyan:    '#56b6c2'
            white:   '#abb2bf'
        bright:
            black:   '#5c6370'
            red:     '#e06c75'
            green:   '#98c379'
            yellow:  '#d19a66'
            blue:    '#61afef'
            magenta: '#c678dd'
            cyan:    '#56b6c2'
            white:   '#ffffff'
    everforest_dark_medium: &everforest_dark_medium
        primary:
            background: '#2f383e'
            foreground: '#d3c6aa'
        normal:
            black:   '#4b565c'
            red:     '#e67e80'
            green:   '#a7c080'
            yellow:  '#dbbc7f'
            blue:    '#7fbbb3'
            magenta: '#d699b6'
            cyan:    '#83c092'
            white:   '#d3c6aa'
        bright:
           black:   '#4b565c'
           red:     '#e67e80'
           green:   '#a7c080'
           yellow:  '#dbbc7f'
           blue:    '#7fbbb3'
           magenta: '#d699b6'
           cyan:    '#83c092'
           white:   '#d3c6aa'
    gruvbox_material_soft_light: &gruvbox_material_soft_light
        primary:
            background: '0xf2e5bc'
            foreground: '0x654735'
        normal:
            black:   '0x654735'
            red:     '0xc14a4a'
            green:   '0x6c782e'
            yellow:  '0xb47109'
            blue:    '0x45707a'
            magenta: '0x945e80'
            cyan:    '0x4c7a5d'
            white:   '0xe6d5ae'
        bright:
            black:   '0x654735'
            red:     '0xc14a4a'
            green:   '0x6c782e'
            yellow:  '0xb47109'
            blue:    '0x45707a'
            magenta: '0x945e80'
            cyan:    '0x4c7a5d'
            white:   '0xe6d5ae'
colors: *everforest_dark_medium
```

</details>
