### ISSUE TITLE
window padding issues

### ISSUE THREAD

**Issue by Fujiwara-Chika** [alacritty/alacritty#5392]
the `window padding` setting did not take effect when launched.

OS: macOS Mojave
Version: `alacritty 0.9.0 (fed349a))` 

this is all my config:

```
window:
  padding:
    x: 20
    y: 20
```
and when typing CJK characters, it drew back to 0 again.

https://user-images.githubusercontent.com/44722787/128048625-aac5d3df-a1d2-4878-a4b7-1235c9eb7468.mov
