### ISSUE TITLE
Alacritty crashes on TMUX with arguments

### ISSUE THREAD

**Issue by mauricioklein** [alacritty/alacritty#5419]
### System

OS: macOS
Version: 0.9.0-dev (b0bc2a2)

### Logs

Crashes: Crash on startup
Font/Terminal size:
Created log file at "/var/folders/fx/58mx3qyd177c7dnkfsyxn1p00000gr/T/Alacritty-27804.log"
[2021-08-15 18:41:21.257285000] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[2021-08-15 18:41:21.257444000] [INFO ] [alacritty] Welcome to Alacritty
[2021-08-15 18:41:21.257472000] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/Users/kleinmau/.config/alacritty/alacritty.yml"
[2021-08-15 18:41:21.282280000] [DEBUG] [alacritty] Estimated DPR: 2
[2021-08-15 18:41:21.282343000] [DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 2440, height: 4375 })
[2021-08-15 18:41:21.282365000] [DEBUG] [alacritty] Estimated cell size: 24 x 51
[2021-08-15 18:41:21.315913000] [INFO ] [alacritty] Device pixel ratio: 1
[2021-08-15 18:41:21.318756000] [INFO ] [alacritty] Initializing glyph cache...
[2021-08-15 18:41:21.329178000] [INFO ] [alacritty] ... finished initializing glyph cache in 0.010324152s
[2021-08-15 18:41:21.329284000] [INFO ] [alacritty] Cell size: 13 x 27
[2021-08-15 18:41:21.329308000] [INFO ] [alacritty] Padding: 10 x 10
[2021-08-15 18:41:21.329325000] [INFO ] [alacritty] Width: 2440, Height: 4375
[2021-08-15 18:41:21.330004000] [INFO ] [alacritty] PTY dimensions: 161 x 186
[2021-08-15 18:41:21.332738000] [INFO ] [alacritty] Initialisation complete
[2021-08-15 18:41:21.435523000] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/folders/fx/58mx3qyd177c7dnkfsyxn1p00000gr/T/Alacritty-27804.log"

---

Related to https://github.com/alacritty/alacritty/issues/1388, but in this case related to the startup command.

My Alacritty.yml file has the following shell session:

```yaml
shell:
  program: /usr/local/bin/fish
  args:
    - --command="/usr/local/bin/tmux" # This works!
    # - --command="/usr/local/bin/tmux new -A -s main" # This doesn't work!
```

My objective is make TMUX always reuse the main session on startup. However, the second version of `--command` argument crashes Alacritty on startup. Detailed logs doesn't show any meaningful reason for that (see above).

Running the resulting command from another terminal emulator (e.g. iTerm2), command works just fine, which discards error on the command itself.

```sh
$ /usr/local/bin/fish --command="/usr/local/bin/tmux new -A -s main"
```

**Comment by chrisduerr** [comment]
Move the quoted text to a separate argument.

**Comment by mauricioklein** [comment]
Thanks for your reply @chrisduerr !

It partially helped, but haven't fixed the problem.

Checking further on Fish shell, I found a setup that works:

```yaml
shell:
  program: /usr/local/bin/fish
  args:
    - --login
    - --init-command
    - "/usr/local/bin/tmux new -A -s main"
```

Thanks for the support!

**Comment by kitified** [comment]
I'm getting this same exact issue, but with zsh.

This works, launching from spotlight:
```yaml
shell:
  program: /bin/zsh
  args:
    - -l
    # - -c
    # - tmux
```

This doesn't work:
```yaml
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - tmux
```

The second config works perfectly when launching from another terminal.
Interestingly, it _also_ works perfectly on my _Intel_ MBP; it crashes on the M1 MBP.

I've tried this both with a manually downloaded binary and with the binary built through brew.
Would love any suggestions!
