### ISSUE TITLE
Alt key_bindings are not applied when a shell program is specified in the config

### ISSUE THREAD

**Issue by reportaman** [alacritty/alacritty#5433]
Alt key_bindings specified in the comment: https://github.com/alacritty/alacritty/issues/62#issuecomment-347552058 work as long as I do not specify a shell program to load on startup in alacritty.yaml file. If I remove the startup shell program from alacritty.yaml file, and restart alacritty, alt key bindings work!

Here's the problem code, removing this makes alacritty apply alt keybindings.
```yaml
shell:
  program: /opt/homebrew/bin/zsh
  args:
    - -l
    - -c
    - "tmux attach 2> /dev/null || tmux"
```

Tmux doesn't seem to be a problem because alt keybindings work well if I remove the above snippet of code from alacritty.yaml file below & launch tmux manually after alacritty launches.

Complete alacritty.yaml file: 
```yaml
env:
  TERM: xterm-256color

shell:
  program: /opt/homebrew/bin/zsh
  args:
    - -l
    - -c
    - "tmux attach 2> /dev/null || tmux"

font:
  size: 19

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: A,         mods: Alt,       chars: "\x1ba"                       }
  - { key: B,         mods: Alt,       chars: "\x1bb"                       }
  - { key: C,         mods: Alt,       chars: "\x1bc"                       }
  - { key: D,         mods: Alt,       chars: "\x1bd"                       }
  - { key: E,         mods: Alt,       chars: "\x1be"                       }
  - { key: F,         mods: Alt,       chars: "\x1bf"                       }
  - { key: G,         mods: Alt,       chars: "\x1bg"                       }
  - { key: H,         mods: Alt,       chars: "\x1bh"                       }
  - { key: I,         mods: Alt,       chars: "\x1bi"                       }
  - { key: J,         mods: Alt,       chars: "\x1bj"                       }
  - { key: K,         mods: Alt,       chars: "\x1bk"                       }
  - { key: L,         mods: Alt,       chars: "\x1bl"                       }
  - { key: M,         mods: Alt,       chars: "\x1bm"                       }
  - { key: N,         mods: Alt,       chars: "\x1bn"                       }
  - { key: O,         mods: Alt,       chars: "\x1bo"                       }
  - { key: P,         mods: Alt,       chars: "\x1bp"                       }
  - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
  - { key: R,         mods: Alt,       chars: "\x1br"                       }
  - { key: S,         mods: Alt,       chars: "\x1bs"                       }
  - { key: T,         mods: Alt,       chars: "\x1bt"                       }
  - { key: U,         mods: Alt,       chars: "\x1bu"                       }
  - { key: V,         mods: Alt,       chars: "\x1bv"                       }
  - { key: W,         mods: Alt,       chars: "\x1bw"                       }
  - { key: X,         mods: Alt,       chars: "\x1bx"                       }
  - { key: Y,         mods: Alt,       chars: "\x1by"                       }
  - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
  - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
  - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
  - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
  - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
  - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
  - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
  - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
  - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
  - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
  - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
  - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
  - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
  - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
  - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
  - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
  - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
  - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
  - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
  - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
  - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
  - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
  - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
  - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
  - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
  - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
  - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
  - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
  - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
  - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
  - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
  - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
  - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
  - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
  - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
  - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
  - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
  - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
  - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
  - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
  - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
  - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
  - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
  - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
  - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
  - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
  - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
  - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
  - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
  - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |
```

### System

OS: macOS 11.5 Darwin Arm
Version: ``alacritty 0.10.0-dev (62a1fad5)``
DE: Aqua, WM: Quartz Compositor

### Logs

Font/Terminal size: `alacritty -vv`
```
[2021-08-19 00:26:26.858209000] [INFO ] [alacritty] Width: 800, Height: 600
[2021-08-19 00:26:26.858626000] [INFO ] [alacritty] PTY dimensions: 27 x 72
```
Keyboard and bindings: `alacritty --print-events`
[print_events.log](https://github.com/alacritty/alacritty/files/7012530/print_events.log)

**Comment by chrisduerr** [comment]
The two are completely unrelated. I'd assume this is only a problem with this specific shell command? Have you actually tested what characters are received when you press these keys?

**Comment by reportaman** [comment]
@chrisduerr I haven't tried with any other command. The following works without ``-c <command>`` option to zsh:

1) 
```
shell:
  program: /opt/homebrew/bin/zsh
  args:
    - -l
```

2) but this does not:
```
    - -c
    - "tmux attach 2> /dev/null || tmux"
```

The thing is, if I tun the exact same command after launching alacritty (instead of having it launched automatically), it works fine & program responds correctly to Alt-<char> bindings. So there is some interaction/race of ``zsh -c <command>`` with Alacritty is what I can think of.

Keys that are printed by ``>>cat <Enter> Ctrl-v`` are:

For case 1) (without ``-c <command>``:

```
^[ca for Alt-a
^[cb for Alt-b
^[cb for Alt-c
```

For case 2) (with ``-c <command>``): Nothing is printed at all! So I guess nothing is received?

**Comment by chrisduerr** [comment]
Sounds like your locale might be different. Have you tried manually sourcing your shell profile/rc?

**Comment by reportaman** [comment]
@chrisduerr Here's the output of locale:

```
❯ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

In further testing this is what I observe: if I start tmux session in some other terminal emulator, and then open Alacrity with the config mentioned in the description (copied below again), then tmux receives the Alt key-bindings and works well with them. But if there is no tmux server already running in other terminal, and I launch Alacritty then tmux does not receive Alt keybindings.

```yaml
shell:
  program: /opt/homebrew/bin/zsh
  args:
    - -l
    - -c
    - "tmux attach 2> /dev/null || tmux"
```

**Comment by chrisduerr** [comment]
> Here's the output of locale:

That's inside a broken environment, right?

**Comment by reportaman** [comment]
@chrisduerr That's inside tmux that has broken environment (Alt-<char> keys don't work), it is also inside Alacritty if I don't specify a custom ``shell:`` field in variable. It is also inside other terminals...

**Comment by chrisduerr** [comment]
Have you tried just `zsh -c tmux` or straight-up setting tmux as the `program`?

**Comment by reportaman** [comment]
@chrisduerr I just did, both of them do not work. Alacritty window doesn't even open if I do that...

**Comment by chrisduerr** [comment]
Have you been able to reproduce this issue without tmux at any point? To me it seems like the multiplexer might be intercepting things despite Alacritty sending the escapes.

**Comment by nicm** [comment]
Run tmux with -vv in both cases (kill it entirely between each test) then look at the server logs and see if anything is different for the incoming keys between the two. IIRC you can grep for "keys are" in the logs, or send them to me.

**Comment by reportaman** [comment]
@chrisduerr Sorry the problem was that I did not have ``source ~/.zshrc`` in the command. Adding that resolved it! Alacritty & Tmux were correctly receiving the Alt keys. I had bound the alt key binding to a shell script that had a command which were not recognized & the command would failed silently, making me think Alacritty+Tmux did not receive the key binding.

```
shell:
  program: /opt/homebrew/bin/zsh
  args:
    - -l
    - -c 
    - "source ~/.zshrc && tmux attach 2> /dev/null || source ~/.zshrc && tmux"
```

Not sure what the precedence of these operators are and if I can get away with one ``source ~/.zshrc``.
