### ISSUE TITLE
Question: Easier way to configure modifier for clicking on urls?

### ISSUE THREAD

**Issue by tmccombs** [alacritty/alacritty#5436]
### System

OS: Linux
Version: 0.9
Linux/BSD: X11/i3

In older versions of alacritty, in order to require a modifier for clicking on a url to open a browser, I just had to have:

```
mouse:
  url:
    modifiers: Control
```

but afaict, since version 0.8 it is now necessary to duplicate the entire default hints section in order to do this, so even though I just want to add the control modifier for mouse, I have to include all of:

```
hints:
  enabled:
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        enabled: true
        mods: Control
      binding:
        key: U
        mods: Control|Shift
```
which seems a little overkill.

Is there a better way to do it that isn't document, (or if there is documentation, I can't find it)?
