### ISSUE TITLE
URL hints issue on wrapped lines

### ISSUE THREAD

**Issue by aleprovencio** [alacritty/alacritty#5453]
Sorry if this is a regex issue, but the following URL hint config won't work for URLs which are wrapped on more than one line.

```
hints:
  alphabet: "jfkdls;ahgurieowpq"
  enabled:
    - regex: "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: qutebrowser
      post_processing: true
      mouse:
        enabled: true
        mods: None
      binding:
        key: U
        mods: Control|Shift
```
### System
OS: Archlinux
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: Sway
