### ISSUE TITLE
Hint post processing crash

### ISSUE THREAD

**Issue by johannesneyer** [alacritty/alacritty#5492]
Alacritty with the following config crashes when hovering over the `)` character.

```yaml
hints:
  enabled:
   - regex: "[^/ ]"
     action: Paste
     post_processing: true
     mouse:
       enabled: true
       mods: None
```

It only crashes with post processing enabled and I get no relevant output with `-vvv` or `--print-events`.

`alacritty 0.9.0 (fed349aa)` on Linux + Wayland (sway)
