### ISSUE TITLE
Gaps between individual colored cells

### ISSUE THREAD

**Issue by jorritwegman** [alacritty/alacritty#5499]
Hey, I have been using Alacritty for a few weeks now and so far I am loving it. I also use kitty every now and then and notices how kitty has no gaps between cells. How do I achieve this in Alacritty? 

I am running qtile on Arch Linux with picom as my compositor.

Difference (left kitty, right alacritty):
![terminals](https://user-images.githubusercontent.com/68782626/133910564-cfa0ec95-1fcc-4ebd-82ee-4d0d5af7d816.png)

alacritty.yml:
```
import:
- /home/ralts/Downloads/alacritty-master/dracula.yml

env:
  WINIT_X11_SCALE_FACTOR: '1.0'

font:

  normal:
    family: FiraCode Nerd Font Mono

  bold:
    family: FiraCode Nerd Font Mono

  italic:
    family: FiraCode Nerd Font Mono

  size: 12.0

  offset:
    x: 0
    y: 0

  lyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

colors:
  primary:
    # background: '#0f0f0f'
    background: '#0d0d0d'
background_opacity: 0.92

window:

  padding:
    x: 4
    y: 4
```
