### ISSUE TITLE
Bell Command Does not work on MacOS

### ISSUE THREAD

**Issue by deoxykev** [alacritty/alacritty#5567]
### System

OS: macOS Big Sur
Version: 0.9.0

The following config does not seem to run when I trigger a bell using `echo -e '\a'`.

```yml
  bell:
     program: bash
     args: [ "/Users/k/scripts/desklights.sh" ]
```

I can't seem to get the visual bell working either, however, I can get the icon to bounce in the system tray.
