### ISSUE TITLE
Question: Control + number key mappings

### ISSUE THREAD

**Issue by Mac-lp3** [alacritty/alacritty#5680]
Hi,

Is it possible to map ctrl+0..9 in Alacritty?

My goal is to map those keystrokes to change window in tmux.

[This post](https://unix.stackexchange.com/questions/96884/using-ctrl0-9-to-cycle-between-windows-using-tmux) reccomends using the sequences `^[[27;5;48~` through `^[[27;5;57~` (though I do not fully understand why).

So I added those to my Alacritty keybindings:
```yaml
key_bindings:
  - { key: Key1, mods: Control, chars: "\x1b[27;5;49~" }
```

And to my tmux.conf:
```
set -s user-keys[0] "\x1b[27;5;49~"
bind -n User0 select-window -t :1
```

Unfortunetly, it isn't working.

Also, when I run `showkey -a`, hitting ctrl+1 doesn't produce any output. I added the key binding characters one at a time and saw `showkey` output up until I added the `27` onward, eg:
```
{ key: Key1, mods: Control, chars: "\x1b[" }         # showkey output: ^[[
{ key: Key1, mods: Control, chars: "\x1b[27" }       # showkey output: blank
{ key: Key1, mods: Control, chars: "\x1b[27;5;49~" } # showkey output: blank
```

As an FYI, I am quite new to the topic of escape/CSI sequences in general. I am not sure if this is a question for Alacritty or if the issue is elsewhere.

Either way, any tips or resources to help me figure this out would be greatly appreciated.

Thanks for taking the time to read.

**Comment by chrisduerr** [comment]
> I added the key binding characters one at a time and saw showkey output up until I added the 27 onward

Then the binding clearly works and the problem is with the receiving end.

**Comment by Mac-lp3** [comment]
Hi @chrisduerr, thanks for your response. 

The issue could potentially be on the receiving side, but I ran a few more tests that might help.

I tested a few different escape key mappings on Alacritty and Windows Terminal.

For this test, I mapped a key in both Alacritty and WT to `^[[A` (capital A):

```
# alacritty
{ key: Key2, mods: Control, chars: "\u001b[A" }

# WT
{ "command": { "action": "sendInput", "input": "\u001b[A" }, "keys": "ctrl+m" }
```

The corresponding `showkey -a` output:

```
# alacritty
^[[A     27 0033 0x1b
         91 0133 0x5b
         65 0101 0x41

# WT
^[[A     27 0033 0x1b
         91 0133 0x5b
         65 0101 0x41
```

I then repeated this for `^[[a` (lowercase a):

```
# alacritty
blank/no output

# WT
^[[a     27 0033 0x1b
         91 0133 0x5b
         97 0141 0x61
```
Obviously the keybindings work in Alacritty, but it doesn't seem to handle all mappings equally/characters.

WT is also able to send the `\x1b[27;5;49~` escape sequence, even when I specify it incrementally in pieces.

Do I just need to declare certain characters of an escape sequence differently in the Alacritty config?

**Comment by it-is-wednesday** [comment]
Not a proper solution, but here's how I dirtily solved it. On Alacritty's level, I bound `C-<n>` to `C-S-F<n>`:
```yaml
key_bindings:
  - { key: Key1, mods: Control, chars: "\x1b[1;6P" }
  - { key: Key2, mods: Control, chars: "\x1b[1;6Q" }
  - { key: Key3, mods: Control, chars: "\x1b[1;6R" }
  - { key: Key4, mods: Control, chars: "\x1b[1;6S" }
  - { key: Key5, mods: Control, chars: "\x1b[15;6~" }
  - { key: Key6, mods: Control, chars: "\x1b[17;6~" }
  - { key: Key7, mods: Control, chars: "\x1b[18;6~" }
  - { key: Key8, mods: Control, chars: "\x1b[19;6~" }
  - { key: Key9, mods: Control, chars: "\x1b[20;6~" }
  - { key: Key0, mods: Control, chars: "\x1b[21;6~" }
```

Then respectively on the side of tmux:
```
bind -n C-S-F1 select-window -t 1
bind -n C-S-F2 select-window -t 2
bind -n C-S-F3 select-window -t 3
bind -n C-S-F4 select-window -t 4
bind -n C-S-F5 select-window -t 5
bind -n C-S-F6 select-window -t 6
bind -n C-S-F7 select-window -t 7
bind -n C-S-F8 select-window -t 8
bind -n C-S-F9 select-window -t 9
bind -n C-S-F10 select-window -t 10
```

I originally hoped to bind F13-F20, but seems like these keys aren't recognized by tmux. So that's good enough if you're not using these keys for any crazy global thingies. I also considered a hyper-esque approach, trying to stack as many modifiers as possible, but adding alt and meta resulted in the exact same escape characters, so C-S is the closest I got.

**Comment by Runeword** [comment]
ctrl + number

Alacritty
`
  - { key: Key1, mods: Control, chars: "\x1b[49;5u" }
  - { key: Key2, mods: Control, chars: "\x1b[50;5u" }
  - { key: Key3, mods: Control, chars: "\x1b[51;5u" }
  - { key: Key4, mods: Control, chars: "\x1b[52;5u" }
  - { key: Key5, mods: Control, chars: "\x1b[53;5u" }
  - { key: Key6, mods: Control, chars: "\x1b[54;5u" }
  - { key: Key7, mods: Control, chars: "\x1b[55;5u" }
  - { key: Key8, mods: Control, chars: "\x1b[56;5u" }
  - { key: Key9, mods: Control, chars: "\x1b[57;5u" }
`
Tmux
`
bind -n C-1 select-window -t1
bind -n C-2 select-window -t2
bind -n C-3 select-window -t3
bind -n C-4 select-window -t4
bind -n C-5 select-window -t5
bind -n C-6 select-window -t6
bind -n C-7 select-window -t7
bind -n C-8 select-window -t8
bind -n C-9 select-window -t9
`

**Comment by siuoly** [comment]
When I using the @Runeword  method, I meet the key sequence problem. Not sure if the alacritty config format has changed.
Now I use following:
```
[keyboard]
bindings= [
  {key="Key0", mods= "Control", chars= "\u001b[48;5u" },
  {key="Key1", mods= "Control", chars= "\u001b[49;5u" },
  {key="Key2", mods= "Control", chars= "\u001b[50;5u" },
  {key="Key3", mods= "Control", chars= "\u001b[51;5u" },
  {key="Key4", mods= "Control", chars= "\u001b[52;5u" },
  {key="Key5", mods= "Control", chars= "\u001b[53;5u" },
  {key="Key6", mods= "Control", chars= "\u001b[54;5u" },
  {key="Key7", mods= "Control", chars= "\u001b[55;5u" },
  {key="Key8", mods= "Control", chars= "\u001b[56;5u" },
  {key="Key9", mods= "Control", chars= "\u001b[57;5u" }
]
```
It works.

**Comment by onns** [comment]
cmd + number switch session
ctrl + number switch window


alaritty.toml:

```toml
[[keyboard.bindings]]
chars = "\u001b1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001b2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001b3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001b4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001b5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001b6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
key = "Key1"
mods = "Control"
chars = "\u001b[49;5u"

[[keyboard.bindings]]
key = "Key2"
mods = "Control"
chars = "\u001b[50;5u"

[[keyboard.bindings]]
key = "Key3"
mods = "Control"
chars = "\u001b[51;5u"

[[keyboard.bindings]]
key = "Key4"
mods = "Control"
chars = "\u001b[52;5u"

[[keyboard.bindings]]
key = "Key5"
mods = "Control"
chars = "\u001b[53;5u"
```

.tmux.conf.local:

```
bind -n M-1 switch-client -t Onns
bind -n M-2 switch-client -t un
bind -n M-3 switch-client -t 3
bind -n M-4 switch-client -t 4
bind -n M-5 switch-client -t 5

bind -n C-1 select-window -t :1
bind -n C-2 select-window -t :2
bind -n C-3 select-window -t :3
bind -n C-4 select-window -t :4
bind -n C-5 select-window -t :5
bind -n C-6 select-window -t :6
bind -n C-7 select-window -t :7
bind -n C-8 select-window -t :8
bind -n C-9 select-window -t :9
```
