### ISSUE TITLE
Keybind commands or SpawnNextInstance options?

### ISSUE THREAD

**Issue by melMass** [alacritty/alacritty#5683]
### System

OS: macOS
Version: alacritty 0.9.0 (fed349a)

---

Hi,

Very basic question, I'm using tmux, and a `main` session like so:

```yml
shell:
  program: /usr/local/bin/tmux
  args:
    - new-session
    - -A
    - -s
    - main
 ```

Now I want to bind a custom keybinding to open a new alacrity instance within another session `logs` (aka `alacritty -e /usr/local/bin/tmux new-session -A -s logs`) but I have no idea if there is a way to pass commands to keybindings
This does not work:

```yml
- { key: N,              mods: Command|Shift,                    action: "alacritty -e /bin/bash"      }
```

So I wonder what would be the best approach?

Thanks
