### ISSUE TITLE
Pass partial result of `regex` instead of entire matching line?

### ISSUE THREAD

**Issue by reckoner** [alacritty/alacritty#5687]
I think this might be a new feature request but maybe not.

### System

OS: Windows WSL2 Ubuntu 18
Version: alacritty 0.9.0 (fed349a)

When using `regex` in alacritty.yml, is it possible to specify that only a portion of the match is passed on to the named program? For example, if my matched line starts like

```
In[10]: some stuff here
```
and I want only `some stuff here`, can I get it via the regular expression configuration? I can get it to match the entire line but I really don't want the `In[10]: ` part. 

Thank you!

**Comment by chrisduerr** [comment]
There is not. You could highlight the entire thing though and then filter it in your own post-processor, like a simple `sed` command.

IIRC I might have looked at this when originally implementing the regex hints and it was unreasonably more complicated to support. So I'm not sure this is something worthwhile to add.

**Comment by reckoner** [comment]
How would I post-process it via `sed`, as you suggest?

**Comment by chrisduerr** [comment]
No, I mean just literally using a `command` that seds before passing it to another application.

**Comment by chrisduerr** [comment]
Adding support for groups would **significantly** increase complexity and as you've shown in your example config the configuration for that is clunky at best. That's why I haven't added support for it and I'm not sure we'll be able to add full group support in the future.

**Comment by dzervas** [comment]
I'd also want to push for regex groups. A very good use case is matching error-generated filenames in python and clicking them to open them with VSCode:

```yaml
    # Matches:
    # src/main.rs:17:1
    # src/main.rs:17
    # File "/home/dzervas/Lab/pcb_mill_calc.py", line 12, in <module>
    - regex: |-
        ["']?(/?(?:\w+/)+)?(\w+\.\w+)(?:["'], line |:)(\d+)(:\d+)?
      # '
      # hyperlinks: true
      post_processing: true
      command:
        program: code
        args:
          - --goto
          # <path>/<filename>:<linenum>:<column>
          # path includes the trainling '/' and column includes the leading ':'
          - '{1}{2}:{3}{4}'
      mouse:
        enabled: true
        mods: None
```

so clicking `File "/home/dzervas/Lab/pcb_mill_calc.py", line 12, in <module>` would result in `code --goto /home/dzervas/Lab/pcb_mill_calc.py:12`

**Comment by kchibisov** [comment]
Well, the thing is that groups could be done in the post processing? Like you can match in your launcher script one more time, but yeah, it's not like we can't pass groups somehow.

**Comment by OJFord** [comment]
Obviously I don't have knowledge of the complexity of implementation, so I take that point and it's just unfortunate.

As for clunky configuration though, consider just the regular command case, not highlighting; here's a couple of mine:
```yaml
    - regex: "(core|community|extra)/[a-zA-Z0-9_-]+"
      command:
        program: sh
        args: ["-c", 'xdg-open "https://archlinux.org/packages?repo=$(echo "$0" | sed -E "s@(.+)/.+@\u\1@")&q=$(echo "$0" | sed -E "s@.+/(.+)@\1@")"']
      mouse:
        enabled: true
        mods: None
      binding:
        key: A
        mods: Super

    - regex: "[a-zA-Z0-9_-]+/[a-zA-Z0-9._-]+#[1-9][0-9]*"
      command:
        program: sh
        args: ["-c", 'xdg-open "https://github.com/$(echo "$0" | sed "s@#@/issues/@")"']
      mouse:
        enabled: true
        mods: None
      binding:
        key: G
        mods: Super
```


If I could use numbered groups like `$1`, `$2` instead of passing the whole line (`$0`) to `sed` or similar, IMO it would be _less_ clunky:
```yaml
    - regex: "(core|community|extra)/([a-zA-Z0-9_-]+)"
      command:
        program: sh
        args: ["-c", 'xdg-open "https://archlinux.org/packages?repo=$1&q=$2"']
      mouse:
        enabled: true
        mods: None
      binding:
        key: A
        mods: Super

    - regex: "([a-zA-Z0-9_-]+)/([a-zA-Z0-9._-]+)#([1-9][0-9]*)"
      command:
        program: sh
        args: ["-c", 'xdg-open "https://github.com/$1/$2/issues/$3"']
      mouse:
        enabled: true
        mods: None
      binding:
        key: G
        mods: Super
```
