### ISSUE TITLE
Incorrectly Sized Font Glyphs

### ISSUE THREAD

**Issue by SmashMineGame** [alacritty/alacritty#5711]
### System

OS: Macos
Version: alacritty 0.9.0 (fed349a)
Linux/BSD: Not sure

### Issue

I added my Inconsolata Nerd Font and it mostly seems to be working fine but the glyphs seem to be incorrectly sized. In addition some glyphs seem to be too large while some other ones are too small.

<img width="1552" alt="Screen Shot 2021-12-22 at 9 02 51 PM" src="https://user-images.githubusercontent.com/32280917/147190640-ec65b1fb-a113-4057-8fb5-d9a7ac035471.png">
<img width="1552" alt="Screen Shot 2021-12-22 at 9 04 46 PM" src="https://user-images.githubusercontent.com/32280917/147190686-26eac13f-cc51-4c23-bab3-a1aab9958f30.png">

The first image is alacritty and the second is a screen shot of iTerm showing how the different glyphs should look like. Specifically look at the ASCII art of HELLO, the triangle glyphs in the bottom row and two icons under the ASCII art.

Here is my config for the font, if it useful.
```
font:
  normal:
    family: Inconsolata Nerd Font Mono
    style: Regular

  bold:
    family: Inconsolata Nerd Font Mono
    style: Bold

  bold_italic:
    family: Inconsolata Nerd Font Mono
    style: Bold

  size: 18.0
```
