### ISSUE TITLE
Uncertain if the font prop accepts a list/sequence of font family values

### ISSUE THREAD

**Issue by EdmundsEcho** [alacritty/alacritty#5715]
Is the following supported?

My system is MacOS.

```
font:
  normal:
    - family: Hasklug Nerd Font
      style: Light
    - family: Menlo
      style: Light
    - family: Apple Symbols

```

The template configuration does not include a list of fonts.  However, solutions to providing a fallback front seem to indicate that the above code should work.  Is it supported?  In my attempts, alacritty raises the "invalid type: sequence, expected a mapping" error.

Thank you in advance.
