### ISSUE TITLE
Syntax for overriding list options?

### ISSUE THREAD

**Issue by bdcarr** [alacritty/alacritty#5746]
I've got my config file set to start tmux on open:
```
shell:
 program: /usr/bin/zsh
 args:
   - -l
   - -c
   - "tmux new -A -s local"
```

But I wanted to test something outside of tmux, so was trying to figure out how to open an alacritty instance without opening tmux. `alacritty -o "shell.args=-l"` and similar things didn't work:

![image](https://user-images.githubusercontent.com/1940488/148217719-5b884072-4f0b-4df2-a625-cc86faaab5d3.png)

`alacritty -o "shell.args="` just produced a new alacritty window, with tmux running.

So yeah, is it possible to override list options? And if so, how's it done? Cheers!
