### ISSUE TITLE
Unable to hear terminal bell in alacritty

### ISSUE THREAD

**Issue by maxreuben** [alacritty/alacritty#5758]
Neither `echo -e "\a"` nor `tput bel` seem to ring an audible bell while this works in other terminals.

My alacritty.yml:-
```
bell:
 command:
    program: tput
    args: [bel]
```

### System

OS: Fedora Linux 34
Version: `alacritty 0.9.0` 
Linux/BSD: X11, Gnome 40.6, Gnome 40.6 Default WM (Mutter?)

### Logs

Crashes: None
Font/Terminal size: LiterationMono Nerd Font, 73x25
