### ISSUE TITLE
Can not load font from ~/Library/Fonts on Mac

### ISSUE THREAD

**Issue by fred214** [alacritty/alacritty#5798]
### System

OS: macOS Monterey 12.1
Version: 0.9.0 (fed349a)
```
font:
  normal:
    family: MesloLGS NF
    style: regular
```
### Logs
```
font FontDesc { name: "MesloLGS NF", style: Specific("regular") } not found
```
`MesloLGS NF Regular.ttf`  in my path ~/Library/Fonts, not in /System/Library/Fonts
How to config alacritty to load fonts from path ~/Library/Fonts ?
