### ISSUE TITLE
Powerline symbols is looking wrong with font: offset: y: 5

### ISSUE THREAD

**Issue by AlphaTechnolog** [alacritty/alacritty#5830]
When I put this in `alacritty.yml`:

```yaml
font:
  offset:
    y: 5
```

The powerline symbols are looking wrong:

![Screenshot](https://user-images.githubusercontent.com/54639968/151672537-e6a39084-6c49-480b-86ee-25b111dcb281.png)

But in another terminals like kitty, are looking correctly:

![Screenshot from 2022-01-29 14-07-03](https://user-images.githubusercontent.com/54639968/151672564-51e21cd4-ad7b-4201-92f3-9fea02e99790.png)

Please help me

### Config

```yaml
colors:
  bright:
    black: '#414868'
    blue: '#7aa2f7'
    cyan: '#7dcfff'
    green: '#9ece6a'
    magenta: '#bb9af7'
    red: '#f7768e'
    white: '#c0caf5'
    yellow: '#e0af68'
  cursor:
    cursor: '#7aa2f7'
    text: '#c0caf5'
  indexed_colors:
  - color: '#ff9e64'
    index: 16
  - color: '#db4b4b'
    index: 17
  normal:
    black: '#15161E'
    blue: '#7aa2f7'
    cyan: '#7dcfff'
    green: '#9ece6a'
    magenta: '#bb9af7'
    red: '#f7768e'
    white: '#a9b1d6'
    yellow: '#e0af68'
  primary:
    background: '#1a1b26'
    foreground: '#c0caf5'
cursor:
  style:
    shape: Beam
env:
  TERM: xterm-256color
font:
  bold:
    family: JetBrains Mono ExtraBold Nerd Font
  italic:
    family: JetBrains Mono Medium Nerd Font
  normal:
    family: JetBrains Mono Medium Nerd Font
  size: 14.0
  offset:
    y: 5
window:
  padding:
    x: 2
    y: 2
```

### System

OS: Linux
Version: alacritty 0.10.0 (8a26dee0)
X11
Compositor: picom
WM: bspwm
