### ISSUE TITLE
[Feature Request] Scroll multiplier for ScrollLineUp

### ISSUE THREAD

**Issue by Dano507** [alacritty/alacritty#5844]
# System
OS: Linux
Version: alacritty 0.10.0 (8a26dee0)
Display Server: X11

# Issue
I have my configuration set up so that I can scroll line by line using `Shift+PageUp` or `Shift+PageDown`:
```yml
scrolling:
  multiplier: 2

key_bindings:
  - { key: PageUp,    mods: shift,   mode: ~Alt,    action: ScrollLineUp, }
  - { key: PageDown,  mods: shift,   mode: ~Alt,    action: ScrollLineUp  }
```
And this works great for me. However, the scroll multiplier only applies to mouse wheel scrolling.
I'd love to see a feature implemented that allows the user to modify the scroll distance of `ScrollLineUp` and `ScrollLineDown`.
