### ISSUE TITLE
Debugging importing a theme to Alacritty?

### ISSUE THREAD

**Issue by victorhooi** [alacritty/alacritty#5887]
I have installed the latest Alacritty via Homebrew onto macOS.

I am trying to install the Dracula theme for Alacrity from here:

https://draculatheme.com/alacritty

It mentions simply adding this to your `~/.config/alacritty/alacritty.yml`:

```
import:
  - ~/.config/alacritty/dracula.yml
```
which I have done:

```
% cat ~/.config/alacritty/alacritty.yml
import:
  - /Users/victorhooi/.config/alacritty/dracula.yml

font:
  normal:
    family: JetBrains Mono
```

However, the actual colours from the theme don't seem to apply. In fact, if I put a garbage path in the import stanza, I don't even get any error messages:

```
% cat ~/.config/alacritty/alacritty.yml
import:
  - /asdfasdfUsers/victorhooi/.config/alacritty/dracula.yml

font:
  normal:
    family: JetBrains Mono
```

I checked, and I can't seem to find any documentation for how to use imports in Alacritty, or for themes - does anybody know where this is documented?

And are there any debugging modes, or logs I can check for why the above mightn't be working?

### System

OS: macOS
Version: alacritty 0.10.0 (8a26dee)
