### ISSUE TITLE
Lag and unusable computer when bell command is run many times

### ISSUE THREAD

**Issue by pokir** [alacritty/alacritty#5951]
### System

OS: macOS (10.12.5)
Version: alacritty 0.10.1 (2844606)

### Bug description

Tried to `$ cat` a large binary file, but alacritty lagged because of the `osascript -e beep` command run to play a sound whenever the bell is rung in .alacritty.yml:

```yml
bell:
  animation: EaseOutSine
  duration: 150
  color: '#009000'
  command: 
    program: osascript
    args: ["-e", "beep"]
```

Alacritty had to be force quit (by long clicking on the icon in the dock and clicking force quit), and no other apps where able to be opened after that (apps that were open already continued working normally) and a forced computer restart was needed.

This did not happen without the `osascript -e beep` command.

### Expected behavior

Expected behavior would be to add an optional delay between the bell commands to reduce lag.

**Comment by kchibisov** [comment]
Duplicate of #3973.

**Comment by unphased** [comment]
I use 
```
bell:
  command:
    program: afplay
    args: ["/System/Library/Sounds/Tink.aiff"]
```

Which I picked up from some suggestion here, and I'm not sure that it's better than the osascript you use. the afplay command blocks and doesn't return until the sound is finished playing though. But that does not seem to impact anything. When accidental bell spam occurs (just go ahead and cat a tar file by accident, have fun), on my machine it does stay responsive (but coreaudiod starts to go nuts). 

I dunno. I think it would be sensible for alacritty to rate-limit the amount of forks being done with this. But on the other hand the philosophy is simplicity and, well, it really is just doing what we're asking of it. 

I am half-convinced that the right way to go about this is to set a command here for handling the bell which performs rate-throttling. This can be done with a reasonably simple approach like this: https://stackoverflow.com/a/59431413/340947

And a working `flock(1)` can be obtained on macOS with homebrew. It uses this: https://github.com/discoteq/flock
