### ISSUE TITLE
URL handler in Alacritty and Alacritty command is not working

### ISSUE THREAD

**Issue by ciscohack** [alacritty/alacritty#5998]
### System

OS: macOS 12.3
Version: `0.10.1.1` 

Hello Experts,

I recently moved to alacrity terminal. I am trying to use the URL handler feature but it's not working in Alacrity. can someone help me fix and config so Alacritty handles URL handling? here is my use case example 

suppose I have URL telnet://192.168.1.1:345678 or ssh://IP: port and if I click it should open alacrity so I could work on it. I also noticed none of the alacritty commands working on my terminal if I ran  "alacritty --version" or any other alacrity command it throw an error "zsh: command not found: alacritty" what to do and how to fix it.

**Comment by kchibisov** [comment]
It opens URL with your system open command or with the one you've specified. By default hovering mouse over it should highlight URL and open with macOS `open` thingy. Is `https://example.com` URL working? I'd assume apple's launcher has no clue what to do wrt `telnet: and `ssh:` url, however you can write a script and use it as a URL handler, so you can provide handling in it for `telnet` and so.

Alacritty's URL handling is very powerful, since you can customize it and do whatever you want with it, given that it's plain regex hints. Could consult corresponding config section and setup your own regexes if you want, like `yank url to clipboard` by pressing hotkey.

>"zsh: command not found: alacritty" what to do and how to fix it.

It's kind of expected given that your alacritty executable is inside `Alacritty.app` on macOS, you should symlink binary to your user `PATH` to make it work.

**Comment by ciscohack** [comment]
@kchibisov Thanks for a prompt response. Unfortunately, the normal URL is also not working. if you don't mind will you please give me a snippet of config as an example? the power of alacittty what can be done more

**Comment by ciscohack** [comment]
@kchibisov Please do help seriously need expert help.. I have this in my config but the normal URL also does not showing the mouse click option and which code section telnet script needed to add 

```
hints:
 enabled:
  - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|telnet:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    command: xdg-open
    post_processing: true
    mouse:
      enabled: true
      mods: Control
    binding:
      key: U
      mods: Control|Shift

```

**Comment by kchibisov** [comment]
It's not correct, you should replace command with your custom script or teach xdg-open or open how to handle that. By custom script I mean the script that checks schema and if it telnet runs something you want otherwise fallback to open.

**Comment by ciscohack** [comment]
> It's not correct, you should replace command with your custom script or teach xdg-open or open how to handle that. By custom script I mean the script that checks schema and if it telnet runs something you want otherwise fallback to open.

@kchibisov where is the documentation page of Alacritty where we have explained the option and its usage..
will you please fix the command for me? I am not able to do it this (exec telnet $(echo -n $URL | cut -d'/' -f3 | tr ':' ' ')") bash script showing open telnet://IP:Port URL and it's working in kitty .. need your help

**Comment by ciscohack** [comment]
@kchibisov I changed the config now when I click on telnet URL it opens alacrity but not session. Here is my config and telnet bash script

```
#!/bin/bash
exec telnet $(echo -n $URL | cut -d'/' -f3 | tr ':' ' ')
```

```
hints:
  enabled:
  - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|telnet:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    command: xdg-open ~/Downloads/FTD-Scripts/telnet.sh
    post_processing: true
    mouse:
      enabled: true
      mods: Control
    binding:
      key: U
      mods: Control|Shift

```

**Comment by ciscohack** [comment]
new script tried and that also not working. basic feature but seems very very complex config

```
  enabled:
  - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|telnet:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    command: xdg-open ~/Downloads/FTD-Scripts/\./telnet_url.sh
    post_processing: true
    mouse:
      enabled: true
      mods: Control
    binding:
      key: U
      mods: Control|Shift
```

#!/bin/bash

# Remove the telnet:// and change the colon before the port
# number to a space.
TELNET_STRING=$(echo $1 | sed -e 's/telnet:\/\///' -e 's/:/ /')

# Telnet to the remote session
/usr/local/bin/telnet $TELNET_STRING

# Don't close out the terminal unless we are done
read -p "Press a key to exit"
