### ISSUE TITLE
Be able to switch color theme when system switches to darkmode

### ISSUE THREAD

**Issue by chtenb** [alacritty/alacritty#5999]
I have my system setup in a way that it switches to and from darkmode based on the time of day. Most applications are able to detect this and be configured to switch to and from a dark color theme. Can alacritty support this as well?

**Comment by chrisduerr** [comment]
The config supports live-reload. You're free to switch your theme whenever you want, however you want.

**Comment by chtenb** [comment]
I know that the config has live reload, that's not what meant.

> Most applications are able to detect this and be configured to switch to and from a dark color theme

I meant that you would be able to configure a light and a dark theme in the config, and that alacritty would automatically choose depending on whether your system is in dark mode or light mode.

**Comment by chrisduerr** [comment]
> I meant that you would be able to configure a light and a dark theme in the config, and that alacritty would automatically choose depending on whether your system is in dark mode or light mode.

There is no desire to add this. Again the existing mechanisms are sufficient.

**Comment by chtenb** [comment]
I just expressed that desire. Why can't this be an open feature request? 

I don't mean to sound rude, I just don't understand your reasoning.

**Comment by chrisduerr** [comment]
> Why can't this be an open feature request?

Because I don't want it to be one.

**Comment by ferologics** [comment]
wow.

**Comment by chtenb** [comment]
I've found that [wezterm is able to to this](https://github.com/wez/wezterm/issues/806) @ferologics in case you're interested in this feature

**Comment by ferologics** [comment]
@chtenb i think i'm just gonna go with the stock terminal app, the friction with setting up something custom is becoming too painful to justify for.

**Comment by ferologics** [comment]
but thx

**Comment by chtenb** [comment]
@ferologics That makes sense, it can be quite a hassle :) If you ever feel like tweaking your setup again feel free to steal my config at https://github.com/chtenb/dotfiles/blob/master/wezterm.lua as a first start.

**Comment by SaahilParikh** [comment]
+1

**Comment by zaz** [comment]
> Again the existing mechanisms are sufficient.

How do we use these?  Do we have to run a separate script to check whether the system theme is light or dark?  That script would then change the Alacritty config and prompt it to reload?  Is that the idea?

Would you accept a patch that adds this feature to Alacritty?  What about a patch to add a small bash script that does the above?

This is a really useful feature, so we really should have a way for users to do it easily.

Thank you for your work on Alacritty!

**Comment by kchibisov** [comment]
There are plenty resources available online on how to switch themes globally or hook to system theme switching and run arbitrary scripts, alacritty is not a separate citizen here, since you have to do the same for your terminal editor if you're using light/dark themes in it, etc. For alacritty you can have your themes in separate files and import the one you need (import section in the config), the config is live reloaded so it'll be picked up right away.

it's really nothing special here.

**Comment by vittorio-c** [comment]
I would love such a feature as well !

in the meantime, could someone put me in the right direction in order to create a bash script that would hook to system theme switching and run something like 

```
sed -i 's/catppuccin-mocha/catppuccin-latte/' ~/.config/alacritty/alacritty.yml
```

(from <https://shapeshed.com/vim-tmux-alacritty-theme-switcher/https://shapeshed.com/vim-tmux-alacritty-theme-switcher/>)

I've searched on the internet, but the closest topic I've found to achieve that is a one related to Emacs : <https://emacs.stackexchange.com/questions/55417/change-theme-when-os-dark-mode-changes>

I'm using Manjaro with Gnome

**Comment by kchibisov** [comment]
On gnome you'd need to hook to dbus monitor stuff and look for changes on `color-scheme` variant iirc. Because the dark/light is a dbus property.

`org.gnome.desktop.interface color-scheme 'prefer-dark'`.

**Comment by tonsky** [comment]
+1 for this feature. I switch my system between light and dark occasionally, and almost every app follows, except for Alacritty

**Comment by nixpulvis** [comment]
> How do we use these? Do we have to run a separate script to check whether the system theme is light or dark? That script would then change the Alacritty config and prompt it to reload? Is that the idea?

In short, yes.

**Comment by vyas-n** [comment]
While this feature isn't a dealbreaker, there is a notable dearth of documentation and general unfriendliness of the alacritty configuration system.

It's not the first time I've tried to configure Alacritty and haven't been able to get very far after weeks of searching.

Until alacritty's documentation improves to better show how to configure it, I'm switching to https://github.com/wez/wezterm

**Comment by christianfosli** [comment]
I made a quick rust-based service to do this for my personal config files.
(this meaning updating/renaming config files such that the theme changes)
See https://github.com/christianfosli/on-colorscheme-changed 

It is written specifically for my config files, but feel free to base your own solutions off of it if you'd like :smile:

**Comment by martin-braun** [comment]
> > Why can't this be an open feature request?
> 
> Because I don't want it to be one.

I just came across alacritty due to a recommendation, but this sort of response will make me look elsewhere. Sorry for the off-topic. Surely, you are free to do what you want and somebody can still fork and implement it on their own, but it's still such a rude response.

**Comment by seguri** [comment]
Such a rude response requires at least a quick & dirty solution for all the poor souls that stumble upon this thread.
This has been tested on macOS.

Requirements:
- node
- `npm i -g alacritty-themes dark-mode-cli`

Add this to your crontab (`crontab -e`):

```sh
* * * * * /path/to/alacritty-themes "$(/bin/test $(/path/to/dark-mode status) = off && /bin/echo Brewer.light || /bin/echo Brewer.dark)"
```

Don't forget to adapt your full paths (`/path/to`), e.g. `/Users/mark/.volta/bin/alacritty-themes`.
I've added a `&& rm ~/.config/alacritty/alacritty.yml.*.bak` at the end of mine crontab cause `alacritty-themes` otherwise generates a backup file every minute.

**Comment by cameronmalek** [comment]
I solved this using the Swift program [bouk/dark-mode-notify](https://github.com/bouk/dark-mode-notify) pointed at a shell script that does all the light/dark changes I want, including Alacritty. I found this to be the most macOS-native way to do this. [The README includes a LaunchAgent](https://github.com/bouk/dark-mode-notify?tab=readme-ov-file#background-agent) to start it in the background automatically.

Then I point it at this shell script:

```bash
if [[ "${DARKMODE}" -eq 0 ]]; then
    sed -i .bak 's/everforest_dark/everforest_light/' ~/.config/alacritty/alacritty.toml
elif [[ "${DARKMODE}" -eq 1 ]]; then
    sed -i .bak 's/everforest_light/everforest_dark/' ~/.config/alacritty/alacritty.toml
fi
```

**Comment by onkoe** [comment]
Sorry to necropost. That said, we shouldn't assert that this functionality already exists.

You must run a daemon alongside the terminal to follow the standard system theming behavior. That's not remotely part of Alacritty. By this logic, you state that Alacritty supports any feature, as a user can write a program with that feature. 

It'd be better to say that you don't plan to implement this feature and its functionality doesn't exist. 

In addition, I'd suggest maintaining a list of unplanned features (or perhaps a GitHub Issues tag) so users don't get their hopes up. Seeing this issue closed, I assumed that Alacritty had implemented it already! 😖️

**Comment by dee-kryvenko** [comment]
For some reason I hate how unreliable string parsing with sed or equivalents can be, and I would not do these rituals described above personally... but there's always another way.

I did clone https://github.com/alacritty/alacritty-theme

```
mkdir -p ~/.config/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
```

I did add to my `~/.config/alacritty/alacritty.toml`:

```toml
import = [
    "~/.config/alacritty/themes/themes/_active.toml"
]
```

And I did add the following to my `~/.zprofile`:

```zsh
alias aladark="ln -fs ~/.config/alacritty/themes/themes/github_dark.toml ~/.config/alacritty/themes/themes/_active.toml"
alias alalight="ln -fs ~/.config/alacritty/themes/themes/github_light.toml ~/.config/alacritty/themes/themes/_active.toml"
```

Works like a charm, I just switch on demand running `aladark` or `alalight`. Sucks that this is not automatic, but neither it is automatic for nvim, and other terminals that I tried on my mac all have problems with the meta key as left option (including iterm2) and alacritty is the only one that works flawlessly, so I'll take that. Thanks for the project.

**Comment by xqm32** [comment]
> For some reason I hate how unreliable string parsing with sed or equivalents can be, and I would not do these rituals described above personally... but there's always another way.
> 
> I did clone https://github.com/alacritty/alacritty-theme
> 
> ```
> mkdir -p ~/.config/alacritty/themes
> git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
> ```
> 
> I did add to my `~/.config/alacritty/alacritty.toml`:
> 
> ```toml
> import = [
>     "~/.config/alacritty/themes/themes/_active.toml"
> ]
> ```
> 
> And I did add the following to my `~/.zprofile`:
> 
> ```shell
> alias aladark="ln -fs ~/.config/alacritty/themes/themes/one_dark.toml ~/.config/alacritty/themes/themes/_active.toml"
> alias alalight="ln -fs ~/.config/alacritty/themes/themes/pencil_light.toml ~/.config/alacritty/themes/themes/_active.toml"
> func alatheme() {
>   ln -fs ~/.config/alacritty/themes/themes/$1.toml ~/.config/alacritty/themes/themes/_active.toml
> }
> ```
> 
> Works like a charm, I just switch on demand running `aladark` or `alalight`. Sucks that this is not automatic, but neither it is automatic for nvim, and other terminals that I tried on my mac all have problems with the meta key as left option (including iterm2) and alacritty is the only one that works flawlessly, so I'll take that. Thanks for the project.

Very good idea, thanks @dee-kryvenko! I did some extra work to make it slightly more automated.

I added to my  `~/.config/alacritty/alacritty.toml`:

```toml
[env]
ALACRITTY = "true"
```

And then I added to my `.zshrc`:

```sh
if [ "$ALACRITTY" = "true" ]
then
  theme() {
    ln -sf $HOME/.config/alacritty/themes/themes/$1.toml $HOME/.config/alacritty/active.toml
  }
  if [ "$(defaults read -g AppleInterfaceStyle)" = "Dark" ]
  then
    theme "github_dark"
  else
    theme "github_light"
  fi
fi
```

Now _Alacritty_ can automatically switch the theme!

**Comment by nilobarp** [comment]
I have always used the following two functions in my `.zshrc`

```sh
function dark() {
        ln -fs ~/.config/alacritty/themes/catppuccin-frappe.yml ~/.config/alacritty/themes/_active.yml
        touch ~/.config/alacritty/alacritty.yml
}
function light() {
        ln -fs ~/.config/alacritty/themes/catppuccin-latte.yml ~/.config/alacritty/themes/_active.yml
        touch ~/.config/alacritty/alacritty.yml
}
```

in alacritty config the simlink is imported
```
import:
  - ~/.config/alacritty/themes/_active.yml
```

since the config file is touched, alacritty auto loads after the function executes.

**Comment by midsorbet** [comment]
Got it working with home-manager + darkman based on https://github.com/alacritty/alacritty/issues/5999#issuecomment-2232283312:
```
  services.darkman = {
    enable = true;
    darkModeScripts = {
      alacritty-theme = ''
        ln -fs ${config.xdg.configHome}/alacritty/dark.toml ${config.xdg.configHome}/alacritty/_active.toml
      '';
    };
    lightModeScripts = {
      alacritty-theme = ''
        ln -fs ${config.xdg.configHome}/alacritty/light.toml ${config.xdg.configHome}/alacritty/_active.toml
      '';
    };
    settings = {
      usegeoclue = true;
    };
  };
  xdg.configFile.alacritty = {
    source = ../config/alacritty;
    recursive = true;
  };
```
And, I have my themes within my `config/alacritty` directory

**Comment by o-be-one** [comment]
Woaw that answer from alacritty dev is really poor! Alright, I guess it's a uninstall, let's go back to that nice WezTerm.
And thanks to people who built something around to support a simple feature that is now available in most OS and in more and more apps.

**Comment by houtianze** [comment]
Nice, just uninstalled Alacritty after reading this, we have iTerm, WezTerm, Warp and many to choose from.

**Comment by ebr** [comment]
> Because I don't want it to be one.

OK, well that sucks.

I've been using alacritty for years, but guess might as well switch to another terminal. As an OSS maintainer myself, I'd never condone being this rude to the community, even as a "benevolent dictator". ick.

**Comment by schulice** [comment]
For someone looking for a solution on Windows, here's an example that uses Auto-Dark-Mode along with busybox-mingw:
```yml
- Name: Alacritty
  Command: cmd
  WorkingDirectory: C:\Users\<username>\AppData\Roaming\alacritty
  ArgsLight: [/c, C:/busybox/sed.exe -i s/onedark/onelight/ alacritty.toml]
  ArgsDark: [/c, C:/busybox/sed.exe -i s/onelight/onedark/ alacritty.toml]
  AllowedSources: [Any]
```

**Comment by andrematias** [comment]
# Alacritty theme sync MacOS

## Update alacritty.toml

```toml
[general]
import = [ "~/.config/alacritty/themes/theme-dark.toml" ]
```

## Create light and dark themes

1. Create theme-dark.toml file

```bash
mkdir -p $HOME/.config/alacritty/themes
touch $HOME/.config/alacritty/themes/theme-dark.toml
```

2. Add theme colors

```toml
# Default colors
[colors.primary]
background = '#24292e'
foreground = '#d1d5da'

# Normal colors
[colors.normal]
black   = '#586069'
red     = '#ea4a5a'
green   = '#34d058'
yellow  = '#ffea7f'
blue    = '#2188ff'
magenta = '#b392f0'
cyan    = '#39c5cf'
white   = '#d1d5da'

# Bright colors
[colors.bright]
black   = '#959da5'
red     = '#f97583'
green   = '#85e89d'
yellow  = '#ffea7f'
blue    = '#79b8ff'
magenta = '#b392f0'
cyan    = '#56d4dd'
white   = '#fafbfc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#f97583'
```

3. Create theme-light.toml file

```bash
mkdir -p $HOME/.config/alacritty/themes
touch $HOME/.config/alacritty/themes/theme-light.toml
```

4. Add light colors theme

```toml
# Default colors
[colors.primary]
background = '#ffffff'
foreground = '#24292f'

# Normal colors
[colors.normal]
black   = '#24292e'
red     = '#d73a49'
green   = '#28a745'
yellow  = '#dbab09'
blue    = '#0366d6'
magenta = '#5a32a3'
cyan    = '#0598bc'
white   = '#6a737d'

# Bright colors
[colors.bright]
black   = '#959da5'
red     = '#cb2431'
green   = '#22863a'
yellow  = '#b08800'
blue    = '#005cc5'
magenta = '#5a32a3'
cyan    = '#3192aa'
white   = '#d1d5da'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#cb2431'

```

## Sync theme script

1. Create the script file

```bash
touch $HOME/.config/alacritty/alacritty-sync-theme
```

2. Add script content

```bash
#!/bin/bash

CONFIG="$HOME/.config/alacritty/alacritty.toml"
DARK="theme-dark.toml"
LIGHT="theme-light.toml"

get_theme() {
  if [[ "$(defaults read -g AppleInterfaceStyle 2>/dev/null)" == "Dark" ]]; then
    echo "dark"
  else
    echo "light"
  fi
}

apply_theme() {
  if [[ "$1" == "dark" ]]; then
    sed -i '' "s/$LIGHT/$DARK/" "$CONFIG"
  else
    sed -i '' "s/$DARK/$LIGHT/" "$CONFIG"
  fi
}

last_mode=""
while true; do
  current_mode=$(get_theme)
  if [[ "$current_mode" != "$last_mode" ]]; then
    apply_theme "$current_mode"
    last_mode="$current_mode"
  fi
  sleep 1
done
```

3. Give execution permissions

```bash
sudo chmod +x $HOME/.config/alacritty/alacritty-sync-theme
```

4. Create symlinks to a PATH directory

```bash
sudo ln -sf $HOME/.config/alacritty/alacritty-sync-theme /usr/local/bin/alacritty-sync-theme
```

## Background service

### Create a plist

1. Create the plist file

```bash
touch $HOME/Library/LaunchAgents/com.matias.alacritty-sync-theme.plist
```

2. Add content into plist file

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.matias.alacritty-theme-sync</string>

    <key>ProgramArguments</key>
    <array>
      <string>/bin/bash</string>
      <string>/usr/local/bin/alacritty-sync-theme</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>
  </dict>
</plist>
```

3. Give permissions

```bash
chmod 644 $HOME/Library/LaunchAgents/com.matias.alacritty-sync-theme.plist
```

4. Load background service

```bash
launchctl unload $HOME/Library/LaunchAgents/com.matias.alacritty-sync-theme.plist 2>/dev/null || true
launchctl load $HOME/Library/LaunchAgents/com.matias.alacritty-sync-theme.plist
```
# Toggle theme preview

https://github.com/user-attachments/assets/53fa968e-3ce9-4581-89ed-e0e73ae18ec3

# Thanks
-  @dee-kryvenko for the `defaults read -g AppleInterfaceStyle` insight

**Comment by spacelatte** [comment]
Not sure why all the fuss here, I understand not _ideal_ but totally doable. Given Alacritty supports live config reload.

My approach was to hook this into the bell (alert) itself. As soon as I saw this thread, I thought of creating a symlink to the theme file and using the config live-reloading. 

Since I already had `\a` (bell) in my `$PS1` (so that I get notified when a command ends) I only needed to create an initial symlink to the theme, such as: `ln -s ~/github/alacritty/alacritty-theme/themes/github_light.toml ~/.alacritty-theme.toml`. 

```toml
import = [
	"~/.alacritty-theme.toml",
]

[bell]
animation = "Ease"
color = "0x808080"
duration = 0
command = { program = "sh", args = [ "-c", "ln -sf \"$(readlink \"${HOME}/.alacritty-theme.toml\" | sed -E \"s:(light|dark):$((defaults read -g AppleInterfaceStyle || echo Light) | tr A-Z a-z):g\";)\" \"${HOME}/.alacritty-theme.toml\"; " ] }
```
