### ISSUE TITLE
macOS: Returning back from fullscreen causes window to get smaller by the height of titlebar

### ISSUE THREAD

**Issue by reportaman** [alacritty/alacritty#6007]
Entering fullscreen and moving out of fullscreen mode changes the size of the window to be smaller by the size of titlebar. 

Video:

https://user-images.githubusercontent.com/71736629/163748925-32945912-441a-49fa-8dda-092cce80ef85.mp4

### System
OS: macOS
Version: alacritty 0.10.0-dev (b0da035e)

**Comment by chrisduerr** [comment]
I'd assume you have window decorations disabled based on your video? Looks like the window is resized to account for decorations and actually draws them, but then the decorations are removed without changing window size.

**Comment by reportaman** [comment]
@chrisduerr Yes, I have ``window.decorations: "none"`` as seen below

```
window:
  #  padding:
  #    x: 0
  #    y: 30
  decorations: "none"
  dimensions:
    columns: 114
    lines: 62
  opacity: 1
```
