### ISSUE TITLE
alacritty does not grab tmux's current directory

### ISSUE THREAD

**Issue by GZLiew** [alacritty/alacritty#6018]
### System
OS: macOS
Version: alacritty 0.10.1 (2844606)

my config

```yml
shell:
  program: /usr/local/bin/tmux
 
key_bindings:
  - { key: N,              mods: Command,                    action: CreateNewWindow      }
```

when I set my shell program to `/bin/bash` for example alacritty was able to open a new window in the last directory
