### ISSUE TITLE
[Feature Request] Conditional imports for config.yml based on OS

### ISSUE THREAD

**Issue by bharatvaj** [alacritty/alacritty#6024]
I have a really small alacritty.yml file which I use between windows and macos. It was fine until I was using the default shells for the respective OSes, but recently I switched to `cmd` in windows and `zsh` in mac and it's mildly painful to modify the shell.program value every time I pull the changes of my dotifles.

Maybe something like this can be added for the config file?
```yml
windows:
  import:
    - ~/.config/alacritty/windows.yml
macos
  import:
    - ~/.config/alacritty/macos.yml
```

or maybe something like this?
```yml
windows_import:
  - ~/.config/alacritty/windows.yml
macos_import:
  - ~/.config/alacritty/macos.yml
```
