### ISSUE TITLE
Regex `hints` do not expose current shell context

### ISSUE THREAD

**Issue by howardjohn** [alacritty/alacritty#6028]
When using regex `hints`, the current shell context is not exposed. This makes it challenging to do things that are not entirely stateless. For example, for a URL match I can open in `chrome` without issue. However, if I want to open a **relative** file path in my IDE, I cannot because the `command` doesn't get any context about where it is run from (PWD).

This actually makes a lot of sense given some text on the terminal and a PWD (or other context) are not really strictly linked. However, it does make this use case impossible so I figured it was worth bringing up.

Config:
```yaml

hints:
  enabled:
  - regex: '.+?\.go:[0-9]*:[0-9]*:
    command: goland
    post_processing: true
    mouse:
      enabled: true
      mods: None
    binding:
      key: U
      mods: Control|Shift

```

### System

OS: Linux
Version: `alacritty 0.9.0`
Linux/BSD: x11 i3 tmux
