### ISSUE TITLE
My .yml still isn't working; I changed the tabs to spaces like I was told to and there's now a different error

### ISSUE THREAD

**Issue by Waddles6272** [alacritty/alacritty#6083]
WHOO; another ticket cause they keep getting closed and I have to just open a new one instead of just updating the one I already had open, let's go!

Anyways, I changed the tabs to spaces like I was told to do, and now I have a new error (https://imgur.com/a/4s9rTyJ) so I don't know what to do or how to continue from here. 

Quick edit: the smaller indents are 3 spaces in, the larger indents are 6 spaces in.

Here is the update .yml:

```
window:
   padding:
      x: 5
      y: 5
   class:
      instance: Alacritty
      general: Alacritty
    
scrolling:
   history: 10000
   multiplier: 3
  
background_opacity: 0.5

font:
   normal:
      family: JetBrains Mono Nerd Font
      style: Medium
   bold:
      family: JetBrains Mono Nerd Font
      style: Bold
   italic:
      family: JetBrains Mono Nerd Font
      style: MediumItalic
   bold_italic:
      family: JetBrains Mono Nerd Font
       style: BoldItalic
   size: 7
   draw_bold_text_with_bright_colors: true
    
colors: 
   primary:
      background: "#020202"
      foreground: "#d8e1e7"
   normal:
      black: "#030404"
      red: "#101315"
      green: "#202529"
      yellow: "#373f44"
      blue: "#545f66"
      magenta: "#76858f"
      cyan: "#9fb2bf"
      white: "#dce3e9"
   bright:
      black: "#7ec1e4"
      red: "#f5dbcf"
      green: "#70a2bc"
      yellow: "#86a95a"
      blue: "#9bba78"
      magenta: "#7fbcad"
      cyan: "#58a4c7"
      white: "#84c2b3"
     
cursor:
   style: Underline
   blinking: Always
   blink-interval: 750
  
selection:
   save_to_clipboard: false
  
live_config_reload: true

shell:
   program: /usr/bin/zsh
  
key_bindings:
   - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
```
