### ISSUE TITLE
Incorrect window padding when using the built-in tabs in macOS

### ISSUE THREAD

**Issue by techvlad** [alacritty/alacritty#6155]
When I open second and more tabs in Alacritty tabs bar overlaps part of the window. Also, the mouse select starts working weirdly. When I'm selectin lines Alacritty selects the line above

Example:
https://user-images.githubusercontent.com/13676043/175787321-2e3c1085-821d-44da-aad0-97499182d290.mp4
![Untitled](https://user-images.githubusercontent.com/13676043/175787471-6e7eaa59-5897-44b0-b183-47f0df8f214b.gif)

### System

OS: macOS 12.4 21F79 arm64
Version: alacritty 0.10.1 (2844606)

### Logs
Config
```yml
live_config_reload: true

font:
  size: 12

key_bindings:
  - { key: T, mods: Command, action: CreateNewWindow }
```
