### ISSUE TITLE
Opacity doesnt work

### ISSUE THREAD

**Issue by ramita-0** [alacritty/alacritty#6168]
Cant make opacity work, it makes terminal darker instead of more transparent.

Could it be because im running on a VM? i have read in another issue that a person said that it may be because of it.

### What im running:
OS: Linux Mint
Alacritty Version: alacritty 0.11.0-dev (6018590d)
X11, running on VMWare

.yml
```yml
window:
    padding:
        x: 30
        y: 10

    # Spread additional padding evenly around the terminal content.
    dynamic_padding: false

    # Window decorations
    #decorations: none
    decorations: full

    # Window opacity as a floating point number from `0.0` to `1.0`.
    opacity: 0.2
```

![term](https://user-images.githubusercontent.com/72410961/176252057-2eaffea1-709e-41c8-b46c-c6b2746eac73.png)
