### ISSUE TITLE
Having specific strings colored by default

### ISSUE THREAD

**Issue by Ok-pass** [alacritty/alacritty#6178]
Would it be possible to implement a color setting in hints.regex or elsewhere, that would allow regex strings to always appear highlighted? 
For example something like
```
hints:
  enabled:
  - regex: "(https:|http:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    color:
      background: '#3388ff'
      foreground: '#000000'
```
to have URLs colored. 
I'm looking for a way to quickly spot full URL paths in large amounts of text.

An alternative is to have the strings matched by a regex highlighted when in Hints mode, similar to how it is in Search mode.

System
OS: Linux
Version: alacritty 0.10.1
