### ISSUE TITLE
Font rendering too bold?

### ISSUE THREAD

**Issue by alphahot1** [alacritty/alacritty#6181]
OS: macOS
Version: 0.10.1

Hi and thanks for  the great app! I looked around but I could't find anything, on MacOS the font is rendered somewhat bold... this is my config:

```
# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
<img width="395" alt="Schermata 2022-07-04 alle 13 15 13" src="https://user-images.githubusercontent.com/984906/177143773-6b63b00a-4618-46b2-a27c-54318c67bb66.png">

    family: "MesloLGM Nerd Font Mono"

    # The `style` can be specified to pick a specific face.
    #style: Regular
```

but with the default config it's the same. With other terminals fonts are rendered more thinner,
I'm attaching a screenshot. Thanks!

<img width="365" alt="image" src="https://user-images.githubusercontent.com/984906/177144062-92c876e5-c480-4a63-aecb-ca7c437239db.png">
