### ISSUE TITLE
Feature request: Customize colors based on window focus

### ISSUE THREAD

**Issue by Hubro** [alacritty/alacritty#6224]
I think it would be cool as hell to be able to customize colors based on the window focus state.

This would be similar to the [CSS pseudo-selector `:focus`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus).

This would enable color schemes to make it visually clear which terminal is focused in tiled window managers, essentially fixing https://github.com/alacritty/alacritty/issues/1982.

Color scheme authors would be free to decide how unfocused windows would look. The simplest implementation would slightly change the background color. The author might also choose to dim all the colors slightly.

The config could look like this, for example:

```yaml
colors:
  primary:
    background: "#222222"

  normal:
    # ...

  bright:
    # ...

  inactive:
    primary:
      background: "#111111"
```

Colors specified under `inactive` (if any) would take precedence when the window loses focus.
