### ISSUE TITLE
Cell size is huge

### ISSUE THREAD

**Issue by Johan-Liebert1** [alacritty/alacritty#6240]
I just installed alacritty in my Manjaro distro using pacman. When I opened the terminal, I could see that the cell size (not font size) was absolutely huge and two cells were taking up half of the terminal's height.

![image](https://user-images.githubusercontent.com/39958783/183015442-6b1782a9-b5df-47a4-95cc-5c447d1152b0.png)

I'm using the default config file (where everything is commented out). I searched around this issue and added a single line in the `env` section of the config file. Following is the change I made which did not affect anything 

```yaml
# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  #TERM: alacritty
  WINIT_X11_SCALE_FACTOR: "1"

```

I have scaling enabled on my machine and when I turned off scaling, the cell sizes were not affected at all. 

For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: alacritty 0.10.1 ()
Linux/BSD: X11

### Logs

Crashes: N/A (does not crash)

Font/Terminal size: `alacritty -vv`
Created log file at "/tmp/Alacritty-6292.log"
[0.000004105s] [INFO ] [alacritty] Welcome to Alacritty
[0.000063824s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000078563s] [INFO ] [alacritty] Running on X11
[0.000401037s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/pragyan/.config/alacritty/alacritty.yml"
[0.019340346s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT | COLOR, render_mode: "Lcd", lcd_filter: 1 }
[0.021428510s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.022076255s] [DEBUG] [alacritty] Estimated DPR: 1
[0.022086205s] [DEBUG] [alacritty] Estimated window size: None
[0.022114916s] [DEBUG] [alacritty] Estimated cell size: 136 x 128
[0.055163357s] [INFO ] [alacritty] Device pixel ratio: 1
[0.056387914s] [INFO ] [alacritty] Initializing glyph cache...
[0.062294503s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT | COLOR, render_mode: "Lcd", lcd_filter: 1 }
[0.069940455s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT | COLOR, render_mode: "Lcd", lcd_filter: 1 }
[0.078367805s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT | COLOR, render_mode: "Lcd", lcd_filter: 1 }
[0.087733381s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT | COLOR, render_mode: "Lcd", lcd_filter: 1 }
[0.090430382s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.094678214s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.098584152s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.102600367s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.106576353s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.050176216s
[0.106625022s] [INFO ] [alacritty] Cell size: 136 x 128
[0.106634859s] [INFO ] [alacritty] Padding: 0 x 0
[0.106639137s] [INFO ] [alacritty] Width: 800, Height: 600
[0.107229507s] [INFO ] [alacritty] PTY dimensions: 4 x 5
[0.108683275s] [INFO ] [alacritty] Initialisation complete
[0.122360036s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.122391312s] [INFO ] [alacritty] Padding: 0 x 0
[0.122416910s] [INFO ] [alacritty] Width: 800, Height: 600
[0.221911456s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1',],['~',],] at line 949
[0.276304767s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.277779153s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[4.344232971s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-6292.log"

Keyboard and bindings: `alacritty --print-events`
