### ISSUE TITLE
Changing font size no longer works

### ISSUE THREAD

**Issue by jaredreardon** [alacritty/alacritty#6245]
I've been having an issue recently where changing the font size in alacritty no longer actually changes it. The part that makes this confusing is that this _was_ working just fine as recently as yesterday and now, all of a sudden, when I change the font size nothing happens. Even after a full reboot, the size remains the same. I haven't changed anything in my alacritty config since this was last working so I honestly have no idea what may be causing this.

Here's my block of code pertaining to fonts in my config if anyone needs it:

```
# Font Configuration
font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  bold_italic:
    family: monospace
    style: Bold Italic
    size: 10.0
```

The version I'm on is alacritty 0.10.1.

Not sure if this is of any help at all but here is the output when I run alacritty -vv:

```
Created log file at "/tmp/Alacritty-12889.log"
[0.000001430s] [INFO ] [alacritty] Welcome to Alacritty
[0.000019598s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000025338s] [INFO ] [alacritty] Running on X11
[0.000240413s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/jared/.config/alacritty/alacritty.yml"
[0.008716779s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.010085004s] [DEBUG] [alacritty] Estimated DPR: 2
[0.010095603s] [DEBUG] [alacritty] Estimated window size: None
[0.010098713s] [DEBUG] [alacritty] Estimated cell size: 15 x 37
[0.041335767s] [INFO ] [alacritty] Device pixel ratio: 2
[0.044265614s] [INFO ] [alacritty] Initializing glyph cache...
[0.046860975s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.049891336s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.052903178s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.055906951s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.062205937s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.017931254s
[0.062240844s] [INFO ] [alacritty] Cell size: 15 x 37
[0.062246244s] [INFO ] [alacritty] Padding: 10 x 4
[0.062248964s] [INFO ] [alacritty] Width: 800, Height: 600
[0.066045500s] [INFO ] [alacritty] PTY dimensions: 16 x 52
[0.067408136s] [INFO ] [alacritty] Initialisation complete
[0.068021054s] [DEBUG] [alacritty_terminal] New num_cols is 136 and num_lines is 55
[0.068433736s] [INFO ] [alacritty] Padding: 6 x 8
[0.068439745s] [INFO ] [alacritty] Width: 2052, Height: 2051
```

**Comment by kchibisov** [comment]
Try this.
```
# Font Configuration
font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  bold_italic:
    family: monospace
    style: Bold Italic
  size: 10.0
```
