### ISSUE TITLE
Alacritty rendering problem when using zellij, some black blocks are not fully rendered

### ISSUE THREAD

**Issue by liaohui5** [alacritty/alacritty#6285]
Alacritty rendering problem when using [zellij](https://github.com/zellij-org/zellij), some black blocks are not fully rendered

I don't know why using zellij in [kitty](https://github.com/kovidgoyal/kitty) and then entering neovim does not have this problem

![image](https://user-images.githubusercontent.com/29266093/186674598-9919e6ad-afe4-4006-af76-81894fafbabd.png)

### System

OS: MacOS 12.4(Monterey) MacBook Pro (16-inch, 2019)
Alacritty Version:  alacritty 0.10.1 (2844606)
shell: zsh

###  bug trigger step

1. open alacritty
2. open zellij
3. open neovim

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Created log file at "/var/folders/yj/8b75fq7130j41vcpzqmyp3qm0000gp/T/Alacritty-82199.log"
[0.000004365s] [INFO ] [alacritty] Welcome to Alacritty
[0.000261068s] [INFO ] [alacritty] Version 0.10.1 (2844606)
[0.001169281s] [INFO ] [alacritty] Configuration files loaded from: "/Users/liaohui5/.config/alacritty/alacritty.yml"
[0.001756600s] [DEBUG] [alacritty] Using environment locale: zh_CN.UTF-8
[0.033641611s] [DEBUG] [alacritty] Estimated DPR: 1
[0.033704681s] [DEBUG] [alacritty] Estimated window size: None
[0.033728804s] [DEBUG] [alacritty] Estimated cell size: 10 x 21
[0.083705406s] [INFO ] [alacritty] Device pixel ratio: 1
[0.087204827s] [INFO ] [alacritty] Initializing glyph cache...
[0.126140025s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.038889603s
[0.126200948s] [INFO ] [alacritty] Cell size: 10 x 21
[0.126222082s] [INFO ] [alacritty] Padding: 2 x 2
[0.126237864s] [INFO ] [alacritty] Width: 800, Height: 600
[0.126327297s] [INFO ] [alacritty] PTY dimensions: 28 x 79
[0.128843954s] [INFO ] [alacritty] Initialisation complete
[0.906563106s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','3','3','7',],['R','e','m','o','t','e','H','o','s','t','=','l','i','a','o','h','u','i','5','@','M','a','c','B','o','o','k','.','l','o','c','a','l',],] at line 949
[0.906615954s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','3','3','7',],['C','u','r','r','e','n','t','D','i','r','=','/','U','s','e','r','s','/','l','i','a','o','h','u','i','5','/','.','c','o','n','f','i','g','/','a','l','a','c','r','i','t','t','y',],] at line 949
[0.906639012s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','3','3','7',],['S','h','e','l','l','I','n','t','e','g','r','a','t','i','o','n','V','e','r','s','i','o','n','=','1','3',],['s','h','e','l','l','=','z','s','h',],] at line 949
[0.912067351s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1',],['.','.','f','i','g','/','a','l','a','c','r','i','t','t','y',],] at line 949
[0.934303930s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','3','3',],['D',],['0',],] at line 949
[0.937320285s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','3','3','7',],['R','e','m','o','t','e','H','o','s','t','=','l','i','a','o','h','u','i','5','@','M','a','c','B','o','o','k','.','l','o','c','a','l',],] at line 949
[0.937369620s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','3','3','7',],['C','u','r','r','e','n','t','D','i','r','=','/','U','s','e','r','s','/','l','i','a','o','h','u','i','5','/','.','c','o','n','f','i','g','/','a','l','a','c','r','i','t','t','y',],] at line 949
[1.028010697s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','3','3',],['A',],] at line 949
[1.028075694s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','3','3',],['B',],] at line 949

Keyboard and bindings: `alacritty --print-events`
[74.713360403s] [INFO ] [alacritty] glutin event: MainEventsCleared
[74.713406983s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[74.713446006s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 2363393017282888 }, requested_resume: None })
[74.714918459s] [INFO ] [alacritty] glutin event: MainEventsCleared
[74.714969984s] [INFO ] [alacritty] glutin event: RedrawEventsCleared

### alacritty.yaml
```yaml
window:
  decorations: "buttonless" # full | buttonless, 设置为 buttonless 就不显示标题栏
  padding:
    x: 2
    y: 2
live_config_reload: true
draw_bold_text_with_bright_colors: false
font:
  normal:
    family: "Hack Nerd Font Mono"
    style: Regular
  bold:
    family: "Hack Nerd Font Mono"
    style: Regular
  italic:
    family: "Hack Nerd Font Mono"
    style: Italic
  bold_italic:
    family: "Hack Nerd Font Mono"
    style: Italic
  size: 16.0
  offset:
    x: 1
    y: 2
cursor:
  blinking: Off
  unfocused_hollow: true

key_bindings:
  - { key: V, mods: command, action: Paste }
  - { key: C, mods: command, action: Copy }
  - { key: T, mods: Alt, chars: "\et" }
  - { key: H, mods: Alt, chars: "\eh" }
  - { key: J, mods: Alt, chars: "\ej" }
  - { key: K, mods: Alt, chars: "\ek" }
  - { key: L, mods: Alt, chars: "\el" }
  - { key: I, mods: Alt, chars: "\ei" }
  - { key: N, mods: Alt, chars: "\en" }

theme: Monokai-Sublime
colors:
  name: Monokai-Sublime
  primary:
    background: "#23241f"
    foreground: "#f8f8f2"
  cursor:
    text: "#f5f5f5"
    cursor: "#4f7beb"
  normal:
    black: "#272822"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f0f0f0"
  bright:
    black: "#75715e"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f9f8f5"
```

Need more information from me?
