### ISSUE TITLE
Font and glyph offset does not look as expected

### ISSUE THREAD

**Issue by abdul-malek-dev** [alacritty/alacritty#6291]
Similar to [another issue opened/closed here](https://github.com/alacritty/alacritty/issues/5830), I've noticed on both macOS and Linux that all combinations of negative `font.offset.y` values and `font.glyph_offset.y` values result in artifacts outside of the line/cell.

This can be compared to `kitty`, for example, where glyphs are centered with no artifacts outside the cell regardless of line height/offset. 

### System

OS: Linux, macOS
Version: 0.10.1
Linux/BSD: Both X11 & Wayland, GNOME

### Notes
I've attached two screenshots, one with:
```
font:
  offset:
    y: -4
  glyph_offset:
    y: -2
```
and the other with:
```
font:
  offset:
    y: -2
  glyph_offset:
    y: -1
```
The same issue occurs on both macOS and Linux. 

![Screen Shot 2022-08-29 at 2 29 45 AM](https://user-images.githubusercontent.com/1343016/187139055-821192df-0b65-4498-b07c-f2ec1b7a2531.png)
![Screen Shot 2022-08-29 at 2 30 18 AM](https://user-images.githubusercontent.com/1343016/187139059-2f9990ac-debd-4cb3-87da-a9a6ff22d423.png)
