### ISSUE TITLE
Need to resize window on startup to use alacritty

### ISSUE THREAD

**Issue by vR4eslav** [alacritty/alacritty#6298]
to use alacritty I need to resize the window every time. moreover, I resize the empty gray window, and the terminal itself appears from the size of 1px with the text like this:

`adminus-deskadminus@adminusadminus@adminusadminus@adadminus@adadminus@adadminus@adadminadminadminadminus@adminus-desktop:~$`

### System

OS: Linux Ubuntu 20.04
Version: 0.11.0-dev
Linux/BSD: Wayland

### Logs
`alacritty -vv`

https://pastebin.com/Hnpx2quH

 `alacritty --print-events`

https://pastebin.com/TjAte1Tk

**Comment by chrisduerr** [comment]
What exactly is your complaint here? If you want Alacritty to spawn at a certain size, set the column/lines or maximize it on start?

**Comment by jeff-blank** [comment]
I ran into this yesterday even with dimensions set up. I found that I need to set the font/size above the window dimensions in the config file.

this does what I want/expect:

```
font:
  normal:
    family: "Cascadia Mono"
  size: 8
window:
  dimensions:
    columns: 80
    lines: 30
```

this gives me the right font size and the wrong window size (actually the right window size for the default font):

```
window:
  dimensions:
    columns: 80
    lines: 30
font:
  normal:
    family: "Cascadia Mono"
  size: 8
```
