### ISSUE TITLE
How to pass click events to Tmux and Vim?

### ISSUE THREAD

**Issue by llinfeng** [alacritty/alacritty#6299]
I'm attempting to switch from Windows Terminal to Alacritty. With WT, left-clicks were sent to vim and tmux sessions for focusing on a different buffer/pane. With exactly the same WSL instance, I can no longer perform these types of actions through mouse clicks.

Please advise what I'm missing from the following `alacritty.yml` file:

```
shell:
    program: "C:\\Windows\\System32\\wsl.exe"

window:
    decorations: None

key_bindings:
    - { key: Space, mods: Control, chars: "\x00" }
    - { key: V,     mods: Control, action: Paste                  }
    # - { key: C,     mods: Control, action: Copy                   }
    # - { key: C,     mods: Control|Shift, chars: "\x03"         }

selection:
    save_to_clipboard: true
```

PS: why to switch away from WT? I'm subject to a malfunctioning UAC management tool from my employer, which would screw up access to `wt.exe` at times. When this happens, I can no longer launch new WT windows. I need to restart the work laptop to fix this access issue.
