### ISSUE TITLE
Normal and bright colors are unexpectedly swapped

### ISSUE THREAD

**Issue by CairnThePerson** [alacritty/alacritty#6341]
Here's a screenshot showing what's going on. On the left is Alacritty, and on the right is URxvt.

![2022-09-16-234814_2560x1440_scrot](https://user-images.githubusercontent.com/73193674/190840144-e8e67db8-1452-49d6-a49d-b40326524ff7.png)

URxvt acts how I expect. I also tried Xterm with the same result as URxvt. Strangely, the normal/bright colors are displayed correctly in the palette section of `neofetch`. But the other places in this screenshot, the normal color is being displayed where the bright color is expected.

I tried reconfiguring Alacritty to use a different $TERM, but that doesn't seem to be the issue. Here's all I have in my Alacritty config (minus the font section):

```yml
colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'
    
  normal:
    black:   '#000000'
    red:     '#f11d1d'
    green:   '#00c100'
    yellow:  '#ff8000'
    blue:    '#0884ff'
    magenta: '#923dff'
    cyan:    '#00d5f7'
    white:   '#6c6c6c'
    
  bright:            
    black:   '#6c6c6c'
    red:     '#f11d1d'
    green:   '#00c100'
    yellow:  '#ebeb00'
    blue:    '#0884ff'
    magenta: '#fb45fb'
    cyan:    '#00d5f7'
    white:   '#e0e0e0'
```

I'm running Alacritty 0.9.0 on X11. I'm using Bash.
