### ISSUE TITLE
issues with font rendering

### ISSUE THREAD

**Issue by bryant-the-coder** [alacritty/alacritty#6372]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: 
Linux/BSD: i3gaps

### Logs
![image](https://user-images.githubusercontent.com/92417638/193455573-ad4b8e29-3fb8-4bca-bc49-c595d252e3da.png)

I am having weird font rendering issues

```yml
window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 1

scrolling:
  history: 10000
  multiplier: 3


font:
  normal:
    family: JetBrains Mono Regular Nerd Font Complete Mono
    style:  Medium
  bold:
    family: JetBrains Mono Bold Nerd Font Complete Mono
    style:  Bold
  italic:
    family: JetBrains Mono Italic Nerd Font Complete Mono
    style:  MediumItalic
  bold_italic:
    family: JetBrains Mono Bold Italic Nerd Font Complete Mono
    style: BoldItalic
  size: 9
draw_bold_text_with_bright_colors: true

colors:
  # Default colors
  primary:
    background: "0x141b1e"
    foreground: "0xdadada"

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: "0xdadada"
    cursor: "0xdadada"

  # Normal colors
  normal:
    black: "0x232a2d"
    red: "0xe57474"
    green: "0x8ccf7e"
    yellow: "0xe5c76b"
    blue: "0x67b0e8"
    magenta: "0xc47fd5"
    cyan: "0x6cbfbf"
    white: "0xb3b9b8"

  # Bright colors
  bright:
    black: "0x2d3437"
    red: "0xef7e7e"
    green: "0x96d988"
    yellow: "0xf4d67a"
    blue: "0x71baf2"
    magenta: "0xce89df"
    cyan: "0x67cbe7"
    white: "0xbdc3c2"

selection:
  save_to_clipboard: true

shell:
  program: /usr/bin/zsh

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
```
