### ISSUE TITLE
Alacritty does not start `shell.program` correctly on macOS

### ISSUE THREAD

**Issue by ananthb** [alacritty/alacritty#6412]
My alacritty configuration is pasted below. Alacritty used to correctly launch fish shell with tmux even though
my user's shell on macOS is the default zsh. I'm not sure what changed but now, instead fish, I get zsh.

```yaml
# vim: set filetype=yaml:

import:
  - ~/.config/alacritty/shell.yml

window:
  dimensions:
    columns: 80
    lines: 24

  dynamic_title: true

font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

selection:
  save_to_clipboard: true

live_config_reload: true
```

alacritty/shell.yaml:
```yaml
# vim: set filetype=yaml:

font:
  size: 16.0

shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -i
    - -c
    - "/opt/homebrew/bin/tmux attach -t main || /opt/homebrew/bin/tmux new-session -t main"
``` 

### System

OS: macOS
Version: alacritty 0.11.0 (8dbaa0b)

### Logs

Font/Terminal size: `[0.000003083s] [INFO ] [alacritty] Welcome to Alacritty
[0.000217000s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0b)
[0.000459916s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/ananth.b/.config/alacritty/alacritty.yml"
                                     "/Users/ananth.b/.config/alacritty/shell.yml"
[0.000623458s] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[0.023466458s] [DEBUG] [alacritty] Loading "Hack Nerd Font" font
[0.055898083s] [DEBUG] [alacritty] Estimated scaling factor: 2
[0.055929458s] [DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 1520, height: 888 })
[0.055942125s] [DEBUG] [alacritty] Estimated cell size: 19 x 37
[0.083240750s] [INFO ] [alacritty] Running on Apple M1 Pro
[0.083273000s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.085689500s] [INFO ] [alacritty] Display scale factor: 2
[0.085715416s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.094134833s] [INFO ] [alacritty] Cell size: 19 x 37
[0.094179000s] [INFO ] [alacritty] Padding: 0 x 0
[0.094187250s] [INFO ] [alacritty] Width: 1520, Height: 888
[0.094281041s] [INFO ] [alacritty] PTY dimensions: 24 x 80
[0.096074375s] [INFO ] [alacritty] Initialisation complete
[0.112010041s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.114983541s] [INFO ] [alacritty] Padding: 0 x 0
[0.115026958s] [INFO ] [alacritty] Width: 1520, Height: 888
[0.127501166s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='q', params=[0], intermediates=[62]
[0.128519458s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='h', params=[7727], intermediates=[63]`

**Comment by chrisduerr** [comment]
If you don't launch tmux, do you get a fish shell?

**Comment by ananthb** [comment]
That worked. tmux isn't running fish like it used to. Alacritty is working correctly.

**Comment by layday** [comment]
Even when alacritty's startup shell is `fish`, `$SHELL` points to `/bin/zsh` (i.e. the user default shell), so subshells spawn zsh. The way tmux works hasn't changed.

Alacritty config:

```json
```

Alacritty 0.10.1:

```sh
~ $ ps
  PID TTY           TIME CMD
 4120 ttys000    0:00.11 /Users/dimitris/.nix-profile/bin/fish -l
~ $ echo $SHELL
/Users/dimitris/.nix-profile/bin/fish
```

Alacritty 0.11.0 with the same config:

```
~ $ ps
  PID TTY           TIME CMD
 4182 ttys000    0:00.12 /Users/dimitris/.nix-profile/bin/fish -l
~ $ echo $SHELL
/bin/zsh
```

It looks like the `$SHELL` override was removed in https://github.com/alacritty/alacritty/pull/6221.

**Comment by mrmeszaros** [comment]
Alacritty `0.12.2` with config:
```yaml
shell:
  program: /opt/homebrew/bin/fish
  args: [--login]
```
Produces:
```fish
~> ps
  PID TTY           TIME CMD
 3900 ttys000    0:00.04 /opt/homebrew/bin/fish --login
~> echo $SHELL
/bin/zsh
```
