### ISSUE TITLE
Top padding, or content vertical align

### ISSUE THREAD

**Issue by qRoC** [alacritty/alacritty#6440]
Hello, I use Alacritty on MacOS with settings:

```yaml
window:
  startup_mode: SimpleFullscreen
font:
  size: 14
  offset:
    y: 1
```

I have free space at the bottom of the window:

<img width="42" alt="Screenshot 2022-10-23 at 20 51 33" src="https://user-images.githubusercontent.com/1789565/197407706-fcf63b74-49b4-4a4a-b3e8-037694145d07.png">

Is it possible to vertical align the content to the bottom or specify the padding only for the top side?
