### ISSUE TITLE
Undercurls too thin

### ISSUE THREAD

**Issue by npearson72** [alacritty/alacritty#6458]
I just noticed the following issue: https://github.com/alacritty/alacritty/issues/5873

I'm struggling to understand the decision behind the change. To me this seems like a matter of preference. In my case the undercurls are too thin. Is there a chance the thickness can be adjusted in the config?

Here is what they look like in Kitty: (Which I would argue look appropriate)
<img width="670" alt="kitty" src="https://user-images.githubusercontent.com/1323414/198923838-32573060-96ff-4d2c-a0a1-d844a3c06542.png">

Here is what they look like in Alacritty: (Which are too thin in my opinion)
<img width="671" alt="alacritty" src="https://user-images.githubusercontent.com/1323414/198923934-8d4bee54-3f09-44ec-84cb-e3d0aae63f39.png">

### System

OS: MacOS
Version: `alacritty 0.11.0 (8dbaa0b)`

Here are my configs, but I don't think they're relevant:

```
env:
  TERM: alacritty

window:
  startup_mode: SimpleFullscreen
  decorations: none

font:
  size: 14
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  offset:
    x: 0
    y: 3

colors:
 # Default Colors
 primary:
   background: '#212121'
   foreground: '#f1f1f1'
 # Normal colors
 normal:
   black:   '#212121'
   red:     '#c30771'
   green:   '#10a778'
   yellow:  '#a89c14'
   blue:    '#008ec4'
   magenta: '#523c79'
   cyan:    '#20a5ba'
   white:   '#f1f1f1'
 # Bright colors
 bright:
   black:   '#424242'
   red:     '#e32791'
   green:   '#5fd7a7'
   yellow:  '#f3e430'
   blue:    '#b6d6fd'
   magenta: '#6855de'
   cyan:    '#4fb8cc'
   white:   '#ffffff'

 cursor:
   cursor: '#1ac7fc'

# background_opacity: 0.99

bell:
  duration: 10
  color: '#626262'

# Use `xxd -psd` to discover other chars hex values
key_bindings:
  - { key: H,         mods: Alt,        chars: "\x1b\x68" }
  - { key: J,         mods: Alt,        chars: "\x1b\x6a" }
  - { key: K,         mods: Alt,        chars: "\x1b\x6b" }
  - { key: K,         mods: Command,    chars: "\x1C"     } # See .tmux.conf
  - { key: L,         mods: Alt,        chars: "\x1b\x6c" }
  - { key: O,         mods: Alt,        chars: "\x1b\x6f" }
  - { key: R,         mods: Shift|Alt,  chars: "\x1b\x52" }
  - { key: R,         mods: Alt,        chars: "\x1b\x72" }
  - { key: S,         mods: Alt,        chars: "\x1b\x73" }
  - { key: T,         mods: Alt,        chars: "\x1b\x74" }
  - { key: W,         mods: Alt,        chars: "\x1b\x77" }
  - { key: Backslash, mods: Shift|Alt,  chars: "\x1b\x7c" }
  - { key: Minus,     mods: Shift|Alt,  chars: "\x1b\x5f" }
  - { key: LBracket,  mods: Alt,        chars: "\x1b\x5b" }
  - { key: RBracket,  mods: Alt,        chars: "\x1b\x5d" }
  - { key: Semicolon, mods: Shift|Alt,  chars: "\x1b\x3a" }
  - { key: Slash,     mods: Alt,        chars: "\x1b\x2f" }

  - {
      key: N,
      mods: Command,
      command: {
        program: "open",
        args: ["-n", "/Applications/Alacritty.app"]
      }
    }

  - {
      key: Return,
      mods: Command,
      action: ToggleSimpleFullscreen
    }
```
