### ISSUE TITLE
macOS: can not autostart tmux on M1 Mac

### ISSUE THREAD

**Issue by MunifTanjim** [alacritty/alacritty#6463]
### System

OS: macOS (Monterey, 12.3)
Version: `alacritty 0.11.0 (8dbaa0b)`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

---

With the following config:

```yaml
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - 'tmux attach || tmux'
```

- ❌ Opening Alacritty from Launchpad/Spotlight does not work
- ☑️ Opening Alacritty from default macos terminal using `alacritty` or `open /Applications/Alacritty.app` works

I've been using this config with Linux/Intel-Mac for years. But I tried on M1 mac today and got this confusing bug... I'm not sure how to debug further or what more information I need to gather.
