### ISSUE TITLE
Cursor not switching shape according to config?

### ISSUE THREAD

**Issue by GRR3ED** [alacritty/alacritty#6466]
This is my alacritty config and i'd like to use underline cursor in normal mode but it always shows the block!
```yml
import:
  # uncomment the flavour you want below:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
  # - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
   # - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
   # - ~/.config/alacritty/catppuccin/catppuccin-latte.yml
font:
  normal:
    family: CaskaydiaCove 
    style: Regular

  bold:
    family: CaskaydiaCove 
    style: Bold

  italic:
    family: CaskaydiaCove Nerd Font Mono
    style: Regular Italic

  bold_italic:
    family: CaskaydiaCove Nerd Font Mono
    style: SemiBold Italic

  size: 8

window:
  padding:
    x: 4
    y: 3

cursor:
  style:
    shape: Underline
  vi_mode_style:
    shape: Block
```

### System

OS: Arch Linux
Version: `0.11.0`
Linux: X11 [Qtile]

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: https://pastebin.com/7q1NtLR6
Keyboard and bindings: https://pastebin.com/2mr77gAj
