### ISSUE TITLE
Error about the hint command on Windows

### ISSUE THREAD

**Issue by rust-kotlin** [alacritty/alacritty#6490]
This command `start "https://doc.rust-lang.org/nightly/rustc/platform-support.html"` works perfectly on Windows. Then I tried to use it to replace the xdg-open as the command of the hint. Then it errors. 

### System

OS:  Windows11 22h2
Version: alacritty 0.10.1 (2844606)

### Logs

[13.607786900s] [WARN ] [alacritty] Unable to launch start with args ["https://doc.rust-lang.org/nightly/rustc/platform-support.html"]

## Config
```
hints:
    enabled:
      - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
        # hyperlink: true
        command: start
        # command: xdg-open
        post_processing: true
        mouse:
            enabled: true
            mods: Control
```

**Comment by kchibisov** [comment]
It couldn't find the program start. In general you don't need to touch it, since it'll use the right command on windows automatically.

**Comment by rust-kotlin** [comment]
> In general you don't need to touch it, since it'll use the right command on windows automatically.

It's true, when I delete the key of `command`, it will open the right web page with the default browser.

But everytime I open alacritty, it will give an error at the bottom of the window.

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/105690584/201508321-75bd7d1d-1ca4-4ae7-bcdd-4e48580922cb.png">

**Comment by rust-kotlin** [comment]
> Otherwise provide a real command.
Why `start` is not a real command?

**Comment by kchibisov** [comment]
Do you have a command named `start` on windows? The default is usually `explorer.exe` or something like that.

`start` is a valid name for a command, it's just not present on your system which is what alacritty tells you.

**Comment by kchibisov** [comment]
The error you're seeing is because your configuration is malformed. I'd suggest to comment out the entire section if you don't want to change the default, otherwise you'd need every field present for it to work.

Such could look like:

```yml
hints:
    enabled:
      - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
        # hyperlink: true
        command:
          program: "cmd"
          args: [ "/c", "start", ""]
        # command: xdg-open
        post_processing: true
        mouse:
            enabled: true
            mods: Control
```
