### ISSUE TITLE
Hyperlink escape sequence are opened with hints.enabled[0].command

### ISSUE THREAD

**Issue by ppwwyyxx** [alacritty/alacritty#6493]
## Problem

Thanks for adding support for hyperlink escape sequence (https://github.com/alacritty/alacritty/pull/6139)! I found that the command that's used to open the hyperlink cannot be configured intuitively. Right now, it is using `hints.enabled[0].command`.

To show what this means, I have the following 4 links on screen:
```
$printf '\e]8;;%s\e\%s\e]8;;\e\n' file://abc abc
abc
$printf '\e]8;;%s\e\%s\e]8;;\e\n' http://abc abc
abc
$echo file://abc
file://abc
$echo http://abc
http://abc
```
And the following in alacritty.yml:
```yaml
  enabled:
   - regex: "file:/[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     command: notify-send
     hyperlinks: true
     post_processing: true
     mouse:
       enabled: true
       # but Shift might be needed anyway to disable mouse in vim
       mods: None
   - regex: "(https:|http:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     command: xdg-open
     hyperlinks: true
     post_processing: true
     mouse:
       enabled: true
       # but Shift might be needed anyway to disable mouse in vim
       mods: None
```
When I clicked the links, what I observed is that, link 1, 2, 3 are opened with `notify-send`, and link 4 is opened with `xdg-open`.

I tried reordering the config in `hints.enabled`, and found the current behavior seems to be:
* For plain-text urls that match regex, use the corresponding command
* For URLs in escape sequences, use the first command in `hints.enabled`   - I think this behavior is unclear and confusing.

## Expected behavior:

There are many potential ways to make it less confusing. 
* An easiest way is probably to introduce a single new config that defines the command to be used for ALL OSC8 hyperlinks.
* A more complex approach could match the OSC8 hyperlink with the existing list of regex, and use the corresponding command.

### System

OS: Linux
Version: 0.11.0
Linux/BSD: X11 KDE
