### ISSUE TITLE
Issue with init shell command

### ISSUE THREAD

**Issue by ansidev** [alacritty/alacritty#6537]
### System

OS: macOS
Version: alacritty 0.11.0 (8dbaa0b)
tmux version: 3.3a

### Issue

I want to start tmux automatically on starting Alacritty. I added this configuration to `alacritty.yml`:

```yaml
shell:
  program: /usr/local/bin/zsh
  args:
    - -c
    - /usr/local/bin/tmux
```

It works partially.

The problem is I am using `tmux` with the `tmux plugin` [tmux-continuum](https://github.com/tmux-plugins/tmux-continuum) to automatically restore the `tmux` session on starting tmux. And the saved `tmux` session is not restored when running tmux with the above configuration.

If I disable the above configuration, start Alacritty, and run `zsh -c /usr/local/bin/tmux` manually, the saved session will be restored. So what is the difference between the two methods?
