### ISSUE TITLE
Extending alacritty terminal over two monitors

### ISSUE THREAD

**Issue by kaatish** [alacritty/alacritty#6600]
### System

OS: Ubuntu 20.04
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: gnome shell

I have been able to span alacritty terminal (v 0.10.1) over two monitors using the config file :
window:
```
  # Window dimensions (changes require restart)
  dimensions:
    columns: 274
    lines: 126
                                                                                                                                                                                                                                                                              
  # Window position (changes require restart)
  position:
    x: 0
    y: 0

  # Window decorations
  decorations: none
```
This is not possible anymore with the newest release. Can this be fixed?

### Logs

<details>
<summary>alacritty -vv</summary>

Created log file at "/tmp/Alacritty-71569.log"
[0.000001697s] [INFO ] [alacritty] Welcome to Alacritty
[0.000104586s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0bb)
[0.000132015s] [INFO ] [alacritty] Running on X11
[0.001332102s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/aatish/.config/alacritty/alacritty.yml"
[0.003945800s] [DEBUG] [alacritty] Loading "Source Code Pro" font
[0.022063609s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.026005632s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.029302422s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.032308939s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.033544357s] [DEBUG] [alacritty] Estimated scaling factor: 2
[0.033565283s] [DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 3836, height: 3906 })
[0.033581164s] [DEBUG] [alacritty] Estimated cell size: 14 x 31
[0.118235157s] [INFO ] [alacritty] Running on Quadro GV100/PCIe/SSE2
[0.118286810s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.120133658s] [INFO ] [alacritty] Display scale factor: 2
[0.120159579s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.124427152s] [INFO ] [alacritty] Cell size: 14 x 31
[0.124452307s] [INFO ] [alacritty] Padding: 0 x 0
[0.124461538s] [INFO ] [alacritty] Width: 3836, Height: 3906
[0.142254784s] [INFO ] [alacritty] PTY dimensions: 126 x 274
[0.146125841s] [INFO ] [alacritty] Initialisation complete
[0.225511510s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.225558148s] [INFO ] [alacritty] Padding: 0 x 0
[0.225573511s] [INFO ] [alacritty] Width: 3836, Height: 3906
[0.293181580s] [DEBUG] [alacritty_terminal] New num_cols is 274 and num_lines is 67
[0.300103594s] [INFO ] [alacritty] Padding: 0 x 0
[0.300133413s] [INFO ] [alacritty] Width: 3840, Height: 2106
[2.984823147s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-71569.log"

</details>
