### ISSUE TITLE
Toggling SimpleFullscreen on mac overrides decorations: buttonless

### ISSUE THREAD

**Issue by zschaffer** [alacritty/alacritty#6630]
When decorations is set to `buttonless` and startupmode is `SimpleFullscreen`, when a user triggers the `ToggleSimpleFullscreen` action the buttons reappear, covering the top line of the terminal.

SimpleFullscreen:
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/101823296/213024953-ef08ef62-fef0-4172-9f6f-eed5e3b94edf.png">

After toggling:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/101823296/213025017-15167e7e-096f-40b0-9d85-5d632b0dcce6.png">

My configuration file is pretty bare:
```yaml
font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    style: SemiBold
  italic:
    style: Italic
  bold_italic:
    style: SemiBold Italic
  size: 14.0
window:
  padding:
    x: 10
    y: 10
  decorations: buttonless
  startup_mode: SimpleFullscreen
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true
alt_send_esc: true
live_config_reload: true
key_bindings:
  - { key: N, mods: Command, action: CreateNewWindow }
  - { key: F, mods: Command|Control, action: ToggleSimpleFullscreen }
import:
  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml

```
### System

OS: macOS
Version: 0.11.0 (8dbaa0b)

### Logs
```
[0.001988333s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[0.026471416s] [DEBUG] [alacritty] Loading "JetBrainsMono Nerd Font Mono" font
[0.057870250s] [DEBUG] [alacritty] Estimated scaling factor: 2
[0.057909125s] [DEBUG] [alacritty] Estimated window size: None
[0.057924791s] [DEBUG] [alacritty] Estimated cell size: 16 x 37
[0.086921291s] [INFO ] [alacritty] Running on Apple M1
[0.086956375s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.089447875s] [INFO ] [alacritty] Display scale factor: 2
[0.089481250s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.097070458s] [INFO ] [alacritty] Cell size: 16 x 37
[0.097101583s] [INFO ] [alacritty] Padding: 20 x 20
[0.097114916s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.115980750s] [INFO ] [alacritty] PTY dimensions: 31 x 97
[0.118161291s] [INFO ] [alacritty] Initialisation complete
[0.123809625s] [DEBUG] [alacritty_terminal] New num_cols is 317 and num_lines is 76
[0.126740208s] [INFO ] [alacritty] Padding: 20 x 20
[0.126775250s] [INFO ] [alacritty] Width: 5120, Height: 2880
/// TOGGLED HERE /// 
[66.931022833s] [DEBUG] [alacritty_terminal] New num_cols is 97 and num_lines is 31
[66.932485166s] [INFO ] [alacritty] Padding: 20 x 20
[66.932556083s] [INFO ] [alacritty] Width: 1600, Height: 1200
```
