### ISSUE TITLE
Feature request - possible to highlight a JIRA ticket number using regexp?

### ISSUE THREAD

**Issue by smangels** [alacritty/alacritty#6683]
I wonder whether it is possible to configure a feature like iTerm2 "trigger" where I could write a regular expression that matches a standard ticker number like `[(A-Z]{3,}-[0-9]{3,})` and create a hyperlink like https://mypage/ticket/\1 using the match group?

### System

OS: macOS
Version: 0.1.0
Linux/BSD: X11/Wayland, DE or Compositor and WM

**Comment by chrisduerr** [comment]
See hints in the config.

**Comment by smangels** [comment]
I'm very sorry, but I could not find any example where it is shown how the argument (that matched the regexp can be used as arguments when calling "open" in MacOS. I've tried different versions but none of them worked.

My current configuration:
```
    - regex: "([A-Z]{3,}-[0-9]{3,})"
         hyperlinks: true
         command: open https://mypage.com/\$1
         post_processing: true
         mouse:
           enabled: true
           mods: None
        binding:
          key: F
          mods: Control|Shift
```
