### ISSUE TITLE
Alacritty starts with the wrong shell on 1 of 3 Macs...

### ISSUE THREAD

**Issue by jby** [alacritty/alacritty#6766]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS:macOS 13.2.1
Version: alacritty 0.12.0-rc2 (e1bc53a)

I've now installed Alacritty 0.12.0-rc2 on 3 different Macs, one 2017 intel iMac, one 13" M2 MBP and my main laptop - a 14" M1 Pro MBP.
For some reason, on the 14", Alacritty starts up with `fish` instead of my default `zsh` that it correctly starts on both of the other Macs.
I can't for the life of me understand why.

This is my complete ~/.config/alacritty/alacritty.yml:
```yaml
---
  import:
    - ~/.config/alacritty/dracula.yml
  window:
    option_as_alt: OnlyLeft
  font:
   normal:
    family: NotoSansMono Nerd Font
    style: Regular
    size: 14
```
My login shell is set to `/opt/homebrew/bin/zsh`, I **do** have `/opt/homebrew/bin/fish` installed as well, but it's not set as my default login shell.
