### ISSUE TITLE
How to conveniently select hyperlinked text?

### ISSUE THREAD

**Issue by dandavison** [alacritty/alacritty#6782]
### Problem
I often need to copy hyperlinked text to the clipboard: mainly file paths and git commits, which have hyperlinks to open them in text editors and web browsers respectively. 

I would normally do that with double-click. However, click on hyperlinked text in alacritty triggers the link behavior.

### Possible solution
Make it (configurable) so that I have to hold down command + click to trigger the hyperlink behavior, otherwise click on hyperlinked text behaves same as click on normal text.

### System

OS: macOS
Version: `alacritty --version` output: `alacritty 0.11.0-rc1 (7cd180da)`

**Comment by chrisduerr** [comment]
You can use hints to automatically copy URLs to the clipboard using keyboard bindings.

**Comment by dandavison** [comment]
Thanks @chrisduerr that is fantastic and better than double click. It almost does what I want, but I don't want to paste the raw hyperlink, I just want to paste the displayed text. Is that currently possible? The config I'm using is

```yaml
hints:
  enabled:
    - hyperlinks: true
      action: Paste
      binding:
        mods: Command
        key: Semicolon
```

If it's not possible might one idea be to use regex capture groups to define such transformations?

Of course, native hyperlink support would be more convenient for my use case, e.g.
```yaml
hints:
  enabled:
    - hyperlinks: true
    - action: PasteHyperlinkText
```
