### ISSUE TITLE
No under curl in tmux session

### ISSUE THREAD

**Issue by michaelvanstraten** [alacritty/alacritty#6802]
I can't seam to get untercurls to work using tmux on my alacritty terminal.

When I am not attached to a tmux session, everything work as expected: 

<img width="652" alt="Screenshot 2023-03-18 at 16 44 06" src="https://user-images.githubusercontent.com/50352631/226300164-033b2790-3e32-4f86-903a-ba1f83dd2e49.png">

but in a tmux session, the under curl gets converted to an underline

<img width="657" alt="Screenshot 2023-03-18 at 16 45 11" src="https://user-images.githubusercontent.com/50352631/226300475-8ec37cf0-7a7d-47a9-a580-822e82ccd865.png">

I don't know if I am doing something wrong or if this is a problem with ether `alacritty` or `tmux`.

## Alacritty config
```yaml
window:
  # opacity: 0.85
  dimensions:
    columns: 128
    lines: 38
  padding:
    x: 5
    y: 3
# Colors (Ayu Dark)
colors:
  # Default colors
  primary:
    background: "#0a0e14"
    foreground: "#b3b1ad"

  # Normal colors
  normal:
    black: "#02060d"
    red: "#EA6C73"
    green: "#91B362"
    yellow: "#ffb454"
    blue: "#59c2ff"
    magenta: "#FAE994"
    cyan: "#95e6cb"
    white: "#C7C7C7"

  # Bright colors
  bright:
    black: "#02060d"
    red: "#EA6C73"
    green: "#91B362"
    yellow: "#ffb454"
    blue: "#59c2ff"
    magenta: "#FAE994"
    cyan: "#95e6cb"
    white: "#C7C7C7"
font:
  size: 16
  normal:
    family: "Hack Nerd Font Mono"
selection:
  save_to_clipboard: true
cursor:
  style:
    shape: Beam

alt_send_esc: false
```
## Tmux Config
```sh
# Rebind Crtl-B to Crtl-A
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Non repeating panel selection
bind-key    k select-pane -U
bind-key    j select-pane -D
bind-key    h select-pane -L
bind-key    l select-pane -R

# Rebind splitting of windows
bind-key h split-window -h -c "#{pane_current_path}"
bind-key v split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Bind r to reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Statusbar style
set -g status-style 'bg=black'

# Hide date/time in status-bar 
set -g status-right ''
set -g status-right-length 0

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Fix colors in tmux 
set -sg terminal-overrides ",*:RGB"
```
### System

OS: macOS on aarch64-apple-darwin
Version: `alacritty 0.11.0 (8dbaa0b)`

Thank you a lot in advance, it would be great if someone could help me with this.

**Comment by kchibisov** [comment]
You should add it into `tmux` config(you need like recent enough tmux for that). `alacritty` is a term value, you could want to use `*` instead.

`set-option -ga terminal-features ",alacritty:usstyle"`

**Comment by michaelvanstraten** [comment]
Thank you for the help, but I'm still not getting any under curl.

**Comment by joshuachp** [comment]
> You should add it into `tmux` config(you need like recent enough tmux for that). `alacritty` is a term value, you could want to use `*` instead.
> 
> `set-option -ga terminal-features ",alacritty:usstyle"`

Can confirm for me it solves the issue

**Comment by michaelvanstraten** [comment]
> Can confirm for me it solves the issue

# Details
- neovim: 0.9.0
- tmux: 3.3a
- alecritty: 0.12.0

The under curl seam to work in a regular tmux session, but not with neovim.

**Comment by kchibisov** [comment]
you should convince neovim to use curled underlines. For that you'd need `tmux-256color` terminfo.

**Comment by michaelvanstraten** [comment]
> tmux-256color

Same result as when setting `TERM` to `alacritty`

**Comment by michaelvanstraten** [comment]
> Have you tried running neovim `:checkhealth` in tmux?

Okay, thanks got something about `TERM` and `default-terminal` not matching.

After overriding the `default-terminal`:
```bash
# Setting default-terminal to not use screen
set-option -g default-terminal "tmux-256color"
```

Undercurl as well as coloring work flawlessly, the only problem is that i cant clear the screen.
```sh
terminals database is inaccessible
```

**Comment by kchibisov** [comment]
That's because `tmux-256color` terminfo is not provided for macOS, you should likely install custom ncurses.

**Comment by michaelvanstraten** [comment]
> That's because `tmux-256color` terminfo is not provided for macOS, you should likely install custom ncurses.

Thank you for the tip.

I followed this [`gist`](https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95) and now everything works as expected, for anyone who has the same problem.

I have to state that alacritty, is by far the best terminal emulator I have used, even thought it has some specialties sometimes.

**Comment by pprotas** [comment]
I've been struggling with this a bit, but I think that I found the permutation of settings that fully allows me to have undercurls, correct colors, italics and bold text on macOS + Alacritty + Tmux + Neovim. What a ride!

So for macOS specific stuff, I followed "The Right Way" in the linked [gist](https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95#the-right-way), but I'm not sure if it was necessary.

For Alacritty, I have **no `env.TERM` in my `~/.config/alacritty/alacritty.toml`**! So do *not* add anything like this:
```toml
[env]
TERM="alacritty/tmux-256color/whatever" # Don't add anything like this!
```

In Tmux (make sure you update it to the newest version), this is the settings you need in `~/.config/tmux/tmux.conf`:
```bash
# Proper colors
set-option -sa terminal-features ',alacritty:RGB' # Makes sure that colors in tmux are the same as without tmux

# Undercurl
set -g default-terminal "tmux-256color" # If you don't add this, then neovim :checkhealth will complain. But "alacritty" also works
set-option -ga terminal-features ",alacritty:usstyle"
```

In Neovim, it should work out of the box, so you shouldn't have any undercurl-specific configs. If it doesn't work, try updating neovim and try out different color schemes as well. I'm on version 0.9.5.
