### ISSUE TITLE
Since 0.12.0 keyboard input does not work (macOS)

### ISSUE THREAD

**Issue by daletman** [alacritty/alacritty#6817]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS 12.6.3 (21G419)
Version: alacritty 0.12.0 (5a72819)

### Logs

Font/Terminal size: [Alacritty-75137.log](https://github.com/alacritty/alacritty/files/11068753/Alacritty-75137.log)

When I start Alacritty using the App Icon or Spotlight, the keyboard input (except Enter, Escape, Backspace and maybe some more) does not work. When I start Alacritty from Terminal it works just fine. Also tested using the default config.

**Comment by chrisduerr** [comment]
Is there a difference to `env` with and without starting it from a terminal?

**Comment by daletman** [comment]
I don't think so. Here is my output of `env` when startet from terminal. I can't give you the output when not startet from termninal since I can't type.

```
ALACRITTY_LOG=/var/folders/my/gzz9nv7x0wq45khvl83pv4br0000gn/T/Alacritty-87920.log
ALACRITTY_SOCKET=/var/folders/my/gzz9nv7x0wq45khvl83pv4br0000gn/T/Alacritty-87920.sock
ALACRITTY_WINDOW_ID=140599583879712
AUTOJUMP_ERROR_PATH=/Users/home/Library/autojump/errors.log
AUTOJUMP_SOURCED=1
COLORTERM=truecolor
FIGTERM_SESSION_ID=10a28307-c551-44c9-b946-d8978bca5f03
FIG_PID=87922
FIG_SET_PARENT=10a28307-c551-44c9-b946-d8978bca5f03
FIG_SET_PARENT_CHECK=1
FIG_TERM=2.14.2
HOME=/Users/home
LC_FIG_SET_PARENT=10a28307-c551-44c9-b946-d8978bca5f03
LOGNAME=home
LaunchInstanceID=B5A35957-A8FE-47C0-8E8E-E55675477347
NNN_PLUG=f:finder;o:fzopen;p:preview-tui;d:diffs;v:imgview;m:mimelist
OLDPWD=/Users/home
P9K_TTY=old
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/home/.cargo/bin:/Users/home/.fig/bin:/Users/home/.local/bin
PWD=/Users/home
SECURITYSESSIONID=186e2
SHELL=/bin/zsh
SHLVL=2
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.uqAP0HBpvq/Listeners
TERM=alacritty
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=445
TERM_SESSION_ID=4012853C-FD39-49BF-A0B0-8A0B1C6D667D
TMPDIR=/var/folders/my/gzz9nv7x0wq45khvl83pv4br0000gn/T/
TTY=/dev/ttys009
USER=home
WINDOWID=140599583879712
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_P9K_SSH_TTY=/dev/ttys009
_P9K_TTY=/dev/ttys009
__CFBundleIdentifier=com.apple.Terminal
__CF_USER_TEXT_ENCODING=0x0:0:2
P9K_SSH=0
LC_CTYPE=UTF-8
_=/usr/bin/env
```

**Comment by daletman** [comment]
I could run `env` through history because arrow up does work. There is no difference.

**Comment by kchibisov** [comment]
Could you try do get a log from the `app` with `persistent_logging` and `print_events` from the `debug` section, using the default config https://github.com/alacritty/alacritty/blob/2df8f860b960d7c96efaf4f059fe2fbbdce82bcc/alacritty.yml#L883 

The place where log file will be saved could be obtained by running with this config from the terminal.

**Comment by daletman** [comment]
Here is the log file when **not** starting from terminal: 
[Alacritty-90697.log](https://github.com/alacritty/alacritty/files/11070159/Alacritty-90697.log)

**Comment by monsterhxw** [comment]
same issue.

**Comment by chrisduerr** [comment]
@daletman Did you perform any keyboard input during this log?

**Comment by kchibisov** [comment]
This is sort of suspicious.

>Using fallback locale: UTF-8

@daletman also, it seems like you haven't enabled the `print_events` log?

**Comment by tetzng** [comment]
Same issue.

I typically alternate between alphanumeric and Japanese input, with the default set to alphanumeric. In my case, when I switch to Japanese input and type any text, then switch back to alphanumeric, I am able to input alphanumeric characters.

**Comment by tetzng** [comment]
> I typically alternate between alphanumeric and Japanese input, with the default set to alphanumeric. In my case, when I switch to Japanese input and type any text, then switch back to alphanumeric, I am able to input alphanumeric characters.

Oh, but if the window loses focus, I can't input alphanumeric characters again.
Similarly, I can't input alphanumeric characters unless I have first entered any text using Japanese input.

**Comment by kchibisov** [comment]
There's not a single log that could help unfortunately, as in the one with `--print-events` output, which has keyboard input captured.

**Comment by tetzng** [comment]
This is the log with only `print-events` changed to `true` in the Default config
[Alacritty-64626.log](https://github.com/alacritty/alacritty/files/11076425/Alacritty-64626.log)

macOS: 13.2.1(22D68)
version: 0.12.0(5a72819)

**Comment by kchibisov** [comment]
I'd assume that you've tried to type something? Because it shows that you've pressed spacebar once and that was about it?

**Comment by daletman** [comment]
@chrisduerr @kchibisov 

Here is a new log file with `print-events` set to `true`. Alacritty **not** started from terminal, after Alacritty started I type the letters `asdf` on german keyboard layout:

[Alacritty-99660.log](https://github.com/alacritty/alacritty/files/11077787/Alacritty-99660.log)

**Comment by Prenoult** [comment]
I got the same issue, except when I launch alacritty with the `alacritty` command in another console everything works well.

**Comment by pbgc** [comment]
@kchibisov This is very strange because I have the same exact system:

OS: macOS 12.6.3
Version: alacritty 0.12.0

And **don't have this problem** ! (I have used all the RC without this problem). If I can help in comparing something etc ... just ask!

**Comment by sly01** [comment]
Same issue here.

**Comment by gzm55** [comment]
> 

maybe this bug only affects some IME. I've two non-ABC IME, one has same issue, another is fine.

**Comment by jansol** [comment]
Potentially related: `window.option_as_alt` seems to completely break input if I set it to something other than None and attempt to type something that requires pressing option to type. (e.g. @ on apple's nordic layout).

If I hit ctrl+c or enter it starts working again.

**Comment by pbgc** [comment]
@jansol 
> Potentially related: `window.option_as_alt` seems to completely break input if I set it to something other than None and attempt to type something that requires pressing option to type. (e.g. @ on apple's nordic layout).

check https://github.com/alacritty/alacritty/issues/6720 and "macOS Alt/Option situation" entry in https://github.com/alacritty/alacritty/releases/tag/v0.12.0-rc1

**Comment by jansol** [comment]
I saw that, but is it really intended that it also eats at least one unrelated key *after* I let go of the key combo? (I think I got it to eat multiple too, but couldn't reproduce that reliably yet)

**Comment by pbgc** [comment]
@kchibisov ok. If you need help testing/compare something just say.
(I have a MBP 16inch 2021 (M1 Pro) with Portuguese layout and have 0 problems)

**Comment by kchibisov** [comment]
I also have macbook and I've tested with japanese IME, chinese IME, korean IME, some other layots, ABC layout, dvorak layout, and I don't have any of the mentioned issues here.

The logs here confirmed that we don't get any keyboard input at all from our windowing library, so it's lost somewhere...

I know that the issue might go away entirely with 0.13.0 version, because upstream library will change the entire keyboard input, but there's no ETA.

**Comment by pbgc** [comment]
@kchibisov what really puzzles me is, for the persons having the prob, that if alacritty is launched from terminal it works! It's doesn't work when launched from the Dock or Spotlight ..

**Comment by gzm55** [comment]
> I also have macbook and I've tested with japanese IME, chinese IME, korean IME, some other layots, ABC layout, dvorak layout, and I don't have any of the mentioned issues here.

could you plz test these two IME?
- has problem: https://im.logcg.com/loginputmac3
- no problem: https://pinyin.sogou.com/mac/

**Comment by kchibisov** [comment]
>has problem: https://im.logcg.com/loginputmac3

I won't install software I have no way of understanding, sorry. It must be something open source or builtin apple solution.

**Comment by ryosoul** [comment]
Hello guys,

I have found to have the same issue here, but not all the time, only when changing from romaji and japanese（For those don't know there's a special key for that). And I my settings are following the guide on the changelog. Found though that
changing the keyboard layout to let's say "us layout" and put back restores the input.

Can some one guide me how to find the alacritty log file? So I put in here too.

macOS: Monterey 12.6.4

My settings:

```
font:
  normal:
    family: Iosevka Nerd Font Mono
    style: Regular
  bold:
    family: Iosevka Nerd Font Mono
    style: bold
  italic:
    family: Iosevka Nerd Font Mono
    style: Italic
  size: 14
window:
  option_as_alt: OnlyLeft
key_bindings:
    # - { key: Paste,                                       action: Paste          }
    # - { key: Copy,                                        action: Copy           }
    # - { key: L,         mods: Control,                    action: ClearLogNotice }
    # - { key: L,         mods: Control, mode: ~Vi|~Search, chars: "\x0c"          }
    # - { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp   }
    # - { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }
    # - { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop    }
    # - { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }

    # Vi Mode
    - { key: Space,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode            }
    - { key: Space,  mods: Shift|Control, mode: Vi|~Search, action: ScrollToBottom          }
    - { key: Escape,                      mode: Vi|~Search, action: ClearSelection          }
    - { key: I,                           mode: Vi|~Search, action: ToggleViMode            }
    - { key: I,                           mode: Vi|~Search, action: ScrollToBottom          }
    - { key: C,      mods: Control,       mode: Vi|~Search, action: ToggleViMode            }
    - { key: Y,      mods: Control,       mode: Vi|~Search, action: ScrollLineUp            }
    - { key: E,      mods: Control,       mode: Vi|~Search, action: ScrollLineDown          }
    - { key: G,                           mode: Vi|~Search, action: ScrollToTop             }
    - { key: G,      mods: Shift,         mode: Vi|~Search, action: ScrollToBottom          }
    - { key: B,      mods: Control,       mode: Vi|~Search, action: ScrollPageUp            }
    - { key: F,      mods: Control,       mode: Vi|~Search, action: ScrollPageDown          }
    - { key: U,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageUp        }
    - { key: D,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageDown      }
    - { key: Y,                           mode: Vi|~Search, action: Copy                    }
    - { key: Y,                           mode: Vi|~Search, action: ClearSelection          }
    - { key: Copy,                        mode: Vi|~Search, action: ClearSelection          }
    - { key: V,                           mode: Vi|~Search, action: ToggleNormalSelection   }
    - { key: V,      mods: Shift,         mode: Vi|~Search, action: ToggleLineSelection     }
    - { key: V,      mods: Control,       mode: Vi|~Search, action: ToggleBlockSelection    }
    - { key: V,      mods: Alt,           mode: Vi|~Search, action: ToggleSemanticSelection }
    - { key: Return,                      mode: Vi|~Search, action: Open                    }
    - { key: Z,                           mode: Vi|~Search, action: CenterAroundViCursor    }
    - { key: K,                           mode: Vi|~Search, action: Up                      }
    - { key: J,                           mode: Vi|~Search, action: Down                    }
    - { key: H,                           mode: Vi|~Search, action: Left                    }
    - { key: L,                           mode: Vi|~Search, action: Right                   }
    - { key: Up,                          mode: Vi|~Search, action: Up                      }
    - { key: Down,                        mode: Vi|~Search, action: Down                    }
    - { key: Left,                        mode: Vi|~Search, action: Left                    }
    - { key: Right,                       mode: Vi|~Search, action: Right                   }
    - { key: Key0,                        mode: Vi|~Search, action: First                   }
    - { key: Key4,   mods: Shift,         mode: Vi|~Search, action: Last                    }
    - { key: Key6,   mods: Shift,         mode: Vi|~Search, action: FirstOccupied           }
    - { key: H,      mods: Shift,         mode: Vi|~Search, action: High                    }
    - { key: M,      mods: Shift,         mode: Vi|~Search, action: Middle                  }
    - { key: L,      mods: Shift,         mode: Vi|~Search, action: Low                     }
    - { key: B,                           mode: Vi|~Search, action: SemanticLeft            }
    - { key: W,                           mode: Vi|~Search, action: SemanticRight           }
    - { key: E,                           mode: Vi|~Search, action: SemanticRightEnd        }
    - { key: B,      mods: Shift,         mode: Vi|~Search, action: WordLeft                }
    - { key: W,      mods: Shift,         mode: Vi|~Search, action: WordRight               }
    - { key: E,      mods: Shift,         mode: Vi|~Search, action: WordRightEnd            }
    - { key: Key5,   mods: Shift,         mode: Vi|~Search, action: Bracket                 }
    - { key: Slash,                       mode: Vi|~Search, action: SearchForward           }
    - { key: Slash,  mods: Shift,         mode: Vi|~Search, action: SearchBackward          }
    - { key: N,                           mode: Vi|~Search, action: SearchNext              }
    - { key: N,      mods: Shift,         mode: Vi|~Search, action: SearchPrevious          }

    # Search Mode
    - { key: Return,                mode: Search|Vi,  action: SearchConfirm         }
    - { key: Escape,                mode: Search,     action: SearchCancel          }
    - { key: C,      mods: Control, mode: Search,     action: SearchCancel          }
    - { key: U,      mods: Control, mode: Search,     action: SearchClear           }
    - { key: W,      mods: Control, mode: Search,     action: SearchDeleteWord      }
    - { key: P,      mods: Control, mode: Search,     action: SearchHistoryPrevious }
    - { key: N,      mods: Control, mode: Search,     action: SearchHistoryNext     }
    - { key: Up,                    mode: Search,     action: SearchHistoryPrevious }
    - { key: Down,                  mode: Search,     action: SearchHistoryNext     }
    - { key: Return,                mode: Search|~Vi, action: SearchFocusNext       }
    - { key: Return, mods: Shift,   mode: Search|~Vi, action: SearchFocusPrevious   }

    # (Windows, Linux, and BSD only)
    #- { key: V,              mods: Control|Shift, mode: ~Vi,        action: Paste            }
    #- { key: C,              mods: Control|Shift,                   action: Copy             }
    #- { key: F,              mods: Control|Shift, mode: ~Search,    action: SearchForward    }
    #- { key: B,              mods: Control|Shift, mode: ~Search,    action: SearchBackward   }
    #- { key: C,              mods: Control|Shift, mode: Vi|~Search, action: ClearSelection   }
    #- { key: Insert,         mods: Shift,                           action: PasteSelection   }
    #- { key: Key0,           mods: Control,                         action: ResetFontSize    }
    #- { key: Equals,         mods: Control,                         action: IncreaseFontSize }
    #- { key: Plus,           mods: Control,                         action: IncreaseFontSize }
    #- { key: NumpadAdd,      mods: Control,                         action: IncreaseFontSize }
    #- { key: Minus,          mods: Control,                         action: DecreaseFontSize }
    #- { key: NumpadSubtract, mods: Control,                         action: DecreaseFontSize }

    # (Windows only)
    #- { key: Return,   mods: Alt,           action: ToggleFullscreen }

    # (macOS only)
    - { key: K,              mods: Command, mode: ~Vi|~Search, chars: "\x0c"                 }
    - { key: K,              mods: Command, mode: ~Vi|~Search, action: ClearHistory          }
    - { key: Key0,           mods: Command,                    action: ResetFontSize         }
    - { key: Minus,          mods: Command|Shift,              action: IncreaseFontSize      }
    - { key: Plus,           mods: Command,                    action: IncreaseFontSize      }
    - { key: NumpadAdd,      mods: Command,                    action: IncreaseFontSize      }
    - { key: Minus,          mods: Command,                    action: DecreaseFontSize      }
    - { key: NumpadSubtract, mods: Command,                    action: DecreaseFontSize      }
    - { key: V,              mods: Command,                    action: Paste                 }
    - { key: C,              mods: Command,                    action: Copy                  }
    - { key: C,              mods: Command, mode: Vi|~Search,  action: ClearSelection        }
    - { key: H,              mods: Command,                    action: Hide                  }
    - { key: H,              mods: Command|Alt,                action: HideOtherApplications }
    - { key: M,              mods: Command,                    action: Minimize              }
    - { key: Q,              mods: Command,                    action: Quit                  }
    - { key: W,              mods: Command,                    action: Quit                  }
    - { key: N,              mods: Command,                    action: SpawnNewInstance      }
    - { key: F,              mods: Command|Control,            action: ToggleFullscreen      }
    - { key: F,              mods: Command, mode: ~Search,     action: SearchForward         }
    - { key: B,              mods: Command, mode: ~Search,     action: SearchBackward        }

    # Option key remapping
    - { key: A,         mods: Alt,       chars: "\x1ba"                       }
    - { key: B,         mods: Alt,       chars: "\x1bb"                       }
    - { key: C,         mods: Alt,       chars: "\x1bc"                       }
    - { key: D,         mods: Alt,       chars: "\x1bd"                       }
    - { key: E,         mods: Alt,       chars: "\x1be"                       }
    - { key: F,         mods: Alt,       chars: "\x1bf"                       }
    - { key: G,         mods: Alt,       chars: "\x1bg"                       }
    - { key: H,         mods: Alt,       chars: "\x1bh"                       }
    - { key: I,         mods: Alt,       chars: "\x1bi"                       }
    - { key: J,         mods: Alt,       chars: "\x1bj"                       }
    - { key: K,         mods: Alt,       chars: "\x1bk"                       }
    - { key: L,         mods: Alt,       chars: "\x1bl"                       }
    - { key: M,         mods: Alt,       chars: "\x1bm"                       }
    - { key: N,         mods: Alt,       chars: "\x1bn"                       }
    - { key: O,         mods: Alt,       chars: "\x1bo"                       }
    - { key: P,         mods: Alt,       chars: "\x1bp"                       }
    - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
    - { key: R,         mods: Alt,       chars: "\x1br"                       }
    - { key: S,         mods: Alt,       chars: "\x1bs"                       }
    - { key: T,         mods: Alt,       chars: "\x1bt"                       }
    - { key: U,         mods: Alt,       chars: "\x1bu"                       }
    - { key: V,         mods: Alt,       chars: "\x1bv"                       }
    - { key: W,         mods: Alt,       chars: "\x1bw"                       }
    - { key: X,         mods: Alt,       chars: "\x1bx"                       }
    - { key: Y,         mods: Alt,       chars: "\x1by"                       }
    - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
    - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
    - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
    - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
    - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
    - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
    - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
    - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
    - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
    - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
    - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
    - { key: Backslash, mods: Alt,       chars: "\\"                          } # \
    - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
    - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
    - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
    - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
    - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
    - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
    - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
    - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
    - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
    - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
    - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |
    - { key: RBracket,  mods: Alt,       chars: "\x1b]"                       } # Alt + ]
    - { key: LBracket,  mods: Alt,       chars: "\x1b["                       } # Alt + [
    - { key: 41,        mods: Alt|Shift, chars: "\x1b+"                       } # Alt + +
    - { key: Minus,     mods: Alt,       chars: "\x1b-"                       } # Alt + -
    ```
