### ISSUE TITLE
Cannot remap Ctrl+backspace in vim but  ctrl+return work

### ISSUE THREAD

**Issue by sokinpui** [alacritty/alacritty#6837]
OS: macOS
Version: alacritty 0.11.0 (8dbaa0b)

I have try to remap `ctrl+backspace` and `alt+backspace` for vim using, while I find that it doesn't work in vim. I have similar key blindings defined in alacritty.ymal, while they are totally work, which is `return` key. `ctrl+return` work fine in vim.

Here is my alacritty.ymal:
```
#import:
#  - /Users/mac/git_repo/themes/alacritty/dracula.yml
## Colors (Doom One)
colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xbbc2cf'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xff6c6b'
    green:   '0x98be65'
    yellow:  '0xecbe7b'
    blue:    '0x51afef'
    magenta: '0xc678dd'
    cyan:    '0x46d9ff'
    white:   '0xbbc2cf'
env:
  TERM: xterm-256color

window:
  decorations: none

  title: Alacritty

scrolling:
  history: 10000

  multiplier: 3

font:
  normal:
    family: Menlo 

      #  bold:
      #    family: Menlo
      #    style: Bold
      #
      #  italic:
      #    family: Menlo
      #    style: Bold Italic
      #
      #  bold_italic:
      #    family: Menlo
      #    style: Bold Italic

  size: 14.0
  
cursor:
  style:
    shape: Block
    blinking: Off

  vi_mode_style: None

mouse:
  hide_when_typing: true

  
bell:
  duration: 0

key_bindings:
  - { key: Return,   mods: Shift,   chars: "\x1b[13;2u" }
  - { key: Return,   mods: Control, chars: "\x1b[13;5u" }
  - { key: Back,   mods: Shift,   chars: "\x1b[8;2u" }
  - { key: Back,   mods: Control, chars: "\x1b[8;5u" }
```

Here is the remap in vim:
```
nnoremap <Bs> :bn<cr> 
nnoremap <S-Bs> :bp<cr> 
nnoremap <C-Bs> :ls<cr> 

nnoremap <C-CR> ^
nnoremap <S-CR> $
onoremap <C-CR> ^
onoremap <S-CR> $
vnoremap <C-CR> ^
vnoremap <S-CR> $
```

**Comment by chrisduerr** [comment]
Working as intended.

**Comment by PotatoesFall** [comment]
I have a similar problem and I don't understand what "working as intended" means. Is it possible to get the desired behavior or is it not possible?

https://github.com/alacritty/alacritty/issues/7100

**Comment by PraxTube** [comment]
By default, alacritty will send a `^H` when you press `CTRL + Backspace`. You can change that in your `alacritty.yml` file with

```
  - { key: Back,     mods: Control,       chars: "\x17"                        }
```

This will sent a `^W` instead. In most shells that will make your `CTRL + Backspace` backspace whole words.

**Comment by kchibisov** [comment]
vi use kitty keyboard protocol, so you don't need such a thing, since ctrl+backspace is properly remapped, thus regular vim binding will work just fine.

**Comment by MeguminSama** [comment]
Adapting @PraxTube's solution (thanks!) to alacritty.toml format:

```toml
[keyboard]
bindings=[
	{ key = "Back", mods = "Control", chars = "\u0017" }
]
```
