### ISSUE TITLE
Shell args cause Alacritty to not startup

### ISSUE THREAD

**Issue by jameygleason** [alacritty/alacritty#6843]
If I use:

```yml
shell:
  program: /bin/bash
  args:
    - --login
    - -c
    - "source ~/.bashrc"
```

Alacritty won't start up

The fix is:

```yml
shell:
  program: /bin/bash
  args:
    - --login
```

However, I would like it to run the args to sync with my bashrc. Currently I have to run `source ~/.bashrc` manually after every startup.

### System

OS: Linux PopOS
Version: alacritty 0.11.0
Linux/BSD: ?

**Comment by kchibisov** [comment]
If your shell can't start, I'm not sure what the behavior should be? You don't need to specify the shell at all in the config on linux. Just set as default shell for your user and you're good to go.

**Comment by jameygleason** [comment]
The problem I'm trying to fix is, Alcritty doesn't load my .bashrc on startup. It use to.

With the args `-c` and `source ~/.bashrc`, it does load the .bashrc, but after a version change at some point it stropped allowing the args.

The behavior that is perplexing is, having any args other than `--login` cause Alacritty to not start.

**Comment by kchibisov** [comment]
`.bashrc` is being loaded by the bash when the bash is being run with `-i` or just `bash`. If you want to source your `.bashrc` on `login` (with `--login`), source it from the `.profile`(or `.bash_profile`).

**Comment by kchibisov** [comment]
Be aware, that your command is sort of correct:
```yml
shell:
  program: /bin/bash
  args:
    - --login
    - -c
    - "source ~/.bashrc"
```

The issue is that bash will just exit after `source` command is done, so even if we decide to fallback to `/bin/sh`, that wouldn't work for you, simply because everything ran exactly as you've configured and worked without any error.
