### ISSUE TITLE
Feature Request: Add font symbol import capability

### ISSUE THREAD

**Issue by al1-ce** [alacritty/alacritty#6861]
This is similar feature to kitty's `symbol` and `symbol_map` configuration.

Proposal:
Add ability to hardcode certain symbols to be imported from other fonts rather then default and fallback ones
And it would be configured something like:
```yaml
font:
    # Normal font settings
    glyph_override:
        - {glyph: "U+FFFF",        font: "Nerd"}
        - {glyph: "U+FF00-U+FFFE", font: "NotNerd"}
    # Other font settings
```

Possible usage:
In my kitty config I'm overriding U+26EC `⛬` to be from Hack font, since it displays it bigger, it would be great to be able to do so in alacritty too. 
Also same goes for some ranges like U+E0A0-U+E0A3 (private use area) which can have different glyphs from font to font and picking it from certain font can be benificial.
