### ISSUE TITLE
neovim background is broken if in tmux

### ISSUE THREAD

**Issue by ZirixCZ** [alacritty/alacritty#6869]
### System

OS: macOS
Version: Version 0.11.0 (8dbaa0b)

Neovim's background is broken while in a tmux session. 

If I start nvim from a tmux session while running in alacritty, the background is broken.

Neovim running inside of alacritty without tmux:
<img width="1680" alt="Screenshot 2023-04-18 at 21 28 25" src="https://user-images.githubusercontent.com/49836430/232884655-bd831607-0a9b-4e79-8a21-f026c241c461.png">

Neovim running inside of tmux inside of alacritty:
<img width="1680" alt="Screenshot 2023-04-18 at 21 26 57" src="https://user-images.githubusercontent.com/49836430/232884306-3d49152b-e48e-44ff-aaf8-5df9467078ca.png">

Neovim running inside of tmux inside of kitty (to demonstrate it is not the fault of tmux):
<img width="1672" alt="Screenshot 2023-04-18 at 21 30 28" src="https://user-images.githubusercontent.com/49836430/232885155-15732129-f612-4797-8a7a-ae13aa0f2ea7.png">

### Configurations
nvim
```
vim.cmd("colorscheme nightfox")
```

tmux
```
set -g base-index 1       # Start numbering windows at 1, not 0.
set -g pane-base-index 1  # Start numbering panes at 1, not 0.
bind -n C-t new-window
bind -n C-PgDn next-window
bind -n C-PgUp previous-window
bind -n C-S-Left swap-window -t -1\; select-window -t -1
bind -n C-S-Right swap-window -t +1\; select-window -t +1
bind -n C-1 select-window -t 1
bind -n C-2 select-window -t 2
bind -n C-3 select-window -t 3
bind -n C-4 select-window -t 4
bind -n C-5 select-window -t 5
bind -n C-6 select-window -t 6
bind -n C-7 select-window -t 7
bind -n C-8 select-window -t 8
bind -n C-9 select-window -t:$
bind -n C-M-w kill-window
bind -n C-M-q confirm -p "Kill this tmux session?" kill-session
bind -n F11 resize-pane -Z

set -g status-style "bg=default"
set -g window-status-current-style "bg=default,reverse"
set -g window-status-separator ''  # No spaces between windows in the status bar.
set -g window-status-format "#{?window_start_flag,, }#I:#W#{?window_flags,#F, } "
set -g window-status-current-format "#{?window_start_flag,, }#I:#W#{?window_flags,#F, } "

set -g mouse on

set -g default-terminal 'xterm-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'
```
I tried running with vanilla tmux settings. The result was the same.

alacritty
```
import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

font:
  normal:
    family: "JetBrainsMonoNL Nerd Font Mono"
    style: Regular

  bold:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold

  italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Italic

  bold_italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold Italic

  size: 14

  env:
    TERM: xterm-256color
```

### epilog
I've been trying to find a fix for this for quite a while now, but nothing seemed to have worked. Perhaps this thread helps somebody in the future.
