### ISSUE TITLE
alacritty closing suddenly in Awesome-WM X.Org X11

### ISSUE THREAD

**Issue by dcoder47** [alacritty/alacritty#6873]
alacritty closing suddenly in Awesome-WM 
1. after successful completion a command 
Example - ```ls``` command
2. un-successful completion of a command 
Examples
2.1. mistyped command such as ```ls``` or ```cd``` then pressing enter
2.2. mistyped command rectification by pressing backspace.
 
### System

OS: Arch Linux 
Kernel: 6.1.24-1-lts
Shell: zsh with zsh-syntax-highlighting, zsh-autosuggestions, zsh-autocomplete
Version: 0.12.0 (5a728195)
Linux/BSD: X11 AwesomeWM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: MesloLGS NF
Keyboard and bindings: 
```
key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
```

Alacritty config: ~/.config/alacritty/alacritty.yml
```
font:
  normal:
    family: MesloLGS NF
    style: Regular

  bold:
    family: MesloLGS NF
    style: Bold

  italic:
    family: MesloLGS NF
    style: Italic

  bold_italic:
    family: MesloLGS NF
    style: Bold Italic

  size: 14

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
```
