### ISSUE TITLE
`decorations_theme_variant` does not work anymore after updating to Gnome 44.1

### ISSUE THREAD

**Issue by puresick** [alacritty/alacritty#6912]
After updating Gnome to 44.1 the `decorations_theme_variant` configuration does not seem to work anymore. Regardless of what is being set, the window decoration always matches the set system theme (light/dark).

### System

OS: Arch Linux (Linux 6.3.1-arch1-1)
Version: alacritty 0.12.0 (5a728195)
Linux/BSD: Wayland, Gnome 44.1

**Comment by kchibisov** [comment]
Could you share your config file?

**Comment by mschwan** [comment]
Can confirm this issue. Here is my config: https://gitlab.com/mschwan/dotfiles/-/blob/master/config/alacritty.yml

Distro: Arch Linux
Kernel: Linux 6.3.1-arch1-1
Alacritty version: 0.12.0
Linux/BSD: X11, Gnome 44.1

**Comment by puresick** [comment]
Sure, here is my config file (cleaned up, i.e. removed all the default commentary from it):

```yaml
window:
  padding:
    x: 16
    y: 24
  startup_mode: Maximized
  decorations_theme_variant: Dark
font:
  normal:
    family: Sligoil
    style: Regular
  bold:
    family: Sligoil
    style: Medium
  italic:
    family: Sligoil
    style: Italic
  size: 11.0
colors:
  primary:
    background: "#101010"
    foreground: "#ebe7e2"
  cursor:
    text: "#202020"
    cursor: "#ebe7e2"
  vi_mode_cursor:
    text: "#202020"
    cursor: "#b85466"
  selection:
    text: "#202020"
    background: "#69b3b3"
  normal:
    black: "#202020"
    red: "#b85466"
    green: "#4b9f68"
    yellow: "#d59e33"
    blue: "#2c85a1"
    magenta: "#cd86d9"
    cyan: "#379292"
    white: "#d1d1d1"
  bright:
    black: "#909090"
    red: "#d993a0"
    green: "#63c985"
    yellow: "#dbd284"
    blue: "#67acc2"
    magenta: "#d7adde"
    cyan: "#69b3b3"
    white: "#ebe7e2"
cursor:
  style:
    shape: Block
    blinking: Off
shell:
  program: /usr/bin/tmux
  args:
    - new
    - -As0
key_bindings:
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Key8, mods: Control, action: DecreaseFontSize }
  - { key: Key9, mods: Control, action: IncreaseFontSize }
```
