### ISSUE TITLE
Allow hints to persist after selection

### ISSUE THREAD

**Issue by djl** [alacritty/alacritty#6976]
foot has a neat feature as part of it's URL hints mode where hint characters are persisted after a hint has been selected. This makes it easy to quickly select multiple hints without having to hit the same key binding repeatedly after each one.

Is this something Alacritty could add?

**Comment by chrisduerr** [comment]
Adding a boolean flag to stay in hint mode after selection seems like a reasonable addition.

Should be a great first issue too if someone is interested.

**Comment by SonuBardai** [comment]
Hey! I've set up a local env and have played around with Alacritty for a bit. Just wanted to get some more clarity on the hints feature. So, if I hit `Ctrl+Shift+U` I see these vimium style keybindings that highlight hyperlinks, and we want them to persist even after the user triggers them? Should this be an opt-in from the yml config file? 

<img width="699" alt="Screenshot 2023-06-11 at 15 21 24" src="https://github.com/alacritty/alacritty/assets/67749330/8c1bf52e-0680-4230-bb17-54f94c5431d1">

**Comment by djl** [comment]
How it works in foot is that the hints are immediately re-enabled after a hint has been selected. Effectively the same as hitting the shortcut again after the selection.

For the config, I imagine this would be on a per-enabled-hint basis. e.g.

```
hints:
  alphabet: "jfkdls;ahgurieowpq"
  enabled:
  - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^\u27e8\u27e9`]+"
    hyperlinks: true
    command: xdg-open
    persist: true
    post_processing: true
    mouse:
      enabled: true
      mods: None
    binding:
      key: O
      mods: Control|Shift
  - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^\u27e8\u27e9`]+"
    hyperlinks: true
    command: xdg-open
    post_processing: true
    mouse:
      enabled: true
      mods: None
    binding:
      key: U
      mods: Control|Shift
```

The first block has `persist: true` while the second block just uses the default of `persist: false`.
