### ISSUE TITLE
Mouse not working in alacritty with WSLv2 on Windows

### ISSUE THREAD

**Issue by wrigleyster** [alacritty/alacritty#6982]
If this worked, it seems it has broken again.

OS: Windows 10(installed), WSL2(usage)
Version: 0.12.1 (5fdfd47f)
Windows: ConPTY (or at least I think so, can't find any way to confirm it)

What works and what doesn't:
- So the buffer will scroll, and selecting from the buffer will highlight and copy the selection to the clipboard
- middle click does paste,
but
- clicks and the like are not forwarded to terminal applications that support it, so
  - vim
  - neovim
  - nano (using `nano -m`)
  - tmux

don't receive the mouse events. In plain wsl (ie. not using alacritty) they do work.

```yaml
# alacritty.yml
font:
  normal:
    family: Cousine Nerd Font Mono
    style: Regular
  size: 9.0
selection:
  save_to_clipboard: true
shell:
  program: wsl
    args:
      - --cd ~
```

_Originally posted by @wrigleyster in https://github.com/alacritty/alacritty/issues/4490#issuecomment-1579591501_
