### ISSUE TITLE
"opacity" in alacritty.yml does not change the Window's opacity

### ISSUE THREAD

**Issue by ignxcy** [alacritty/alacritty#6985]
OS: Fedora
Version: 0.12.1
WM: i3

When I change the "opacity" variable in the config, it just changes the color of the background, if it's 0.0 the background is jut black but the opacity doesn't change

Here is the config:
```yaml
window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  #dimensions:
  #  columns: 0
  #  lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 6
    y: 6

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.50
```
