### ISSUE TITLE
Example toml config

### ISSUE THREAD

**Issue by kenricqq** [alacritty/alacritty#6999]
With the migration from yml over to toml, settings can look quite different. Something like alacritty.toml as an example would be very helpful.

**Comment by chrisduerr** [comment]
What exactly would you need that example for? If your goal is to migrate your own configuration file, I would recommend using `alacritty migrate`.

**Comment by kchibisov** [comment]
Also, if there're man pages, which are not that bad rendered even on github. So the need for a config is questionable, given that it's extra maintenance.

**Comment by kenricqq** [comment]
Thanks for the tip, and def recommend you guys put `alacritty migrate` in readme.md.

As for example page, yes, it might mean extra maintenance, but it's going to attract more new users in the long run due to the increased ease of use of having an example. Anyway, just a suggestion for the taking.

**Comment by kchibisov** [comment]
it's in the changelog, but it's probably better to put it in the `warning`.

**Comment by chrisduerr** [comment]
Not interested in adding an example configuration file at this point.

**Comment by cideM** [comment]
Since this is the issue people will stumble on when they can no longer find the convenient example configuration file in the root repository, I'll just add this here.

At the time of writing this comment you are unlikely to have an Alacritty version installed that already ships the new man pages. So just go [here](https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd) to read the man page on the configuration on GitHub.

Eventually you'll be able to get there with `man 5 alacritty`.

**Comment by kchibisov** [comment]
You're using alacritty version not supporting toml yet, you need to build alacritty yourself if you want a toml config.

**Comment by 0323pin** [comment]
If people really need an example, feel free to [take what you want](https://codeberg.org/pin/netbsd-marswm/raw/branch/main/.config/alacritty/alacritty.toml) 

I'm always running my builds from git-HEAD and had no issues migrating to `toml`.
Regards

**Comment by antonwnk** [comment]
Ugh I see, bad oversight on my side. Assumed toml was the recommended config already in 12.1
Sorry and thanks for the answers!

**Comment by tonymcneil** [comment]
Good documentation and examples are key to adoption IMHO. Just telling somebody to RTFM is not going to win over users... for example I was looking at theming and arrived at https://github.com/alacritty/alacritty-theme and all the examples are yaml, then looking at https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd isn't clear to me (somebody new to toml) if there is a way I can easily import the theme that's defined in yaml and get it working with the core toml config? I see that `alacritty migrate` was mentioned so I assume I need to use that on the yaml theme if wanting to use it.

**Comment by kchibisov** [comment]
While we don't won't to bring the `TOML` file separately back. We likely to change the way we represent the defaults inside the man pages. The PR https://github.com/alacritty/alacritty/pull/7107 should have all the defaults inlined, so you can simply copy paste them out of the man page if you want to.

Given that the man page will be hosted on `alacritty.org` for every release the end experience should hopefully be better, the `alarcitty.org` will be linked from the `# Configuration` section in the `README`.

**Comment by TheLustriVA** [comment]
So, there's no way to tell if I have a minimum viable config for the .toml version then? The man 5 page isn't self-contained and doesn't distinguish between config and instruction.

**Comment by chrisduerr** [comment]
> So, there's no way to tell if I have a minimum viable config for the .toml version then?

The minimum viable config is an empty file.

**Comment by TheLustriVA** [comment]
> > So, there's no way to tell if I have a minimum viable config for the .toml version then?
> 
> The minimum viable config is an empty file.

Yeah, my comment wasn't worded particularly well so this is 100% true. I should have added "Once I start adding things I'm not sure about."

Also, thumbs-up given because this inspired me to go write a yaml to toml converter in python.

**Comment by kchibisov** [comment]
I guess that's a good learning experience. We provide one with `alacritty` though via `alacritty migrate`.

**Comment by TheLustriVA** [comment]
> I guess that's a good learning experience. We provide one with `alacritty` though via `alacritty migrate`.

It worked a treat as well, I was definitely doing it for the learning experience though.

**Comment by hardyoyo** [comment]
Hey, so, I installed Alacrity on Ubuntu via Cargo and somehow ended up with version 13, which apparently wants to be configured with toml... And I went looking for docs and found this friendly discussion. I like Alacritty, I have is installed on my work notebook. I just want to switch the color theme on my personal Linux notebook. Any chance y'all will reconsider your stance on an example config, so I can use this app?

**Comment by hardyoyo** [comment]
It doesn't help that alacritty-theme complains about a missing config. I think y'all either need an example config, or you need to bootstrap one, if you're going to be requiring it.

**Comment by pcesar22** [comment]
If anyone thinks this is silly, let me be a data point of someone who was looking into changing from kitty to alacritty, ran into this exact issue (e.g. just give me a basic .toml to get started with), then saw the response above, then noped out of it. Back to kitty for me. Providing an example config of the recommended way to configure something is just common sense

**Comment by daveman1010221** [comment]
> If anyone thinks this is silly, let me be a data point of someone who was looking into changing from kitty to alacritty, ran into this exact issue (e.g. just give me a basic .toml to get started with), then saw the response above, then noped out of it. Back to kitty for me. Providing an example config of the recommended way to configure something is just common sense

Same here, bud. Same here. That response above is just wild. Found out about Alacritty very recently, was curious enough to try it out. I don't have an existing config to "migrate". The installation instructions say to install it using 'cargo', which I did. Turns out cargo doesn't install man pages. LOL

**Comment by kchibisov** [comment]
I mean reading is hard and installing git versions is also hard. https://github.com/alacritty/alacritty/blob/master/INSTALL.md#manual-page

Even when every option is documented reading is also hard apparently. Especially when we said multiple times that we'll even host man pages **once release will actually be**.

But yeah, let's just blame developers because they owe something to you.

**Comment by daveman1010221** [comment]
> I mean reading is hard and installing git versions is also hard. https://github.com/alacritty/alacritty/blob/master/INSTALL.md#manual-page
> 
> Even when every option is documented reading is also hard apparently. Especially when we said multiple times that we'll even host man pages **once release will actually be**.
> 
> But yeah, let's just blame developers because they owe something to you.

There's a pretty big difference between saying you haven't gotten around to writing docs yet and marking something WONTFIX.

**Comment by daveman1010221** [comment]
> What do you even mean? The docs are right here https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd . The only issue is that they are not hosted to make them more accessible for macOS/Windows users, because the version is not released. And that's a PR on the website [alacritty/website#15](https://github.com/alacritty/website/pull/15)
> 
> Also, homebrew even ships man pagas, but the version you want docs for requires manual build, because you've done a manual build from the git or used cargo instead of package manager.

The recommended install method is either to use your platform package manager (mine is apt) or 'cargo install alacritty'. Neither method installs the man 5 pages, which apparently contain config docs. Shell version is 0.12.2. Even if you go to the Github release page, which the latest release is July 1, there's no download for the man 5 file. In fact, at 0.12.2, there's no 'alacritty migrate' command, either:

```
alacritty migrate
error: Found argument 'migrate' which wasn't expected, or isn't valid in this context

USAGE:
    alacritty [OPTIONS] [SUBCOMMAND]

For more information try --help
```

So I assue none of this thread actually applies to the generally available version of Alacritty, and users of the currently available version should still be using the YAML config. Now, you'll probably respond with something like, "All of these directions only apply to the very latest bleeding edge version that's found in the source repo on Github." As it turns out, not everyone wants to run the bleeding edge and when I searched for "alacritty config file example", this Github issue is the one that came up in the search results. Even the Install guide doesn't make mention of the config file: https://github.com/alacritty/alacritty/blob/master/INSTALL.md and this issue says I should use the newer TOML format, which I attempted to do but couldn't find the docs on. The problem isn't the lack of docs, though. The problem is the attitude of the some of the developers for this project towards new users. You're not helping here.

**Comment by kchibisov** [comment]
Have you read this https://github.com/alacritty/alacritty#configuration ? It clearly says that before `0.13.0` your config is in `alacritty.yml`?

**Comment by kchibisov** [comment]
Which is available with your distro (they install in shared) or on release page https://github.com/alacritty/alacritty/releases

**Comment by zilverjk** [comment]
alacritty --migrate doesn't work in 0.12.2, there is no alacritty.toml as an example and there is not v0.13 in the releases nor branches of the repo.

**Comment by zilverjk** [comment]
@kchibisov it warns about using alacritty.toml instead of the yml file. I had to use a online converter from yml to toml file and get rid of the unused keys in order to not se the warning when launching the app.

**Comment by kchibisov** [comment]
@zilverjk but that means that you've build the application yourself? So if your app complains that you use `yml` then it can `migrate`, because you've explicitly built the version which supports `toml`.

You likely have multiple `alacritty` binaries in the path or something like that `which -a alacritty` could give a hint.

`toml` was added with the `migrate` in the same commit, they can't exist without each other.

**Comment by zilverjk** [comment]
@kchibisov that's what I thought is a weird behavior. take a look at this. I don't have the yml file anymore in the `0.12.2` version and it works fine with the toml config file and there is no migrate for the alacritty command.
<img width="650" alt="image" src="https://github.com/alacritty/alacritty/assets/7515854/448777f6-0b8d-4158-a8bd-aa5d88721c5e">

**Comment by chrisduerr** [comment]
Sounds like you have two different Alacritty versions installed and getting yourself confused.

**Comment by nixpulvis** [comment]
Sorry if this was already mentioned, but it doesn’t seem like it would be hard to make alacritty dump its defaults to a file. Maybe something like `alacritty migrate —defaults` that way there’s no maintainable needed, and users can always get the latest example when they want.

Personally, I’d just print to STDOUT and let people decide if they want to grep, or redirect to a file or something.

I’m glad we have a nice man page now, but I hate to admit that I too would prefer to just read the default config file in TOML. No translation needed that way.

**Comment by chrisduerr** [comment]
> Sorry if this was already mentioned, but it doesn’t seem like it would be hard to make alacritty dump its defaults to a file. Maybe something like alacritty migrate —defaults that way there’s no maintainable needed, and users can always get the latest example when they want.

We do **not** want that. Nobody should ever have a full configuration file with all defaults easily available, because it only causes problems.

**Comment by w4xccino** [comment]
I'm new using Alacritty and I used to copy the `.yaml` example file to use it. Simple as that. Now I can't change font style  because nobody wants to show an example. The documentation is unclear for me.

**Comment by zkxjzmswkwl** [comment]
Docs are bad.
No example config for toml.
No reason to adopt the software.

Solid time-waste, though.

**Comment by kenricqq** [comment]
personally adopted kitty and have no complaints, good docs and defaults; alacritty and kitty performance diff is negligible

**Comment by luminous-whispers** [comment]
Just a suggestion, ReadMe file is not that clear. Perhaps where the software before v0.13.0 will look for .yaml configuration file should also be mentioned here:

> Alacritty versions before 0.13.0 are using YAML configuration files and all their settings were documented in the alacritty.yml. The example alacritty.yml file for each release can be found on [GitHub releases page](https://github.com/alacritty/alacritty/releases).
>
> Alacritty doesn't create the config file for you, but it looks for one in the following locations:
 `$XDG_CONFIG_HOME/alacritty/alacritty.toml`  <<< here

**Comment by afonsolage** [comment]
Sorry for bringing this back, but I'm having a hard time trying to config `alacritty.toml`. An example `alacritty.toml` file would be very welcome to new users.

**Comment by Audiosutras** [comment]
> What exactly would you need that example for? If your goal is to migrate your own configuration file, I would recommend using `alacritty migrate`.

From game chat to the comments

**Comment by wookayin** [comment]
Alacritty 0.13.0 was just released. https://github.com/alacritty/alacritty/releases/tag/v0.13.0 does not have an example TOML config file as promised in the REDAME.

**Comment by TheKissOfDragon** [comment]
when run alacritty migrate command, it warn `zsh: command not found: alacritty`, how to fix it.

**Comment by chrisduerr** [comment]
> does not have an example TOML config file as promised in the REDAME.

Where did you even pull this nonsense from?

> This issue didn't have a pointer to the most relevant documentation page

This is in the README, all you have to do is actually read it.

**Comment by bassmake** [comment]
You are probably losing a lot of new adopters just for not being able to provide config sample. I as a newcomer am not that familiar with TOML so I can create valid configuration file just from documentation.

**Comment by kchibisov** [comment]
@bassmake so you can't use examples inside the documentation?

![image](https://github.com/alacritty/alacritty/assets/27620401/37be1beb-59c8-4e09-a00c-dcce7b35cd2e)


This is from our docs, if you can't extend examples, which we have for each tricky section I'm not sure how to help.

**Comment by bassmake** [comment]
@kchibisov Thanks a lot, got lost in the long keyboard actions list. Now that you pointed it out it is obvious :).

As it is definitely my bad not reading through the document thoroughly, maybe making examples visually different or putting them on the beginning of the section might improve experience a bit.

**Comment by 0323pin** [comment]
@bassmake Linked my own config on this issue earlier.
If you need an example, [just grab what you want](https://codeberg.org/pin/netbsd/raw/branch/main/.config/alacritty/alacritty.toml)

I'm always running `alacritty-dev`, so the config is up-to-date.

**Comment by iuliandita** [comment]
[Here's another](https://gist.github.com/iuliandita/a4c1dd0e25460af91ebeeef51e0ef7ec) TOML model for whoever needs one.
It includes all the defaults (commented out) and the color scheme is Catpuccin Mocha.

**Comment by ManuGithubSteam** [comment]
Here is mine: https://github.com/ManuGithubSteam/dotfiles/blob/main-broken/alacritty.toml
My toml is similar to the color scheme of: Shapeshifter.dark

 If the project aims for wider adoption something like a example conf should be common sense.

**Comment by chrisduerr** [comment]
> If the project aims for wider adoption

It doesn't.

**Comment by IzhakJakov** [comment]
Here is mine:
```toml
import = ["colors/vscode_terminal.toml"]

[colors.primary]
background = "#181818"

[window]
decorations = "transparent"
opacity = 1
startup_mode = "Maximized"
padding = { x = 4, y = 28 }

[env]
TERM = "alacritty"
ZDOTDIR = "~/.config/zsh"

[bell]
color = "#003300"
duration = 32

[font]
size = 13
offset = { x = 1, y = 1 }
normal      = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold        = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic      = { family = "UbuntuMono Nerd Font", style = "Italic" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
	{ chars = "\u001F", key = "Slash", mods = "Control" },
	{ chars = "\u001F", key = "Slash", mods = "Control|Shift" },
	{ chars = "\u0000", key = "Space", mods = "Control" },
	{ action = "None", key = "W", mods = "Command" },
	{ action = "ToggleFullscreen", key = "Return", mods = "Command" },
	{ action = "SpawnNewInstance", key = "N", mods = "Command" }
]
```

**Comment by Gigas002** [comment]
@IzhakJakov is `ZDOTDIR = "~/.config/zsh"` works fine for you? In my case it only works when I set the full path fr unknown reason

**Comment by IzhakJakov** [comment]
Hi @Gigas002,

Actually I am using the absolute path for both `ZDOTDIR` and `import` but did not want to confuse people who might copy/paste my config.

It seems like only absolute paths are supported.  I tried a relative path for `import` and using `${XDG_CONFIG_HOME}` (env var) for `ZDOTDIR` and neither is working.

**Comment by azigler** [comment]
I created a default [`alacritty.toml`](https://github.com/azigler/dotfiles/blob/main/alacritty/alacritty.toml) from the [configuration options page](https://alacritty.org/config-alacritty.html) that is comprehensive:

```toml
# https://alacritty.org/config-alacritty.html

###########
# GENERAL #
###########

# Import additional configuration files
import = []

# Shell program and its arguments
# Default for Linux/BSD/macOS is $SHELL or user's login shell
# Default for Windows is "powershell"
[shell]
program = "/bin/zsh"  # Example for Linux/BSD/macOS
args = ["-l"]

# Working directory
working_directory = "None"  # Default: "None"

# Live config reload (changes require restart)
live_config_reload = true  # Default: true

# Offer IPC using alacritty msg (unix only)
ipc_socket = true  # Default: true

#######
# ENV #
#######

[env]
# Environment variables

##########
# WINDOW #
##########

[window]

# Window dimensions
dimensions = { columns = 0, lines = 0 }  # Default: columns = 0, lines = 0

# Window startup position
position = "None"  # Default: "None"

# Padding
padding = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Dynamic padding
dynamic_padding = false  # Default: false

# Window decorations
decorations = "Full"  # Default: "Full"

# Opacity
opacity = 1.0  # Default: 1.0

# Blur (macOS/KDE Wayland only)
blur = false  # Default: false

# Startup mode
startup_mode = "Windowed"  # Default: "Windowed"

# Window title
title = "Alacritty"  # Default: "Alacritty"

# Dynamic title
dynamic_title = true  # Default: true

# Window class (Linux/BSD only)
class = { instance = "Alacritty", general = "Alacritty" }  # Default: instance = "Alacritty", general = "Alacritty"

# Decorations theme variant
decorations_theme_variant = "None"  # Default: "None"

# Resize increments
resize_increments = false  # Default: false

# Option as Alt (macOS only)
option_as_alt = "None"  # Default: "None"

#############
# SCROLLING #
#############

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 3  # Default: 3

########
# FONT #
########

[font]

# Normal font style
normal = { family = "monospace", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Bold font style
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold

# Italic font style
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 11.25  # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true

##########
# COLORS #
##########

[colors]

# Transparent background colors
transparent_background_colors = false  # Default

# Draw bold text with bright colors
draw_bold_text_with_bright_colors = false  # Default

# Primary colors
[colors.primary]
foreground = "#d8d8d8"  # Default
background = "#181818"  # Default
dim_foreground = "#828482"  # Default
bright_foreground = "None"  # Default

# Cursor colors
[colors.cursor]
text = "CellBackground"  # Default
cursor = "CellForeground"  # Default

# Vi mode cursor colors
[colors.vi_mode_cursor]
text = "CellBackground"  # Default
cursor = "CellForeground"  # Default

# Search colors
[colors.search.matches]
foreground = "#181818"  # Default
background = "#ac4242"  # Default

[colors.search.focused_match]
foreground = "#181818"  # Default
background = "#f4bf75"  # Default

# Hint colors
[colors.hints.start]
foreground = "#181818"  # Default
background = "#f4bf75"  # Default

[colors.hints.end]
foreground = "#181818"  # Default
background = "#ac4242"  # Default

# Line indicator colors
[colors.line_indicator]
foreground = "None"  # Default
background = "None"  # Default

# Footer bar colors
colors.footer_bar]
foreground = "#181818"  # Default
background = "#d8d8d8"  # Default

# Selection colors
[colors.selection]
text = "CellBackground"  # Default
background = "CellForeground"  # Default

# Normal colors
[colors.normal]
black = "#181818"  # Default
red = "#ac4242"  # Default
green = "#90a959"  # Default
yellow = "#f4bf75"  # Default
blue = "#6a9fb5"  # Default
magenta = "#aa759f"  # Default
cyan = "#75b5aa"  # Default
white = "#d8d8d8"  # Default

# Bright colors
[colors.bright]
black = "#6b6b6b"  # Default
red = "#c55555"  # Default
green = "#aac474"  # Default
yellow = "#feca88"  # Default
blue = "#82b8c8"  # Default
magenta = "#c28cb8"  # Default
cyan = "#93d3c3"  # Default
white = "#f8f8f8"  # Default

# Dim colors
[colors.dim]
black = "#0f0f0f"  # Default
red = "#712b2b"  # Default
green = "#5f6f3a"  # Default
yellow = "#a17e4d"  # Default
blue = "#456877"  # Default
magenta = "#704d68"  # Default
cyan = "#4d7770"  # Default
white = "#8e8e8e"  # Default

########
# BELL #
########

[bell]

# Visual bell animation effect
animation = "Linear"  # Default: "Linear"

# Duration of the visual bell flash in milliseconds
duration = 0  # Default: 0

# Visual bell animation color
color = "#ffffff"  # Default: "#ffffff"

# Command executed when the bell is rung
command = "None"  # Default: "None"

#############
# SELECTION #
#############

[selection]

# Characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"

# When set to true, selected text will be copied to the primary clipboard
save_to_clipboard = false  # Default: false

##########
# CURSOR #
##########

[cursor]

# Cursor style
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = "None"  # Default: "None"

# Cursor blinking interval in milliseconds
blink_interval = 750  # Default: 750

# Time after which cursor stops blinking, in seconds
blink_timeout = 0  # Default: 5

# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true  # Default: true

# Thickness of the cursor relative to the cell width
thickness = 0.15  # Default: 0.15

############
# TERMINAL #
############

[terminal]

# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste"  # Default: "OnlyCopy"

#########
# MOUSE #
#########

[mouse]

# When true, the cursor is temporarily hidden when typing
hide_when_typing = true  # Default: false

# Mouse bindings (actual bindings need to be defined as per user preference)
# Example: bindings = [{ mouse = "Left", action = "Paste" }]
bindings = []

#########
# HINTS #
#########

[hints]

# Define the keys used for hint labels
alphabet = "jfkdls;ahgurieowpq"  # Default: "jfkdls;ahgurieowpq"

# Enable specific hints
#[[hints.enabled]]
# Example configuration (actual settings to be defined based on user preference)
# regex = "..."
# hyperlinks = true
# post_processing = true
# persist = false
# action = "..."
# command = "..."
# binding = { key = "...", mods = "...", mode = "..." }
# mouse = { mods = "...", enabled = true }

# KEYBOARD section of Alacritty configuration

[keyboard]

# Define keyboard bindings here
# Example placeholder (actual bindings need to be defined based on user preference)
bindings = [
    # { key = "Key", mods = "Modifiers", action = "Action" },
    # { key = "Key", mods = "Modifiers", chars = "Characters to send" },
    # ...
]
```
