### ISSUE TITLE
alacrity shortcut cannot scroll

### ISSUE THREAD

**Issue by newyorkthink** [alacritty/alacritty#7021]
![image](https://github.com/alacritty/alacritty/assets/87791643/3c0f53a7-871d-4766-9325-eeb3f1dca48a)

i set two shortcut , but it not work

**Comment by chrisduerr** [comment]
Could you elaborate? Also please delete that newline above the bindings.

**Comment by cu8code** [comment]
> alacrity 0.11.0
```yml
shell:
  program: /bin/fish
  args:
    - --login

font:
  size: 8
  normal:
    family: JetBrains Mono
    style: Regular

key_bindings:
  - {key: J, mods: Control, action: ScrollPageUP}
  - {key: K, mods: Control, action: ScrollPageDown}

```

seems to work fine just remember to press **ctr + j** to scroll up and **crt + k** to scroll down
