### ISSUE TITLE
Cannot set cursor to Block shape

### ISSUE THREAD

**Issue by Mithrandir2k18** [alacritty/alacritty#7027]
### System

OS: Archlinux 6.3.8
Version: 0.12.1
Linux/BSD: X11 with Qtile

### Logs

Font/Terminal size: DejaVu Sans Mono, 14.0
This output keeps coming up in the output of `alacritty -vvv`:
[345.210693816s] [TRACE] [alacritty_terminal] Saving cursor position
[345.210698806s] [TRACE] [alacritty_terminal] Restoring cursor position
[345.210704596s] [TRACE] [alacritty_terminal] Setting cursor style Some(CursorStyle { shape: Beam, blinking: false })

Here's my cursor configuration ([see full config here](https://github.com/Mithrandir2k18/dotfiles/blob/master/alacritty/alacritty.yml)):

```
cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block
  vi_mode_style:
    shape: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  #unfocused_hollow: true
```

I'm used to just always have the block cursor, so I wouldn't mind that. Having a beam when in insert mode/typing in the terminal would also be fine, but having the beam in Normal/Visual Mode in vim just isn't an option. Ideally I'd like to get "always block" working though, but right now I cannot get it to work, it seems to periodically reset for whatever reason.
