### ISSUE TITLE
How to remove padding in floating windows?

### ISSUE THREAD

**Issue by sokinpui** [alacritty/alacritty#7029]
### System
Linux: Wayland, Gnome44 and Fedora38

I just discover there is air gap at alacritty float window the right edge and bottom edge, if the window is resize by `win+arrow`, then there is no gap.

How can I fill the gap when using alacritty float window? I found Emacs Gui have the same issue, but I can solve it by add `(setq frame-resize-pixelwise t)` in init.el.

I have already set the window padding to 0 in alacritty.yml:
```
window:
  decorations: none
  startup_mode: Maximized

  padding:
    x: 0
    y: 0

  class:
    instance: Alacritty
    general: Alacritty

  resize_increments: true
```

Float window:
![image](https://github.com/alacritty/alacritty/assets/104958540/edee7a39-f459-4051-9fd5-dded7a476846)
![image](https://github.com/alacritty/alacritty/assets/104958540/fbd8ee7b-0edf-436b-800b-6ca43689e85c)

Resized by `win+right arrow`
![image](https://github.com/alacritty/alacritty/assets/104958540/ed98ee2e-16e2-435b-a371-c4c6810e571d)
