### ISSUE TITLE
issue with nerd fonts ? 

### ISSUE THREAD

**Issue by XxHiroTTVxX** [alacritty/alacritty#7036]
### System

OS: Linux
Version: `alacritty 0.12.1 (5fdfd47f)
Linux/BSD: X11

so basically the prompt I have gets messed up in the terminal 

```yml
# Dracula theme for Alacritty
# Font config:
Font:
normal:
    family: FiraCode Nerd Font
    style: Regular


# Dracula theme for Alacritty
colors:
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'
    bright_foreground: '#ffffff'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'
    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'
  footer_bar:
    background: '#282a36'
    foreground: '#f8f8f2'
  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'
    end:
      foreground: '#f1fa8c'
      background: '#282a36'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '#44475a'
  normal:
    black: '#21222c'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#f8f8f2'
  bright:
    black: '#6272a4'
    red: '#ff6e6e'
    green: '#69ff94'
    yellow: '#ffffa5'
    blue: '#d6acff'
    magenta: '#ff92df'
    cyan: '#a4ffff'
    white: '#ffffff'
```

![image](https://github.com/alacritty/alacritty/assets/101534563/e21d750f-7f9d-4a53-a40b-6de2e118e823)
