### ISSUE TITLE
Using shell to run / reconnect to tmux in alacritty.toml (after migrate from yaml) fails

### ISSUE THREAD

**Issue by MrHappy** [alacritty/alacritty#7044]
In my yml-file I have the following
```
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
```
And this works fine, but since my recent update I got a warning to migrate to toml. So I did.
That converted above part to
```
[shell]
args = ["-l", "-c", "tmux attach || tmux"]
log_level = "Trace"
persistent_logging = true
print_events = false
program = "/bin/zsh"
```

Now when I restart Alacritty, I get the following error:
`[0.001140165s] [ERROR] [alacritty_config_derive] Config error: shell: data did not match any variant of untagged enum Program`

### System

OS: Linux
Version: `  alacritty 0.13.0-dev (1a67fc35)` 
Linux/BSD: Wayland
