### ISSUE TITLE
how to find what font is used 

### ISSUE THREAD

**Issue by nbari** [alacritty/alacritty#7057]
### System

OS: Linux
Version: `alacritty 0.13.0-dev (edf4df66)` 
Linux: Wayland `cargo build --release --no-default-features --features=wayland`

When using the font `Monoid Nerd Font`, I notice that when commenting or writing some commands font change, wondering how could I customize it, in the below screenshot, the 3 commented lines in gray have a different font style, how to choose/configure that font? 

![Screenshot from 2023-07-06 17-35-49](https://github.com/alacritty/alacritty/assets/364199/a3414a4f-626a-47c4-b992-8d71fae431f3)

Also when selecting the `[` font changes:

[font changes](https://github.com/alacritty/alacritty/assets/364199/860cc7fd-41f9-4862-ba0a-b161a2878193)

This is my current font configuration:

```toml
[font]
size = 10.0

[font.normal]
family = "Monoid Nerd Font"
style = "Retina"

# [font.normal]
# family = "M+ 1m"
# style = "light"

[font.bold]
family = "M+ 1m"
style = "regular"

[font.italic]
family = "M+ 1m"
style = "Italic"

[font.bold_italic]
family = "M+ 1m"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0


[font.offset]
x = 0
y = 0

```
