### ISSUE TITLE
TOML Configuration shell might not work

### ISSUE THREAD

**Issue by tomkcey** [alacritty/alacritty#7087]
### System

OS: Pop_OS! 22.04 LTS
Version: alacritty 0.13.0-dev
Compositor: x11

### Logs

`cat /tmp/Alacritty-8778.log`

```log
[0.000402633s] [WARN ] [alacritty_config_derive] Unused config key: shell
```

### Config

```toml
live_config_reload = true

[cursor]
shell = { program = "/bin/bash", args = "-l -c tmux" }

[env]
TERM =  "alacritty"

[window]
dynamic_title = true
startup_mode = "Maximized"
padding = { x = 8, y = 8 }
opacity = 0.9

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
        { action = "Copy", key = "C", mods = "Control|Shift" },
        { action = "Paste", key = "V", mods = "Control|Shift" }
]

[mouse]
hide_when_typing = true
```

### Problem

Reading the man page `man 5 alacritty` it seems pretty clear the `shell` key-value pair under the `cursor` table should work. Any idea why it doesn't?

**Comment by kchibisov** [comment]
Hm, yeah, the man page is wrong, it's in a separate section.

**Comment by tomkcey** [comment]
> Hm, yeah, the man page is wrong, it's in a separate section.

Do you know in which section it is?

**Comment by kchibisov** [comment]
It should be in its own section.

**Comment by qrooel** [comment]
`[shell]
program = "/bin/zsh"
args = ["-l"]`

**Comment by sascha-wi** [comment]
So why is this still showing the "old way"? https://alacritty.org/config-alacritty.html

**Comment by kchibisov** [comment]
It shows the right thing. `shell` is a part of `terminal` section.

**Comment by sascha-wi** [comment]
```
[terminal.shell]
program = "/usr/bin/fish"

```
This is how it works now for me without warning messages. No clue if thats debian specific thing, but this is NOT what is shown on the link provided above.

**Comment by kchibisov** [comment]
that's also valid syntax. Link implies the
```toml
[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }
```

Which is the same as you wrote. Assuming that you put everything into the single `[terminal]` section.
