### ISSUE TITLE
Hint regex with large chars amount. Hanging and continues memory consumption 

### ISSUE THREAD

**Issue by cpof-tea** [alacritty/alacritty#7097]
### Problem

With the `Qm[0-9A-Za-z]{44}` as a hint regex pattern, Alacritty hangs upon activating Hints and memory consumption starts to growth continuously.

```yml
# ... rest of the config
hints:
  enabled:
    - regex: 'Qm[0-9A-Za-z]{44}'
      action: Copy
      binding:
        key: U
        mods: Control|Shift
```

But no issues with `sha256:([0-9a-f]{64})` pattern.

```yml
# ... rest of the config
hints:
  enabled:
    - regex: 'sha256:([0-9a-f]{64})'
      action: Copy
      binding:
        key: U
        mods: Control|Shift
```
No any hangs, hints highlighted almost immediately

### System

Version: 0.12.2
OS: Ubuntu 20.04
Compositor: compton
WM: xmonad

### Logs

Crashes: NONE

Font/Terminal size:
[screenshot](https://github.com/alacritty/alacritty/assets/29537473/e70f66a4-9ef0-4e26-b012-0c8c985db0b0)

Keyboard and bindings:
After activating Hints with the mentioned pattern Alacritty hangs and stops reporting any events with `--report-events` option
