### ISSUE TITLE
White line randomly appears under macOS tabs bar

### ISSUE THREAD

**Issue by rosingrind** [alacritty/alacritty#7134]
https://github.com/alacritty/alacritty/assets/108860307/f9faa6fb-4ceb-48b0-8e34-662659c90023

### Reproduction

1. Open a window and go fullscreen
2. Do some typing actions
3. Open new tab with Cmd-T
4. Perform some typing again (on this step the line should show up)
5. If you hover over top bar with tabs and controls, the line disappears

Explanation of [5]:

- as seen in the video at 0:13, hovering over controls bar makes the line disappear
- at 0:19 the line persists until the controls bar pops out, which makes cursor hover over it

### System

OS: macOS Ventura 13.5 (22G74)
Version: alacritty 0.12.2 (9d9982d)

### Config

```yml
window:
  dimensions:
    columns: 80 # 132
    lines: 24 # 43
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  dynamic_title: true
  option_as_alt: Both

font:
  # Normal (roman) font face
  normal:
    family: SF Mono
    style: Regular
  bold:
    family: SF Mono
    style: Bold
  italic:
    family: SF Mono
    style: Italic
  bold_italic:
    family: SF Mono
    style: Bold Italic
  size: 12
  builtin_box_drawing: false

bell:
  animation: EaseOutExpo
  duration: 80
  color: '#848484'
  command:
    program: osascript
    args: ["-e", "beep"]

key_bindings:
  - { key: T, mods: Command, action: CreateNewWindow }
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
```
