### ISSUE TITLE
Can't change font size from config file

### ISSUE THREAD

**Issue by akabolov** [alacritty/alacritty#7178]
Issue: Cant change the font size from the config file, only using cmd+ and cmd-.
Previously it was working fine, I didn't do anything prior to the current issue, right now each time I start Alacritty I manually resize it.

Setting the font size to `40.0` (as an example) just makes no difference.

### Config file 
```yaml
env:
  TERM: xterm-256color

window:
  dimensions:
    lines: 0
  padding:
    x: 10
    y: 10
  opacity: 1
    

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true
  decorations: buttonless
    # startup_mode: Fullscreen

scrolling:
  history: 10000
  multiplier: 3

# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    #family: "MesloLGS NF"
    #family: "Hack Nerd Font"
    family: "Iosevka Nerd Font"
    style: Light
    size: 20.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

mouse:
  hide_when_typing: false

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: false

cursor:
  style: Block
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true


colors:
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: CellForeground
    background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    #bar:
     # background: '#434c5e'
      #foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'
```

### System

OS: macOS 
Version: alacritty 0.12.2 (9d9982d)

### Logs
❯ alacritty --version
alacritty 0.12.2 (9d9982d)

❯ alacritty -vv
Created log file at "/var/folders/87/dmj2h3_d7nq9zhkwl3j6b96h0000gn/T/Alacritty-3357.log"
[0.000005708s] [INFO ] [alacritty] Welcome to Alacritty
[0.000211292s] [INFO ] [alacritty] Version 0.12.2 (9d9982d)
[0.000511375s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/akabolov/.config/alacritty/alacritty.yml"
[0.000841833s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[0.025567125s] [INFO ] [alacritty] Using Apple CGL
[0.055140083s] [INFO ] [alacritty] Window scale factor: 1
[0.056015417s] [DEBUG] [alacritty] Loading "Iosevka Nerd Font" font
[0.095799667s] [INFO ] [alacritty] Running on Apple M1 Pro
[0.095834875s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.099219250s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.107686292s] [INFO ] [alacritty] Cell size: 5 x 14
[0.107723250s] [INFO ] [alacritty] Padding: 10 x 13
[0.107733625s] [INFO ] [alacritty] Width: 800, Height: 600
[0.109301042s] [INFO ] [alacritty] PTY dimensions: 41 x 156
[0.111163625s] [INFO ] [alacritty] Initialisation complete
[0.141157458s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`
