### ISSUE TITLE
Ability to hide title bar but not borders in Mac OS

### ISSUE THREAD

**Issue by bendavis78** [alacritty/alacritty#7194]
### System
OS: macOS
Version: master

---
I would like to be able to hide my title bar, but keep window borders. Hiding borders causes other tiling window apps to not be able to resize the window. Alacritty only has a configuration option for decorations that hides the title bar, which is "None".

**Comment by chrisduerr** [comment]
There's already too many decoration options, I have no interest in adding this.

**Comment by bendavis78** [comment]
Would you be open to discussing an alternative? It might make more sense to have each option as a boolean, such as:

```toml
[window.decorations]
border = true
titlebar = false
transparent = false
buttons = true
```
