### ISSUE TITLE
Capital letter tops being cut off by a few pixels

### ISSUE THREAD

**Issue by egorbn** [alacritty/alacritty#7198]
It looks like the glyph box is chopping off tops of capital letters in [`UbuntuMono Nerd Font`](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/UbuntuMono.zip).

<img width="850" alt="alacritty_font" src="https://github.com/alacritty/alacritty/assets/116128944/4b269606-dd83-415f-b853-33f864dea6ad">

iTerm2 on left, alacritty on right

Here's the font config:
```yaml
font:
  normal:
    family: UbuntuMono Nerd Font
    style: Regular
  bold:
    style: Bold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic
  size: 16.0
  offset:
    y: 4
```

Any ideas why this is happening?

### System

OS: macOS
Version: 0.12.2 (9d9982d)
