### ISSUE TITLE
How do I change the font on Windows?

### ISSUE THREAD

**Issue by oscarorange** [alacritty/alacritty#7215]
This does not seem to work, I am struggling to understand the docs
```toml
[font]
normal = { family = "JetBrains Mono NL" }
size = 15
```
