### ISSUE TITLE
Cursor shape reset (From Beam to Block) after opening and closing neovim

### ISSUE THREAD

**Issue by Antonio-Rocchia** [alacritty/alacritty#7255]
To reproduce the bug:
1. Set cursor shape to beam
2. Open alacritty (the cursor should be a beam)
3. Launch neovim
4. Quit neovim
5. *Now the cursor is a block*

### System

OS: Linux (Fedora 38): Wayland, Gnome 44
Version: alacritty 0.12.2

My settings:
```yml
import:
  - ~/.config/alacritty/themes/catppuccin/catppuccin-mocha.yml

cursor:
  style:
    shape: Beam

font:
  normal:
    family: RobotoMono Nerd Font
    style: Regular
  bold:
    family: RobotoMono Nerd Font
    style: Bold
  italic:
    family: RobotoMono Nerd Font
    style: Italic

  size: 12.0


shell:
  program: /bin/bash
```
