### ISSUE TITLE
Tmux doesn't start up along with alacritty

### ISSUE THREAD

**Issue by sbushmanov** [alacritty/alacritty#7274]
I'm trying to start `nnn` file manager in `alacritty` instance like so:

```
alacritty -e nnn -e
```
(which is assigned to keyboard shortcut or tested in another terminal, say gnome-terminal)

My problem `tmux` doesn't start up along with `alacritty` terminal (however, if I simply start by `alacritty`, without arguments, it does)

Is there a way to start `tmux` automatically along with `alacritty`?

(I know this is old issue, but as one may see, the problem does exist).  

### System

Linux/Ubuntu
alacritty 0.13.0-dev

top of `alacritty` config:
```
#~/.config/alacritty/alacritty.yml
shell:
  program: /usr/bin/tmux
  args:
  - new-session
  - -A
  - -D
  - -s
  - main
  ```
