### ISSUE TITLE
No italics (and blink)

### ISSUE THREAD

**Issue by taitep** [alacritty/alacritty#7312]
I just ran a program that acts as a terminal styling tester. I noticed that the blink and italics modes did not work. Why not?

### System

OS: Manjaro Linux
Version: alacritty 0.12.3

### Logs

`alacritty -vv` output:
```
Created log file at "/tmp/Alacritty-18234.log"
[0.000003838s] [INFO ] [alacritty] Welcome to Alacritty
[0.000049710s] [INFO ] [alacritty] Version 0.12.3 (5efb0690)
[0.000057246s] [INFO ] [alacritty] Running on X11
[0.000528260s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/taitep/.config/alacritty/alacritty.yml"
                                     "/home/taitep/.config/alacritty/catppuccin/catppuccin-macchiato.yml"
[0.012442136s] [INFO ] [alacritty] Using GLX 1.4
[0.015305680s] [INFO ] [alacritty] Window scale factor: 1.0833333333333333
[0.026027697s] [DEBUG] [alacritty] Loading "FiraMono Nerd Font Mono" font
[0.043200038s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.046676965s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.050319418s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.053437389s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.187069524s] [INFO ] [alacritty] Running on NVIDIA GeForce GTX 1660/PCIe/SSE2
[0.187089379s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.206825384s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.210234679s] [INFO ] [alacritty] Cell size: 10 x 20
[0.210250684s] [INFO ] [alacritty] Padding: 0 x 0
[0.210255124s] [INFO ] [alacritty] Width: 800, Height: 600
[0.230633770s] [INFO ] [alacritty] PTY dimensions: 30 x 80
[0.232532803s] [INFO ] [alacritty] Initialisation complete
[0.274355853s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[40.141480557s] [DEBUG] [alacritty_terminal] Term got unhandled attr: BlinkSlow
[40.148267291s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
```

The `font` part of `alacritty.yml`:
```
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: FiraMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    #style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: FiraMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: FiraMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: FiraMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 11.0
```
