### ISSUE TITLE
Some characters have incorrect width and uncertain font size (Windows)

### ISSUE THREAD

**Issue by O5-7** [alacritty/alacritty#7335]
### Configuration:
```
font:
  size: 12
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: 新宋体
```

### font size

in powershell the `font size` is 16 , and the display font size is 16 x 16

![image](https://github.com/alacritty/alacritty/assets/40710644/00151abd-65e2-4ad4-b203-4db2ad26da8d)

but in alacritty the `font size` is 12, but the display font size is 16 x 18

![image](https://github.com/alacritty/alacritty/assets/40710644/2abf8d0f-7bcb-4fa6-ac91-cb24b6483fe0)

### up: powershell ==== left: alacritty

![image](https://github.com/alacritty/alacritty/assets/40710644/5185b64e-253b-4d46-ae43-99121ea548da)

℃`U+2103` , ①`U+2460` , ⅳ`U+2173` and many other chars have same situation

---

### System

OS: Windows
Version: 0.12.2 (9b9982d)

### Logs

```
Crashes: STDERR, STDOUT
[INFO ] [alacritty] Window scale factor: 1
[0.062597200s] [INFO ] [alacritty] Using WGL
[0.074970300s] [DEBUG] [alacritty] Loading "新宋体" font
[0.078021400s] [INFO ] [alacritty] Running on NVIDIA GeForce RTX 2070/PCIe/SSE2
[0.078185000s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.119164600s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.145041600s] [INFO ] [alacritty] Cell size: 8 x 18
[0.145341800s] [INFO ] [alacritty] Padding: 0 x 0
[0.145451500s] [INFO ] [alacritty] Width: 800, Height: 600
[0.161267600s] [INFO ] [alacritty] PTY dimensions: 33 x 100
[0.169645300s] [INFO ] [alacritty] Initialisation complete
[0.170508000s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.237200700s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='l', params=[25], intermediates=[]
```

Keyboard and bindings: Default
