### ISSUE TITLE
"Alt + backtick" on macOS defaults to dead key shortcut

### ISSUE THREAD

**Issue by Kentokamoto** [alacritty/alacritty#7342]
On macOS, pressing and holding the Option key plus ["`", "e", "u", "i", "n"] allows for quick access to shortcuts to some letter types with accents displayed on top. More information can be found [here](https://support.apple.com/guide/mac-help/enter-characters-with-accent-marks-on-mac-mh27474/mac)

I've tried adding different keybindings in the `config.yml` file that disables these and have them default to the  `\x1b<char>` combination instead but the key that is registered is still the  dead key counterpart. This is even with the `option_as_alt` config enabled to "both"

All other "Alt + \<key>" combinations are working fine.

#### Current Behavior
* Alt + \` -> ` Deadkey shortcut
* Alt + e -> ´ Deadkey shortcut
* Alt + u -> ¨ Deadkey shortcut
* Alt + i  -> ˆ Deadkey shortcut
* Alt + n -> ˜ Deadkey shortcut

#### Expected Behavior
* Alt + \` -> \<ESC>`
* Alt + e -> \<ESC>e
* Alt + u -> \<ESC>u
* Alt + i  -> \<ESC>i
* Alt + n -> \<ESC>n

### System

OS: macOS (Sonoma 14.0)
Version: `alacritty --version` output **0.12.2 (1)**
Keyboard Layout: ANSI

### Logs

Config File:
```
# Window decorations
#
# Values for `decorations`:
#     - full: Borders and title bar
#     - none: Neither borders nor title bar
#
# Values for `decorations` (macOS only):
#     - transparent: Title bar, transparent background and title bar buttons
#     - buttonless: Title bar, transparent background and no title bar buttons
decorations: full


# Startup Mode (changes require restart)
#
# Values for `startup_mode`:
#   - Windowed
#   - Maximized
#   - Fullscreen
#
# Values for `startup_mode` (macOS only):
#   - SimpleFullscreen
startup_mode: Windowed

# Make `Option` key behave as `Alt` (macOS only):
#   - OnlyLeft
#   - OnlyRight
#   - Both
#   - None (default)
option_as_alt: Both

#scrolling:
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history: 10000


# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: Hack Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Hack Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Hack Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Italic
  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Hack Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 12.0


# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: "0x24283b"
    foreground: "0xc0caf5"

  # Normal colors
  normal:
    black: "0x1d202f"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xa9b1d6"

  # Bright colors
  bright:
    black: "0x414868"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xc0caf5"

  indexed_colors:
    - { index: 16, color: "0xff9e64" }
    - { index: 17, color: "0xdb4b4b" }


key_bindings:
  - { key: A, mods: Alt, chars: "\x1ba" }
  - { key: B, mods: Alt, chars: "\x1bb" }
  - { key: C, mods: Alt, chars: "\x1bc" }
  - { key: D, mods: Alt, chars: "\x1bd" }
  - { key: E, mods: Alt, chars: "\x1be" }
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: G, mods: Alt, chars: "\x1bg" }
  - { key: H, mods: Alt, chars: "\x1bh" }
  - { key: I, mods: Alt, chars: "\x1bi" }
  - { key: J, mods: Alt, chars: "\x1bj" }
  - { key: K, mods: Alt, chars: "\x1bk" }
  - { key: L, mods: Alt, chars: "\x1bl" }
  - { key: M, mods: Alt, chars: "\x1bm" }
  - { key: N, mods: Alt, chars: "\x1bn" }
  - { key: O, mods: Alt, chars: "\x1bo" }
  - { key: P, mods: Alt, chars: "\x1bp" }
  - { key: Q, mods: Alt, chars: "\x1bq" }
  - { key: R, mods: Alt, chars: "\x1br" }
  - { key: S, mods: Alt, chars: "\x1bs" }
  - { key: T, mods: Alt, chars: "\x1bt" }
  - { key: U, mods: Alt, chars: "\x1bu" }
  - { key: V, mods: Alt, chars: "\x1bv" }
  - { key: W, mods: Alt, chars: "\x1bw" }
  - { key: X, mods: Alt, chars: "\x1bx" }
  - { key: Y, mods: Alt, chars: "\x1by" }
  - { key: Z, mods: Alt, chars: "\x1bz" }
  - { key: A, mods: Alt|Shift, chars: "\x1bA" }
  - { key: B, mods: Alt|Shift, chars: "\x1bB" }
  - { key: C, mods: Alt|Shift, chars: "\x1bC" }
  - { key: D, mods: Alt|Shift, chars: "\x1bD" }
  - { key: E, mods: Alt|Shift, chars: "\x1bE" }
  - { key: F, mods: Alt|Shift, chars: "\x1bF" }
  - { key: G, mods: Alt|Shift, chars: "\x1bG" }
  - { key: H, mods: Alt|Shift, chars: "\x1bH" }
  - { key: I, mods: Alt|Shift, chars: "\x1bI" }
  - { key: J, mods: Alt|Shift, chars: "\x1bJ" }
  - { key: K, mods: Alt|Shift, chars: "\x1bK" }
  - { key: L, mods: Alt|Shift, chars: "\x1bL" }
  - { key: M, mods: Alt|Shift, chars: "\x1bM" }
  - { key: N, mods: Alt|Shift, chars: "\x1bN" }
  - { key: O, mods: Alt|Shift, chars: "\x1bO" }
  - { key: P, mods: Alt|Shift, chars: "\x1bP" }
  - { key: Q, mods: Alt|Shift, chars: "\x1bQ" }
  - { key: R, mods: Alt|Shift, chars: "\x1bR" }
  - { key: S, mods: Alt|Shift, chars: "\x1bS" }
  - { key: T, mods: Alt|Shift, chars: "\x1bT" }
  - { key: U, mods: Alt|Shift, chars: "\x1bU" }
  - { key: V, mods: Alt|Shift, chars: "\x1bV" }
  - { key: W, mods: Alt|Shift, chars: "\x1bW" }
  - { key: X, mods: Alt|Shift, chars: "\x1bX" }
  - { key: Y, mods: Alt|Shift, chars: "\x1bY" }
  - { key: Z, mods: Alt|Shift, chars: "\x1bZ" }
  - { key: Key1, mods: Alt, chars: "\x1b1" }
  - { key: Key2, mods: Alt, chars: "\x1b2" }
  - { key: Key3, mods: Alt, chars: "\x1b3" }
  - { key: Key4, mods: Alt, chars: "\x1b4" }
  - { key: Key5, mods: Alt, chars: "\x1b5" }
  - { key: Key6, mods: Alt, chars: "\x1b6" }
  - { key: Key7, mods: Alt, chars: "\x1b7" }
  - { key: Key8, mods: Alt, chars: "\x1b8" }
  - { key: Key9, mods: Alt, chars: "\x1b9" }
  - { key: Key0, mods: Alt, chars: "\x1b0" }
  - { key: Space, mods: Control, chars: "\x00" } # Ctrl + Space
  - { key: Grave, mods: Alt, chars: "\x1b`" } # Alt + `
  - { key: Grave, mods: Alt|Shift, chars: "\x1b~" } # Alt + ~
  - { key: Period, mods: Alt, chars: "\x1b." } # Alt + .
  - { key: Key8, mods: Alt|Shift, chars: "\x1b*" } # Alt + *
  - { key: Key3, mods: Alt|Shift, chars: "\x1b#" } # Alt + #
  - { key: Period, mods: Alt|Shift, chars: "\x1b>" } # Alt + >
  - { key: Comma, mods: Alt|Shift, chars: "\x1b<" } # Alt + <
  - { key: Minus, mods: Alt|Shift, chars: "\x1b_" } # Alt + _
  - { key: Key5, mods: Alt|Shift, chars: "\x1b%" } # Alt + %
  - { key: Key6, mods: Alt|Shift, chars: "\x1b^" } # Alt + ^
  - { key: Backslash, mods: Alt, chars: "\x1b\\" } # Alt + \
  - { key: Backslash, mods: Alt|Shift, chars: "\x1b|" } # Alt + |```


```

**Comment by Kentokamoto** [comment]
Seems to be fixed in Version 0.13.0 (1). I'm going to close the comment.

**Comment by jzaleski** [comment]
@Kentokamoto I am still seeing this issue on 13.1 -- specifically Alt+E is the one I'm looking to go to work and it's printing a backtick and hanging.

**Comment by Kentokamoto** [comment]
@jzaleski, I just updated to version 13.1 and was unable to repro the issue. Have you converted your config to using toml since that seems to be a big switch between 12 and 13.  Here's a look at my config if you'd like to compare:

```toml
[window]
decorations = "full"
option_as_alt = "Both"
startup_mode = "Windowed"
opacity = 0.9
blur = true

[scrolling]
history = 10000

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x1d202f"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xc0caf5"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B`"
key = "`"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B~"
key = "`"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B*"
key = "Key8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B#"
key = "Key3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = "Period"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B<"
key = "Comma"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B_"
key = "Minus"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B%"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B^"
key = "Key6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Alt|Shift"

```
