### ISSUE TITLE
tmux: can't change windows/tabs with cmd+number

### ISSUE THREAD

**Issue by vojtechmares** [alacritty/alacritty#7353]
Hello, I am new to Alacritty and tmux, I was using iTerm2 before, but I was having some issues, so I migrated.

I learned that Alacritty does not support tabs by design, therefore I started learning tmux. It is super-powerful tool, yet you have to know what you are doing. I am not comfortable with it yet.

My issue is, that, when I want to switch from one tmux-window to another with Cmd+num, I can't. It writes the numbers to the terminal prompt and does nothing. I can use mouse to switch them, but that goes against "working from terminal without mouse" philosophy.

I tried googling solutions over several past days, with no luck tho. I was able to change the theme of Alacritty and tmux, change some behaviour, but I had no success with the windows/tabs. Please help.

### Tmux configuration
```conf
# ~/.tmux.conf
# Set prefix key to c-f instead of default c-b
unbind C-b
set -g prefix C-f
bind C-f send-prefix

set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin"

set-option -g default-shell /bin/zsh

# toogle last window by hitting again C-f
bind-key C-f last-window

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Split horiziontal and vertical splits, instead of % and ". We also open them
# in the same directory.  Because we use widescreens nowadays, opening a
# vertical split that takes half of the screen is not worth. For vertical we
# only open 100 lines width, for horizontal it's 20 columns.
bind-key v split-window -h -l 100 -c '#{pane_current_path}'
bind-key s split-window -v -l 30 -c '#{pane_current_path}'

# if multiple clients are attached to the same window, maximize it to the
# bigger one
set-window-option -g aggressive-resize

# Disable confirm before killing
bind-key x kill-pane

# Titles
set -g set-titles on
set -g set-titles-string "#T"

# Faster command sequence
set -s escape-time 0

# Have a very large history
set -g history-limit 1000000

# Mouse mode on
set -g mouse on

# Start windows and pane numbering with index 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1 

# re-number windows when one is closed
set -g renumber-windows on

# Select panes
# NOTE(arslan): See to prevent cycling https://github.com/tmux/tmux/issues/1158
bind-key j select-pane -D
bind-key k select-pane -U
bind-key h select-pane -L
bind-key l select-pane -R

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Enter copy mode with /
bind-key / copy-mode \; send-key ?

# emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs

# focus events enabled for terminals that support them
set -g focus-events on

# Sync panes (Send input to all panes in the window). When enabled, pane
# borders become red as an indication.
bind C-s if -F '#{pane_synchronized}' \
        'setw synchronize-panes off; \
         setw pane-active-border-style fg=colour63,bg=default; \
         setw pane-border-format       " #P "' \
        'setw synchronize-panes on; \
         setw pane-active-border-style fg=red; \
         setw pane-border-format       " #P - Pane Synchronization ON "'

# Change windows
bind-key 1 select-window -t :1
bind-key 2 select-window -t :2
bind-key 3 select-window -t :3
bind-key 4 select-window -t :4
bind-key 5 select-window -t :5
bind-key 6 select-window -t :6
bind-key 7 select-window -t :7
bind-key 8 select-window -t :8
bind-key 9 select-window -t :9

# catppuccin <3
set -g @catppuccin_flavour 'mocha' # latte, frappe, macchiato, mocha

set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application session user host date_time"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M"

# List of plugins
# see this https://github.com/tmux-plugins/tpm to installation
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-battery'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

### Alacritty config

```yaml
# ~/.config/alacritty/alacritty.yml

env:
  TERM: xterm-256color

window:
  opacity: 1.0
  dynamic_title: true
  padding:
    x: 12
    y: 12

live_config_reload: true

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: '|:"'' {}()[]<>'
  save_to_clipboard: true

draw_bold_text_with_bright_colors: true

cursor:
  style: Block
  unfocused_hollow: true

font:
  normal:
    family: "FiraMono Nerd Font"
    style: Regular
  bold:
    family: "FiraMono Nerd Font"
    style: Bold
  italic:
    family: "FiraMono Nerd Font"
    style: Italic
  bold_italic:
    family: "FiraMono Nerd Font"
    style: Bold Italic
  size: 18.0

shell:
#  program: /bin/zsh
#  args:
#    - --login
  program: /opt/homebrew/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - main

import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml

key_bindings:
  ## Alacritty ##
  # Quit.
  - {key: Q, mods: Command, action: Quit}

  # Copy & paste.
  - {key: V, mods: Command, action: Paste}
  - {key: C, mods: Command, action: Copy}

  # Font size.
  - {key: Key0, mods: Command, action: ResetFontSize}
  - {key: Equals, mods: Command, action: IncreaseFontSize}
  - {key: Minus, mods: Command, action: DecreaseFontSize}

  # Toggle fullscreen.
  - {key: F, mods: Command|Control, action: ToggleFullscreen}

  # Clear log.
#  - {key: K, mods: Command, action: ClearLogNotice}

  ## Tmux ##
  # Move one tab right.
  - { key: RBracket, mods: Command|Shift, chars: "\x01\x6e" }

  # Move one tab left.
  - { key: LBracket, mods: Command|Shift, chars: "\x01\x70" }

  # Move to tab x.
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }

  - { key: D,     mods: Command,       chars: "\x06\x76" } 
  - { key: D,     mods: Command|Shift, chars: "\x06\x73" }
  - { key: W,     mods: Command,       chars: "\x06\x78" }
  - { key: H,     mods: Command,       chars: "\x06\x68" }
  - { key: J,     mods: Command,       chars: "\x06\x6a" }
  - { key: K,     mods: Command,       chars: "\x06\x6b" }
  - { key: L,     mods: Command,       chars: "\x06\x6c" }
  - { key: T,     mods: Command,       chars: "\x06\x63" }

  - { key: Left,  mods: Command,       chars: "\x06\x48" }
  - { key: Down,  mods: Command,       chars: "\x06\x4a" }
  - { key: Up,    mods: Command,       chars: "\x06\x4b" }
  - { key: Right, mods: Command,       chars: "\x06\x4c" }

  - {key: Return, mods: Command|Shift, chars: "\x06\x7a"}

  # Cleanup
  - {key: B, mods: Command, action: None}
  - {key: F, mods: Command, action: None}

hints:
  enabled:
    - regex:
        "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
        [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      hyperlinks: true
      command: xdg-open
      post_processing: true
      mouse:
        enabled: true
        mods: None
      binding:
        key: U
        mods: Control|Shift
```

### System

OS: macOS Sonoma 14.0
Version: `alacritty 0.12.3 (5efb069)`

### Logs

```shell
$ alacritty -vv
Created log file at "/var/folders/8l/0tggr4b15f169tpxwcwthbl80000gn/T/Alacritty-17417.log"
[0.000004375s] [INFO ] [alacritty] Welcome to Alacritty
[0.000406959s] [INFO ] [alacritty] Version 0.12.3 (5efb069)
[0.001147584s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/Vojta_1/.config/alacritty/alacritty.yml"
                                     "/Users/Vojta_1/.config/alacritty/catppuccin/catppuccin-mocha.yml"
[0.001346584s] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[0.020256750s] [INFO ] [alacritty] Using Apple CGL
[0.051640250s] [INFO ] [alacritty] Window scale factor: 2
[0.052636334s] [DEBUG] [alacritty] Loading "FiraMono Nerd Font" font
[0.077304500s] [INFO ] [alacritty] Running on Apple M1 Pro
[0.077337459s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.080724959s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.084993334s] [INFO ] [alacritty] Cell size: 21 x 44
[0.085015042s] [INFO ] [alacritty] Padding: 24 x 24
[0.085024959s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.095928792s] [INFO ] [alacritty] PTY dimensions: 26 x 73
[0.098055209s] [INFO ] [alacritty] Initialisation complete
[0.117859417s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.470393542s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='q', params=[0], intermediates=[62]
[0.489426792s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='h', params=[7727], intermediates=[63]
[3.856175292s] [DEBUG] [alacritty_terminal] New num_cols is 141 and num_lines is 40
[3.864620667s] [INFO ] [alacritty] Padding: 24 x 24
[3.864691917s] [INFO ] [alacritty] Width: 3024, Height: 1832
```

```shell
$ alacritty --print-events
# the logs are being spammed a lot, therefore I trimmed them for last few lines
# ...
[20.056028583s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1226226, tv_nsec: 157198041 }, requested_resume: Some(Instant { tv_sec: 1226226, tv_nsec: 159411917 }) })
[20.056040625s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5185345584))), payload: Terminal(Wakeup) })
[20.056047875s] [INFO ] [alacritty] winit event: MainEventsCleared
[20.056053833s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[20.056091000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1226226, tv_nsec: 157247541 }, requested_resume: Some(Instant { tv_sec: 1226226, tv_nsec: 159411917 }) })
[20.056103750s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5185345584))), payload: Terminal(Wakeup) })
[20.056110708s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5185345584))), payload: Terminal(Wakeup) })
[20.056117292s] [INFO ] [alacritty] winit event: MainEventsCleared
[20.056123458s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[20.056151792s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1226226, tv_nsec: 157317208 }, requested_resume: Some(Instant { tv_sec: 1226226, tv_nsec: 159411917 }) })
[20.056166333s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5185345584))), payload: Terminal(Wakeup) })
[20.056175250s] [INFO ] [alacritty] winit event: MainEventsCleared
[20.056183042s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[20.056199667s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1226226, tv_nsec: 157378416 }, requested_resume: Some(Instant { tv_sec: 1226226, tv_nsec: 159411917 }) })
[20.059166750s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5185345584))), payload: Terminal(Wakeup) })
[20.059197333s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5185345584))), payload: Terminal(Wakeup) })
[20.059205167s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5185345584)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 8, state: Pressed, virtual_keycode: Some(C), modifiers: CTRL }, is_synthetic: false } }
[20.059218417s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5185345584)), event: ReceivedCharacter('\u{3}') }
[20.059226292s] [INFO ] [alacritty] winit event: MainEventsCleared
[20.059232917s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[20.059255458s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1226226, tv_nsec: 160436458 }, requested_resume: None })
[20.059266042s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5185345584))), payload: Frame })
[20.059273208s] [INFO ] [alacritty] winit event: MainEventsCleared
[20.059279542s] [INFO ] [alacritty] winit event: RedrawEventsCleared
```
