### ISSUE TITLE
alacritty ignoring toml on macOS

### ISSUE THREAD

**Issue by Alt-iOS** [alacritty/alacritty#7368]
I had an alacritty.toml in ~/.config/alacritty/ but it never changed anything, so I run alacritty -v and it would say, no config file, loading defaults. After that I tried with the .yml version and that one was not ignored.  Just in case its useful, here are my TOML and YML versions 

```toml
[font]
normal.family = "JetBrainsMonoNF-Bold"
bold.family = "JetBrainsMonoNF-ExtraBold"
italic.family = "JetBrainsMonoNF-BoldItalic"
bold.italic.family = "JetBrainsMonoNF-ExtraBoldItalic"

size = 15.0
```

```yml
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Bold
  bold:
    family: JetBrainsMono Nerd Font
    style: ExtraBold
  italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  # Point size of the font
  size: 15
```
### System

OS: macOS
Version: Version 0.12.3 (5efb069)
