### ISSUE TITLE
Issues with font in mac OS sonoma 14 

### ISSUE THREAD

**Issue by asmit203** [alacritty/alacritty#7379]
I have downloaded the fonts that i want to apply in alacritty but when mentioning in the config file of alacritty they are not recognised and it can't load the font.

the config file
```yaml
font:
  normal:
    family: JetBrains Mono Nerd Font
    style: Medium
  bold:
    family: JetBrains Mono Nerd Font
    style: Bold
  italic:
    family: JetBrains Mono Nerd Font
    style: MediumItalic
  bold_italic:
    family: JetBrains Mono Nerd Font
    style: BoldItalic
  size: 13
  draw_bold_text_with_bright_colors: true
```
### System

OS: macOS
Version: alacritty 0.12.3 

### Logs

[0.053249333s] [WARN ] [crossfont] Unable to load specified font JetBrains Mono Nerd Font, falling back to Menlo
[0.054292916s] [ERROR] [alacritty] font FontDesc { name: "JetBrains Mono Nerd Font", style: Specific("Medium") } not found
[0.071721125s] [WARN ] [crossfont] Unable to load specified font JetBrains Mono Nerd Font, falling back to Menlo
[0.073004500s] [WARN ] [crossfont] Unable to load specified font JetBrains Mono Nerd Font, falling back to Menlo
[0.073446833s] [WARN ] [crossfont] Unable to load specified font JetBrains Mono Nerd Font, falling back to Menlo
