### ISSUE TITLE
Can't not start with tmux in macos

### ISSUE THREAD

**Issue by boringplay** [alacritty/alacritty#7440]
Can't not start with tmux in macos. My config:
```yml
shell:
  program: /usr/local/bin/tmux
  args:
   - new-session
```

Whenever I launch Alacritty, it immediately stops after it opened.

### System

OS: macOS
Version: `alacritty 0.12.3 (5efb069)`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
What does `alacritty -e /usr/local/bin/tmux new-session` give you?

**Comment by boringplay** [comment]
It works. How should I modify the configuration?

**Comment by chrisduerr** [comment]
Please send your full config. Both of these are identical, so if one works and the other doesn't then you're doing something wrong.

**Comment by boringplay** [comment]
```yml
shell:
  program: /usr/local/bin/tmux
  args:
   - new-session

window:
  dimensions:
    columns: 100
    lines: 36

  position:
    x: 120
    y: 20

  padding:
    x: 12
    y: 16
  dynamic_padding: false
  startup_mode: Maximized
  decorations: full

font:
  normal:
    family: Monaco
  size: 14

selection:
  save_to_clipboard: true

key_bindings:
  # new

  # new pane/tab/window:
  - { key: D, mods: Command, chars: "\x02d" } # new vertical pane with default shell
  - { key: D, mods: Command | Shift, chars: "\x02\x44" } # new horizontal pane with default shell
  - { key: T, mods: Command, action: CreateNewWindow } # new tab
  - { key: N, mods: Command, action: SpawnNewInstance }

  # switch panes/tabs
  - { key: LBracket, mods: Command, chars: "\x02\x5b" } # previous panels
  - { key: RBracket, mods: Command, chars: "\x02\x5d" } # next panels

  # copy
  - { key: C, mods: Command, chars: "\x02c" } # copy with tmux
  - { key: Escape, mods: Command, chars: "\x02\x60" } # exit tmux copy-mode
  - { key: V, mods: Command, action: Paste }

  - { key: R, mods: Command, mode: ~Vi|~Search, chars: "\x0c" }
  - { key: R, mods: Command, mode: ~Vi|~Search, action: ClearHistory }

  - { key: Left, mods: Alt, chars: "\x1bb" } # Skip word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # Skip word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End
  - { key: Back, mods: Command, chars: "\x15" } # Delete line
  - { key: Back, mods: Alt, chars: "\x1b\x7f" } # Delete word

  # scroll
  - { key: Up, mods: Command, action: ScrollToTop }
  - { key: Down, mods: Command, action: ScrollToBottom }

  # search
  - { key: F, mods: Command, chars: "\x02f" } # new vertical pane with default shell

  # window size
  - { key: F, mods: Command | Shift, action: ToggleFullscreen }
  - { key: F, mods: Command | Control, action: ToggleMaximized }

  # font size
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: Key0, mods: Command, action: ResetFontSize }
```
