### ISSUE TITLE
alacritty.yml throws error when importing existing themes

### ISSUE THREAD

**Issue by burgues0** [alacritty/alacritty#7457]
So, I'm trying to import a theme by following https://github.com/alacritty/alacritty-theme README.md.

However, when I provide a valid path, the bottom of the Alacritty terminal throws the error in the logs below.

When I provide a file or path that doesn't exist, the error goes away!

The spaces in the file are as follows:

import:
2 spaces-1 space~/path

so:
import:
  - ~/path

### System

OS: Linux
Version: alacritty 0.12.3 (5efb0690)
Archlinux: Wayland, Hyprland

### Logs

> /tmp/Alacritty-6061.log

```
[2318.729835504s] [ERROR] [alacritty_config_derive] Unable to import config "/home/user/.config/alacritty/themes/alabaster.toml": Config error: did not find expected <document start> at line 5 column 1
```

> ls /home/user/.config/alacritty/themes/

```
alabaster.toml   hardhacker.toml       kanagawa_wave.toml
blood_moon.toml  hyper.toml            nightfox.toml
doom_one.toml    kanagawa_dragon.toml
```

> cat /home/user/.config/alacritty/alacritty.yml

```
import:
  - ~/.config/alacritty/themes/alabaster.toml

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
#env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  #TERM: alacritty

window:
  padding:
    x: 7
    y: 7

  opacity: 0.85

  class:
    instance: Alacritty
    general: Alacritty

  title: Alacritty
  dynamic_title: false

  scrolling:
    history: 10000
    multiplier: 3

  decorations_theme_variant: Dark
#...
```
