### ISSUE TITLE
[PSA] how to restore pre-0.13 colour scheme

### ISSUE THREAD

**Issue by cyqsimon** [alacritty/alacritty#7467]
I have no problem with the default changing or the justification for it. It's just as a long-time user I've gotten used to the old colours and it has become my personal preference. This PSA is for anyone who feels similar.

---

The change was made in #6933, so the colour values here are taken directly from the pre-change defaults:

```toml
[colors.bright]
black = "#666666"
red = "#d54e53"
green = "#b9ca4a"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#c397d8"
cyan = "#70c0b1"
white = "#eaeaea"

[colors.dim]
black = "#131415"
red = "#864343"
green = "#777c44"
yellow = "#9e824c"
blue = "#556a7d"
magenta = "#75617b"
cyan = "#5b7d78"
white = "#828482"

[colors.hints]
start = { foreground = "#1d1f21", background = "#e9ff5e" }
end = { foreground = "#e9ff5e", background = "#1d1f21" }

[colors.normal]
black = "#1d1f21"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

[colors.primary]
foreground = "#c5c8c6"
background = "#1d1f21"

[colors.search]
matches = { foreground = "#000000", background = "#ffffff" }
focused_match = { foreground = "#ffffff", background = "#000000" }
```

---

I don't think I missed anything, but in case I did, please point it out and I'll make an edit.
