### ISSUE TITLE
Warning Unused config key: path

### ISSUE THREAD

**Issue by fadri14** [alacritty/alacritty#7477]
### System
Arch Linux with sway
alacritty version : alacritty 0.13.0 (78fa4d6f)

### Logs

warning in the terminal: Unused config key: path

log:
`
[0.000183146s] [WARN ] [alacritty_config_derive] Unused config key: path
[0.000216556s] [WARN ] [alacritty_config_derive] Unused config key: path
[0.000222672s] [WARN ] [alacritty_config_derive] Unused config key: path
[0.000227844s] [WARN ] [alacritty_config_derive] Unused config key: path
[0.000239505s] [WARN ] [alacritty_config_derive] Unused config key: size
`

My config:
`
import = ["/home/adrien/.config/alacritty/github_light.toml"]

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10

[window.size]
columns = 80
lines = 24

[cursor]
style = "Underline"

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
path = "/home/adrien/.local/share/fonts/HackNerdFontMono-Bold.ttf"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
path = "/home/adrien/.local/share/fonts/HackNerdFontMono-BoldItalic.ttf"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
path = "/home/adrien/.local/share/fonts/HackNerdFontMono-Italic.ttf"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
path = "/home/adrien/.local/share/fonts/HackNerdFontMono-Regular.ttf"
style = "Regular"
`

**Comment by kchibisov** [comment]
it tells you pretty clear that `path` is unused because there's no such thing and never was. See your font configs.

**Comment by fadri14** [comment]
Hello. I would like to point out that the pathst are correct and that everything worked before converting to toml.

**Comment by kchibisov** [comment]
I'd like to point out that `path` was ignored and never warned about since we never warned about unused keys before and that I surely know every alacritty config option ever presented in it since 0.2.0 or something.

**Comment by fadri14** [comment]
I don't quite understand what this means. If I remove all the configuration in relation to the fonts, it's clear that it's not the same font. So my fonts exist and work fine.

**Comment by kchibisov** [comment]
remove `path` not the all config.
```toml
[font.bold]
family = "Hack Nerd Font"
path = "/home/adrien/.local/share/fonts/HackNerdFontMono-Bold.ttf"
style = "Bold"
```

so it should be

```toml
[font.bold]
family = "Hack Nerd Font"
style = "Bold"
```

**Comment by fadri14** [comment]
I have always the same problem

**Comment by kchibisov** [comment]
You need to do that for every section you had `path`.

**Comment by kchibisov** [comment]
That's how your config should look

```toml
import = ["/home/adrien/.config/alacritty/github_light.toml"]

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 80
lines = 24

[cursor]
style = "Underline"

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
```

if I fix the unused keys and options which never worked in yaml.
