### ISSUE TITLE
parsing error: Yaml conversion error: unsupported unit type

### ISSUE THREAD

**Issue by Neo-29** [alacritty/alacritty#7482]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: `alacritty --version` output   alacritty 0.13.0 (78fa4d6f)
Linux/Wayland archlinux gnome 45.2

### Logs

```Created log file at "/tmp/Alacritty-5985.log"
[0.000004706s] [INFO ] [alacritty] Welcome to Alacritty
[0.000170810s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6f)
[0.000190624s] [INFO ] [alacritty] Running on Wayland
[0.000311016s] [WARN ] [alacritty] YAML config "/home/neo29/.config/alacritty/alacritty.yml" is deprecated, please migrate to TOML using `alacritty migrate`
[0.000772982s] [ERROR] [alacritty_config_derive] Unable to load config "/home/neo29/.config/alacritty/alacritty.yml": Yaml conversion error: unsupported unit type
[0.000822255s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/neo29/.config/alacritty/alacritty.yml"
[0.050096516s] [INFO ] [alacritty] Using EGL 1.5
[0.161335815s] [INFO ] [alacritty] Window scale factor: 1
[0.225710888s] [INFO ] [alacritty] Running on Mesa Intel(R) UHD Graphics 600 (GLK 2)
[0.225782772s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.1-arch1.1, shader_version 4.60
[0.225812905s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.284467365s] [INFO ] [alacritty] Cell size: 9 x 22
[0.284537199s] [INFO ] [alacritty] Padding: 0 x 0
[0.284555040s] [INFO ] [alacritty] Width: 800, Height: 600
[0.284627950s] [INFO ] [alacritty] PTY dimensions: 27 x 88
[0.312649713s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-5985.log"
Error: Custom { kind: NotFound, error: "Failed to spawn command 'rsion': No such file or directory (os error 2)" }```

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
it doesn't know what command `rsion` is. The unit type just failed conversion, see https://github.com/alacritty/alacritty/issues/7463 . You need to fixup your yaml first, I think.

**Comment by Neo-29** [comment]
> rsion

I don´t get it sorry too technical for me 
Can you be more specific

**Comment by kchibisov** [comment]
>Error: Custom { kind: NotFound, error: "Failed to spawn command 'rsion': No such file or directory (os error 2)" }```

Though we internally convert yaml.

I'd suggest to fixup unit type in your yaml file. If you can share your config I can fix it for you.

**Comment by Neo-29** [comment]
[alacritty (copie).txt](https://github.com/alacritty/alacritty/files/13788815/alacritty.copie.txt)

tks a lot @kchibisov

**Comment by kchibisov** [comment]
```toml
[window]
decorations = "None"
opacity = 0.85

[font]
size = 7

[cursor]
style = { blinking = "Always" }

[colors.primary]
background = "#20201d"
foreground = "#a6a28c"

[colors.cursor]
text   = "#20201d"
cursor = "#a6a28c"

[colors.normal]
black   = "#20201d"
red     = "#d73737"
green   = "#60ac39"
yellow  = "#cfb017"
blue    = "#6684e1"
magenta = "#b854d4"
cyan    = "#1fad83"
white   = "#a6a28c"

[colors.bright]
black   =  "#7d7a68"
red     =  "#d73737"
green   =  "#60ac39"
yellow  =  "#cfb017"
blue    =  "#6684e1"
magenta =  "#b854d4"
cyan    =  "#1fad83"
white   =  "#fefbec"

```
