### ISSUE TITLE
After running "alacritty migrate" command  the next launch of alacritty reports several warnings about Unused config key

### ISSUE THREAD

**Issue by rsramkis** [alacritty/alacritty#7488]
Hi,

I ran the "alacritty migrate" command to transition my alacritty.yml to alacritty.toml. After this I am getting several warning about "Unused config key" like:

```
[0.000457840s] [WARN ] [alacritty_config_derive] Unused config key: hints
[0.000510321s] [WARN ] [alacritty_config_derive] Unused config key: columns
[0.000523543s] [WARN ] [alacritty_config_derive] Unused config key: gtk_theme_variant
[0.000536461s] [WARN ] [alacritty_config_derive] Unused config key: lines
[0.000550653s] [WARN ] [alacritty_config_derive] Unused config key: colors.draw_bold_text_with_bright_colors
[0.000560530s] [WARN ] [alacritty_config_derive] Unused config key: keyboard.bindings
[0.000570580s] [WARN ] [alacritty_config_derive] Unused config key: mouse.bindings
```

I filed this bug to get feedback on which **setting in my alacritty.toml are no longer valid.**

### Troubleshoot:

1. I did go through the alacritty change logs and renamed or removed the configuration settings that were mentioned.

2. I tried commenting out the configuration settings like 'lines', ' 'columns', "colors.draw_bold_text_with_bright_colors" and the specific warnings to these messages disappeared.

### System

OS: EndeavourOS Linux x86_64 Arch Linux
Version: 0.13.0 (78fa4d6f)
Linux/Wayland, Gnome 45.2, Mutter

### Logs

**Font/Terminal size: `alacritty -vv`:**
```
❯ alacritty -vv
Created log file at "/tmp/Alacritty-18317.log"
[0.000003055s] [INFO ] [alacritty] Welcome to Alacritty
[0.000066407s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6f)
[0.000080985s] [INFO ] [alacritty] Running on Wayland
[0.000457840s] [WARN ] [alacritty_config_derive] Unused config key: hints
[0.000510321s] [WARN ] [alacritty_config_derive] Unused config key: columns
[0.000523543s] [WARN ] [alacritty_config_derive] Unused config key: gtk_theme_variant
[0.000536461s] [WARN ] [alacritty_config_derive] Unused config key: lines
[0.000550653s] [WARN ] [alacritty_config_derive] Unused config key: colors.draw_bold_text_with_bright_colors
[0.000560530s] [WARN ] [alacritty_config_derive] Unused config key: keyboard.bindings
[0.000570580s] [WARN ] [alacritty_config_derive] Unused config key: mouse.bindings
[0.000594801s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/rsruser/.config/alacritty/alacritty.toml"
[0.028118523s] [INFO ] [alacritty] Using EGL 1.5
[0.028186193s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2 | GLES3)
                                     srgb_capable: true
[0.057189842s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.062293735s] [INFO ] [alacritty] Window scale factor: 1
[0.063974177s] [DEBUG] [alacritty] Loading "JetBrainsMono Nerd Font" font
[0.065463325s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.068582165s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.071083150s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.073305959s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.077331312s] [INFO ] [alacritty] Running on Mesa Intel(R) HD Graphics 5500 (BDW GT2)
[0.077358085s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.1-arch1.1, shader_version 4.60
[0.077380804s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.087434191s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.087533942s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.093871153s] [INFO ] [alacritty] Cell size: 9 x 21
[0.093893521s] [INFO ] [alacritty] Padding: 4 x 6
[0.093911906s] [INFO ] [alacritty] Width: 800, Height: 600
[0.093964078s] [INFO ] [alacritty] PTY dimensions: 28 x 88
[0.096756559s] [INFO ] [alacritty] Initialisation complete
[0.101864909s] [DEBUG] [alacritty_terminal] New num_cols is 88 and num_lines is 26
[0.108781787s] [INFO ] [alacritty] Font size changed to 16.0 px
[0.108818674s] [INFO ] [alacritty] Cell size: 9 x 21
[0.129502999s] [INFO ] [alacritty] Padding: 4 x 6
[0.129536803s] [INFO ] [alacritty] Width: 800, Height: 600
[0.134817317s] [DEBUG] [alacritty_terminal] Ignoring unknown mode 7727 in set_private_mode
[41.395940802s] [DEBUG] [alacritty_terminal] New num_cols is 88 and num_lines is 28
[41.398897500s] [INFO ] [alacritty] Padding: 4 x 6
[41.398971722s] [INFO ] [alacritty] Width: 800, Height: 600
```

**Alacritty.toml:**
```
"colors.draw_bold_text_with_bright_colors" = true
live_config_reload = true
working_directory = "None"

[["keyboard.bindings"]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[["keyboard.bindings"]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[["keyboard.bindings"]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[["keyboard.bindings"]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[["keyboard.bindings"]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[["keyboard.bindings"]]
action = "ToggleFullscreen"
key = "F11"
mods = "Control"

[["keyboard.bindings"]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"

[["keyboard.bindings"]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[["mouse.bindings"]]
action = "Copy"
mouse = "Middle"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors.bright]
black = "#575b70"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.cursor]
cursor = "#d8dee9"
text = "#191919"

[colors.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.selection]
background = "#d8dee9"
text = "#191919"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "alacritty"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = -1
y = -1

[mouse]
hide_when_typing = true

[mouse.hints]
modifiers = "None"

[mouse.hints.launcher]
args = []
program = "xdg-open"

[scrolling]
history = 8000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-l", "-c", "tmux"]
program = "/usr/bin/zsh"

[window]
columns = 600
lines = 400
decorations = "full"
dynamic_padding = true
dynamic_title = true
gtk_theme_variant = "dark"
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
```

**Comment by kchibisov** [comment]
```toml
live_config_reload = true
working_directory = "None"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[mouse.bindings]]
action = "Copy"
mouse = "Middle"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors.bright]
black = "#575b70"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.cursor]
cursor = "#d8dee9"
text = "#191919"

[colors.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.selection]
background = "#d8dee9"
text = "#191919"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "alacritty"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = -1
y = -1

[mouse]
hide_when_typing = true


[scrolling]
history = 8000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-l", "-c", "tmux"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

```
