### ISSUE TITLE
alacritty migrate emits error 

### ISSUE THREAD

**Issue by i3d** [alacritty/alacritty#7496]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS

Version: `alacritty --version` output
0.13.0

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

nothing works in this case.

Just cargo build the latest alacritty and asked me to migrate to TOML config, ran and got this.

`alacritty migrate`

```
~/.config/alacritty/alacritty.yml": parsing error: Yaml conversion error: unsupported unit type
```

since there is no line number information and no input information, I don't really know what exact this error is coming from. none of the debug command above works... :(

Here is the original config

```
window:
  dimensions:
    columns: 200
    lines: 35
  padding:
    x: 2
    y: 2
  decorations: none
scrolling:
  history: 100000
  multiplier: 3
window.opacity : 0.97
window.dynamic_title: true

url:
  #launcher: open
selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true
live_config_reload: true

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold:
    family:  CartographCF Nerd Font
    style: Bold
  italic:
    family:  CartographCF Nerd Font
    style: Italic
  size: 34
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 1
colors:
  primary:
    background: "#101010"
    foreground: "#4B4C4B"
  normal:
    black: "#141414"
    red: "#575757"
    green: "#81B32C"
    yellow: "#B39700"
    blue: "#848484"
    magenta: "#412a4D"
    cyan: "#7f847f"
    white: "#7D7D7D"
  bright:
    black: "#333333"
    red: "#666666"
    green: "#81B32C"
    yellow: "#B39700"
    blue: "#FAFAFA"
    magenta: "#412A4D"
    cyan: "#9F9F9F"
    white: "#E6E6E6"
  selection:
    text: "#E6E6E6"
    background: "#1A1A1A"
    white: "#FAFAFA"
  cursor:
    cursor: "#404040"
    text: "#404040"
cursor:
  style: Block
  unfocused_hollow: true
```
