### ISSUE TITLE
Failed to spawn command '/bin/zsh' 

### ISSUE THREAD

**Issue by kiran94** [alacritty/alacritty#7498]
After upgrading to 0.13.0 and migrating to the `toml` configuration, I was no longer able to open `alacritty` with the error below.

### System

OS: Linux
Version: `alacritty 0.13.0 (78fa4d6f)`
Linux/BSD: X11
ZSH Version: `zsh 5.9 (x86_64-pc-linux-gnu)`

### Logs

Crashes: 

```bash
Error: Custom { kind: NotFound, error: "Failed to spawn command '/bin/zsh': No such file or directory (os error 2)" }
```

Font/Terminal size: `alacritty -vv`:

```bash
❯ alacritty -vv
Created log file at "/tmp/Alacritty-52020.log"
[0.000003684s] [INFO ] [alacritty] Welcome to Alacritty
[0.000055110s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6f)
[0.000061428s] [INFO ] [alacritty] Running on X11
[0.000337966s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/kiran/.config/alacritty/alacritty.toml"
[0.003445405s] [INFO ] [alacritty] Using GLX 1.4
[0.034295183s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2)
                                     srgb_capable: false
[0.063100223s] [INFO ] [alacritty] Window scale factor: 2
[0.064821693s] [DEBUG] [alacritty] Loading "JetBrainsMono NF" font
[0.072661582s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.077238621s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.083183574s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.089134836s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.094116778s] [INFO ] [alacritty] Running on Mesa Intel(R) UHD Graphics (CML GT2)
[0.094136107s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.2-arch1.2, shader_version 4.60
[0.094139705s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.098879886s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.099070753s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.117353189s] [INFO ] [alacritty] Cell size: 18 x 39
[0.117394208s] [INFO ] [alacritty] Padding: 0 x 0
[0.117416063s] [INFO ] [alacritty] Width: 2520, Height: 1482
[0.134064830s] [INFO ] [alacritty] PTY dimensions: 38 x 140
[0.142615771s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-52020.log"
Error: Custom { kind: NotFound, error: "Failed to spawn command '/bin/zsh': No such file or directory (os error 2)" }

```

Keyboard and bindings: `alacritty --print-events`:

```bash
❯ alacritty --print-events
Created log file at "/tmp/Alacritty-52248.log"
[0.000003012s] [INFO ] [alacritty] Welcome to Alacritty
[0.000050205s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6f)
[0.000058985s] [INFO ] [alacritty] Running on X11
[0.000307432s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/kiran/.config/alacritty/alacritty.toml"
[0.001826408s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.001857861s] [INFO ] [alacritty] winit event: Resumed
[0.003072846s] [INFO ] [alacritty] Using GLX 1.4
[0.055278751s] [INFO ] [alacritty] Window scale factor: 2
[0.075247669s] [INFO ] [alacritty] Running on Mesa Intel(R) UHD Graphics (CML GT2)
[0.075267154s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.2-arch1.2, shader_version 4.60
[0.075270718s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.098797518s] [INFO ] [alacritty] Cell size: 18 x 39
[0.098837124s] [INFO ] [alacritty] Padding: 0 x 0
[0.098843952s] [INFO ] [alacritty] Width: 2520, Height: 1482
[0.103600176s] [INFO ] [alacritty] PTY dimensions: 38 x 140
[0.109307807s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(15))), event: Key(RawKeyEvent { physical_key: Code(Enter), state: Released }) }
[0.110954661s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(33554435)), event: Ime(Disabled) }
[0.110976358s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(33554435)), event: Destroyed }
[0.110990047s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(33554435)), event: RedrawRequested }
[0.110997831s] [INFO ] [alacritty] winit event: AboutToWait
[0.111003916s] [INFO ] [alacritty] winit event: LoopExiting
[0.111155990s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-52248.log"
Error: Custom { kind: NotFound, error: "Failed to spawn command '/bin/zsh': No such file or directory (os error 2)" }
```

The File does exist and is executable:

```bash
❯ ls -lha /bin/zsh
.rwxr-xr-x root root 1.1 MB Mon Jul 10 00:27:24 2023  /bin/zsh
```

If I run using my old `yaml` config, it still launches fine 

```bash
alacritty --config-file $HOME/.config/alacritty/alacritty.yml 
```

Making me think it's not the actual `/bin/zsh` at issue here.

I had this in my configuration 

```yaml
[shell]
args = ["--login"]
program = "/bin/zsh"
```

I've tried launching it with and without this section and it yields the same result. 

Let me know if I can provide any more information. Thanks

**Comment by chrisduerr** [comment]
Does `alacritty -e /bin/zsh` work?

**Comment by kiran94** [comment]
No it shows the same error: 

```bash
❯ alacritty -e /bin/zsh
Error: Custom { kind: NotFound, error: "Failed to spawn command '/bin/zsh': No such file or directory (os error 2)" }
```

**Comment by kchibisov** [comment]
I'd assume just running `/bin/zsh` actually works, does `alacritty -e zsh` works?

**Comment by kiran94** [comment]
Running `/bin/zsh` works as normal, it spawns a new shell. I also tried just `zsh` which also works. 

However running `alacritty -e zsh` yields a similar error: 

```bash
❯ alacritty -e zsh
Error: Custom { kind: NotFound, error: "Failed to spawn command 'zsh': No such file or directory (os error 2)" }
````

**Comment by chrisduerr** [comment]
Can you try `alacritty --config-file /dev/null -e zsh`?

**Comment by kiran94** [comment]
Both of these work:

```bash
alacritty --config-file /dev/null -e bash
alacritty --config-file /dev/null -e zsh
```

Looks like it just opens a new barebones Alacritty window with the respective shell

**Comment by kchibisov** [comment]
Could you share your entire config?

**Comment by kiran94** [comment]
Yes I will attach both pre and post migration

Just a note for the `working_directory` field here. You can see in the `yaml` file, it's commented out, I had to do this because for some reason `alacritty migrate` did not like this field. So I commented it out, generated the `toml` and then added it back to the newly generated config. Not sure if it's related but just mentioning it in case.

**alacritty.toml**

```toml
live_config_reload = true
working_directory = "~"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#81a2be"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#ffffff"
yellow = "#f0c674"

[colors.cursor]
cursor = "#ffffff"
text = "#1d1f21"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#70c0ba"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#373b41"
yellow = "#e6c547"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[cursor]
unfocused_hollow = true
vi_mode_style = "Beam"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"
TERMINAL = "alacritty"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = false
opacity = 0.98
startup_mode = "Windowed"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 0
y = 0

[window.position]
x = 10
y = 10
```

**alacritty.yml**

```yaml
# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Template
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

live_config_reload: true
env:
  TERM: xterm-256color
  TERMINAL: alacritty
shell:
  program: /bin/zsh
  args:
    - --login
# working_directory: ~
window:
  dimensions:
    columns: 140
    lines: 38
  position:
    x: 10
    y: 10
  padding:
    x: 0
    y: 0
  dynamic_padding: false
  decorations: full
  startup_mode: Windowed
  dynamic_title: false
  opacity: 0.98
scrolling:
  history: 10000
  multiplier: 3
font:
  size: 11.0
  normal:
    family: JetBrainsMono NF
    # family: CaskaydiaCove Nerd Font
    # family: JetBrainsMono Nerd Font
    # family: SpaceMono Nerd Font
    # style: Regular
  bold:
    family: JetBrainsMono NF
    # family: CaskaydiaCove Nerd Font
    # family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrainsMono NF
    # family: CaskaydiaCove Nerd Font
    # family: JetBrains Mono
    style: Italic
  bold_italic:
    family: JetBrainsMono NF
    # family: CaskaydiaCove Nerd Font
    # family: JetBrains Mono
    style: Bold Italic
  # Offset is the extra space around each character. `offset.y` can be thought
  # of as modifying the line spacing, and `offset.x` as modifying the letter
  # spacing.
  offset:
    x: 0
    y: 0
  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the
  # right, increasing `y` moves the glyph upward.
  glyph_offset:
    x: 0
    y: 0
cursor:
  style:
    shape: Block
    blinking: Off
  vi_mode_style: Beam
  unfocused_hollow: true
  #thickness: 0.15
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true
colors:

  # Colors (Tomorrow Night)
  primary:
    background: '#1d1f21'
    foreground: '#c5c8c6'
  cursor:
    text: '#1d1f21'
    cursor: '#ffffff'
  normal:
    black:   '#1d1f21'
    red:     '#cc6666'
    green:   '#b5bd68'
    yellow:  '#e6c547'
    blue:    '#81a2be'
    magenta: '#b294bb'
    cyan:    '#70c0ba'
    white:   '#373b41'
  bright:
    black:   '#666666'
    red:     '#ff3334'
    green:   '#9ec400'
    yellow:  '#f0c674'
    blue:    '#81a2be'
    magenta: '#b77ee0'
    cyan:    '#54ced6'
    white:   '#ffffff'

  # Campbell (Windows 10 default)
  # primary:
  #   background: '#0c0c0c'
  #   foreground: '#cccccc'
  # normal:
  #   black:      '#0c0c0c'
  #   red:        '#c50f1f'
  #   green:      '#13a10e'
  #   yellow:     '#c19c00'
  #   blue:       '#0037da'
  #   magenta:    '#881798'
  #   cyan:       '#3a96dd'
  #   white:      '#cccccc'
  # bright:
  #   black:      '#767676'
  #   red:        '#e74856'
  #   green:      '#16c60c'
  #   yellow:     '#f9f1a5'
  #   blue:       '#3b78ff'
  #   magenta:    '#b4009e'
  #   cyan:       '#61d6d6'
  #   white:      '#f2f2f2'

  # Solarized
  # primary:
  #   background: '#fdf6e3' # base3
  #   foreground: '#657b83' # base00
  # cursor:
  #   text:   '#fdf6e3' # base3
  #   cursor: '#657b83' # base00
  # normal:
  #   black:   '#073642' # base02
  #   red:     '#dc322f' # red
  #   green:   '#859900' # green
  #   yellow:  '#b58900' # yellow
  #   blue:    '#268bd2' # blue
  #   magenta: '#d33682' # magenta
  #   cyan:    '#2aa198' # cyan
  #   white:   '#eee8d5' # base2
  # bright:
  #   black:   '#002b36' # base03
  #   red:     '#cb4b16' # orange
  #   green:   '#586e75' # base01
  #   yellow:  '#657b83' # base00
  #   blue:    '#839496' # base0
  #   magenta: '#6c71c4' # violet
  #   cyan:    '#93a1a1' # base1
  #   white:   '#fdf6e3' # base3

# Mouse bindings
#
# Mouse bindings are specified as a list of objects, much like the key
# bindings further below.
#
# To trigger mouse bindings when an application running within Alacritty
# captures the mouse, the `Shift` modifier is automatically added as a
# requirement.
#
# Each mouse binding will specify a:
#
# - `mouse`:
#
#   - Middle
#   - Left
#   - Right
#   - Numeric identifier such as `5`
#
# - `action` (see key bindings)
#
# And optionally:
#
# - `mods` (see key bindings)
#mouse_bindings:
#  - { mouse: Middle, action: PasteSelection }

# Key bindings
#
# Key bindings are specified as a list of objects. For example, this is the
# default paste binding:
#
# `- { key: V, mods: Control|Shift, action: Paste }`
#
# Each key binding will specify a:
#
# - `key`: Identifier of the key pressed
#
#    - A-Z
#    - F1-F24
#    - Key0-Key9
#
#    A full list with available key codes can be found here:
#    https://docs.rs/glutin/*/glutin/event/enum.VirtualKeyCode.html#variants
#
#    Instead of using the name of the keys, the `key` field also supports using
#    the scancode of the desired key. Scancodes have to be specified as a
#    decimal number. This command will allow you to display the hex scancodes
#    for certain keys:
#
#       `showkey --scancodes`.
#
# Then exactly one of:
#
# - `chars`: Send a byte sequence to the running application
#
#    The `chars` field writes the specified string to the terminal. This makes
#    it possible to pass escape sequences. To find escape codes for bindings
#    like `PageUp` (`"\x1b[5~"`), you can run the command `showkey -a` outside
#    of tmux. Note that applications use terminfo to map escape sequences back
#    to keys. It is therefore required to update the terminfo when changing an
#    escape sequence.
#
# - `action`: Execute a predefined action
#
#   - ToggleViMode
#   - SearchForward
#       Start searching toward the right of the search origin.
#   - SearchBackward
#       Start searching toward the left of the search origin.
#   - Copy
#   - Paste
#   - IncreaseFontSize
#   - DecreaseFontSize
#   - ResetFontSize
#   - ScrollPageUp
#   - ScrollPageDown
#   - ScrollHalfPageUp
#   - ScrollHalfPageDown
#   - ScrollLineUp
#   - ScrollLineDown
#   - ScrollToTop
#   - ScrollToBottom
#   - ClearHistory
#       Remove the terminal's scrollback history.
#   - Hide
#       Hide the Alacritty window.
#   - Minimize
#       Minimize the Alacritty window.
#   - Quit
#       Quit Alacritty.
#   - ToggleFullscreen
#   - SpawnNewInstance
#       Spawn a new instance of Alacritty.
#   - ClearLogNotice
#       Clear Alacritty's UI warning and error notice.
#   - ClearSelection
#       Remove the active selection.
#   - ReceiveChar
#   - None
#
# - Vi mode exclusive actions:
#
#   - Open
#       Perform the action of the first matching hint under the vi mode cursor
#       with `mouse.enabled` set to `true`.
#   - ToggleNormalSelection
#   - ToggleLineSelection
#   - ToggleBlockSelection
#   - ToggleSemanticSelection
#       Toggle semantic selection based on `selection.semantic_escape_chars`.
#
# - Vi mode exclusive cursor motion actions:
#
#   - Up
#       One line up.
#   - Down
#       One line down.
#   - Left
#       One character left.
#   - Right
#       One character right.
#   - First
#       First column, or beginning of the line when already at the first column.
#   - Last
#       Last column, or beginning of the line when already at the last column.
#   - FirstOccupied
#       First non-empty cell in this terminal row, or first non-empty cell of
#       the line when already at the first cell of the row.
#   - High
#       Top of the screen.
#   - Middle
#       Center of the screen.
#   - Low
#       Bottom of the screen.
#   - SemanticLeft
#       Start of the previous semantically separated word.
#   - SemanticRight
#       Start of the next semantically separated word.
#   - SemanticLeftEnd
#       End of the previous semantically separated word.
#   - SemanticRightEnd
#       End of the next semantically separated word.
#   - WordLeft
#       Start of the previous whitespace separated word.
#   - WordRight
#       Start of the next whitespace separated word.
#   - WordLeftEnd
#       End of the previous whitespace separated word.
#   - WordRightEnd
#       End of the next whitespace separated word.
#   - Bracket
#       Character matching the bracket at the cursor's location.
#   - SearchNext
#       Beginning of the next match.
#   - SearchPrevious
#       Beginning of the previous match.
#   - SearchStart
#       Start of the match to the left of the vi mode cursor.
#   - SearchEnd
#       End of the match to the right of the vi mode cursor.
#
# - Search mode exclusive actions:
#   - SearchFocusNext
#       Move the focus to the next search match.
#   - SearchFocusPrevious
#       Move the focus to the previous search match.
#   - SearchConfirm
#   - SearchCancel
#   - SearchClear
#       Reset the search regex.
#   - SearchDeleteWord
#       Delete the last word in the search regex.
#   - SearchHistoryPrevious
#       Go to the previous regex in the search history.
#   - SearchHistoryNext
#       Go to the next regex in the search history.
#
# - macOS exclusive actions:
#   - ToggleSimpleFullscreen
#       Enter fullscreen without occupying another space.
#
# - Linux/BSD exclusive actions:
#
#   - CopySelection
#       Copy from the selection buffer.
#   - PasteSelection
#       Paste from the selection buffer.
#
# - `command`: Fork and execute a specified command plus arguments
#
#    The `command` field must be a map containing a `program` string and an
#    `args` array of command line parameter strings. For example:
#       `{ program: "alacritty", args: ["-e", "vttest"] }`
#
# And optionally:
#
# - `mods`: Key modifiers to filter binding actions
#
#    - Command
#    - Control
#    - Option
#    - Super
#    - Shift
#    - Alt
#
#    Multiple `mods` can be combined using `|` like this:
#       `mods: Control|Shift`.
#    Whitespace and capitalization are relevant and must match the example.
#
# - `mode`: Indicate a binding for only specific terminal reported modes
#
#    This is mainly used to send applications the correct escape sequences
#    when in different modes.
#
#    - AppCursor
#    - AppKeypad
#    - Search
#    - Alt
#    - Vi
#
#    A `~` operator can be used before a mode to apply the binding whenever
#    the mode is *not* active, e.g. `~Alt`.
#
# Bindings are always filled by default, but will be replaced when a new
# binding with the same triggers is defined. To unset a default binding, it can
# be mapped to the `ReceiveChar` action. Alternatively, you can use `None` for
# a no-op if you do not wish to receive input characters for that binding.
#
# If the same trigger is assigned to multiple actions, all of them are executed
# in the order they were defined in.
#key_bindings:
  #- { key: Paste,                                       action: Paste          }
  #- { key: Copy,                                        action: Copy           }
  #- { key: L,         mods: Control,                    action: ClearLogNotice }
  #- { key: L,         mods: Control, mode: ~Vi|~Search, chars: "\x0c"          }
  #- { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp,  }
  #- { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }
  #- { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop,   }
  #- { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }

  # Vi Mode
  #- { key: Space,  mods: Shift|Control, mode: Vi|~Search, action: ScrollToBottom          }
  #- { key: Space,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode            }
  #- { key: Escape,                      mode: Vi|~Search, action: ClearSelection          }
  #- { key: I,                           mode: Vi|~Search, action: ScrollToBottom          }
  #- { key: I,                           mode: Vi|~Search, action: ToggleViMode            }
  #- { key: C,      mods: Control,       mode: Vi|~Search, action: ToggleViMode            }
  #- { key: Y,      mods: Control,       mode: Vi|~Search, action: ScrollLineUp            }
  #- { key: E,      mods: Control,       mode: Vi|~Search, action: ScrollLineDown          }
  #- { key: G,                           mode: Vi|~Search, action: ScrollToTop             }
  #- { key: G,      mods: Shift,         mode: Vi|~Search, action: ScrollToBottom          }
  #- { key: B,      mods: Control,       mode: Vi|~Search, action: ScrollPageUp            }
  #- { key: F,      mods: Control,       mode: Vi|~Search, action: ScrollPageDown          }
  #- { key: U,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageUp        }
  #- { key: D,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageDown      }
  #- { key: Y,                           mode: Vi|~Search, action: Copy                    }
  #- { key: Y,                           mode: Vi|~Search, action: ClearSelection          }
  #- { key: Copy,                        mode: Vi|~Search, action: ClearSelection          }
  #- { key: V,                           mode: Vi|~Search, action: ToggleNormalSelection   }
  #- { key: V,      mods: Shift,         mode: Vi|~Search, action: ToggleLineSelection     }
  #- { key: V,      mods: Control,       mode: Vi|~Search, action: ToggleBlockSelection    }
  #- { key: V,      mods: Alt,           mode: Vi|~Search, action: ToggleSemanticSelection }
  #- { key: Return,                      mode: Vi|~Search, action: Open                    }
  #- { key: K,                           mode: Vi|~Search, action: Up                      }
  #- { key: J,                           mode: Vi|~Search, action: Down                    }
  #- { key: H,                           mode: Vi|~Search, action: Left                    }
  #- { key: L,                           mode: Vi|~Search, action: Right                   }
  #- { key: Up,                          mode: Vi|~Search, action: Up                      }
  #- { key: Down,                        mode: Vi|~Search, action: Down                    }
  #- { key: Left,                        mode: Vi|~Search, action: Left                    }
  #- { key: Right,                       mode: Vi|~Search, action: Right                   }
  #- { key: Key0,                        mode: Vi|~Search, action: First                   }
  #- { key: Key4,   mods: Shift,         mode: Vi|~Search, action: Last                    }
  #- { key: Key6,   mods: Shift,         mode: Vi|~Search, action: FirstOccupied           }
  #- { key: H,      mods: Shift,         mode: Vi|~Search, action: High                    }
  #- { key: M,      mods: Shift,         mode: Vi|~Search, action: Middle                  }
  #- { key: L,      mods: Shift,         mode: Vi|~Search, action: Low                     }
  #- { key: B,                           mode: Vi|~Search, action: SemanticLeft            }
  #- { key: W,                           mode: Vi|~Search, action: SemanticRight           }
  #- { key: E,                           mode: Vi|~Search, action: SemanticRightEnd        }
  #- { key: B,      mods: Shift,         mode: Vi|~Search, action: WordLeft                }
  #- { key: W,      mods: Shift,         mode: Vi|~Search, action: WordRight               }
  #- { key: E,      mods: Shift,         mode: Vi|~Search, action: WordRightEnd            }
  #- { key: Key5,   mods: Shift,         mode: Vi|~Search, action: Bracket                 }
  #- { key: Slash,                       mode: Vi|~Search, action: SearchForward           }
  #- { key: Slash,  mods: Shift,         mode: Vi|~Search, action: SearchBackward          }
  #- { key: N,                           mode: Vi|~Search, action: SearchNext              }
  #- { key: N,      mods: Shift,         mode: Vi|~Search, action: SearchPrevious          }

  # Search Mode
  #- { key: Return,                mode: Search|Vi,  action: SearchConfirm         }
  #- { key: Escape,                mode: Search,     action: SearchCancel          }
  #- { key: C,      mods: Control, mode: Search,     action: SearchCancel          }
  #- { key: U,      mods: Control, mode: Search,     action: SearchClear           }
  #- { key: W,      mods: Control, mode: Search,     action: SearchDeleteWord      }
  #- { key: P,      mods: Control, mode: Search,     action: SearchHistoryPrevious }
  #- { key: N,      mods: Control, mode: Search,     action: SearchHistoryNext     }
  #- { key: Up,                    mode: Search,     action: SearchHistoryPrevious }
  #- { key: Down,                  mode: Search,     action: SearchHistoryNext     }
  #- { key: Return,                mode: Search|~Vi, action: SearchFocusNext       }
  #- { key: Return, mods: Shift,   mode: Search|~Vi, action: SearchFocusPrevious   }

  # (Windows, Linux, and BSD only)
  #- { key: V,              mods: Control|Shift, mode: ~Vi,        action: Paste            }
  #- { key: C,              mods: Control|Shift,                   action: Copy             }
  #- { key: F,              mods: Control|Shift, mode: ~Search,    action: SearchForward    }
  #- { key: B,              mods: Control|Shift, mode: ~Search,    action: SearchBackward   }
  #- { key: C,              mods: Control|Shift, mode: Vi|~Search, action: ClearSelection   }
  #- { key: Insert,         mods: Shift,                           action: PasteSelection   }
  #- { key: Key0,           mods: Control,                         action: ResetFontSize    }
  #- { key: Equals,         mods: Control,                         action: IncreaseFontSize }
  #- { key: Plus,           mods: Control,                         action: IncreaseFontSize }
  #- { key: NumpadAdd,      mods: Control,                         action: IncreaseFontSize }
  #- { key: Minus,          mods: Control,                         action: DecreaseFontSize }
  #- { key: NumpadSubtract, mods: Control,                         action: DecreaseFontSize }

  # (Windows only)
  #- { key: Return,   mods: Alt,           action: ToggleFullscreen }

  # (macOS only)
  #- { key: K,              mods: Command, mode: ~Vi|~Search, chars: "\x0c"                 }
  #- { key: K,              mods: Command, mode: ~Vi|~Search, action: ClearHistory          }
  #- { key: Key0,           mods: Command,                    action: ResetFontSize         }
  #- { key: Equals,         mods: Command,                    action: IncreaseFontSize      }
  #- { key: Plus,           mods: Command,                    action: IncreaseFontSize      }
  #- { key: NumpadAdd,      mods: Command,                    action: IncreaseFontSize      }
  #- { key: Minus,          mods: Command,                    action: DecreaseFontSize      }
  #- { key: NumpadSubtract, mods: Command,                    action: DecreaseFontSize      }
  #- { key: V,              mods: Command,                    action: Paste                 }
  #- { key: C,              mods: Command,                    action: Copy                  }
  #- { key: C,              mods: Command, mode: Vi|~Search,  action: ClearSelection        }
  #- { key: H,              mods: Command,                    action: Hide                  }
  #- { key: H,              mods: Command|Alt,                action: HideOtherApplications }
  #- { key: M,              mods: Command,                    action: Minimize              }
  #- { key: Q,              mods: Command,                    action: Quit                  }
  #- { key: W,              mods: Command,                    action: Quit                  }
  #- { key: N,              mods: Command,                    action: SpawnNewInstance      }
  #- { key: F,              mods: Command|Control,            action: ToggleFullscreen      }
  #- { key: F,              mods: Command, mode: ~Search,     action: SearchForward         }
  #- { key: B,              mods: Command, mode: ~Search,     action: SearchBackward        }

#debug:
  # Display the time it takes to redraw each frame.
  #render_timer: false

  # Keep the log file after quitting Alacritty.
  #persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - Off
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  #log_level: Warn

  # Print all received window events.
  #print_events: false
```
