### ISSUE TITLE
Compatibility with CopyQ (clipboard manager) broken

### ISSUE THREAD

**Issue by asandikci** [alacritty/alacritty#7500]
When using CopyQ (a clipboard manager) to paste from clipboard, new version of alacritty does not recognizes it and pastes previous command. This problem is about new version of alacritty (bcs I didn't update copyq, also works with old alacritty versions and konsole/kitty terminal)

### System

OS: Linux
Version: alacritty 0.13.0 (78fa4d6f)
Linux/BSD: KDE Plasma X11

### Logs
There is no crash or related log

### Configuration
```toml
[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"

[scrolling]
history = 5000

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.8
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
```
note: deleted unnecessary schemes. and color.

**Comment by kchibisov** [comment]
Is it always something previous or you get new content _eventually_?

**Comment by asandikci** [comment]
Getting previous command until I manually stroke Ctlr+V shortcut (instead of directly clicking clipboard item from CopyQ)

**Comment by kchibisov** [comment]
Maybe the item is not getting into the clipboard for some reason, there's no notion of what is `previous` or a concept of clipboard manager, we just use whatever we get from the X server.

**Comment by asandikci** [comment]
I mean last used command in the alacritty terminal with `previous`

**Comment by asandikci** [comment]
Maybe this video could help
https://github.com/alacritty/alacritty/assets/94538585/a6157d3d-b1c7-43f9-a3b1-1005f10e072e
(I click just enter to automatically paste to current pointer position in copyq, in the 26th second I stroke Ctrl+V and it works but It should also works without it as alacirtty < 0.13)

**Comment by kchibisov** [comment]
Could you test this patch

```diff
diff --git a/alacritty/Cargo.toml b/alacritty/Cargo.toml
index ad732cfd..f6fb317c 100644
--- a/alacritty/Cargo.toml
+++ b/alacritty/Cargo.toml
@@ -25,7 +25,7 @@ version = "0.1.3-dev"
 ahash = { version = "0.8.6", features = ["no-rng"] }
 bitflags = "2.2.1"
 clap = { version = "4.2.7", features = ["derive", "env"] }
-copypasta = { version = "0.10.0", default-features = false }
+copypasta = { version = "0.8.0", default-features = false }
 crossfont = { version = "0.7.0", features = ["force_system_fontconfig"] }
 glutin = { version = "0.31.1", default-features = false, features = ["egl", "wgl"] }
 home = "0.5.5"

```

**Comment by awused** [comment]
So I tried copyq since I couldn't reproduce the other bug. My experience isn't exactly what this bug has, maybe due to bracketed pasting, but it is broken at git head, and it remains broken even after downgrading copypasta to 0.8.0 from https://github.com/alacritty/alacritty/issues/7500#issuecomment-1872295185.

If I checkout 5efb0690a3174dd4e21516bda59f74f3aa8ba3e3 (alacritty 0.12.3 release) and upgrade copypasta alone to 0.10.0, I _do not_ reproduce the bug.

I expect the bug is in alacritty or one of the other dependencies, if it's not some other weird interaction.

**Comment by kchibisov** [comment]
have you tried downgrading to 0.7.0? as I said it's all up to x11 clibpoard, you can even do that with the recent copypasta, just lower the x11-clipboard.

**Comment by awused** [comment]
`alacritty@head` + `copypasta@head` + `x11-clipboard@0.7.0` is broken.
`alacritty@0.12.3` + `copypasta@head` + `x11-clipboard@0.7.0` is working.

**Comment by kchibisov** [comment]
@asandikci could you post `--print-events`? Maybe the application is just _special_ and tries to paste by other means, like via synthetic input or something like that?

**Comment by awused** [comment]
Whatever the bad commit is, it's either 80d4daccc307622f8e604af4f36ac89ecccf5db7 (which would make it a winit bug) or before it. Unfortunately there's a large range of unbuildable commits going back months before that, making bisecting a huge pain. All the commits that were actually buildable before that range worked as expected with copypasta 0.10.0, but that doesn't narrow it down a lot.

**Comment by kchibisov** [comment]
What do you mean by unbuildable? Each commit should build just fine, there was never a case when git dependency was used in a master branch nor anything like that.

Ensure that you build with stable rust and it should be more than enough. In case something doesn't build if you bisect alacritty, please, just link it to me.

**Comment by awused** [comment]
After noticing the `-beta` winit dependencies and using `--locked`, db903503df024a3f5066937fbe0272be88226738 is the first commit that breaks copyq.

**Comment by kchibisov** [comment]
Ah, so it speculates with the keyboard input to get this working. Then could post the `--print-events` before and after?

**Comment by awused** [comment]
Here's the before

```
[3.777415639s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6589, tv_nsec: 160634989 }, requested_resume: None })
[3.777465322s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: Button { button: 1, state: Pressed } }
[3.777478256s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.777484328s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[3.778131747s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 272808735 }, requested_resume: None })
[3.778958030s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: ModifiersChanged((empty)) }
[3.778973930s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: Focused(false) }
[3.778983888s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.778990070s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[3.779555345s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 274870796 }, requested_resume: None })
[3.779576004s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(109051908))), payload: Frame })
[3.779588898s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.779598526s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[3.873366632s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 274929265 }, requested_resume: None })
[3.873421584s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: Button { button: 1, state: Released } }
[3.873438837s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.873446280s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[3.909283177s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 368774555 }, requested_resume: None })
[3.909310548s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: Button { button: 1, state: Pressed } }
[3.909324444s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.909329864s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[3.913538364s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 404654823 }, requested_resume: None })
[3.915371056s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: Focused(true) }
[3.915383009s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 1018.0, y: -160.0 }, modifiers: (empty) } }
[3.915841755s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.915848147s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[3.916144310s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 411460663 }, requested_resume: None })
[3.916157726s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(109051908))), payload: Frame })
[3.916165310s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.916171892s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[3.963931455s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 411497131 }, requested_resume: None })
[3.965251310s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(5))), event: Key(KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: (empty) }) }
[3.965263944s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: ModifiersChanged(SHIFT) }
[3.965293088s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(5))), event: Key(KeyboardInput { scancode: 110, state: Pressed, virtual_keycode: Some(Insert), modifiers: SHIFT }) }
[3.965315790s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.965320128s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[3.965926912s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 460644806 }, requested_resume: None })
[3.965970353s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: SHIFT }, is_synthetic: false } }
[3.965982425s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.965986713s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[3.967187836s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 461311942 }, requested_resume: None })
[3.967213554s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 110, state: Pressed, virtual_keycode: Some(Insert), modifiers: SHIFT }, is_synthetic: false } }
[3.967220848s] [INFO ] [alacritty] winit event: MainEventsCleared
[3.967224365s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.017447849s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 512758491 }, requested_resume: None })
[4.017459902s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(5))), event: Key(KeyboardInput { scancode: 110, state: Released, virtual_keycode: Some(Insert), modifiers: SHIFT }) }
[4.017494356s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(5))), event: Key(KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: SHIFT }) }
[4.017500037s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: ModifiersChanged((empty)) }
[4.017524803s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: Button { button: 1, state: Released } }
[4.017532778s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.017537346s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.017888171s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 512860842 }, requested_resume: None })
[4.017911886s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: ModifiersChanged(SHIFT) }
[4.017915843s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 110, state: Released, virtual_keycode: Some(Insert), modifiers: SHIFT }, is_synthetic: false } }
[4.017939608s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: SHIFT }, is_synthetic: false } }
[4.017945859s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.017949386s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.020648106s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6590, tv_nsec: 513271769 }, requested_resume: None })
[4.020656952s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(109051908))), payload: Terminal(Wakeup) })
[4.020664607s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.020669506s] [INFO ] [alacritty] winit event: RedrawEventsCleared
```

and after

```
[4.692999498s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6409, tv_nsec: 56370869 }, requested_resume: None })
[4.693056985s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.693066673s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.740856722s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6410, tv_nsec: 843877801 }, requested_resume: None })
[4.740911805s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.740920862s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.821460882s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6410, tv_nsec: 891732010 }, requested_resume: None })
[4.821517017s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.821525553s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.826310278s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6410, tv_nsec: 972336601 }, requested_resume: None })
[4.830301612s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: Focused(true) }
[4.830332900s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 1030.0, y: -194.0 } } }
[4.830568500s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.830578389s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.831759384s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6410, tv_nsec: 982555424 }, requested_resume: None })
[4.831773861s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(109051908))), payload: Frame })
[4.831780774s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.831785233s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.883007120s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6410, tv_nsec: 982593625 }, requested_resume: None })
[4.884858488s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.884870270s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.886423360s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6411, tv_nsec: 35682319 }, requested_resume: None })
[4.886455800s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: ShiftLeft, logical_key: Shift, text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Shift, text_with_all_modifiers: None } }, is_synthetic: false } }
[4.886492469s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Insert, logical_key: Insert, text: None, location: Standard, state: Pressed, repeat: true, platform_specific: KeyEventExtra { key_without_modifiers: Insert, text_with_all_modifiers: None } }, is_synthetic: false } }
[4.886501746s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.886506425s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.912757269s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6411, tv_nsec: 37332411 }, requested_resume: None })
[4.912776465s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.912782967s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.935044511s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6411, tv_nsec: 63591871 }, requested_resume: None })
[4.935213407s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }) }
[4.935229186s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.935236189s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[4.939525760s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6411, tv_nsec: 86047888 }, requested_resume: None })
[4.939573269s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Insert, logical_key: Insert, text: None, location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Insert, text_with_all_modifiers: None } }, is_synthetic: false } }
[4.939617241s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(109051908)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: ShiftLeft, logical_key: Shift, text: None, location: Left, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Shift, text_with_all_modifiers: None } }, is_synthetic: false } }
[4.939630355s] [INFO ] [alacritty] winit event: MainEventsCleared
[4.939637248s] [INFO ] [alacritty] winit event: RedrawEventsCleared
```

Anyway I've spent enough time on this to convince myself my change wasn't bad. It's easy to install copyq to test this yourself.

**Comment by kchibisov** [comment]
>Anyway I've spent enough time on this to convince myself my change wasn't bad. It's easy to install copyq to test this yourself.

Thanks. I don't have easy access to X11, so no, it's not easy for me to perform such things.

@asandikci could you configure copyq to emit not `Shift + Insert`, but e.g. `Paste` for alacritty? Or at least properly update xkb state, since while it presses `Shift` it doesn't change the state of the modifiers for the keyboard.

**Comment by kchibisov** [comment]
I'll close it as a duplicate of #7502 since the other has more clear evidence.

**Comment by asandikci** [comment]
Problem still persist for me after building patch with older copypasta and winit versions

**Comment by kchibisov** [comment]
@asandikci have you really build the patch correctly? I tried copyq and it works as expected after my patch to winit linked on this issue, without it it wasn't working at all, so clearly something should change.

The way it works is by sending events to alacritty to trigger some clipboard load, which is primary clipboard, since it sends `Shift + Insert`(note that it's a ctrl + v in other apps, but usually not in terminals).

**Comment by asandikci** [comment]
Umm probably I built correcly. And I even get some warnings while building about winit 
<details>
<summary>see build warnings</summary>


Compiling alacritty v0.14.0-dev (/home/asandikci/tmp/alacritty/alacritty)
warning: use of deprecated method `winit::window::Window::set_cursor_icon`: Renamed to `set_cursor`
   --> alacritty/src/display/window.rs:178:16
    |
178 |         window.set_cursor_icon(current_mouse_cursor);
    |                ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated method `winit::window::Window::set_cursor_icon`: Renamed to `set_cursor`
   --> alacritty/src/display/window.rs:251:25
    |
251 |             self.window.set_cursor_icon(cursor);
    |                         ^^^^^^^^^^^^^^^
</details>

Interestingly its sometimes working, sometimes not working. I don't know really why. Could you please share proper `[[keyboard.bindings]]` -> `action = "Paste"` and `action = "PasteSelection"` . Maybe my configurations are wrong

**Comment by kchibisov** [comment]
I've used default config. You can share  `alacritty --print-events` when it's not working and we can try figure... But I think what it wants is this


```toml
[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"
```

since most guis use `Paste` and not `PasteSelection` for this binding.
