### ISSUE TITLE
Change text foreground color if contrast is low

### ISSUE THREAD

**Issue by ArchUsr64** [alacritty/alacritty#7510]
In using the terminal, there are instances when the color options of the tool I'm using aren't meant for the terminal's theme. This is especially true when using a light theme as many low-saturation colors get washed out. I have provided screenshots for a few of these instances below:
### Lazygit
![image](https://github.com/alacritty/alacritty/assets/83179501/81f7b546-5bcd-4fc0-9314-eaee14f52c09)
### Bat
![image](https://github.com/alacritty/alacritty/assets/83179501/0708d911-5974-4561-b1c7-16e53d949624)
Although alacritty provides various themes and color configuration options, fixing it for one CLI tool might adversely affect visibility of some other tool. The only way is to configure the colors of each tool separately and be independent of the terminal's color theme.

I suggest the handling of these cases by the terminal. If too low of contrast (the threshold could be configurable) exists between the foreground and background, the terminal would render the foreground with a different color to improve visibility.

I would be happy to implement such a feature if it's within the scope of the project.

Color scheme used for the screenshots:
```yaml
colors:

  primary:
    foreground: '0x000000'
    background: '0xffffff'

  bright:
    black: '0x444444'
    red: '0xff0000'
    green: '0x44ff44'
    yellow: '0xdddd00'
    blue: '0x2222ff'
    magenta: '0xff22ff'
    cyan: '0x22ffff'
    white: '0xcccccc'

  normal:
    black: '0x222222'
    red: '0xdd2222'
    green: '0x22aa22'
    yellow: '0xcccc00'
    blue: '0x0000aa'
    magenta: '0xaa00aa'
    cyan: '0x00aaaa'
    white: '0xaaaaaa'
```
