### ISSUE TITLE
Cursor stopped blinking when migrated to toml config

### ISSUE THREAD

**Issue by pandfun** [alacritty/alacritty#7545]
When I opened Alacritty, I got a message saying yaml config was deprecated, and so, I ran `alacritty migrate` as it prompted me to. Now when I open Alacritty, I get the follow error message always. And my cursor has stopped blinking.

```
[0.000331917s] [ERROR] [alacritty_config_derive] Config error: style: data did not match any variant of untagged enum ConfigCursorStyle
[0.000531954s] [WARN ] [alacritty_config_derive] Unused config key: multuplier
```

Maybe there is some bug with how the call to migrate converts the yaml confg to toml? Since it was working fine before.

### System

OS: Linux
Version: `alacritty 0.13.0 (78fa4d6f)`
Linux/BSD: Gnome

**Comment by kchibisov** [comment]
Could you post your old config?

**Comment by pandfun** [comment]
Cursor Related config
```yml
# Cursor styles
cursor:
    style:
        blinking: Always
        blink-interval: 750
```

Full config
```yml
# How far it can scroll back | 10000 lines
# Each scroll will be 3 lines
scrolling:
    history: 10000
    multuplier: 3

# Cursor styles
cursor:
    style:
        blinking: Always
        blink-interval: 750

# Fonts
font:
    normal:
        family: SF Mono
        style: Regular
    size: 12

window:
    dimensions:
        lines: 32
        columns: 110

colors:
    primary:
        background: "#171717"
        foreground: "#FFFFFF"
    cursor:
        text: "#FFFFFF"
        cursor: "#FFFFFF"
    bright:
        black: "#000000"
        red: "#990000"
        green: "#00A600"
        yellow: "#999900"
        blue: "#0000B2"
        magenta: "#B200B2"
        cyan: "#00A6B2"
        white: "#FFFFFF"
    normal:
        black: "#666666"
        red: "#E60000"
        green: "#00D900"
        yellow: "#E6E600"
        #blue: "#0000FF"
        blue: "#0050FF"
        magenta: "#E600E6"
        cyan: "#00E6E6"
        white: "#FFFFFF"

# Custom keybinds
key_bindings:
    - { key: T, mods: Control, action: SpawnNewInstance }
```

**Comment by kchibisov** [comment]
```yml
# Cursor styles
cursor:
    style:
        blinking: Always
        blink-interval: 750

```

the yaml itself is not really correct cursor config, it should be

```yml
# Cursor styles
cursor:
    style:
        blinking: Always
    blink_interval: 750

```
