### ISSUE TITLE
Request: Allow YAML configs again

### ISSUE THREAD

**Issue by chenasraf** [alacritty/alacritty#7554]
The toml format is a horrible choice.  It is extremely inconvenient to use, key bindings are ugly and hard to update, many of the old keys cause problems. 

I'm no one special but maybe my tiny voice can make a difference. Until then I am downgrading to 0.12 and locking it there.

**Comment by kchibisov** [comment]
>. It is extremely inconvenient to use, key

Have you actually used `yaml`? Maybe you live in a different timeline or yaml means something else. Clearly a format with hooks, implicit nulls, and indention based is good for people.

Especially how many broken yaml configs were found and how many of them I fixed myself in the past because users can't indent keys.

>many of the old keys cause problems.

Before claiming something provide an example.

Yes, bindings look really ugly.

```toml

[keyboard]
bindings = [
  { key = "N",      mods = "Control|Shift",                        action = "CreateNewWindow" },
  { key = "Escape", mods = "Control",                              action = "ToggleViMode"    },
  { key = "K",      mods = "Control|Shift",                        action = "ClearHistory"    },

  { key = "F",      mods = "Control|Shift", mode = "~Vi|~Search",  action = "ToggleViMode"    },
  { key = "F",      mods = "Control|Shift", mode = "~Search",      action = "SearchForward"   },

  { key = "B",      mods = "Control|Shift", mode = "~Vi|~Search",  action = "ToggleViMode"    },
  { key = "B",      mods = "Control|Shift", mode = "~Search",      action = "SearchBackward"  },

  { key = "N",                              mode = "Vi|~Search",   action = "SearchNext"            },
  { key = "N",                              mode = "Vi|~Search",   action = "CenterAroundViCursor"  },

  { key = "N",      mods = "Shift"        , mode = "Vi|~Search",   action = "SearchPrevious"        },
  { key = "N",      mods = "Shift"        , mode = "Vi|~Search",   action = "CenterAroundViCursor"  },

  { key = "P",      mods = "Control|Shift", mode = "~Vi|~Search",  action = "ToggleViMode"          },
  { key = "P",      mods = "Control|Shift", mode = "~Vi|~Search",  action = "SearchBackward"        },
  { key = "P",      mods = "Control|Shift", mode = "~Vi|~Search",  chars  = ""                     },
  { key = "P",      mods = "Control|Shift", mode = "~Vi|~Search",  action = "SearchConfirm"         },
  { key = "P",      mods = "Control|Shift", mode = "~Vi|~Search",  action = "CenterAroundViCursor"  },

  { key = "P",                              mode = " Vi|~Search",  action = "Paste"           },
]
```

Because compared to yaml they don't have leading `-` anymore, very ugly indeed.

**Comment by kchibisov** [comment]
>Figuring out how to run alacritty without having the command on macOS because the documentation isn't there

That's the issue of your package manager though if it doesn't expose the end command. But I think they try to.

>Breaking change for the most base without notice in-app

![image](https://github.com/alacritty/alacritty/assets/27620401/20bd1e6b-1c39-4c7c-a2ac-2f787f568db2)

>by the way, wth is position 679? It's not a line number, or a col number. Wth am I supposed to fix now?

I have no idea what you had in your config which could cause this, but it seems like you just decided to throw a bunch of rocks, like we owe you something instead of actually sharing config and error from conversion.

>Your binding example is one I didn't see anywhere else, instead I found these examples, which I what, have to manually migrate now, I guess?

Have you looked into man page (man 5 alacritty) or web site? It's right there

![image](https://github.com/alacritty/alacritty/assets/27620401/dacab2bd-f945-48ac-983f-7db6c6193034)

You also don't need anything in your config that is default, all your bindings are default, so just remove them? Like I don't see why you'd even need them in the first place. Like that's also a part of the issue since users think that they need to comment out every field to make a working config.

**Comment by chenasraf** [comment]
Okay I was completely out of line with my behavior. I apologize for that. It's just been a terrible morning with even more now on top of it. Not your fault, mine entirely.

The screenshot was an example I found of the config in another issue.

This is my actual config, which doesn't work for migration, and without the config working, my dev setup is pretty much completely different:

```yaml
cursor:
  vi_mode_style:
    shape: Block
draw_bold_text_with_bright_colors: true
# shell:
#   args:
#     - -l
#     - -c
#     - '/bin/zsh -c "tmux attach || tmux"'
#   program: /bin/zsh
window:
  padding:
    x: 2
    y: 2

  dynamic_padding: true
  decorations: full
  opacity: 0.95
font:
  normal:
    family: 'MesloLGS NF'
  size: 14.0
  builtin_box_drawing: true
hints:
  enabled:
    - binding:
        key: U
        mods: Control|Shift
      command: open
      hyperlinks: true
      mouse:
        enabled: true
        mods: None
      post_processing: true
      regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\0-\x1f-<>\"\\s{-}\\^⟨⟩`]+"

# Cheat sheet
# \x02 - TMUX esc
# \x17 - vim - Ctrl+W
# \e   - ESC
key_bindings:
  # Navigate entire words
  # - { key: Right, mods: Alt, chars: "\x1BF" }
  # - { key: Left, mods: Alt, chars: "\x1BB" }
  # - { key: Left, mods: Alt, chars: "\eb" }
  # - { key: Right, mods: Alt, chars: "\ew" }
  # - { key: Left, mods: Control, chars: "\eb" }
  # - { key: Right, mods: Control, chars: "\ef" }
  # TODO: don't know what this does - figure it out
  # - { chars: "\eOH", key: Left, mode: AppCursor, mods: Command }
  # - { chars: "\eOF", key: Right, mode: AppCursor, mods: Command }

  # move between tmux panes: Cmd+Shift+(HJKL) or Cmd+Shift+(Left Down Up Right) Arrow
  - { chars: "\x02\e[D", key: Left, mods: Command|Shift }
  - { chars: "\x02\e[D", key: H, mods: Command|Shift }
  - { chars: "\x02\e[C", key: Right, mods: Command|Shift }
  - { chars: "\x02\e[C", key: L, mods: Command|Shift }
  - { chars: "\x02\e[A", key: Up, mods: Command|Shift }
  - { chars: "\x02\e[A", key: K, mods: Command|Shift }
  - { chars: "\x02\e[B", key: Down, mods: Command|Shift }
  - { chars: "\x02\e[B", key: J, mods: Command|Shift }
  # move between vim panes: Cmd+(HJKL) or Cmd+(Left Down Up Right) Arrow
  - { chars: "\x17j", key: Down, mods: Command }
  - { chars: "\x17j", key: J, mods: Command }
  - { chars: "\x17k", key: Up, mods: Command }
  - { chars: "\x17k", key: K, mods: Command }
  - { chars: "\x17l", key: Right, mods: Command }
  - { chars: "\x17l", key: L, mods: Command }
  - { chars: "\x17h", key: Left, mods: Command }
  - { chars: "\x17h", key: H, mods: Command }
  # Select all in nvim: Cmd+A
  - { chars: "\eggVG", key: A, mods: Command }
  # Delete entire row: Cmd+Backspace
  - { chars: "\x15", key: Back, mods: Command }
  # Delete entire word: Alt+Backspace
  - { chars: "\u0017", key: Back, mods: Alt }
  # Delete entire word forward Alt+Delete
  # - { chars: "\ew\u0017", key: Delete, mods: Alt }
  # Rename the current tmux window
  - { chars: "\x02,", key: Comma, mods: Command }
  # Select a new tmux session for the attached client interactively
  - { chars: "\x02s", key: P, mods: Command|Shift }
  # vim pick file
  - { chars: "\e\e sf", key: P, mods: Command }
  # Select window 1-9
  - { chars: "\x021", key: Key1, mods: Command }
  - { chars: "\x022", key: Key2, mods: Command }
  - { chars: "\x023", key: Key3, mods: Command }
  - { chars: "\x024", key: Key4, mods: Command }
  - { chars: "\x025", key: Key5, mods: Command }
  - { chars: "\x026", key: Key6, mods: Command }
  - { chars: "\x027", key: Key7, mods: Command }
  - { chars: "\x028", key: Key8, mods: Command }
  - { chars: "\x029", key: Key9, mods: Command }
  - { chars: "\x020", key: Key0, mods: Command }
  # Switch to last tmux session
  # - { chars: "\x02L", key: L, mods: Command }
  # ???
  # - { chars: "\x02[", key: LBracket, mods: Command }
  # - { chars: "\x02]", key: RBracket, mods: Command }
  # Change to the previous tmux window
  - { chars: "\x02p", key: LBracket, mods: Command|Shift }
  # Change to the next tmux window
  - { chars: "\x02n", key: RBracket, mods: Command|Shift }
  # Split the current pane into two, left and right
  - { chars: "\x02_", key: D, mods: Command|Shift }
  # Split the current pane into two, top and bottom.
  - { chars: "\x02|", key: D, mods: Command }
  # Type <escape>:w<enter> to save neovim
  - { chars: "\e\e:w\n", key: S, mods: Command }
  # Type <escape>:wa<enter> to save all neovim files in nvim window
  - { chars: "\e\e:wa\n", key: S, mods: Command|Shift }
  # Type <escape>ZZ to save and quit current pane
  - { chars: "\e\eZZ", key: S, mods: Command|Alt }
  # Create a new tmux window
  - { chars: "\x02c", key: T, mods: Command }
  # Break the current tmux pane out of the tmux window
  # - { chars: "\x02!", key: T, mods: Command|Shift }
  # Kill the current tmux pane (and window if last pane)
  - { chars: "\x02x", key: W, mods: Command }
  # Detach from session
  - { chars: "\x02d", key: W, mods: Command|Shift }
  # Toggle the zoom state of the current tmux pane
  - { chars: "\x02z", key: Z, mods: Command }
  - { chars: "\e[1;9D", key: Right, mods: Command|Shift }
  # Nvim navigate while in insert mode
  - { chars: "\e\eja", key: J, mods: Alt }
  - { chars: "\e\eka", key: K, mods: Alt }
  - { chars: "\e\ei", key: H, mods: Alt }
  - { chars: "\e\ela", key: L, mods: Alt }
  - { chars: "\x02M", key: K, mods: Control }

live_config_reload: true
```

**Comment by kchibisov** [comment]
Yeah, the file migrates for me fine as well. maybe once you posted it on github it fixed itself? Could you try copy what you posted from github and running migrate? Though, I don't think yaml lib we used could work on non-valid utf-8...

>man alacritty I still have no alternative yet.

if you install manually man pages won't be populated, brew usually puts them in the right place, but that's out of our control. 

```toml
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor.vi_mode_style]
shape = "Block"

[font]
builtin_box_drawing = true
size = 14.0

[font.normal]
family = "MesloLGS NF"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F�-�<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0017j"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017k"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017l"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017h"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BggVG"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B\u001B sf"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002_"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002|"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B\u001B:wa
"""
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B\u001BZZ"
key = "S"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002d"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;9D"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B\u001Bja"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u001Bka"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u001Bi"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u001Bla"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002M"
key = "K"
mods = "Control"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 2
y = 2

```

**Comment by chenasraf** [comment]
Thank you for the config, but I now understand where the format I saw earlier came from - the auto migration. It didn't just come from another issue, I showed a config someone got from the migration.

I also see more clearly the problems I have with this format. This config (IMHO) is way less readable and less convenient to edit or figure out easily.

Syntax highlighting doesn't work in TOML strings for unicode sequences (at least in Vim+treesitter), so most keys look like a jumbled mess, which will be way harder to edit, debug and make sense of. Also they're way more similar to each other (see the comments I had in my original file) which contributes to this being even less maintainable.

I get that it should be machine readable and that's the only thing that matters to the app itself in the end, but **one of the main things I liked about Alacritty** was that instead of having convoluted UIs to update configs, I could do it all in a simple file, which I periodically update. Now that giant plus has been yanked away because the configs aren't as readable for the **main thing I usually update** - key bindings.

I still **respectfully hope** you find it a worthy task to add back support for Yaml - even just as an alternative opt-in. It's not unheard of to allow multiple plugin formats.

**Comment by chrisduerr** [comment]
> I could do it all in a simple file

YAML is anything but a simple file. The toml configuration file is simpler than YAML, which isn't much of a surprise since YAML is one of the most complex markup languages out there. That applies both to parsing and human comprehension, which is why we switched.

> I still respectfully hope you find it a worthy task to add back support for Yaml

This will **never** happen. Supporting YAML is a completely unnecessary maintenance burden.

**Comment by 3y3p4tch** [comment]
I use YAML references for color schemes. I have multiple different color schemes bound to YAML reference, then I use the reference to select which color scheme I want. This, for example, lets me switch from dark mode to light mode or vice-versa with a single modification in the config file. I further extend this to switch color scheme for my whole setup.

The following is the config I use:
```yaml
schemes:
  # source: https://github.com/alacritty/alacritty/wiki/Color-schemes#multiple-schemes
  # (Ayu Light)
  ayu_light: &light
    # Default colors
    primary:
      background: '#202734'
      foreground: '#CBCCC6'

    # Normal colors
    normal:
      black: '#191E2A'
      red: '#FF3333'
      green: '#BAE67E'
      yellow: '#FFA759'
      blue: '#73D0FF'
      magenta: '#FFD580'
      cyan: '#95E6CB'
      white: '#C7C7C7'

    # Bright colors
    bright:
      black: '#686868'
      red: '#F27983'
      green: '#A6CC70'
      yellow: '#FFCC66'
      blue: '#5CCFE6'
      magenta: '#FFEE99'
      cyan: '#95E6CB'
      white: '#FFFFFF'

  # (Ayu Mirage)
  ayu_mirage: &ayu_mirage
    # Default colors
    primary:
      background: "#202734"
      foreground: "#CBCCC6"

    # Normal colors
    normal:
      black: "#191E2A"
      red: "#FF3333"
      green: "#BAE67E"
      yellow: "#FFA759"
      blue: "#73D0FF"
      magenta: "#FFD580"
      cyan: "#95E6CB"
      white: "#C7C7C7"

    # Bright colors
    bright:
      black: "#686868"
      red: "#F27983"
      green: "#A6CC70"
      yellow: "#FFCC66"
      blue: "#5CCFE6"
      magenta: "#FFEE99"
      cyan: "#95E6CB"
      white: "#FFFFFF"

  # (Ayu Dark)
  ayu_dark: &ayu_dark
    # Default colors
    primary:
      background: '#0A0E14'
      foreground: '#B3B1AD'

    # Normal colors
    normal:
      black: '#01060E'
      red: '#EA6C73'
      green: '#91B362'
      yellow: '#F9AF4F'
      blue: '#53BDFA'
      magenta: '#FAE994'
      cyan: '#90E1C6'
      white: '#C7C7C7'

    # Bright colors
    bright:
      black: '#686868'
      red: '#F07178'
      green: '#C2D94C'
      yellow: '#FFB454'
      blue: '#59C2FF'
      magenta: '#FFEE99'
      cyan: '#95E6CB'
      white: '#FFFFFF'

  # (One Light)
  one_light: &one_light
    primary:
      background: "#fafafa"
      foreground: "#383a42"
    cursor:
      text: CellBackground
      cursor: "#526eff" # syntax-cursor-color
    selection:
      text: CellForeground
      background: "#e5e5e6" # syntax-selection-color
    normal:
      black: "#696c77" # mono-2
      red: "#e45649" # red 1
      green: "#50a14f"
      yellow: "#c18401" # orange 2
      blue: "#4078f2"
      magenta: "#a626a4"
      cyan: "#0184bc"
      white: "#a0a1a7" # mono-3

  # (One Dark) - https://gist.github.com/r-darwish/f8bb21a6c89a02c4bef76cc38bddad39
  one_dark: &one_dark
    primary:
      background: '0x12151d'
      foreground: '0xabb2bf'

      # Bright and dim foreground colors
      bright_foreground: '0xe6efff'

    # Normal colors
    normal:
      black:   '0x282c34'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xd19a66'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0x828791'

    # Bright colors
    bright:
      black:   '0x5c6370'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xd19a66'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0xe6efff'

    # Dim colors
    dim:
      black:   '0x1e222a'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xd19a66'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0x828791'

colors: *one_dark
```

My question now is how do I do what I used to do with the TOML change. I would like to clarify that I do not care much about what configuration format is used, but I do care about functionality. I would be happy to switch to TOML if I can get a similar functionality with TOML.
