### ISSUE TITLE
[WARN] Unused config key: Keybinding

### ISSUE THREAD

**Issue by kurayami07734** [alacritty/alacritty#7556]
I keep getting this warning
```bash
[0.001499037s] [WARN ] [alacritty_config_derive] Unused config key: Keybinding
```
after I migrated to using toml for the config file.
I did so using the `alacritty migrate` command

### System

OS: Linux (Endeavour OS)
Version: alacritty 0.13.0 (78fa4d6f)
Linux/BSD: X11, BSPWM

---
alacritty.toml file
```toml
[[Keybinding]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[Keybinding]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[Keybinding]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[Keybinding]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[Keybinding]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[Keybinding]]
action = "IncreaseFontSize"
key = "Add"
mods = "Control"

[[Keybinding]]
action = "DecreaseFontSize"
key = "Subtract"
mods = "Control"

[[Keybinding]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[Keybinding]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[Keybinding]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[Keybinding]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[Keybinding]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[Keybinding]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xfd971f"
index = 16

[[colors.indexed_colors]]
color = "0xcc6633"
index = 17

[[colors.indexed_colors]]
color = "0x383830"
index = 18

[[colors.indexed_colors]]
color = "0x49483e"
index = 19

[[colors.indexed_colors]]
color = "0xa59f85"
index = 20

[[colors.indexed_colors]]
color = "0xf5f4f1"
index = 21

[colors.bright]
black = "0x75715e"
blue = "0x66d9ef"
cyan = "0xa1efe4"
green = "0xa6e22e"
magenta = "0xae81ff"
red = "0xf92672"
white = "0xf9f8f5"
yellow = "0xf4bf75"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x272822"

[colors.normal]
black = "0x272822"
blue = "0x66d9ef"
cyan = "0xa1efe4"
green = "0xa6e22e"
magenta = "0xae81ff"
red = "0xf92672"
white = "0xf8f8f2"
yellow = "0xf4bf75"

[colors.primary]
background = "0x272822"
foreground = "0xf8f8f2"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"

[window.dimensions]
columns = 90
lines = 27

[window.padding]
x = 6
y = 6
```
