### ISSUE TITLE
Key bindings with Alt not working on macOS

### ISSUE THREAD

**Issue by chenasraf** [alacritty/alacritty#7557]
### System

OS: `macOS Ventura 13.4.1 (22F82)`
Version: `alacritty 0.13.0 (78fa4d6)`

Key binding config:

```toml
[[keyboard.bindings]]
chars = "\u001B\u001BZZ"
key = "S"
mods = "Command|Alt"
```

**Expected**: Should send `<esc><esc>ZZ`

**Actual**: Sends `Alt-S` (which translates to `ß`)

**Note**: This was working in `0.12.x` with the following binding:

```yaml
- { chars: "\e\eZZ", key: S, mods: Command|Alt }
```

### Logs

Keyboard bindings log: [gist (was too long for issue)](https://gist.github.com/chenasraf/d5050ba6d5838569465d9284722cd826)

**Comment by chenasraf** [comment]
Nvm, my bad.

**Comment by chenasraf** [comment]
I turned `option_as_alt` to `"Both"` and it still behaves the same.

```toml
[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95
option_as_alt="Both"
```
