### ISSUE TITLE
version 0.13.0+ : keyboard.bindings : `command` not documented

### ISSUE THREAD

**Issue by cattyhouse** [alacritty/alacritty#7594]
### System

OS: macOS
Version: alacritty 0.13.1 (fe2a3c5)

### Issue

I have this setting, it is working with 0.13.0 and 0.13.1 

```toml
[keyboard]
bindings = [
{ command = { program = "sh" , args = [ "-c", "open ~/.config/alacritty/alacritty.toml" ] }, key = "Comma" , mods = "Command" }
]
````

But **not documented** in `man 5 alacritty`:

````
bindings = [{ <key>, <mods>, <mode>, <action> | <chars> },]
````
