### ISSUE TITLE
SelectNextTab and SelectNextTab not working on macOS after upgrading to 0.13.x

### ISSUE THREAD

**Issue by LvcasX1** [alacritty/alacritty#7698]
I have upgraded alacritty from v0.12.x to v0.13.x and suddenly some there are two actions that are not working anymore, the actions are: **SelectNextTab** and **SelectNextTab**, when i type the key binding i only get "[" or "]" in screen. I downgraded again to v0.12.x and it worked like a charm, I tried migrating my config file to TOML and nothing worked, only a rollback to v0.12.x

### System

OS: macOS
Version: v0.13.0~v0.13.1

**Comment by kchibisov** [comment]
They were not even present on 0.12. Not sure what is working for you.

**Comment by FrankKair** [comment]
I have a similar issue to @LvcasX1, where using the `TOML` config does not work alongside `tmux` any longer.

In TOML, none of these work:
```toml
[[keyboard.bindings]]
chars = "\u0002["
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SelectPreviousTab"
key = "["
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SelectNextTab"
key = "]"
mods = "Command|Shift"
```

Where in YAML this worked:
```yaml
  - { key: LBracket, mods: Command|Shift, chars: "\x02\x70" }
  - { key: RBracket, mods: Command|Shift, chars: "\x02\x6e" }
```

System:
```
macOS 14.5 (23F79) (sonoma)
Alacritty 0.13.2
tmux 3.3a
```
