### ISSUE TITLE
Character Ghosting Inside Multiplexers

### ISSUE THREAD

**Issue by andrew-george** [alacritty/alacritty#7758]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

Alacritty is suffering from ghosting of characters while inside multiplexers but not in normal alacritty instance without multiplexer layer

DEMO

Normal

![alacritty_a959peoA6p](https://github.com/alacritty/alacritty/assets/95014217/8580c527-e39d-4348-b42d-f13c7e356767)

Tmux

![alacritty_Mzv98qLxxR](https://github.com/alacritty/alacritty/assets/95014217/7427e483-e0fe-4ecf-9ef7-178bc422960f)

Zellij

![alacritty_UjkHvqGDJd](https://github.com/alacritty/alacritty/assets/95014217/095f373f-3c8f-4cbd-89e5-9f33e7329cc1)

the mentioned multiplexers are working fine in other terminals (Windows Terminal, Wezterm)

### System

OS: Windows (WSL2)
Version: alacritty 0.13.1 (fe2a3c5)

### config

```toml
# Start Alacritty Themes
import = ["C:\\Users\\Andrew\\AppData\\Roaming\\alacritty\\colors\\gruvbox_dark.toml"]
# End Alacritty Themes

shell = "wsl -d Ubuntu-22.04 --cd ~"
# shell = "pwsh -nologo -wd ~"

[window]
decorations = "none"
# opacity = 0.95

[window.padding]
x = 10
y = 10

[window.dimensions]
lines = 30
columns = 90

[font]
size = 13
offset = { y = 6 }

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[cursor.style]
shape = "Block"
blinking = "Always"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  # {key,mods,mode,action|chars}
  { key = "n", mods = "Control | Shift", action = "CreateNewWindow" },
  { key = "v", mods = "Control", action = "Paste" },
  { key = "Enter", mods = "Alt", action = "ToggleFullscreen" },
]

```
