### ISSUE TITLE
Add `ToggleBlur` action

### ISSUE THREAD

**Issue by GregoryConrad** [alacritty/alacritty#7767]
Pretty much as the title states, I'd like a `ToggleBlur` action for use in keybindings. Would this be an appropriate addition?

**Comment by kchibisov** [comment]
you can use `alacritty msg config window.blur=false` for that.

**Comment by GregoryConrad** [comment]
@kchibisov Thanks for the quick turnaround. I'm a bit new here; how can I have that done via the `alacritty.toml` from a keybinding? I.e., I'm looking for something like this:
```toml
[[keyboard.bindings]]
key = "Escape"
mods = "Command"
action = "ToggleBlur"
```

**Comment by GregoryConrad** [comment]
I tried this:
```toml
[[keyboard.bindings]]
key = "Escape"
mods = "Command"
chars = "alacritty msg config window.blur=false\n"
```
But:
1. This doesn't toggle it, but rather just sets it to some pre-defined value
2. Writes the command directly to the terminal instead of just executing it.

**Comment by chrisduerr** [comment]
You need to change it to command. Haven't tested it, but this should work:

```toml
[[keyboard.bindings]]
key = "Escape"
mods = "Command"
command = { program = "alacritty", args = ["msg", "config", "window.blur=false"] }
```
