### ISSUE TITLE
Allow usage of tilde/environment variables in alacritty.toml env

### ISSUE THREAD

**Issue by Gigas002** [alacritty/alacritty#7801]
As the title says, some portions of config works perfectly well with tilde, e.g. `import = ["~/.config/alacritty/cyberpunk.toml"]`

However, the `[env]` seems to not allow `~` or environment variables (or at least it doesn't work as expected):

```toml
# this works
ZDOTDIR = "/home/gigas/.config/zsh/"
# these two not
ZDOTDIR = "~/.config/zsh/"
ZDOTDIR = "$HOME/.config/zsh/"
```

And the output of `echo $ZDOTDIR` is exactly the string, that had been written in `toml` file:

```sh
gigas-acer% echo $ZDOTDIR
~/.config/zsh/
```

```sh
gigas-acer% echo $ZDOTDIR
$HOME/.config/zsh/
```

But as the result, the zsh config, in this case, is loaded only if specified with full path

### System

OS: Linux 6.7.7-x64v3-xanmod1
Version: `alacritty 0.13.1 (fe2a3c56)`
Linux: Wayland, Hyprland
