### ISSUE TITLE
overwrite line when glyphs are used in bash prompt

### ISSUE THREAD

**Issue by D3vil0p3r** [alacritty/alacritty#7838]
When I set a Bash prompt in `.bashrc` file in Arch Linux with a glyph, and I write the alacritty current row until the end of alacritty terminal window, it will overwrite the current row.

It does not happen with other terminals.

I'm using `PS1="🚀 \$(pwd) $ "` as prompt example.

Before writing:
![image](https://github.com/alacritty/alacritty/assets/83867734/4607a98e-0dd9-4d2a-a565-ae4fa406a4d6)

After writing:
![image](https://github.com/alacritty/alacritty/assets/83867734/4585909f-06a8-46cc-8b70-237fde0f5841)

If I remove the glyph from PS1, it works correctly.

### System

OS: Arch Linux
Version: alacritty 0.13.1 (fe2a3c56)
Linux/BSD: X11 XFCE

### alacritty config

```toml
[window]
decorations = "full"
opacity = 0.8

[font]
size = 12

  [font.normal]
  family = "JetBrainsMono NF"

  [font.bold]
  family = "JetBrainsMono NF"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono NF"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono NF"
  style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x000b1e"
foreground = "0x0abdc6"

[colors.normal]
black = "0x123e7c"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x123e7c"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[colors.bright]
black = "0x1c61c2"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x00ff00"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[colors.dim]
black = "0x1c61c2"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x123e7c"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"
```
