### ISSUE TITLE
Overriding default binding with hint is impossible

### ISSUE THREAD

**Issue by jeeger** [alacritty/alacritty#7859]
With the following configuration, Ctrl+Shift+F triggers *both* Vi mode and the hint. Expected behavior is only triggering the hint.

### Configuration 

```
bindings:
  - key: "F"
    mods: "Control|Shift"
    action: "None"

hints:
  enabled:
    - command: "xdg-open"
      hyperlinks: true
      post_processing: true
      persist: false
      mouse.enabled: true
      binding:
        key: "F"
        mods: "Control|Shift"
      regex: "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
```

### System

OS: Linux
Version: alacritty 0.12.2
Linux/BSD: Wayland, Sway

### Log
Relevant event:

```
[9.977221717s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94392394314496)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 21, state: Pressed, virtual_keycode: Some(F), modifiers: SHIFT | CTRL }, is_synthetic: false } }
[9.977245071s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94392394314496)), event: ReceivedCharacter('\u{6}') }
```
