### ISSUE TITLE
Error in shell setting

### ISSUE THREAD

**Issue by wra1w0** [alacritty/alacritty#7877]
I copied this example straight from the manual. Did I miss something, or why did I get an error here? 

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

### Logs

```
[ERROR] [alacritty_config_derive] Config error: shell: data did not match any variant of untagged enum Program
```

My config:
```toml
# Shell
[shell]
program = "/bin/zsh"
args = ["-l"]

# Theme
import = [
    "~/.config/alacritty/themes/themes/solarized_light.toml"
]

# Configs
[window]
option_as_alt = "Both"
```
