### ISSUE TITLE
Cursor rendering once cell behind input in nvim

### ISSUE THREAD

**Issue by duexcoast** [alacritty/alacritty#7902]
When using `nvim`, at what seems to be an arbitrary point in time, a file will suddenly start having the cursor rendered one cell to the left of its correct position. This doesn't effect other files, the problem is localized to particular files.

Once this begins for a given file, the cursor is permanently stuck this way. I can fix it by changing the file name. But if I change the file name back to the previous name, then the problem with the cursor returns.

https://github.com/alacritty/alacritty/assets/94135596/f5805e66-f979-4b01-9f91-52b2aeea3bdd

This happens both with and without `tmux`. 

This is my first time opening an issue, so let me know if there is more information I can provide.

### System

OS: macOS Ventura 13.2
Version: 0.13.1

### Config
```toml
# Import colorscheme.
import = [ "~/.config/alacritty/colors/catppuccin-mocha.toml" ]

# Environment Variables
[env]
TERM = "alacritty-direct"
LC_ALL = "en_US.UTF-8"
LANG = "en_US.UTF-8"

[shell]
program = "/bin/zsh"
args = [ "--login" ]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
# When set to true, the cursor will be rendered
# as a hollow box when the window is not focused.
unfocused_hollow = true

[font]
size = 14
normal = { family = "Hasklug Nerd Font", style = "Regular" }
bold = {  style = "Regular" }
italic = { style = "Regular" }
bold_italic = { style = "Regular" }

[window]
option_as_alt = "OnlyLeft"
startup_mode = "SimpleFullscreen"

[keyboard]
# These bindings allows me to create mappings for these keys in nvim.
# https://stackoverflow.com/questions/16359878/how-to-map-shift-enter/42461580#42461580
bindings = [
  { key = "Return", mods = "Shift", chars = "\u001b[13;2u" },
  { key = "Return", mods = "Control", chars = "\u001b[13;5u" }
]
```
