### ISSUE TITLE
Character Ghosting and misaligned inside Multiplexers with Lunarvim

### ISSUE THREAD

**Issue by Curricane** [alacritty/alacritty#7914]
Using alacritty + zellij + lunarvim, when using nvim-tree, the subdirectories are displayed, residual characters will appear, and the boundaries of nvim-tree will be misaligned

### System
Windows 11 22H2   22621.3374
alacritty version: 0.13.2

zellij version:  0.40.0
nvim version: 0.9.5
lunarvim version: release-1.3/neovim-0.9-d1c1bace

## DEMO
![image](https://github.com/alacritty/alacritty/assets/36157286/e76b15f8-da30-4ef3-8c14-17dc22d277c8)

## refer
issues 7758 may had same problem.
https://github.com/alacritty/alacritty/issues/7758

## notice
alacritty + tmux + lunarvim have the similar problem
![image](https://github.com/alacritty/alacritty/assets/36157286/890d5288-000b-4a17-a1de-6857cd703b08)

alacritty + zellij + nvcard nvim without the problem of ghosting but still have character misaligned problem
![image](https://github.com/alacritty/alacritty/assets/36157286/b767587e-b279-493a-bd00-65641455ad9c)

**Comment by Curricane** [comment]
my alacritty config is
```toml
[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"  # Default: "Full"

[scrolling]
multiplier = 1  # Default: 3

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }  # Inherits family from normal, Default style: Bold
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }  # Inherits family from normal, Default style: Italic
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic
#size = 12  # Default: 11.25
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true

[selection]
# Characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"

# When set to true, selected text will be copied to the primary clipboard
save_to_clipboard = false  # Default: false

##########
# CURSOR #
##########

[cursor]
# Cursor style
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

# Time after which cursor stops blinking, in seconds
blink_timeout = 0  # Default: 5

[terminal]
# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste"  # Default: "OnlyCopy"
```
