### ISSUE TITLE
BUG :: Some("BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by Sanix-Darker** [alacritty/alacritty#8067]
### System

OS: Linux/Ubuntu-22
Version: `alacritty 0.13.1` 
Linux/BSD: i3wm

### Logs

Crashes: `Error: Error { raw_code: Some(2), raw_os_message: Some("BadValue (integer parameter out of range for operation)"), kind: BadAttribute }`
Font/Terminal size: `alacritty -vv`
```
$ alacritty -vv
Created log file at "/tmp/Alacritty-358482.log"
[0.000001122s] [INFO ] [alacritty] Welcome to Alacritty
[0.000069035s] [INFO ] [alacritty] Version 0.13.1
[0.000078189s] [INFO ] [alacritty] Running on X11
[0.000401732s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/dk/.config/alacritty/alacritty.toml"
[0.020185750s] [INFO ] [alacritty] Using GLX 1.4
[0.020381953s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2)
                                     srgb_capable: true
[0.030116645s] [INFO ] [alacritty] Window scale factor: 1
[0.044104147s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-358482.log"
Error: Error { raw_code: Some(2), raw_os_message: Some("BadValue (integer parameter out of range for operation)"), kind: BadAttribute }
```
Keyboard and bindings: `alacritty --print-events`
```
Created log file at "/tmp/Alacritty-360448.log"
[0.000001094s] [INFO ] [alacritty] Welcome to Alacritty
[0.000071343s] [INFO ] [alacritty] Version 0.13.1
[0.000080009s] [INFO ] [alacritty] Running on X11
[0.000391601s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/dk/.config/alacritty/alacritty.toml"
[0.001868308s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.001886259s] [INFO ] [alacritty] winit event: Resumed
[0.014916632s] [INFO ] [alacritty] Using GLX 1.4
[0.024378129s] [INFO ] [alacritty] Window scale factor: 1
[0.031597269s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(88080389)), event: Ime(Enabled) }
[0.031636716s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(88080389)), event: RedrawRequested }
[0.031645810s] [INFO ] [alacritty] winit event: AboutToWait
[0.031651604s] [INFO ] [alacritty] winit event: LoopExiting
[0.032199096s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-360448.log"
Error: Error { raw_code: Some(2), raw_os_message: Some("BadValue (integer parameter out of range for operation)"), kind: BadAttribute }
```

**Comment by chrisduerr** [comment]
How did you install Alacritty?

**Comment by chrisduerr** [comment]
Do you have any config set? The error does not seem to come directly from Alacritty.

**Comment by Sanix-Darker** [comment]
> Do you have any config set? The error does not seem to come directly from Alacritty.

Yes, and i tried several updates on it but am still getting the same error : 

```toml
[colors]
indexed_colors = [
  { color = "0xd18616", index = 16 },
  { color = "0xffa198", index = 17 }
]

[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x39c5cf"
green = "0x56d364"
magenta = "0xd2a8ff"
red = "0xffa198"
white = "0xb3b1ad"
yellow = "0xe3b341"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x3fb950"
magenta = "0xbc8cff"
red = "0xff7b72"
white = "0xb3b1ad"
yellow = "0xd29922"

[colors.primary]
background = "0x0d1117"
foreground = "0xb3b1ad"

[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", mode = "Vi|Search", action = "ClearSelection" },
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "F11", action = "ToggleFullscreen" },
  { key = "H", mods = "Control|Shift", chars = "\u001B[1;5D" },
  { key = "L", mods = "Control|Shift", chars = "\u001B[1;5C" },
  { key = "H", mods = "Control|Shift|Alt", chars = "\u001B[D" },
  { key = "L", mods = "Control|Shift|Alt", chars = "\u001B[C" },
  { key = "K", mods = "Control|Shift", chars = "\u001B[A" },
  { key = "J", mods = "Control|Shift", chars = "\u001B[B" },
  { key = "P", mods = "Control", chars = "\n\ntmux-jump\n" }
]

[window]
opacity = 0.7
```
