### ISSUE TITLE
Mouse bindings don't work at all

### ISSUE THREAD

**Issue by KaeLL** [alacritty/alacritty#8150]
### System

OS: Linux
Version: alacritty 0.14.0-dev (5abb4b73) (Wayland only build)
Linux/BSD: Fedora 40, Wayland, Gnome, Mutter
Keyboard and bindings:
```toml
[font]
size = 12
normal = { family = "Ubuntu Mono", style = "Regular" }
bold = { family = "Ubuntu Mono", style = "Bold" }
italic = { family = "Ubuntu Mono", style = "Italic" }
bold_italic = { family = "Ubuntu Mono", style = "Bold Italic" }
offset = { x = 0, y = -1 }

[scrolling]
history = 100000

[mouse]
bindings = [
	{ mouse = "Right", mode = "AppCursor | AppKeypad | Search | Alt | Vi", action = "None" },
	{ mouse = "Left", mode = "AppCursor | AppKeypad | Search | Alt | Vi", action = "None" },
	{ mouse = "Middle", mode = "AppCursor | AppKeypad | Search | Alt | Vi", action = "None" },
	{ mouse = "Back", mode = "AppCursor | AppKeypad | Search | Alt | Vi", action = "CopySelection" },
	{ mouse = "Forward", mode = "AppCursor | AppKeypad | Search | Alt | Vi", action = "PasteSelection" }
]

[keyboard]
bindings = [
	{ key = "ArrowUp", mods = "Alt", action = "ScrollLineUp" },
	{ key = "ArrowDown", mods = "Alt", action = "ScrollLineDown" },
	{ key = "PageUp", mods = "Alt", action = "ScrollHalfPageUp" },
	{ key = "PageDown", mods = "Alt", action = "ScrollHalfPageDown" }
]
```
Title. Mouse bindings don't work at all. I'm still able to select and expand selection with both primary buttons, middle click still pastes selection, and the side buttons don't do anything.
