### ISSUE TITLE
Pass hint text to stdin of command instead of as last argument

### ISSUE THREAD

**Issue by AguirreIF** [alacritty/alacritty#8181]
Hi, first of all thanks for this great terminal, been using it for a few months and it's awesome :)
 
I have configured this `hint` to copy the `URL` to the clipboard with the `xsel` command, but is not working:

```toml
[[hints.enabled]]
command         = { program = "xsel", args = [ "--input", "--clipboard" ] }
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "Y", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|go‐pher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
```

`xsel` read the text from `stdin`, but according to documentation the `command` option always attaches the hint's text as the last argument, so, is there a way to pass the hint's text to the stdin of the command?

In the meantime I created a script to do just that:

```shell
#/bin/sh
echo -n "$1" | xsel --input --clipboard
```

Thanks,
