### ISSUE TITLE
Alacritty doesn't render nerd fonts correctly.

### ISSUE THREAD

**Issue by moyeh04** [alacritty/alacritty#8235]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows
Version: alacritty 0.13.2 (bb8ea18)

### Logs
Crashes: STDERR, STDOUT
Font/Terminal size:
[0.390167600s] [INFO ] [alacritty] Using WGL                                                        [0.428834200s] [DEBUG] [alacritty] Picked GL Config:                                                                                         buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })                                              alpha_size: 8                                                                                           num_samples: 0                                                                                          hardware_accelerated: true                                                                              supports_transparency: Some(false)                                                                      config_api: Api(OPENGL | GLES1 | GLES2)                                                                 srgb_capable: true                                                 [0.438026500s] [DEBUG] [alacritty] Loading "JetBrainsMono Nerd Font" font                               [0.446568800s] [INFO ] [alacritty] Running on NVIDIA GeForce GTX 1650/PCIe/SSE2                         [0.446946100s] [INFO ] [alacritty] OpenGL version 3.3.0 NVIDIA 552.22, shader_version 3.30 NVIDIA via Cg compiler                                                                                               [0.447274600s] [INFO ] [alacritty] Using OpenGL 3.3 renderer                                            [0.620167000s] [DEBUG] [alacritty] Enabled debug logging for OpenGL                                     [0.620775800s] [DEBUG] [alacritty] Filling glyph cache with common glyphs                               [0.626911100s] [INFO ] [alacritty] Cell size: 15 x 35                                                   [0.627272700s] [INFO ] [alacritty] Padding: 18 x 18                                                     [0.627549300s] [INFO ] [alacritty] Width: 800, Height: 600                                              [0.727792000s] [INFO ] [alacritty] PTY dimensions: 16 x 50                                              [0.732163700s] [INFO ] [alacritty_terminal] Using Windows API for pseudoconsole                         [0.747517500s] [INFO ] [alacritty] Initialisation complete                                              [0.749751600s] [DEBUG] [alacritty] [gl_render] Buffer detailed info: Buffer object 2 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (2), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (3), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (4), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.

### Description
There is a rendering issue when using Nerd fonts in Alacritty, (I tried other different Nerd fonts but the issue persists), and it works fine on Windows Terminal
Alacritty:
![image](https://github.com/user-attachments/assets/c0a1210a-f2e5-498a-b4c0-84c6de516513)
Windows Terminal
![image](https://github.com/user-attachments/assets/39d95f9b-a20c-4f71-8953-f78bf885309c)

Another Example when using LazyGit (The boxes are not rendered correctly):
Windows Terminal
![image](https://github.com/user-attachments/assets/b7e16d36-6510-40e2-9207-ae7f748b0e76)

Alacritty:
![image](https://github.com/user-attachments/assets/025efd95-b82f-4b13-907a-64378a5f6123)

# My current config
```toml
live_config_reload = true

[colors.primary]
background = '#11121d'
foreground = '#a0a8cd'

[colors.normal]
black = '#06080a'
blue = '#7199ee'
cyan = '#38a89d'
green = '#95c561'
magenta = '#a485dd'
red = '#ee6d85'
white = '#a0a8cd'
yellow = '#d7a65f'

[colors.bright]
black = '#212234'
blue = '#7199ee'
cyan = '#38a89d'
green = '#95c561'
magenta = '#a485dd'
red = '#ee6d85'
white = '#a0a8cd'
yellow = '#d7a65f'

[colors.cursor]
cursor = '#a0a8cd'
text = '#11121d'

[colors.selection]
background = '#11121d'
text = '#a0a8cd'

[shell]
program = "C:\\windows\\system32\\wsl.exe"
args = ["--cd ~"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 16

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
decorations = "full"

[scrolling]
history = 0

[window.padding]
x = 15
y = 15
```
