### ISSUE TITLE
Paste action does not work for vi mode binding

### ISSUE THREAD

**Issue by johannesneyer** [alacritty/alacritty#8281]
The paste action does nothing when triggered from a vi mode binding:

```toml
[[hints.enabled]]
action = "Paste"
binding = { key = "f", mode = "Vi" }
regex   = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
```

Note that this worked in `alacritty 0.13.2 (bb8ea18e)`.

### System

OS: Linux
Version: `alacritty 0.14.0 (22a44757)`
WM: Sway

**Comment by chrisduerr** [comment]
How did you expect this to work?

**Comment by johannesneyer** [comment]
I expect it to paste the matched content to the commandline. When using a binding that does not use the `mode` key it works:

```toml
[[hints.enabled]]
action = "Paste"
binding = { key = "O", mods = "Control|Shift" }
regex   = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
```

**Comment by chrisduerr** [comment]
Yeah because the mode makes no sense in this context. What do you expect to happen when you execute that binding?

**Comment by johannesneyer** [comment]
When I press f in vi mode I want alacritty to show the hint labels and when I then press the key indicated by the label I want alacritty to execute the configured action. Currently it shows the labels but does not execute the action when I press the key indicated by the label.

I am sorry, but I do not understand why the `mode` key does not make sense in this context.

**Comment by johannesneyer** [comment]
Ohh intersting, using the `f` key is the problem:

```toml
[[hints.enabled]]
action = "Paste"
binding = { key = "x", mode = "Vi" } # works
# binding = { key = "f", mode = "Vi" } # does not work
regex   = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
```

Any ideas why that might be the case?

**Comment by chrisduerr** [comment]
> Any ideas why that might be the case?

Can you share the `alacritty --print-events` output? It might send a different character or maybe it's being captured by something else (though that seems unlikely on Sway).

**Comment by johannesneyer** [comment]
working binding with `x`:
```
[15.317434650s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyX), logical_key: Character("x"), text: Some("x"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("x"), key_without_modifiers: Character("x") } }, is_synthetic: false }
[15.317559944s] [INFO ] [alacritty_winit_event] About to wait
[15.317650938s] [INFO ] [alacritty_winit_event] RedrawRequested
[15.323922848s] [INFO ] [alacritty_winit_event] About to wait
[15.400235898s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyX), logical_key: Character("x"), text: Some("x"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("x"), key_without_modifiers: Character("x") } }, is_synthetic: false }
[15.400339103s] [INFO ] [alacritty_winit_event] About to wait
[15.898207538s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("j"), key_without_modifiers: Character("j") } }, is_synthetic: false }
[15.898319611s] [INFO ] [alacritty_winit_event] About to wait
[15.898693467s] [INFO ] [alacritty_winit_event] RedrawRequested
[15.903318420s] [INFO ] [alacritty_winit_event] About to wait
[15.903366992s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(106537272658928)), payload: Terminal(CursorBlinkingChange) }
[15.903376975s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(106537272658928)), payload: Terminal(Wakeup) }
[15.903393946s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("j"), key_without_modifiers: Character("j") } }, is_synthetic: false }
[15.903432288s] [INFO ] [alacritty_winit_event] About to wait
[15.903452382s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(106537272658928)), payload: Terminal(Wakeup) }
[15.903459270s] [INFO ] [alacritty_winit_event] About to wait
[15.903674937s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(106537272658928)), payload: Terminal(CursorBlinkingChange) }
[15.903687347s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(106537272658928)), payload: Terminal(Wakeup) }
[15.903693772s] [INFO ] [alacritty_winit_event] About to wait
[15.903705648s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(106537272658928)), payload: Terminal(Wakeup) }
[15.903710964s] [INFO ] [alacritty_winit_event] About to wait
[15.904890077s] [INFO ] [alacritty_winit_event] RedrawRequested
[15.906218073s] [INFO ] [alacritty_winit_event] About to wait
```

broken binding with `f`:

```
[15.986808187s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyF), logical_key: Character("f"), text: Some("f"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("f"), key_without_modifiers: Character("f") } }, is_synthetic: false }
[15.986908098s] [INFO ] [alacritty_winit_event] About to wait
[15.987029858s] [INFO ] [alacritty_winit_event] RedrawRequested
[15.992486421s] [INFO ] [alacritty_winit_event] About to wait
[15.992581032s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyF), logical_key: Character("f"), text: Some("f"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("f"), key_without_modifiers: Character("f") } }, is_synthetic: false }
[15.992594747s] [INFO ] [alacritty_winit_event] About to wait
[18.311428137s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("j"), key_without_modifiers: Character("j") } }, is_synthetic: false }
[18.311525375s] [INFO ] [alacritty_winit_event] About to wait
[18.311888389s] [INFO ] [alacritty_winit_event] RedrawRequested
[18.317153002s] [INFO ] [alacritty_winit_event] About to wait
[18.317278021s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("j"), key_without_modifiers: Character("j") } }, is_synthetic: false }
[18.317340438s] [INFO ] [alacritty_winit_event] About to wait
```

**Comment by chrisduerr** [comment]
Ah, your problem is that `F` already is a binding in vi mode, as one would expect. Do you want to disable jumping to characters with `F`?

**Comment by johannesneyer** [comment]
Ah ok, that makes sense.

> Do you want to disable jumping to characters with `F`?

Yes, if that's what it take to get the binding working. Ideally though, the vim bindings should be temporarily disabled while the hints are shown.

**Comment by chrisduerr** [comment]
Confirmed this to work with the following config, I think that should be a fine solution:

```toml
[[hints.enabled]]
action = "Paste"
binding = { key = "f", mode = "Vi" }
regex   = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[keyboard]
bindings = [
  { key = "f",                              mode = "Vi|~Search", action = "ReceiveChar"   },
]
```
