### ISSUE TITLE
How to bind `Ctrl+.` in 0.14.0?

### ISSUE THREAD

**Issue by jjeffcaii** [alacritty/alacritty#8296]
I used `Ctrl + .` as prefix key in my tmux:
```
# ~/.tmux.conf
set -g prefix ^.
```

In 0.13.0, I use the config below, and it works.

```toml
[[keyboard.bindings]]
action = "ReceiveChar"
key = "."
mods = "Control"
```

But when I upgrade alacritty to 0.14.0, it doesn't work. How do I change my keybinding config?

### System

OS: macOS
Version: 0.14.0
