### ISSUE TITLE
When setting the font offset y, the font icon appears incorrectly

### ISSUE THREAD

**Issue by A-caibird** [alacritty/alacritty#8311]
## Desciption
When setting the font offset y, the font icon appears incorrectly, but not on Kitty

### System
OS: macOS15 ， m2Pro Apple chip
Version: alacritty 0.14.0 (22a4475
### Config
```toml
[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = {family = "MesloLGS NF", style = "Bold" }
size = 12.00
offset = { x = 0, y = 10 }
```
#### normal
<img width="884" alt="image" src="https://github.com/user-attachments/assets/25c5efcb-ff2e-4795-aa4d-0a0fe9f2e00a">

#### Lazy.vim
<img width="898" alt="image" src="https://github.com/user-attachments/assets/1848a110-7ecd-48e0-a449-dcc40f0356b1">

### Expected
<img width="925" alt="image" src="https://github.com/user-attachments/assets/a6c4feea-1acb-457d-8ce6-a5cfa7ee9886">
