### ISSUE TITLE
Not rendering Nerd Font correctly

### ISSUE THREAD

**Issue by fishBone000** [alacritty/alacritty#8318]
### System

OS: Arch Linux
Version: alacritty 0.14.0 (22a44757)
Linux/BSD: Wayland, KDE

### Logs
No log is required I believe

![alacritty nerd font 1](https://github.com/user-attachments/assets/ad69f5fa-8e8d-46ea-a173-c99b4917ab20)
![alacritty nerd font 2](https://github.com/user-attachments/assets/df21db4f-6af7-4e7d-9a6d-a6a842d2ec0c)
![alacritty nerd font 3](https://github.com/user-attachments/assets/8325bd30-8048-44c9-b06f-78c8b516a9f4)

Tried Kitty, Kitty works fine. 

Config file
```toml
[bell]
animation = "Ease"
color = "#25302F"
duration = 200

[colors.primary]
# background = "#24292E"
background = "#141921"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 10.5

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[window]
dynamic_title = true
title = "Alacritty"
```
