### ISSUE TITLE
`colors.selection` does not have any effect 

### ISSUE THREAD

**Issue by Blinkuu** [alacritty/alacritty#8329]
Setting `background` or `text` colors in `[colors.selection]` does not take any effect.

For example, when I change the `colors.primary.background` to `#ff0000`, the entire background becomes red. However, setting `colors.selection.background` doesn't take any effect, no matter the color.

My primary config:
```toml
[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/opt/homebrew/bin/zellij"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.98
option_as_alt = "Both"
```

My colors config:
```toml
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#7aa2f7'
```

### System

OS: macOS 15.1 (24B83)
Version: alacritty 0.14.0 (22a4475)

### Logs

```bash
[0.000003167s] [INFO ] [alacritty] Welcome to Alacritty
[0.000198667s] [INFO ] [alacritty] Version 0.14.0 (22a4475)
[0.001333750s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/lukasz/.config/alacritty/alacritty.toml"
                                     "/Users/lukasz/.config/alacritty/theme.toml"
                                     "/Users/lukasz/.config/alacritty/font.toml"
                                     "/Users/lukasz/.config/alacritty/font-size.toml"
                                     "/Users/lukasz/.local/share/omacub/defaults/alacritty.toml"
[0.001908000s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8/UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8
[0.019343792s] [INFO ] [alacritty] Using Apple CGL
[0.031357292s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL)
                                     srgb_capable: true
[0.044293208s] [INFO ] [alacritty] Window scale factor: 2
[0.045265458s] [DEBUG] [alacritty] Loading "CaskaydiaMono Nerd Font" font
[0.086750500s] [INFO ] [alacritty] Running on Apple M1 Pro
[0.086788375s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 89.3, shader_version 4.10
[0.086797417s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.090373917s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.098740875s] [INFO ] [alacritty] Cell size: 12 x 25
[0.098800875s] [INFO ] [alacritty] Padding: 20 x 20
[0.098810542s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.107354042s] [INFO ] [alacritty] PTY dimensions: 46 x 130
[0.109143792s] [INFO ] [alacritty] Initialisation complete
[0.116295792s] [INFO ] [alacritty] Font size changed to 29.333334 px
[0.116328375s] [INFO ] [alacritty] Cell size: 12 x 25
2024-11-26 20:25:06.724 alacritty[16096:3403601] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-26 20:25:06.724 alacritty[16096:3403601] +[IMKInputSession subclass]: chose IMKInputSession_Modern
[0.154851667s] [INFO ] [alacritty] Padding: 20 x 20
[0.154911458s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.181481250s] [DEBUG] [alacritty_terminal] New num_cols is 154 and num_lines is 37
[0.182023042s] [INFO ] [alacritty] Padding: 20 x 20
[0.182053417s] [INFO ] [alacritty] Width: 1890, Height: 976
[0.205664583s] [DEBUG] [alacritty_terminal] Ignoring unknown mode 1015 in set_private_mode
[0.210775875s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
[0.210809917s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
[0.210825792s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
[0.210835083s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
[0.210844417s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
```

**Comment by kchibisov** [comment]
Does it work outside of zellij?

**Comment by Blinkuu** [comment]
@kchibisov Yeah, it seems to be working outside alacritty, basically with the following config:

```toml
[env]
TERM = "xterm-256color"

# [terminal.shell]
# program = "/opt/homebrew/bin/zellij"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.98
option_as_alt = "Both"
```
