### ISSUE TITLE
Mouse cursor is always invisible or incorrect in NixOS

### ISSUE THREAD

**Issue by pamburus** [alacritty/alacritty#8357]
The mouse cursor is always invisible when it is over Alacrity window in NixOS 24.11 regardless of the focus.

However, if I open a Console window, then the last mouse cursor shape that was used in the Console window, is reflected when the cursor enters Alacritty window.

When the cursor is over the Alacritty's windows title, it is also either hidden, or has the shape that last appeared in the Console window.

### System

OS: Linux (NixOS)
Version: 0.14.0
Linux/BSD: Wayland

### Screen recording

https://github.com/user-attachments/assets/915b2fab-30fd-4751-966d-3f47f20c4ee1

#### alacritty.toml
```toml
[colors.cursor]
cursor = "#d17277"
text = "CellBackground"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 10
[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "LiterationMono Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = false
```

#### NixOS configuration
[nix.zip](https://github.com/user-attachments/files/18135484/nix.zip)
