### ISSUE TITLE
Crash on typing right after Caps Lock been pressed (MacOS)

### ISSUE THREAD

**Issue by the-main-thing** [alacritty/alacritty#8442]
It can be easily reproduced on my machine. Just press `caps lock + any letter`.
But I'm not sure if it is really an alacritty issue.
I have carabiner installed, so maybe the issue there.
This bug appears only in alacritty, not in default terminal and not in ghostty.

This also may be related to my settings - caps lock on my system set to switch between keyboard languages.

What info should I provide for debug?

My config:
```toml
[scrolling]
history = 50000
multiplier = 3

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 24

[window]
dimensions = { columns = 120, lines = 36 }
position = { x = 540, y = 400 }
decorations = "None"
padding = { x = 4, y = 2 }
dynamic_title = true
decorations_theme_variant = "Dark"
startup_mode = "Maximized"

[keyboard]
bindings = [
    { key = "Escape", mods = "Shift", action = "ToggleViMode" },
]
```
