### ISSUE TITLE
shift + enter doesn't work on windows

### ISSUE THREAD

**Issue by baleti** [alacritty/alacritty#8470]
I'm not sure where to report it, but if you are unable to pass shift + enter to wsl add this to your %appdata%/alacritty/alacritty.toml

```
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"
```

this got it to work, enjoy

**Comment by shipurjan** [comment]
For me this worked:
```
[keyboard]
{ key = "Return", mods = "Shift", chars = "\u001b\u000a" }
```

**Comment by baleti** [comment]
you are right, it works after all - my config for other combos ctrl+enter, shift+enter, ctrl+shift+enter

```toml
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\u000a"

[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001b\u000d"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
chars = "\u001b[13;6u"
```
