### ISSUE TITLE
[Feature] Window.position support String position to center

### ISSUE THREAD

**Issue by Tunglies** [alacritty/alacritty#8530]
In config-alacritty.html it declares that WINDOW.position is default to "None"
or can ONLY using by define integer x and integer y.

Switching from different monitors likes laptop build-in monitor
or external monitor which has different resolution.

Simply const integer for x and y
can not to adjust alacritty show up position as expect as center of screen.

Expect usage:
```toml
[window]
position = "Center"
```
or
```toml
[window]
position = { x = 10, y = "Center" }

[window]
position = { x = "Center", y = 10 }
```
