### ISSUE TITLE
Enhancement: `font.<style>.highlight = "-60%"`

### ISSUE THREAD

**Issue by mrusme** [alacritty/alacritty#8570]
First and foremost, thank you all for your exceptional work on this beautiful piece of software. I'm writing not to report a bug, but to propose a feature request. Admittedly this is a niche one, and I understand that it may not be prioritized or considered to begin with. Nevertheless, I believe it's worth sharing.

Personally, I find bold and italic fonts in the terminal visually distracting, as they tend to make words _jump_ in a way that overwhelms my visual sensory processing. That said, I still recognize and appreciate the functional value of visual emphasis, particularly how bold text is often used to highlight important keywords in tools like `nvim`.

In my current setup, I configure all font weights to use the same base style (except italic), like so:

```toml
[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.bold]
family = "Berkeley Mono"
style = "Regular"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.bold_italic]
family = "Berkeley Mono"
style = "Italic"
```

This approach removes any typographic distinction between normal and bold text, which unfortunately means I lose the visual context that bold is intended to provide.

To address this, I'd like to propose an alternative: A `highlight` property that can be used in place of traditional font styling. The inspiration for this idea comes from the [Fluoromachine](https://github.com/maxmx03/fluoromachine.nvim) color scheme for `nvim`, which uses a `glow` option to add emphasis by adjusting background shading.

The concept is simple. Instead of changing the font weight or style, Alacritty could apply a background color derived from the foreground color, using a configurable contrast offset. For example, a value like `highlight = "-40%"` could darken the foreground color by 40% and apply it as a background, thereby visually distinguishing the text without altering the font itself.

A possible configuration might look like this:

```toml
[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.bold]
family = "Berkeley Mono"
style = "Regular"
highlight = "-40%"

[font.italic]
family = "Berkeley Mono"
style = "Italic"
highlight = "-60%"

[font.bold_italic]
family = "Berkeley Mono"
style = "Italic"
highlight = "-50%"
```

### Example

If a program uses `#ff5d62` as the foreground color, Alacritty could compute a background like `#2a0001`, creating contrast and emphasis without relying on bold or italic font styles.

This feature could enhance accessibility and flexibility for users who, like me, find traditional emphasis methods visually jarring but still want a way to perceive semantic cues in terminal output.

I use this approach manually across different tools, e.g. within `eza` to highlight directories, but it requires adjusting each tool individually:

![Image](https://github.com/user-attachments/assets/382a22a3-5a66-4f55-9a77-fdbd9016b96f)

Thank you again for your outstanding work and consideration.
