### ISSUE TITLE
Some fonts fail to display italics

### ISSUE THREAD

**Issue by ivanbrennan** [alacritty/alacritty#894]
Which operating system does the issue occur on? Ubuntu 17.04

If on linux, are you using X11 or Wayland? X11

I configured alacritty.yml to use `Source Code Pro` fonts, but found that italic text wasn't being italicized. Nor would italics work for several other font families I tried (`monospace`, `Noto Mono`, ...). I confirmed that these fonts do display italics in a different terminal emulator (gnome-terminal) on my system.

I found a couple fonts that will display italics, including `FreeMono` and `Liberation Mono`.

I installed the alacritty terminfo entry and tried changing the `TERM` variable in alacritty.yml to `alacritty-256color`, but it made no difference. I also tried removing the terminfo entries I'd previously installed to `~/.terminfo` to support italics in a different emulator, but found that had no effect (I actually found that italics worked in gnome-terminal without my custom-installed terminfo entries, so maybe Ubuntu comes with a more complete entry than my previous system did).

For completeness, here are the terminfo source files I have:
xterm-256color.terminfo
```
xterm-256color|xterm with 256 colors and italic,
  sitm=\E[3m, ritm=\E[23m,
  use=xterm-256color,
```

tmux-256color.terminfo
```
tmux-256color|tmux with 256 colors,
  sitm=\E[3m, ritm=\E[23m,
  smso=\E[7m, rmso=\E[27m,
  use=screen-256color,
```

alacritty.info
```
alacritty| alacritty,
  use=xterm-256color,
  ritm=\E[23m,
  sitm=\E[3m,
  Tc,

alacritty-256color| alacritty with 256 colors,
  use=alacritty,
```

I compiled them with:
```
tic    -o $HOME/.terminfo xterm-256color.terminfo
tic    -o $HOME/.terminfo tmux-256color.terminfo
tic -x -o $HOME/.terminfo alacritty.info
```
(The -x silences a compiler warning about the unrecognized Tc in alacritty.info, so tic will treat it as a user-defined capability.)

I tested italics by running the following, both inside and outside of tmux:
```sh
echo -e "\e[3m foo \e[23m"
echo `tput sitm` foo `tput ritm`
```

With `TERM` set to xterm-256color, running infocmp shows:
```
#       Reconstructed via infocmp from file: /home/ivan/.terminfo/x/xterm-256color
xterm-256color|xterm with 256 colors and italic,
        ...
        ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
        rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
        ...
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
        smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m,
        ...
```

With `TERM` set to alacritty-256color, running infocmp shows:
```
#       Reconstructed via infocmp from file: /home/ivan/.terminfo/a/alacritty-256color
alacritty-256color| alacritty with 256 colors,
        ...
        ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
        rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
        ...
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
        smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m,
        ...
```

The `font` section of my alacritty.yml (I'm using `Liberation Mono` for italics, since `Source Code Pro` wasn't italicizing):
```yml
font:
  # The normal (roman) font face to use.
  normal:
    family: Source Code Pro # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: Source Code Pro # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: Liberation Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Italic
```

**Comment by codeinabox** [comment]
> Alacritty encountered an unrecoverable error:
> 
> 	Couldn't find a font with name 'Fira Mona' and style 'slant=Normal, weight=Normal'
> 	Please check the font config in your alacritty.yml.

**Comment by petobens** [comment]
Hi, I have a similar problem. I'm using  [SauceCodePro Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro) with the following font settings in my `alacritty.yml`:
```yaml
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: SauceCodePro Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: SauceCodePro Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: SauceCodePro Nerd Font
    # family: Menlo
    # Style can be specified to pick a specific face.
    style: Italic
```
and [this terminfo](https://github.com/petobens/dotfiles/blob/master/tmux-xterm-256color-italic.terminfo) that enables italics under tmux. While I do have proper bold fonts i can't get italics to work (on the other hand tmux on iTerm displays italics just fine with these settings). Any ideas? Thanks in advance!

**Comment by kbobyrev** [comment]
Same here. Using Hack font family.

**Comment by jsatk** [comment]
Same here. Using Operator Mono.

**Comment by Congee** [comment]
> Same here. Using Hack font family.

Can you show your config?
I am using Hack but cannot see italics..

My current config
```
# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    family: Hack

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Hack

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Hack

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Point size
  size: 12.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  use_thin_strokes: true
```

The font is already installed in macOS.
```
~/src/haskell/hello$ fc-list | rg Hack
Fontconfig warning: "/usr/local/etc/fonts/fonts.conf", line 86: unknown element "blank"
/Users/CC/Library/Fonts/Hack-Bold.ttf: Hack:style=Bold
/Users/CC/Library/Fonts/Hack-Italic.ttf: Hack:style=Italic
/Users/CC/Library/Fonts/Hack-BoldItalic.ttf: Hack:style=Bold Italic
/Users/CC/Library/Fonts/Hack-Regular.ttf: Hack:style=Regular
```

**Comment by kchibisov** [comment]
@Congee Does your `terminfo` really supports italics? `macOS` is known for it's bad preinstalled terminfos. If your `$TERM` variable is `xterm-256color`, what's output of `infocmp | grep "[sr]itm"`?

**Comment by Congee** [comment]
> 
> 
> @Congee Does your `terminfo` really supports italics? `macOS` is known for it's bad preinstalled terminfos. If your `$TERM` variable is `xterm-256color`, what's output of `infocmp | grep "[sr]itm"`?

Thank you prompt. I found Alacritty supports italics with `TERM=xterm-256color` outside tmux. I din't get italics displayed because I previously using `XTERM=screen-256color` inside tmux, particularly for some compatibility issue in tmux.

According to [tmux FAQ](https://github.com/tmux/tmux/wiki/FAQ) the TERM variable must be `screen` or `tmux` . I changed it to `tmux-256color` and haven't come across any issue regarding true color and font.

So, tmux says they support only `{screen,tmux}-256color`, and `screen-256color` does not work nicely with Alacritty and italics. **I went by `set-option -g default-terminal "tmux-256color`**. Note that this will ignore `export TERM` for tmux to display italics.

Another mystic thing is setting the TERM variable to `xterm-256color` works fine, too. I have no idea why tmux does not explicitly support it.

`infocmp | grep "[sr]itm"` outputs nothing and the return code is 1 in any of the above tmux and TERM combinations.

**Comment by chris-morgan** [comment]
I’m using Triplicate T4 on Windows and am running into this issue. I’ve tried both the WinPTY and ConPTY backend.

The symptoms I observe are consistent with `CSI [3m` just not working at all. If I set the bold face to {family: Triplicate T4, style: Italic}, then bold text renders in the correct italic font, but I can never get the font set in font.italic to take effect (e.g. if I set font.bold to Consolas it renders in that different font, but if I set font.italic to Consolas I never see it).

I think I’m probably starting to care about this enough to delve.

The quick test line that I’ve been using:

```sh
echo -e 'Normal, \x1b[1mbold\x1b[22m, \x1b[3mitalic\x1b[23m, \x1b[1;3mbold italic\x1b[22;23m'
```

**Comment by chris-morgan** [comment]
After further research, I suspect that the Windows thing is a different issue altogether, and have filed #2745 for it.

**Comment by speguero** [comment]
I wanted to also provide my two cents and mention that I'm also noticing the lack of italicized and bold characters with the `Noto Mono` font under **X.Org** in **Debian Testing** with **Alacritty v0.4.3**. This is my config:

```yml

# = FONT =>

font:
  normal:
    family: DejaVu Sans Mono
    style: Book

  bold:
    family: DejaVu Sans Mono
    style: Bold

  italic:
    family: DejaVu Sans Mono
    style: Oblique

  bold_italic:
    family: DejaVu Sans Mono
    style: Bold Oblique

  size: 10

  offset:
    x: 0
    y: 5

# = COLORS (MONOKAI SODA) =>

colors:
  primary:
    background: '#1a1a1a'
    foreground: '#c4c5b5'

  normal:
    black:   '#1a1a1a'
    red:     '#f4005f'
    green:   '#98e024'
    yellow:  '#fa8419'
    blue:    '#9d65ff'
    magenta: '#f4005f'
    cyan:    '#58d1eb'
    white:   '#c4c5b5'

  bright:
    black:   '#625e4c'
    red:     '#f4005f'
    green:   '#98e024'
    yellow:  '#e0d561'
    blue:    '#9d65ff'
    magenta: '#f4005f'
    cyan:    '#58d1eb'
    white:   '#f6f6ef'

# = OTHER =>

url:
  launcher:
    program: xdg-open
    args: []

dynamic_title: true
draw_bold_text_with_bright_colors: true
history: 10000
```

**Notes:**
  - The `DejaVu Sans Mono` font is instead set for now, as it shows italicized and bold characters. Please let me know if you need more information.
  - I also installed Alacritty using the `Alacritty-v0.4.3-ubuntu_18_04_amd64.deb` package, so the fact that I installed an Ubuntu package on Debian Testing might be of importance to maintainers.

Otherwise, thank you for this terminal emulator thus far!
